UI Automation in Windows Console: Always use ConsoleUIATextInfo in UIA consoles
nvaccess/nvda pull request #10052
Opened 2019-08-08 11:54 UTC by codeofdusk

### Link to issue number:
Fixes #10030.

### Summary of the issue:
NVDA incorrectly reports an empty selection when focusing Windows consoles.

Since the `TextInfo` property on consoles was prefixed with an underscore, NVDA dynamically selected the right `TextInfo`. This means that when a console is first focused, `UIATextInfo` is selected, so our patched `isCollapsed` logic isn't used and `speech.speakPreselectedText` is called (see lines 191–193 in `speech/__init__.py`).

### Description of how this pull request fixes the issue:
Assign the `textInfo` class as `WinConsoleUIA.TextInfo` rather than `WinConsoleUIA._TextInfo`.

### Testing performed:
Tested steps from the issue and confirmed that no superfluous selections are reported.

### Known issues with pull request:
None.

### Change log entry:
None.

2019-08-08 11:54 UTC, codeofdusk commented
Cc @feerrenrut @leonardder

2019-08-08 11:59 UTC, LeonarddeR approved these changes

2019-08-12 18:01 UTC, feerrenrut requested changes

2019-08-12 18:01 UTC, feerrenrut commented on source/NVDAObjects/UIA/winConsoleUIA.py
> +	TextInfo = consoleUIATextInfo
Please add a comment on this. If I understand correctly: 

Overriding `_get_TextInfo` and thus the `TextInfo` property on `NVDAObjects.UIA.UIA`
consoleUIATextInfo works around issues with collapsed UIA text ranges.

2019-08-13 10:35 UTC, feerrenrut commented on source/NVDAObjects/UIA/winConsoleUIA.py
> +	TextInfo = consoleUIATextInfo
I think it's key to use the term "overriding" in this comment, also very helpful for these dynamically built inheritance hierarchies if you refer to the thing you are expecting to override. After all, the logic of this is tightly coupled to that.

Thinking about this some more, given that you are overriding _get_TextInfo I think it makes sense to define it here in the same way. That way, when people search for _get_TextInfo looking for implementations, they find this one.

When this class is used, is it always on top of `NVDAObjects.UIA.UIA`? If not then the below comment should be adjust to mention what it IS always overriding. 

```suggestion
	# Overriding _get_TextInfo and thus the TextInfo property on NVDAObjects.UIA.UIA
	# consoleUIATextInfo fixes expand/collapse, implements word movement, and 
	# bounds review to the visible text.
	def _get_TextInfo(self):
		return consoleUIATextInfo
```

2019-08-13 14:43 UTC, feerrenrut approved these changes

2019-08-13 14:47 UTC, merged