port of pr 10153 into beta.
nvaccess/nvda pull request #10234
Opened 2019-09-17 09:58 UTC by lukaszgo1

### Link to issue number:
Fixes #5337 port of #10153 into beta.

### Testing performed:
Ensured that the crash no longer occurs.
### Known issues with pull request:
None
### Change log entry:
Same as in #5337

2019-09-17 10:51 UTC, Brian1Gaff commented
Was there not a second fix for  a problem with the mouse being used in 
certain circumstances? This was the most annoying one we had, since sighted 
rather than turn off nvda, merely muted the sound then had nearly 50 
explorer crashes in 10 minutes.

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message ----- 
From: "Łukasz Golonka" <notifications@github.com>
To: "nvaccess/nvda" <nvda@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Sent: Tuesday, September 17, 2019 10:58 AM
Subject: [nvaccess/nvda] port of pr 10153 into beta. (#10234)


> ### Link to issue number:
> Fixes #5337 port of #10153 into beta.
>
> ### Testing performed:
> Ensured that the crash no longer occurs.
> ### Known issues with pull request:
> None
> ### Change log entry:
> Same as in #5337
> You can view, comment on, or merge this pull request online at:
>
>  https://github.com/nvaccess/nvda/pull/10234
>
> -- Commit Summary --
>
>  * port of pr 10153 into beta.
>
> -- File Changes --
>
>    M source/appModules/explorer.py (19)
>
> -- Patch Links --
>
> https://github.com/nvaccess/nvda/pull/10234.patch
> https://github.com/nvaccess/nvda/pull/10234.diff
>
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/pull/10234
>

2019-09-17 11:32 UTC, LeonarddeR requested changes

2019-09-17 11:32 UTC, leonardder commented on source/appModules/explorer.py
> +			cls.TextInfo = super().TextInfo
This is not compatible with Python 2

```suggestion
			cls.TextInfo = super(MetadataEditField, self).TextInfo
```

2019-09-17 11:54 UTC, lukaszgo1 commented
@leonardder All done

2019-09-17 12:14 UTC, leonardder commented on source/appModules/explorer.py
> +			cls.TextInfo = super(MetadataEditField, self).TextInfo
Ugh. I made this mistake in my initial comment and updated the comment afterwards. Yet, the initial version of the comment ended up in the code:

```suggestion
			cls.TextInfo = super(MetadataEditField, cls).TextInfo
```

2019-09-17 20:57 UTC, michaelDCurran commented
> 
> Was there not a second fix for a problem with the mouse being used in certain circumstances? This was the most annoying one we had, since sighted rather than turn off nvda, merely muted the sound then had nearly 50 explorer crashes in 10 minutes.

Yes, this is already in the beta branch.

2019-09-23 03:12 UTC, michaelDCurran commented
@leonardder I think you have a review pending on this pr.

2019-09-23 04:55 UTC, LeonarddeR approved these changes
sorry for missing this @michaelDCurran

2019-09-23 06:47 UTC, michaelDCurran approved these changes

2019-09-23 06:48 UTC, merged