Vocalize the shortcut to toggle displaying nonprintable characcters i…
nvaccess/nvda pull request #10242
Opened 2019-09-18 12:43 UTC by CyrilleB79

### Link to issue number:
Fixes #10241

### Summary of the issue:
In an MS Word Document, look at the end of a paragraph and press Ctrl+Shift+8 (main keyboard) 2 or 3 times. You will see the end of paragraph mark appear and disappear but NVDA does not give a vocal feedback of this action.

### Description of how this pull request fixes the issue:
NVDA announces the state of displaying nonprinting characters when the toggle shortcut Ctrl+Shift+8 is executed.

### Testing performed:
In a Word document pressed Ctrl+Shift+8 various times.

#### Blind check
NVDA announce "Display nonprinting character on" or "off" when the shortcut is executed. After each gesture, I have checked in the Home  ribbon, group paragraph that the state of "Show all" button is in accordance with the previously announced state.

#### Visual check
I have checked that NVDA announce "Display nonprinting character on" or "off" when end of paragraph and space marks appear and disappear at the same time.

### Known issues with pull request:
None

### Change log entry:

*Changes*
`NVDA now announces the state of display non printing character when pressing the toggle shortcut Ctrl+Shift+8 . (#10241)`

2019-09-18 21:09 UTC, JulienCochuyt requested changes
Please use the new `script` method decorator instead of the legacy `__gestures` dictionary.

2019-09-18 21:09 UTC, JulienCochuyt commented on source/NVDAObjects/window/winword.py
> +	def script_toggleDisplayNonprintingCharacters(self, gesture):
```suggestion
	@script(gesture="kb:control+shift+8")
	def script_toggleDisplayNonprintingCharacters(self, gesture):
```

2019-09-18 21:09 UTC, JulienCochuyt commented on source/NVDAObjects/window/winword.py
> +		"kb:control+shift+8": "toggleDisplayNonprintingCharacters",
```suggestion
```

2019-09-19 07:33 UTC, CyrilleB79 commented
@JulienCochuyt
Thanks for suggestion. I have committed it on my side. Sorry, I realized just after that proposed suggestions can be directly committed via github (and maybe you would have been credited this way...)

2019-09-19 07:38 UTC, JulienCochuyt commented
> @JulienCochuyt
> Thanks for suggestion. I have committed it on my side. Sorry, I realized just after that proposed suggestions can be directly committed via github (and maybe you would have been credited this way...)

Indeed, but no problem at all.
Thank you for your contribution.

2019-09-19 07:40 UTC, CyrilleB79 commented
Another point:
:
I realize now that the announced messages are a bit long. Especially thinking that they will be translated in languagees more verbose than English. Any idea to shorten them?

Proposal 1:
Display nonprinting characters / Hide nonprinting characters.

Proposal 2:
Display nonprinting chars / Hide nonprinting chars
Would a native english user understand that message? Even with no programming knowledge?

2019-09-23 08:00 UTC, michaelDCurran commented
Proposal 1 is the best as "chars" certainly may not be understood by many users.

2019-09-23 23:06 UTC, michaelDCurran approved these changes

2019-09-23 23:06 UTC, merged