Add appModule for Spring Tool Suite 4
nvaccess/nvda pull request #10339
Opened 2019-10-06 19:26 UTC by lukaszgo1

### Link to issue number:
Fixes #10001 
### Summary of the issue:
Spring Tool Suite 4 changed name of its main executable. Because of this proper appModule wasn't loaded.
### Description of how this pull request fixes the issue:
Add app Module for a proper executable. This simply imports module for Eclipse.
### Testing performed:
TBD
### Known issues with pull request:
None known
### Change log entry:

Section: Bug fixes

Spring Tool Suite Version 4 is now supported

2019-10-06 19:41 UTC, lukaszgo1 commented
This PR causes two Flake8 errors: F403 and F401. Can I simply ignore these with an appropriate noqa? All app modules importing module for different program are doing exactly the same.  cc @feerrenrut

2019-10-06 19:45 UTC, lukaszgo1 commented
@alexandretoco Could you please download [this build](https://ci.appveyor.com/api/buildjobs/n1red402sa9r9gk0/artifacts/output%2Fnvda_snapshot_pr10339-18879%2C1566466d.exe), temporarily remove module that I've send you privately from the scratchpad directory and confirt that the issue is fixed?

2019-10-06 21:33 UTC, alexandretoco commented
Hi Lukasz!
I can confirm that the snapshot corrected the problem in eclipse.
How ever, I came back to the 2019.2.1 because I use eloquence and the snapshot didn’t recognize it.


Enviado do Email para Windows 10

De: Łukasz Golonka
Enviado:domingo, 6 de outubro de 2019 16:45
Para: nvaccess/nvda
Cc:alexandretoco; Mention
Assunto: Re: [nvaccess/nvda] Add appModule for Spring Tool Suite 4 (#10339)

@alexandretoco Could you please download this build, temporarily remove module that I've send you privately from the scratchpad directory and confirt that the issue is fixed?
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

2019-10-06 22:20 UTC, lukaszgo1 commented
The add-on that you ate using is not compatible with Python 3, so this isn't caused by this PR.

2019-10-07 15:22 UTC, feerrenrut commented
>  Can I simply ignore these with an appropriate noqa? 

In most cases, despite it breaking consistency, I would prefer just what is used be imported explicitly. In this case, because the goal is to map a new executable name to the same app module without having to maintain another file then I agree `import *` is the least brittle way. However please make sure you add a comment to explain why this `#noqa` is an exception.

I would really like app modules to be mapped via a more flexible mechanism than by matching the python file name with the executable.

2019-10-07 16:10 UTC, lukaszgo1 commented
@feerrenrut Done, I hope my commend is clear enough. I'd be nice to have this merged in time for 2019.3 because without this fix latest version of Spring Tool isn't really usable according to @alexandretoco

2019-10-08 11:06 UTC, LeonarddeR requested changes

2019-10-08 11:06 UTC, leonardder commented on source/appModules/springtoolsuite4.py
> +Normally these Flake8 errors shouldn't be ignored but in this case we are simply reusing existing ap module.
Could you please move this line out of the doc string and make it a comment?

2019-10-08 11:07 UTC, leonardder commented
@feerrenrut wrote:
> I would really like app modules to be mapped via a more flexible mechanism than by matching the python file name with the executable.

see #10248, which is related to that desire.

2019-10-26 11:03 UTC, lukaszgo1 commented
@leonardder You have pending review here.

2019-10-26 11:39 UTC, LeonarddeR approved these changes

2019-10-26 11:39 UTC, leonardder commented on source/appModules/springtoolsuite4.py
> +from .eclipse import *  # noqa: F403,F401
```suggestion
from .eclipse import *  # noqa: F401, F403
```

2019-10-31 22:49 UTC, lukaszgo1 commented
@feerrenrut This is ready for a review if you have time.

2019-11-30 18:07 UTC, lukaszgo1 commented
@feerrenrut Would you be able to review this, and if it looks ok get it into 2019.3? I understand that we are quite close to the release, however the change itself is very small and without it someone depending on latest version of Spring Tool has to wait a few more months.

2019-12-03 11:28 UTC, feerrenrut approved these changes
Thanks @lukaszgo1

2019-12-03 11:29 UTC, merged