Read-only states for UIA objects
nvaccess/nvda pull request #10494
Opened 2019-11-14 19:25 UTC by francipvb

### Link to issue number:
None known.

### Summary of the issue:
For various WPF text controls, read-only state isn't added. This is because the current implementation only tries to get the **ValueIsReadOnly** property. However WPF text controls don't support it.

### Description of how this pull request fixes the issue:
This PR adds checks and looks at the document range from the text pattern, if the control implements it. Then it checks for the *Is Read-Only* attribute and adds the state according to the returned value.

### Testing performed:
Tested with output text view of Visual Studio 2019.

### Known issues with pull request:
None known, but I expect some side effects with complex documents with read-only root range and editable content inside them.

### Change log entry:

Section: Changes
* Now NVDA detects more read-only text UIA controls.

2019-11-14 19:27 UTC, francipvb commented
CC @leonardder @josephsl @Adriani90

2019-11-15 07:49 UTC, leonardder commented
Thanks for this contribution. I think that the code will be more readable if the STATE_READONLY state is only added once in the code. Something like this:

```
		except COMError:
			isReadOnly=UIAHandler.handler.reservedNotSupportedValue
		if (
			isReadOnly == UIAHandler.handler.reservedNotSupportedValue
			and self.UIATextPattern
		):
			# Most UIA text controls don't support the "ValueIsReadOnly" property, so we need to
			# 	look at root document "IsReadOnly" attribute.
			document = self.UIATextPattern.documentRange
			isReadOnly = document.GetAttributeValue(UIAHandler.UIA_IsReadOnlyAttributeId):
		if isReadOnly != UIAHandler.handler.reservedNotSupportedValue:
			states.add(controlTypes.STATE_READONLY)
```

2019-11-16 08:10 UTC, LeonarddeR requested changes

2019-11-16 08:10 UTC, leonardder commented on source/NVDAObjects/UIA/__init__.py
> +		if isReadOnly:
I think reservedNotSupportedValue evaluates to True. I think we either need to do

```suggestion
		if isReadOnly and isReadOnly != UIAHandler.handler.reservedNotSupportedValue:
```

or

```suggestion
		if isReadOnly is True:
```

2019-11-18 07:43 UTC, LeonarddeR approved these changes
Thanks for this.

One additional suggestion in which case this new patch improves things.

In the outlook appModule, OutlookUIAWordDocument class, the isReadonlyViewer property can now simply return `controlTypes.STATE_READONLY in self.states`. SO, we no longer have to rely on the object model.

I leave it up to you whether you want to file this as a separate pr after this one, or do it in this one. I think it makes sense to do it as part of this pr.

2019-11-18 13:47 UTC, LeonarddeR approved these changes
Thanks @francipvb, confirmed that Outlook still behaves as expected with this.

2020-07-16 17:15 UTC, leonardder commented
@michaelDCurran I think this code looks ok. Could either you or @feerrenrut have a look? This one is pretty small, so shouldn't take longer than a minute or five.

2020-07-22 12:56 UTC, feerrenrut requested changes
Overall this looks good, thank you @francipvb . Please let me know if you won't have time to extract the method.

2020-07-22 12:56 UTC, feerrenrut commented on source/NVDAObjects/UIA/__init__.py
> +		# Read-only state
Could you please extract this whole section into a new private method `_getIsReadOnlyState()`

2020-07-22 23:09 UTC, francipvb commented
Hello,

I don't have time to code on NVDA right now, too much work. I'm sorry...

-- 
Cuando tus fuerzas terminan, las de mi Dios comienzan.

2020-07-23 16:02 UTC, feerrenrut approved these changes

2020-07-23 16:17 UTC, merged