UIA/SearchField: catch COMError when attempting to look for search fields
nvaccess/nvda pull request #10492
Opened 2019-11-14 16:44 UTC by josephsl

### Link to issue number:
Fixes #10422 

### Summary of the issue:
In Windows 10, error tone is heard when navigating through pages in Settings, as well as when opening emoji panel.

### Description of how this pull request fixes the issue:
Catch COMError thrown when attempting to add overlay class for search fields.

### Testing performed:
Tested via Windows 10 App Essentials add-on and on source code version to make sure error tone is no longer heard.

### Known issues with pull request:
None

### Change log entry:
None

### Additional context:
Although #10397 will catch this and resolve this at the UIA handler thread level, it is sometimes useful to figure out the root cause of issues, hence this pull request.

2019-11-14 18:21 UTC, LeonarddeR requested changes

2019-11-14 18:21 UTC, leonardder commented on source/NVDAObjects/UIA/__init__.py
> +			pass
I think this should still be logged.

2019-11-14 18:23 UTC, josephsl commented
Hi, I see – changes under way. Thanks.

 

From: Leonard de Ruijter <notifications@github.com> 
Sent: Thursday, November 14, 2019 10:22 AM
To: nvaccess/nvda <nvda@noreply.github.com>
Cc: Joseph Lee <joseph.lee22590@gmail.com>; Author <author@noreply.github.com>
Subject: Re: [nvaccess/nvda] UIA/SearchField: catch COMError when attempting to look for search fields (#10492)

 

@leonardder requested changes on this pull request.

  _____  

In source/NVDAObjects/UIA/__init__.py <https://github.com/nvaccess/nvda/pull/10492#discussion_r346471747> :

> @@ -863,8 +863,11 @@ def findOverlayClasses(self,clsList):
               if isDialog:
                       clsList.append(Dialog)
               # #6241: Try detecting all possible suggestions containers and search fields scattered throughout Windows 10.
-              if self.UIAElement.cachedAutomationID in ("SearchTextBox", "TextBox"):
-                      clsList.append(SearchField)
+              try:
+                      if self.UIAElement.cachedAutomationID in ("SearchTextBox", "TextBox"):
+                              clsList.append(SearchField)
+              except COMError:
+                      pass

I think this should still be logged.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub <https://github.com/nvaccess/nvda/pull/10492?email_source=notifications&email_token=AB4AXEANZO7SQKIJPQNSRWDQTWJK7A5CNFSM4JNOOVCKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCLTYPPY#pullrequestreview-317163455> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/AB4AXECTMZ4LK4VAPL6A3QLQTWJK7ANCNFSM4JNOOVCA> .

2019-11-18 05:09 UTC, LeonarddeR approved these changes

2019-11-18 08:51 UTC, michaelDCurran approved these changes

2019-11-18 08:52 UTC, merged