Avoid StopIteration error when navigating through non link text
nvaccess/nvda pull request #10563
Opened 2019-11-30 15:37 UTC by jakubl7545

### Link to issue number:
closes 10038
### Summary of the issue:
In alpha versions powered by Python 3 when user reaches last non link text instead of normal message an error sound is played and message about StopIteration error appears in the log.
### Description of how this pull request fixes the issue:
Currently during iteration through quick navigation items a StopIteration exception is caught to inform that there is no next element to iterate and then a proper message is displayed.
But, according to this article
https://www.python.org/dev/peps/pep-0479/
handling of this exception was modified and RuntimeError is now produced instead.
First I've replaced StopIteration with RuntimeError but it somehow broke quick navigation to other elements in chrome.
Finally I combined both errors in one catch to ensure that iteration through non link text and other elements will work properly.
### Testing performed:
Checked in chrome, firefox and edge that iteration through non link text and other quick navigation elements works without errors.
### Known issues with pull request:
It's unclear to me, how non link text differs from others and my knowledge about generators and iterators is limited so I hope somebody with better understanding of those confirms it is a right approach.
### Change log entry:

2019-11-30 18:40 UTC, leonardder commented
While this solution fixes the problem, I'd like to propose an another approach that fixes the actual issue, namely that Python converts a StopIteration raised inside a generator function into a RuntimeError. This is caused by BrowseModeDocumentTreeInterceptor._iterNotLinkBlock calling next on a link iterator.

Probably the cleanest way to fix this is by adding a default to the next calls, like this:

```
		item1 = next(links, default=None)
		if item1 is None:
			return
```

And

```
		while True:
			item2 = next(links, default=None)
			if item2 is None:
				break
```

You than can safely revert the change you made in the current state of this pr.

2019-12-02 06:37 UTC, michaelDCurran requested changes
All though this approach does work, it may hide other bugs where a RuntimeError really identifies another serious issue.
The problem comes from the fact that manually calling next() on an iterator or generator raises StopIteration when the generator or iterator has run out. The implementation of _iterNotLinkBlock (browseMode.py line 1751) calls next() multiple times, thus possibling raising StopIteration, which in Python3, gets converted to RuntimeError. 
I would suggest instead that the implementation of _iterNotLinkBlock be changed to use a for loop over links iterator rather than the initial call to next() and the infinite while loop. However, item1 will have to be initially set to None, and the top of the body of the for loop should assign item2 to item1 and continue. In other words, the first loop of the for loop is only used to set item1. 
Moving this into a for loop and avoiding manual calls to next() here will ensure that StopIteration is not raised from this iterator, rather it just returns with no more items.

2019-12-02 06:40 UTC, michaelDCurran commented
Oops. I missed the comment from @leonardder .  I think you can borrow ideas from both comments:
Add a default keyword to the first cal to next() outside the loop. But I'd still convert the while loop into a for loop, avoiding the second call to next()

2019-12-02 06:43 UTC, leonardder commented
Agreed that a for loop is a major improvement too.

2019-12-02 19:15 UTC, jakubl7545 commented
I made it working with a while loop but after converting to a for loop I always get a message about no more text after block of links as if StopIteration error was caught. I wrote the following:
item1 = next(links, None)
		if item1 is None:
			return
		for item1 in links:
			item2 = item1
			if item2 is None:
				break

2019-12-02 20:18 UTC, leonardder commented
`for item1 in links:` should be ``for item2 in links:`. Then, you need to set item1 to item2 at the end of the loop. In fact, it should be enough to replace the `while True` with `for item2 in links` and remove the item2 assignment from the for loop.

2019-12-02 22:05 UTC, jakubl7545 commented
It should be now fixed. Thanks for your suggestions.

2019-12-03 01:45 UTC, michaelDCurran approved these changes

2019-12-03 01:49 UTC, merged