Initialize tones with a dedicated initialize method
nvaccess/nvda pull request #10573
Opened 2019-12-03 11:33 UTC by leonardder

### Link to issue number:
Split from #9968 

### Summary of the issue:
The tones module initializes at the module level, importing the module triggers initialization. This causes sphinx to spit warnings about it not being able to initialize tones. Theoretically while unit testing, this is also the case because the tones module is imported by several other modules used within the unit testing framework.

### Description of how this pull request fixes the issue:
Added a initialize method to tones. Rename the cleanup method to terminate. Made sure that initialization and termination takes place in core.

### Testing performed:
Make sure that tones still play.

### Known issues with pull request:
None known

### Change log entry:
None needed.

2019-12-04 21:27 UTC, michaelDCurran requested changes
Tones should also be terminated and re-initialized in core.resetConfiguration.

2019-12-05 10:57 UTC, leonardder commented
I applied changes as requested and also did some reordering. Tones is now initialized after and terminated before NVDAHelper, as it relies on it.

2019-12-05 12:18 UTC, dingpengyu commented
hi @leonardder 
appveyor The following prompt appears
Checking for ability to merge automatically…
Hang in there while we check the branch’s status.
thanks

2019-12-05 21:00 UTC, michaelDCurran approved these changes

2019-12-05 21:01 UTC, merged