Fixes #10446, shorten "out of element" message
nvaccess/nvda pull request #10714
Opened 2020-01-23 14:34 UTC by yozaam

Based on the suggestion this has been made into  "element end"

### Link to issue number: #10446 

### Summary of the issue: Instead of "out of list", announce 'list end", since this is shorter

### Description of how this pull request fixes the issue: Have changed the strings where we have the longer message

### Testing performed:

### Known issues with pull request: as mentioned in my [comment](https://github.com/nvaccess/nvda/issues/10446#issuecomment-577704988) do unsure about the need to make changes in other locations like 
line 2143 text=("out of grammar error")
line 2174 _("out of table") 
or file source/locale/th/LC_MESSAGES/nvda.po lines 2403 etc

### Change log entry:

Section: New features, Changes, Bug fixes

2020-01-23 17:13 UTC, leonardder commented
@yozaam Out of interest, how did you manage in asking me for review? I thought this was only for collaborators.

2020-01-24 04:38 UTC, yozaam commented
> @yozaam Out of interest, how did you manage in asking me for review? I thought this was only for collaborators.

I'm sorry, when sending the request I just got the button on the right to ask for a reviewer, and since you opened the issue I though I'll ask you

2020-01-24 06:55 UTC, leonardder commented
> I'm sorry, when sending the request I just got the button on the right to ask for a reviewer, and since you opened the issue I thought I'll ask you

No problem at all. I'm just amazed that you were able to see this button.

2020-01-24 06:57 UTC, LeonarddeR requested changes
There are several additional `out of` messages, please use `git grep "_(\"out of "` to find them

2020-01-24 06:57 UTC, leonardder commented on source/speech/__init__.py
>  				# Translators: Indicates end of something (example output: at the end of a list, speaks out of list).
Please fix this comment accordingly

2020-01-24 12:44 UTC, yozaam commented on source/speech/__init__.py
>  				# Translators: Indicates end of something (example output: at the end of a list, speaks out of list).
Yes I will do this ASAP, thank you

2020-01-24 18:53 UTC, Adriani90 commented
@yozaam you should fix the flake8 errors otherwise this PR cannot be merged.
1. Go to test results
2. Go to artefacts
3. Open flake8errors.txt where the errors are displayed along with the source file
4. solve them in the source file.
In your case it seems there are just white space errors before and after the = operator in a function.

2020-01-25 11:06 UTC, yozaam commented
> @yozaam you should fix the flake8 errors otherwise this PR cannot be merged.
> 
>     1. Go to test results
> 
>     2. Go to artefacts
> 
>     3. Open flake8errors.txt where the errors are displayed along with the source file
> 
>     4. solve them in the source file.
>        In your case it seems there are just white space errors before and after the = operator in a function.

Thank you so much for explaining it to me in this format :D I am fixing it right now

2021-02-05 07:40 UTC, feerrenrut requested changes
Apologies this has been pending for so long, and welcome to the NVDA project 🎉

As I [mentioned on the issue](https://github.com/nvaccess/nvda/issues/10446#issuecomment-773852041) I'm happy let our alpha users try this out and give feedback. 

Though using `git grep -i "_(\"out of" -- "*.py"` I found one more:
`source/appModules/kindle.py:                _("out of popular highlight")`

Fix this up and we can go ahead.

2021-02-05 08:37 UTC, CyrilleB79 commented
Hello
Sorry to comment here a bit late.

Here is a strange use case that we should take into consideration.
Steps to reproduce:
* On a web page, press L to go to first element of a list
* Press UpArrow
In current version of NVDA, you hear "Out of list".
With this PR, if I understand correctly, you would hear "List end". This seems strange because we go out of the list across its start boundary.

Any feedback from braille users on this point?

For real containers (tables, lists, etc.), I do not have any better suggestion than the existing "out of". For containers that seem more formatting (e.g. spelling error, link), I guess "no spelling error" / "no link" would be suitable, but maybe it's out of the scope of this PR.

I do not advocate for any specific solution or change. But I wanted at least highlight this use case.

I do not

2021-02-05 08:51 UTC, feerrenrut commented
Thanks @CyrilleB79, that's a very useful observation. I'm not sure what to suggest either. I'm also interested in braille users perspective on this. For those not familiar with the braille behavior the start of a list shows `lst` and the end shows `lst end`. If going through the document backwards, you encounter `lst end` first then `lst`.

2021-06-24 03:39 UTC, seanbudd commented
Closed as this has been taken over by the more recently maintained and created #12260

2021-06-24 03:39 UTC, closed without merging