Add missing progress bar settings
nvaccess/nvda pull request #10804
Opened 2020-02-19 23:47 UTC by dawidpieper

### Link to issue number:
#9206 
(Partially)

### Summary of the issue:
Three options associated with progress bars:
* speechPercentageInterval
* beepPercentageInterval
* beepMinHZ

were available, but configurable only manually.

### Description of how this pull request fixes the issue:
The respective options were added to Object Presentation Settings.

### Testing performed:
All tests passed.
All three configurations work properly.

### Known issues with pull request:
None yet.
My only doubt is whether the minBeepHZ setting should not be moved to the advanced settings.

### Change log entry:
Changes
In Object Presentation Settings one can set progress bar update intervals and beep frequency.

2020-03-01 09:12 UTC, zstanecic commented
cc
@feerrenrut 
@michaelDCurran

2020-04-08 08:36 UTC, feerrenrut commented
Thanks for the contribution @dawidpieper. Generally I'm not sure we would accept this as it is. I'd prefer a more user friendly way of configuring this, one danger with open source software is that configuration becomes a sea of options, many of which aren't relevant (or worse, actually confusing) for the average user.

I'd prefer to see this implemented with a single verbosity level setting (low, medium, high) which is used to set both `speechPercentageInterval` and `beepPercentageInterval`. As for the frequency, my eventual plan is to make this configurable with "audio themes". An "audio theme" would also be able to configure exactly what "low / medium / high" verbosity means for `[speech|beep]PercentageInterval`.

Since I can't give any concrete timeline for "audio themes", perhaps we can accept this PR as an interim solution. This would be with the understanding that it will be removed in the future. I'll discuss this possibility with the rest of the team. 

If we decide to accept this feature, I would like to see a single verbosity level option, and these options grouped together (`wx.StaticBoxSizer`) under "Progress Bars"

2020-09-13 15:46 UTC, dawidpieper commented
Could it be potentialy included in NVDA 2020.4/2021.1 if changed in suggested way? @feerrenrut

2020-09-14 08:34 UTC, feerrenrut commented
Yes, please go ahead if you are happy with the plan I outlined. Otherwise please feel free to suggest other ideas.

2020-09-16 20:01 UTC, dawidpieper commented
As for progress bar, I think speech percentage interval is significantly more important than beep one. For example, I can simply imagine scenarios where one requires more or less detailed information about percents, while beeps every 1 percent are in most scenarios relevant.
Therefore I see two options:
* Enabling user to set only speech interval (maybe a combobox: 1, 2, 5, 10, 20 percent)
* Enabling user to set it independently.
As for combining these, I cannot imagine how should it be useful.
As for frequencies, I don't know if this option is worth implementing, if audiothemes are coming in the future. If so, I would suggest creating one combobox defining both beeps percentage interval and frequencies.

2020-09-22 19:26 UTC, dawidpieper commented
cc @feerrenrut

2020-09-30 08:06 UTC, feerrenrut commented
I'm not sure I totally followed you. I'd be happy with a single combo box affecting speech and beeps for progress bar reporting with the values you suggest.

Thinking more about this, the granularity of reporting should be a function of the rate of value change. IE, if a progress bar goes from 0 to 100 in 1 second, it would be enough to hear "100%". If the progress bar jumps quickly to 50% then crawls up from there, it would be better to hear "50%, 51%, 52%... etc". Still people will have a preference for verbosity, ie how long of a gap between reporting, though presumably allowing speech to finish would satisfy most.

2020-11-20 18:45 UTC, leonardder requested changes

2020-11-20 18:45 UTC, leonardder commented on source/config/configSpec.py
> +		speechPercentageInterval = integer(default=10,min=1,max=20)
Please add commas.

```suggestion
		speechPercentageInterval = integer(default=10, min=1, max=20)
```

2020-11-20 18:45 UTC, leonardder commented on source/config/configSpec.py
> +		beepPercentageInterval = integer(default=1,min=1,max=20)
```suggestion
		beepPercentageInterval = integer(default=1, min=1, max=20)
```

2020-11-20 18:45 UTC, leonardder commented on source/gui/settingsDialogs.py
> +		beepMinHZLabelText = _("Progress bar minimum beep &frequency (Hz)")
I"m not sure whether I'd agree with adding this to the gui. Expressing pitch in terms of frequency sounds rather technical. I think I'd move this to the advanced settings panel or remove it again. Thoughts @feerrenrut?

2020-11-20 18:45 UTC, leonardder commented on source/gui/settingsDialogs.py
> +		self.SpeechIntrEdit.Enable(evt.GetSelection() == 1 or evt.GetSelection() == 3)
```suggestion
		self.SpeechIntrEdit.Enable(evt.GetSelection() in (1, 3)
```

2020-11-20 18:45 UTC, leonardder commented on source/gui/settingsDialogs.py
> +		self.BeepIntrEdit.Enable(evt.GetSelection() == 2 or evt.GetSelection() == 3)
```suggestion
		self.BeepIntrEdit.Enable(evt.GetSelection() == in (2, 3)
```

2020-11-20 18:45 UTC, leonardder commented on user_docs/en/userGuide.t2t
> +This setting allows you to set after which percentage change the new progress bar state will be read by the synthesizer.
Could you add examples? For example:

`For example, when the value of this option is set to 10, NVDA will announce the value of the progress bar every time the percentage increased with 10%`

2020-11-20 18:45 UTC, leonardder commented on user_docs/en/userGuide.t2t
> +The default value of 110Hz corresponds to the sound A in the great octave.
This also sounds familiar to people who have affinity with music, but what if one changes the minimum frequency to an e? how would they know what frequency to input?

2024-05-28 02:45 UTC, closed without merging