Catch exceptions when creating shortcuts
nvaccess/nvda pull request #10875
Opened 2020-03-13 17:19 UTC by feerrenrut

### Link to issue number:
fixes #5166
fixes #6326

Related, alternative approach: #10874

### Summary of the issue:
The way that shortcuts are created (wsh) does not handle unicode characters. This results in the installer presenting an error. 

### Description of how this pull request fixes the issue:
Wrap each call to create shortcut in a try block, on error try to create the shortcut without translation.

### Testing performed:
Manually replaced translated versions of the strings with unicode characters (including the hotkey).
Checked that an error is presented in the log, but the shortcut is still created.

### Known issues with pull request:
- When an error occurs the shortcuts / hotkey will not be translated.
- So many try blocks makes the code hard to read!

### Change log entry:

Section: New features, Changes, Bug fixes

2020-03-15 22:52 UTC, michaelDCurran requested changes
Lots of flake8 errors at the moment also.

2020-03-15 22:52 UTC, michaelDCurran commented on source/installer.py
> +def _updateShotcuts(NVDAExe, installDir, shouldCreateDesktopShortcut, slaveExe, startMenuFolder) -> None:
Rename _updateShotcuts to _updateShortcuts please.

2020-03-16 20:58 UTC, feerrenrut commented
Since the linter was complaining about the complexity of the function, and I agree it was hard to read, I have re-worked it. The new function wraps the calls to create shortcut, falling back on the non-translated name / hotkey as necessary.

2020-03-17 04:43 UTC, michaelDCurran approved these changes

2020-03-17 06:50 UTC, merged