Modify SConscript to make it possible to build with different version of Scons than the one bundled in the repo
nvaccess/nvda pull request #10883
Opened 2020-03-18 21:30 UTC by lukaszgo1

### Link to issue number:
Closes #10876
supersedes #10870
### Summary of the issue:
If for any reason the version of Scons included in NVDA repository is not working on a particular configuration developer suffering from this issue has to request NVDA team to update Scons which takes time and is being done only when never version brings a important improvements for the project. It would be easier if NVDA's build Sconscript could  be invoked with the Scons installed in the Python distribution.
Its currently not possible as our Sconscript cannot be started directly -  scons.py has to set PYTHONPATH in a particular way to make it working.
### Description of how this pull request fixes the issue:
The imports during Scons execution has been reorganized. Now scons.py imports only Scons, and other directories containing Python packages required during build are imported by the sconscript. Also check ensuring that build is being run with the correct Python version has been moved to the Sconscript. While at it I've also added additional check to ensure that someone is not building with Python 3.7.6 (see #10696, and [this commend from pr 10870](https://github.com/nvaccess/nvda/pull/10870#issuecomment-598092551)).
### Testing performed:
- Tested launcher creation when invoked with the Scons from the repository.
- On a machine on which currently included Scons fails also tested building with the Scons installed in Python by moving to the top dir of the repo and executing c:\Python37\Scripts\scons.bat. Ensured that build is succesfull.
- Tests on AppVeyor are pending.

### Known issues with pull request:
I haven't updated readme yet - I don't thing we should encourage usage of non-default version of Scons, and if someone asks on a bug tracker or on NVDA-Devel we can always explain how to use more recent Scons.

### Change log entry:
None needed

2020-03-18 21:46 UTC, lukaszgo1 commented
@feerrenrut I would appreciate your review. While the diff for this is quite big it just copy-paste from one file to another and copyright headers reformatting for the most part.

2020-03-19 07:26 UTC, LeonarddeR requested changes
Looks nice!

2020-03-19 07:26 UTC, leonardder commented on sconstruct
> +	print(
I understand why you used print here, it's just what the original script did. However, given what we do elsewhere in the scons environment, I think it makes sense to raise RuntimeError here.

Please:

1. As the message spans multiple lines, store it in its own variable
2. Then, raise a RuntimeError with that variable as message.

Using old style string formatting is fine of course.

2020-03-19 07:26 UTC, leonardder commented on sconstruct
> +	print(
Please merge this with the message above

2020-03-19 07:26 UTC, leonardder commented on sconstruct
> +	print("Building with Python 3.7.6 is not possible.")
Same as above, please raise RuntimeError or something similar.

2020-03-19 12:40 UTC, lukaszgo1 commented
@leonardder All you commends are now addressed.

2020-03-19 14:37 UTC, LeonarddeR approved these changes
Thanks @lukaszgo1

2020-03-19 16:00 UTC, feerrenrut approved these changes
Looks good, I'll merge this soon.

2020-03-20 09:54 UTC, merged