Update CLDR to version 36.1
nvaccess/nvda pull request #10999
Opened 2020-04-13 19:38 UTC by Nardol

### Link to issue number:

### Summary of the issue:
Some emojis have been added since CLDR 36.0
For example, the black cat, person/man/woman giving milk to baby...

### Description of how this pull request fixes the issue:
CLDR submodule is updated to last master revision, which includes CLDR version 36.1 which add these emojis

### Testing performed:
With last NVDA Alpha, these emojis are not pronounced correctly and these are juste a part:
🐈‍⬛ (in french, I have "chat carré noir")
🐻‍❄ (in french "ours flocon")
With CLDR 36.1 these emojis are pronounced correctly.

### Known issues with pull request:

### Change log entry:

Section: Changes
- CLDR annotations have been updated to version 36.1

2020-04-13 19:57 UTC, josephsl requested changes
Can you edit readme to mention CLDR 36.1? Thanks.

2020-04-13 20:12 UTC, Nardol commented
in the patch, I have for readme.md:
```-* [Unicode Common Locale Data Repository (CLDR)](http://cldr.unicode.org/) Emoji Annotations, version 36.0
+* [Unicode Common Locale Data Repository (CLDR)](http://cldr.unicode.org/) Emoji Annotations, version 36.1```
I might miss-understand your change request, sorry. What should I add/update please?

2020-04-13 20:32 UTC, josephsl commented
Hi, no need to change anything (I’ll do something about my mistake). Thanks. 

 

From: Patrick ZAJDA <notifications@github.com> 
Sent: Monday, April 13, 2020 1:13 PM
To: nvaccess/nvda <nvda@noreply.github.com>
Cc: Joseph Lee <joseph.lee22590@gmail.com>; Comment <comment@noreply.github.com>
Subject: Re: [nvaccess/nvda] Update CLDR to version 36.1 (#10999)

 

in the patch, I have for readme.md:

+* [Unicode Common Locale Data Repository (CLDR)](http://cldr.unicode.org/) Emoji Annotations, version 36.1```
I might miss-understand your change request, sorry. What should I add/update please?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub <https://github.com/nvaccess/nvda/pull/10999#issuecomment-613074983> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/AB4AXEHGN5K4U2LQRQ7EO2DRMNW3RANCNFSM4MHF3HLA> .

2020-04-13 20:32 UTC, josephsl approved these changes

2020-04-13 20:33 UTC, josephsl commented
@LeonardDer, may I request a second look from you please? Thanks.

2020-04-14 06:13 UTC, michaelDCurran commented
"CLDR submodule is updated to last master revision, which includes CLDR version 36.1":
Is the commit you used exactly 36.1, or contains 36.1? I.e.  are there any commits on their master branch beyond 36.1? We should really use a 36.1 tag commit if it exists.

2020-04-14 06:20 UTC, leonardder commented
> 
> 
> "CLDR submodule is updated to last master revision, which includes CLDR version 36.1":
> Is the commit you used exactly 36.1, or contains 36.1? I.e. are there any commits on their master branch beyond 36.1? We should really use a 36.1 tag commit if it exists.

I was about to say something like that. However, there doesn't seem to be a tag like this. Having said that, there is only one commit difference between this branch and what we're using in alpha now, and that's the exact commit we need. SO I think it's ok.

2020-04-14 06:24 UTC, michaelDCurran approved these changes

2020-04-14 06:30 UTC, merged