Foobar2000: implement a custom status bar routine to fix playback status commands
nvaccess/nvda pull request #11087
Opened 2020-05-01 23:19 UTC by josephsl

Hi,

This is a follow-up to #9792:

### Link to issue number:
Fixes #11082 

### Summary of the issue:
In Foobar2000 with NVDA alpha.20080 and later (with custom status bar commit), NVDA says 'no track playing" when trying to obtain elpased time, total time, and remaining time for a playing track.

### Description of how this pull request fixes the issue:
Implemented a custom status bar fetcher for Foobar2000 that uses windowUtils.findDescendentWindow to retrieve the status bar for the foreground object.

### Testing performed:
Tested with Foobar2000 with latest alpha and with app module changes applied through this PR.

### Known issues with pull request:
None

### Change log entry:
None, as it is a follow-up to a change in alpha

2020-05-02 05:09 UTC, JulienCochuyt commented
All apologies for missing this impact.

@josephsl,
Thanks for taking care of cleaning my mess.
While renaming the `statusBar` attribute in `appModules.fooBar2000.AppModule` to something like `statusBarObj` would have been enough to fix #11082, I understand how your approach is more efficient than the default `api.getStatusBar`.
Still, I would advocate for the following changes to this PR:
 - Add a comment clarifying that the technique used is not a replacement for the failing standard one, but rather an optimization.
 - Fallback to raising `NotImplementedError` rather than returning `None`: This way, if a foobar2000 plug-in displays a status bar which does not have the class name "ATL:msctls_statusbar32", its content could still be read. Or do you know for sure such a scenario is unlikely to happen? (I'm only a seldom user of foobar2000, and unaware of the diversity of its plug-ins.)

2020-05-02 05:26 UTC, josephsl commented
HI, no need to apologize over it (I made the same mistake several times in my own code). I think NotImplementedError makes sense if _get_statusBar isn’t defined in the first place. Since it is encountered inside the very thing it is supposed to do, it could amount to lying at the source code level. As for that check, as I’m not a seasoned Foobar2000 user myself, I’d ask users. Thanks.

 

From: Julien Cochuyt <notifications@github.com> 
Sent: Friday, May 1, 2020 10:10 PM
To: nvaccess/nvda <nvda@noreply.github.com>
Cc: Joseph Lee <joseph.lee22590@gmail.com>; Mention <mention@noreply.github.com>
Subject: Re: [nvaccess/nvda] Foobar2000: implement a custom status bar routine to fix playback status commands (#11087)

 

All apologies for missing this impact.

@josephsl <https://github.com/josephsl> ,
Thanks for taking care of cleaning my mess.
While renaming the statusBar attribute in appModules.fooBar2000.AppModule to something like statusBarObj would have been enough to fix #11082 <https://github.com/nvaccess/nvda/issues/11082> , I understand how your approach is more efficient than the default api.getStatusBar.
Still, I would advocate for the following changes to this PR:

*	Add a comment clarifying that the technique used is not a replacement for the failing standard one, but rather an optimization.
*	Fallback to raising NotImplementedError rather than returning None: This way, if a foobar2000 plug-in displays a status bar which does not have the class name "ATL:msctls_statusbar32", its content could still be read. Or do you know for sure such a scenario is unlikely to happen? (I'm only a seldom user of foobar2000, and unaware of the diversity of its plug-ins.)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub <https://github.com/nvaccess/nvda/pull/11087#issuecomment-622670395> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/AB4AXEEYCYSMAAUEYEBZDYLRPOTKHANCNFSM4MXNUQEQ> .

2020-05-02 12:27 UTC, lukaszgo1 reviewed
I'm slightly worried about performance here. Previously the status bar object was fetched once and then stored as an attribute of the appModule instance, whereas now it is fetched each time when one of the time requesting scripts is executed

2020-05-02 12:27 UTC, lukaszgo1 commented on source/appModules/foobar2000.py
>  # For more details see: https://www.gnu.org/licenses/gpl-2.0.htmlimport appModuleHandler
Could you please clean-up this line while at it?

2020-05-02 18:10 UTC, josephsl commented
Hi,

Copyright header: I need cleanup reasons, as all I did there is update the copyright header (we will need to go through files again to do copyright header management at some point).

As for performance and previous implementation: it was done that way for consistency with what Julian wrote.

There is an issue that was present in old and current implementations that will require a separate PR to fix: NVDA will get wrong status bar if something other than the playlist gets focused when NVDA starts. This is caused by gain focus event caching the "active" status bar from anywhere as long as status bar isn't defined. The ideal solution is either using Foobar2000 API to announce playback time, or locating the status bar object from Foobar2000's main window handle. Resolving that issue means there is no need for this PR, or better yet, modifying the PR to account for changes introduced in recent alpha snapshots along with a better solution for #11082.

Thanks.

2020-05-02 18:25 UTC, lukaszgo1 commented
The line  says:
`# For more details see: https://www.gnu.org/licenses/gpl-2.0.htmlimport appModuleHandler`

I don't think `import appModuleHandler` should be there :-)

2020-05-02 18:35 UTC, josephsl commented
Hi, you’re right – thanks for catching this (Tuukka Ojala was the last person who edited this app module file).

 

From: Łukasz Golonka <notifications@github.com> 
Sent: Saturday, May 2, 2020 11:26 AM
To: nvaccess/nvda <nvda@noreply.github.com>
Cc: Joseph Lee <joseph.lee22590@gmail.com>; Mention <mention@noreply.github.com>
Subject: Re: [nvaccess/nvda] Foobar2000: implement a custom status bar routine to fix playback status commands (#11087)

 

The line says:
# For more details see: https://www.gnu.org/licenses/gpl-2.0.htmlimport appModuleHandler

I don't think import appModuleHandler should be there :-)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub <https://github.com/nvaccess/nvda/pull/11087#issuecomment-622994969> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/AB4AXEEVZ7DPVKUHWFMIXRTRPRQTTANCNFSM4MXNUQEQ> .

2020-05-04 14:55 UTC, feerrenrut requested changes

2020-05-04 14:55 UTC, feerrenrut commented on source/appModules/foobar2000.py
> +		# #11082: retrieve status bar handle and resulting NVDA object from playlist window.
Could you add a comment to this method to explain why this implementation is preferred over the standard statusbar lookup.

2020-05-04 19:07 UTC, josephsl commented
Hi, part of that has to do with recursion limit – I’ll add a more friendly explanation of what I just said. Thanks.

 

From: Reef Turner <notifications@github.com> 
Sent: Monday, May 4, 2020 7:55 AM
To: nvaccess/nvda <nvda@noreply.github.com>
Cc: Joseph Lee <joseph.lee22590@gmail.com>; Mention <mention@noreply.github.com>
Subject: Re: [nvaccess/nvda] Foobar2000: implement a custom status bar routine to fix playback status commands (#11087)

 

@feerrenrut requested changes on this pull request.

  _____  

In source/appModules/foobar2000.py <https://github.com/nvaccess/nvda/pull/11087#discussion_r419498280> :

>  
-       def event_gainFocus(self, obj, nextHandler):
-              if not self.statusBar: self.statusBar=api.getStatusBar()
-              nextHandler()
+       def _get_statusBar(self):
+              # #11082: retrieve status bar handle and resulting NVDA object from playlist window.

Could you add a comment to this method to explain why this implementation is preferred over the standard statusbar lookup.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub <https://github.com/nvaccess/nvda/pull/11087#pullrequestreview-405066176> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/AB4AXECU67TNXOD7GVEM5L3RP3JNVANCNFSM4MXNUQEQ> .

2020-05-07 07:45 UTC, feerrenrut commented on source/appModules/foobar2000.py
> +		# If only default status bar routine is used to assign status bar object,
Do you mean that calling `api.getStatusBar()` from here leads to a recursion error? That's true, and was a concern when reviewing #9792. In the end I decided that any future work could split that function to break the recursion.

This is really a tangent to what I was trying to ask. The way that this works is different from `api.getStatusBar()`, is there a reason? In `api.getStatusBar()` we hit test 1 pixel up from the bottom of the foreground object and walk up the tree looking for the statusbar role. This implementation enumerates all child windows of the ForegroundObject looking for this particular class name.

2020-05-07 07:59 UTC, josephsl commented
Hi, on-screen method could have worked here. My concern was about attribute name and to better detect status bar from main window. Thanks.

 

From: Reef Turner <notifications@github.com> 
Sent: Thursday, May 7, 2020 12:46 AM
To: nvaccess/nvda <nvda@noreply.github.com>
Cc: Joseph Lee <joseph.lee22590@gmail.com>; Mention <mention@noreply.github.com>
Subject: Re: [nvaccess/nvda] Foobar2000: implement a custom status bar routine to fix playback status commands (#11087)

 

@feerrenrut commented on this pull request.

  _____  

In source/appModules/foobar2000.py <https://github.com/nvaccess/nvda/pull/11087#discussion_r421304188> :

> @@ -46,6 +46,8 @@ class AppModule(appModuleHandler.AppModule):
 
        def _get_statusBar(self):
               # #11082: retrieve status bar handle and resulting NVDA object from playlist window.
+              # If only default status bar routine is used to assign status bar object,

Do you mean that calling api.getStatusBar() from here leads to a recursion error? That's true, and was a concern when reviewing #9792 <https://github.com/nvaccess/nvda/pull/9792> . In the end I decided that any future work could split that function to break the recursion.

This is really a tangent to what I was trying to ask. The way that this works is different from api.getStatusBar(), is there a reason? In api.getStatusBar() we hit test 1 pixel up from the bottom of the foreground object and walk up the tree looking for the statusbar role. This implementation enumerates all child windows of the ForegroundObject looking for this particular class name.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub <https://github.com/nvaccess/nvda/pull/11087#pullrequestreview-407224147> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/AB4AXEHEDYM6ED4QV2PF6ZLRQJRKFANCNFSM4MXNUQEQ> .

2020-05-08 14:25 UTC, feerrenrut commented
> and to better detect status bar from main window

But can you explain why this approach is better?

2020-05-08 17:32 UTC, josephsl commented
Hi,

The biggest advantage is looking at status bar that is located somewhere other than bottom left.

After thinking about this, I think it would be best to go with renaming the attribute (option 1) due to 2020.2 beta preparation. I'll submit a different PR that should resolve this (and an advice for fututre committers: when adding or chanigng class attributes, be sure to check everywhere in the source code (or relevant sectino) to make sure this kind of regression is minimized).

Thanks.

2020-05-08 17:32 UTC, closed without merging