Various typo and spelling fixes in user guide
nvaccess/nvda pull request #11193
Opened 2020-05-24 16:28 UTC by codeofdusk

### Link to issue number:
None.

### Summary of the issue:
* The user guide contained various typos (arived, promt, carret).
* English spelling conventions were not followed consistently (behavior/behaviour, center/centre, color/colour, etc) in the user guide.
* Both addon and add-on were used to refer to NVDA add-ons in the user guide.

### Description of how this pull request fixes the issue:
* Corrected the typos and spelling errors.
* Resolved spelling variation conflicts to the [Oxford spelling](https://en.wikipedia.org/wiki/Oxford_spelling) variants.
* Changed mentions of addon in running text to add-on.

### Testing performed:
None.

### Known issues with pull request:
None.

### Change log entry:
None.

2020-05-24 16:29 UTC, codeofdusk commented
Cc @feerrenrut, @Qchristensen.

2020-06-03 08:43 UTC, feerrenrut approved these changes
Thanks @codeofdusk 

A spell check lint tool would be pretty useful for the user-guide  / changes file / other docs!

2020-06-03 08:45 UTC, merged

2020-06-03 08:48 UTC, Qchristensen requested changes
All looks good, thank you.  Just that one change I wanted to suggest (notification area rather than notification centre / center)

2020-06-03 08:48 UTC, Qchristensen commented on user_docs/en/userGuide.t2t
> +- Toast notifications have been introduced in Windows 10 and appear in the notification centre in the system tray, informing about several events (i.e. if an update has been downloaded, a new e-mail
Microsoft Style Guide indicates the term should be "notification area" (rather than notification centre or other temrs).

2020-06-03 08:48 UTC, Qchristensen commented on user_docs/en/userGuide.t2t
> +- Toast notifications have been introduced in Windows 10 and appear in the notification centre in the system tray, informing about several events (i.e. if an update has been downloaded, a new e-mail
Link to Style Guide section on notification area: https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/n/notification-area

2020-06-03 21:18 UTC, XLTechie commented
If it is to be notification area, I think it should be "notification area of the 
system tray" not "notification area in the system tray".


On Wed, 3 Jun 2020, Quentin Christensen wrote:

> 
> @Qchristensen requested changes on this pull request.
> 
> All looks good, thank you. Just that one change I wanted to suggest (notification area rather than notification centre / center)
> 
> ____________________________________________________________________________________________________________________________________________________________
> 
> In user_docs/en/userGuide.t2t:
> 
> > @@ -1553,7 +1553,7 @@ Many Windows and controls show a small message (or tooltip) when you move the mo
>  ==== Report notifications ====[ObjectPresentationReportNotifications]
>  This checkbox, when checked, tells NVDA to report help balloons and toast notifications as they appear.
>  - Help Balloons are like tooltips, but are usually larger in size, and are associated with system events such as a network cable being unplugged, or perhap
> s to alert you about Windows security issues.
> -- Toast notifications have been introduced in Windows 10 and appear in the notification center in the system tray, informing about several events (i.e. if 
> an update has been downloaded, a new e-mail arived in your inbox, etc.).
> +- Toast notifications have been introduced in Windows 10 and appear in the notification centre in the system tray, informing about several events (i.e. if 
> an update has been downloaded, a new e-mail arrived in your inbox, etc.).
> 
> Microsoft Style Guide indicates the term should be "notification area" (rather than notification centre or other temrs).
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or
> unsubscribe.[AB6DH4DGW443BMR5OPSGGVDRUYE6RA5CNFSM4NI6PDYKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGODE53EQY.gif]
> 
> 
>