Added clarification that ctrl+enter activates the element containing formula in Math content
nvaccess/nvda pull request #11226
Opened 2020-06-03 16:33 UTC by Adriani90

### Link to issue number:
none
### Summary of the issue:
As discussed in #11215, when Math ML is a button containing formula but the button itself can be activated to display a separate dialog, enter or space is not working because this is already used by Math ML to enter the formula. So in this case to activate the element and to display the dialog, an user must press ctrl+enter instead.

### Description of how this pull request fixes the issue:
Documented this properly in chapter 7.1.

### Testing performed:
Tested in different browsers on the website provided in issue #11215 and also on other websites with Math ML in elements that ctrl+enter activates the elements.

### Known issues with pull request:
None

### Change log entry:
Not needed.

2020-06-12 09:51 UTC, Qchristensen approved these changes
Is there an extra space in between "the" and "formula" on line 649?  Otherwise, reads well.

2020-06-12 13:09 UTC, feerrenrut requested changes

2020-06-12 13:09 UTC, feerrenrut commented on user_docs/en/userGuide.t2t
> +To activate the button or the element containing the  formula, press ctrl+enter.
As per @Qchristensen comment, there is a double space here.

```suggestion
To activate the button or the element containing the formula, press ctrl+enter.

```

2020-06-16 08:33 UTC, feerrenrut approved these changes

2020-06-16 08:34 UTC, merged