Update CLDR to version 37
nvaccess/nvda pull request #11306
Opened 2020-06-26 23:32 UTC by dingpengyu

### Link to issue number:
#11303  
### Summary of the issue:
Update CLDR to version 37
### Description of how this pull request fixes the issue:
Synchronize the latest official CLDR version
### Testing performed:
The local environment has been used to compile and test, and the build is completed.
### Known issues with pull request:
none
### Change log entry:

Section: Changes
- Update CLDR to version 37. (#11303)
thanks

2020-06-27 00:21 UTC, OzancanKaratas requested changes
Please update the readme reference.

After updating, this pull request can be merged and fixes #11303.

2020-06-27 00:23 UTC, josephsl commented
Hi, for whoever is going to merge this, I think it would be best to cherry-pick rather than a squash merge due to what’s new edits. Thanks.

 

From: Ozancan Karataş <notifications@github.com> 
Sent: Friday, June 26, 2020 5:21 PM
To: nvaccess/nvda <nvda@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: Re: [nvaccess/nvda] Update CLDR to version 37 (#11306)

 

@OzancanKaratas requested changes on this pull request.

Please update the readme reference.

After updating, this pull request can be merged and fixes #11303 <https://github.com/nvaccess/nvda/issues/11303> .

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub <https://github.com/nvaccess/nvda/pull/11306#pullrequestreview-438653524> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/AB4AXEFWJMW2XLZXHT2FVVLRYU3QFANCNFSM4OJXVPLQ> .

2020-06-27 06:26 UTC, LeonarddeR submitted a review, later dismissed

2020-06-27 06:26 UTC, leonardder commented on user_docs/en/changes.t2t
> +- Update CLDR to version 37. (#11303)
Please revert this change. What's new is dealt with by NV Access at merge time.

```suggestion
```

2020-06-30 10:52 UTC, feerrenrut approved these changes
This seems fine to me, the actions from @leonardder have been addressed.

2020-06-30 12:08 UTC, merged