nvwave: make idle close delay configurable
nvaccess/nvda pull request #11481
Opened 2020-08-10 22:48 UTC by codeofdusk

### Link to issue number:
https://github.com/nvaccess/nvda/pull/11024#issuecomment-625802805

### Summary of the issue:
In #11024, some users asked for the ability to increase the default timeout of 10 seconds for holding open the audio device. This would improve performance on systems with newer Realtek audio chipsets at the cost of some battery power. Others asked to decrease or disable the delay, as their systems do not exhibit this issue and there is concern that holding open the audio device in this way might use more power.

### Description of how this pull request fixes the issue:
Adds a new advanced setting for configuring the idle close delay, and replaces the `IDLE_CLOSE_DELAY` constant in `nvwave` with references to this new setting.

### Testing performed:
Added a beep in `nvwave._close` and observed that it played according to user-configured values of the `idleCloseDelay` setting.

### Known issues with pull request:
None.

### Change log entry:
Add a second sub-point to the #11024 entry:
  - This timeout is 10 seconds by default, but it is configurable in advanced settings.

2020-08-10 22:50 UTC, codeofdusk commented
Cc @feerrenrut @jcsteh @leonardder @michaelDCurran @neurrone

2020-08-11 04:14 UTC, Adriani90 commented
This needs also documentatiom in the user guide, including a statement that chamging it can shorten the batery time.

2020-08-11 06:12 UTC, LeonarddeR requested changes

2020-08-11 06:12 UTC, leonardder commented on source/config/configSpec.py
> +	idleCloseDelay = integer(default=10000,min=0,max=86400000)
Wow, a day is a bit long isn't it? May be leave out the max, or set it somewhere around an hour.

2020-08-11 06:12 UTC, leonardder commented on source/gui/settingsDialogs.py
> +			min=0,
I believe there is logic to get this from config. Search for usage of `config.conf.getConfigValidation`

2020-08-11 06:12 UTC, leonardder commented on source/nvwave.py
> +					if config.conf["audio"]["idleCloseDelay"]:
I think this can be made one if statement with the closeWhenIdle check

2020-08-11 06:12 UTC, leonardder commented on user_docs/en/userGuide.t2t
> +By default, NVDA keeps the device open for 10,000 ms (10 seconds) after a speech utterence to improve performance on these systems.
SHouldn't Utterence be utterance?

```suggestion
By default, NVDA keeps the device open for 10,000 ms (10 seconds) after a speech utterance to improve performance on these systems.
```

2020-08-11 06:12 UTC, leonardder commented on user_docs/en/userGuide.t2t
> +Setting the delay to 0 causes NVDA to close the device immediately after each utterence, matching the behaviour of version 2020.2 and earlier.
```suggestion
Setting the delay to 0 causes NVDA to close the device immediately after each utterance, matching the behaviour of version 2020.2 and earlier.

```

2020-08-11 06:53 UTC, Brian1Gaff commented
I understand most people with this issue now use that silencio program that 
keeps it open with silence played at all times.
 Jaws seems to now have something like that built in. None of the many 
suggestions on here address the wake up issue and truncating, they just give 
it a longer time out. Just how much power is saved by shutting down the 
player?
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message ----- 
From: "Bill Dengler" <notifications@github.com>
To: "nvaccess/nvda" <nvda@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Sent: Monday, August 10, 2020 11:48 PM
Subject: [nvaccess/nvda] nvwave: make idle close delay configurable (#11481)


> &lt;!--
> Please fill in the following template, for an explanation of the sections 
> see:
> https://github.com/nvaccess/nvda/wiki/Github-pull-request-template-explanation-and-examples
> --&gt;
>
> ### Link to issue number:
> https://github.com/nvaccess/nvda/pull/11024#issuecomment-625802805
>
> ### Summary of the issue:
> In #11024, some users asked for the ability to increase the default 
> timeout of 10 seconds for holding open the audio device. This would 
> improve performance on systems with newer Realtek audio chipsets at the 
> cost of some battery power. Others asked to decrease or disable the delay, 
> as their systems do not exhibit this issue and there is concern that 
> holding open the audio device in this way might use more power.
>
> ### Description of how this pull request fixes the issue:
> Adds a new advanced setting for configuring the idle close delay, and 
> replaces the `IDLE_CLOSE_DELAY` constant in `nvwave` with references to 
> this new setting.
>
> ### Testing performed:
> Added a beep in `nvwave._close` and observed that it played according to 
> user-configured values of the `idleCloseDelay` setting.
>
> ### Known issues with pull request:
> None.
>
> ### Change log entry:
> Add a second sub-point to the #11024 entry:
>  - This timeout is 10 seconds by default, but it is configurable in 
> advanced settings.
> You can view, comment on, or merge this pull request online at:
>
>  https://github.com/nvaccess/nvda/pull/11481
>
> -- Commit Summary --
>
>  * nvwave: make idle close delay configurable.
>
> -- File Changes --
>
>    M source/config/configSpec.py (1)
>    M source/gui/settingsDialogs.py (24)
>    M source/nvwave.py (32)
>    M user_docs/en/userGuide.t2t (9)
>
> -- Patch Links --
>
> https://github.com/nvaccess/nvda/pull/11481.patch
> https://github.com/nvaccess/nvda/pull/11481.diff
>
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/pull/11481
>

2020-08-11 08:46 UTC, feerrenrut commented
Introducing configuration here increases the maintenance and support costs of NVDA. It's another way that end users can introduce variability into their installation. Instead we should aim to get the default value right in this case.

It only seems to be an assumption that releasing the audio device will save power. I suspect what the operating system does with physical devices (for power saving) is quite separate from what NVDA does here (calling `winmm.waveOutOpen`). Even if NVDA didn't call `winmm.waveOutClose` until termination, I wouldn't be surprised if the operating system is able to optimize power usage significantly. In addition, I suspect that the act of industrializing libraries, allocating memory etc while calling open/close regularly uses more power than just doing it once. In the absence of data we are just guessing, and possibly doing more harm than good.

Without supporting evidence to show that this does indeed save power, or solve some other problem, I propose that this PR be closed.

Typically an issue should be created so that we can have this discussion before the work is completed.

2020-08-11 08:46 UTC, closed without merging

2020-08-12 04:47 UTC, Neurrone commented
I don't think we're going to be able to have a default that will suit everyone due to the nature of the problem.

10 seconds is far from optimal, because it is easy to encounter a situation where no speech is spoken for more than 10 seconds, then have the first part of speech being cut off the next time that NVDA speaks.

If we want to choose a default that will definitely work, it should be set to a much longer value, especially if there are doubts about whether leaving the audio device on consumes more power.

Another point to consider is that for bluetooth headphones, leaving it on does cause its battery to drain faster.

2020-08-12 04:49 UTC, Neurrone commented
The ideal solution would to get Microsoft to either fix this themselves if they can, or put their foot down regarding this behaviour and make it a hard failure when certifying audio drivers for example. Sadly I don't ever see this happening, not sure who would even be the right person to contact.

This is a plague and screen reader users are far from the only users who're affected.

2020-08-12 04:54 UTC, jcsteh commented
It'd be interesting to know whether the closeWhenIdle change actually helps
those Bluetooth headsets which really aggressively power save. The
Bluetooth Audio add-on sends silence to deal with these headsets. In
contrast, the closeWhenIdle change does not send silence; it just delays
before closing the device. While that does fix one class of problem, I make
no guarantees that it fixes the Bluetooth headset problem, since I don't
have such a device to test.

2020-08-12 07:13 UTC, feerrenrut commented
> While that does fix one class of problem, I make
no guarantees that it fixes the Bluetooth headset problem, since I don't
have such a device to test.

I can confirm, this change does NOT solve the problem you describe with my BT headset.

2020-08-13 02:23 UTC, jcsteh commented
We could probably change the current implementation to play silence instead
of just keeping the device open. It shouldn't have a significant perf
impact and it would fix a broader set of problems.

2020-08-13 02:46 UTC, codeofdusk commented
> We could probably change the current implementation to play silence instead
of just keeping the device open.

Sounds good to me, but in that case I strongly vote to reopen this PR.