Hide option to show braille messages indefinitely when messages timeout is set to 0
nvaccess/nvda pull request #11602
Opened 2020-09-14 09:29 UTC by dawidpieper

### Summary of the issue:
When user sets braille messages timeout to 0, option to show them indefinitely still appears. Its checking does not take any effect, though. I found it confusing for some people.

### Description of how this pull request fixes the issue:
When braille messages timeout is set to 0, the option to show them indefinitely is hidden.

### Testing performed:
All tests passed.

### Known issues with pull request:
None yet

### Change log entry:

Changes
When message timeout in Braille settings is set to 0, option to show messages indefinitely is hidden

2020-09-14 12:59 UTC, feerrenrut commented
It may not be immediately obvious why this control is missing.

Instead, perhaps the following approach:
- Use a comboBox "Show braille messages", with options: "Disable", "Use timeout", "Show indefinitely"
- When "Show indefinitely" is selected, then the timeout control is enabled, otherwise it is disabled.

Also, please check the user guide and confirm that it describes these options well (or needs changes).

2020-09-14 13:25 UTC, dawidpieper commented
Thank you, I think it would be a good approach. I'll try to prepare it tomorrow.

2020-09-14 20:49 UTC, XLTechie commented
I'm slightly confused by this:

>  *  Use a comboBox "Show braille messages", with options: "Disable", "Use timeout", "Show indefinitely"
>  *  When "Show indefinitely" is selected, then the timeout control is enabled, otherwise it is disabled.

Why would the timeout control be available while "Show indefinitely" is 
selected, instead of while "Use timeout" is selected?

If I was using this option, I would expect "Use timeout" to give me control over 
what the timeout was, not the other way around.

Now, I don't use any braille options, so I am maybe missing an important factor, 
but just thinking about it logically.

2020-09-14 22:38 UTC, dawidpieper commented
I may be wrong, but I suppose it was a small error in the comment.

2020-09-15 15:05 UTC, feerrenrut commented
> If I was using this option, I would expect "Use timeout" to give me control over
what the timeout was, not the other way around.

Yes, you are correct. I guess I was thinking one thing and typing another. I'll edit the comment to avoid any future confusion.

2020-09-17 14:36 UTC, feerrenrut requested changes
Generally looks good, thanks @dawidpieper

2020-09-17 14:36 UTC, feerrenrut commented on source/gui/settingsDialogs.py
> +			minTimeout = 1
If you decide to keep it like this, it is probably a good idea to add a comment to the config spec to document what 0 means. Search for `messageTimeout` in the config spec to find it.

2020-09-22 19:03 UTC, dawidpieper commented
I've harcoded 1 as a minimum value. I don't know what is the main policy for config specs - readability or simplicity. I can also change config specs and prepare upgrade as suggested, if it is the preferred way.

2020-10-06 15:34 UTC, feerrenrut approved these changes
Thanks @dawidpieper

2020-10-06 15:37 UTC, merged