Fix up of 11738: Force UIA for BrokenCommctrl5Item controls, even though they don't support UIA natively
nvaccess/nvda pull request #11828
Opened 2020-11-10 20:05 UTC by lukaszgo1

### Link to issue number:
Fixes #11797
### Summary of the issue:
In #11738 before using UIA for a particular control we added a check to ensure that the control in question supports UIA natively. This unfortunately broke access to tree view items used in Windows HTML help since for these controls we're using UIA explicitly even  though they're not native (MSAA is broken for them).

### Description of how this pull request fixes the issue:
I've added additional kwarg to `UIA.kwargsFromSuper` which allows to disable this check for a particular control and disabled it for `BrokenCommctrl5Item`. While at it I've also made error logged when we cannot get UIA element for these tree view items an error rather than debugWarning to make debugging such issues easier in the future.
### Testing performed:
Ensured that tree view items in HTML help are once again readable.
### Known issues with pull request:
None known
### Change log entry:
None needed - this bug is not in a release yet.

2020-11-10 20:13 UTC, lukaszgo1 commented
cc @michaelDCurran

2020-11-10 22:42 UTC, michaelDCurran requested changes

2020-11-10 22:42 UTC, michaelDCurran commented on source/NVDAObjects/UIA/__init__.py
> +			if not UIAHandler.handler.isNativeUIAElement(UIAElement) and ignoreNonNativeElementsWithFocus:
Please check ignoreNonnativeElementWithFocus before calling isNativeUIAElement, as the isNativeUIAElement call is more costly.

2020-11-11 10:45 UTC, lukaszgo1 commented
@michaelDCurran Done.

2020-11-12 01:00 UTC, michaelDCurran approved these changes

2020-11-12 01:00 UTC, merged