Suppress duplicate Visual Studio tooltips
nvaccess/nvda pull request #11841
Opened 2020-11-18 13:31 UTC by leonardder

### Link to issue number:
Closes #11611 

### Summary of the issue:
In Visual Studio, the tooltip opened event is fired twice for IntelliSense popups.

### Description of how this pull request fixes the issue:
In an overlay class, ignore the event if it was fired less than 0.2 seconds ago and had the same name.

### Testing performed:
Tested that tool tips are only announced once.

### Known issues with pull request:
None
### Change log entry:
* Bug fixes
    + In Visual Studio, IntelliSense tool tips that provide additional details about the currently selected IntelliSense item are now only reported once. (#11611)

2020-11-20 07:51 UTC, feerrenrut commented
Can you expand on how you chose 0.2 seconds?

2020-11-20 07:59 UTC, feerrenrut requested changes

2020-11-20 07:59 UTC, feerrenrut commented on source/NVDAObjects/UIA/VisualStudio.py
> +		if newText == oldText and oldTime is not None and (newTime - oldTime) < 0.2:
I think this really needs a comment to explain why this is done.

For instance, it is probably worth pointing out that a user may intentionally be trying to hear the same tooltip twice, hence the 0.2 seconds. I think the value could be larger (eg 1 second). Given that the text must be equal consecutively, we should look to approach the limit of how rapidly a user could ever intentionally try to trigger the same tooltip twice in a row.

2020-11-20 08:55 UTC, leonardder commented
> Can you expand on how you chose 0.2 seconds?

This was by trial and error, I was looking for a small window. I can give a more in depth rationalisation based on logging if you desire.

> I think the value could be larger (eg 1 second).

I was just looking for the smallest window. This was actually mostly copied from the should accept UIA live region code, however there, the interval was 0.5 seconds. I could think of situations where one would rapidly arrow back and forth between IntelliSense items, so my feeling says one second might be too much.

2020-11-24 09:04 UTC, feerrenrut commented
> I could think of situations where one would rapidly arrow back and forth between IntelliSense items

In this case the `newText == oldText` test should fail though, right?

2020-11-24 09:48 UTC, leonardder commented
> 
> 
> > I could think of situations where one would rapidly arrow back and forth between IntelliSense items
> 
> In this case the `newText == oldText` test should fail though, right?

Not in the following situation:

1. Item a has focus, tool tip is shown
2. User presses down arrow, item b is focused but tool tip takes a little while to come up
3. Before the tool tip comes up, user presses up arrow. Item a gets focus again, but tool tip is ignored if the time range is too long.

2020-11-26 05:18 UTC, feerrenrut commented
Ok, yes that situation needs to be considered too. 

Could we tie this to input somehow? EG make this longer timeout, but reset when there is keyboard input?

2020-11-26 06:58 UTC, leonardder commented
> Could we tie this to input somehow? EG make this longer timeout, but reset when there is keyboard input?

I'm afraid that's pretty hacky. Not sure whether to register the reset, then.

2020-11-26 08:42 UTC, feerrenrut commented
I don't think there is any other reasonable heuristic we can use to determine whether the tooltip showing is the user's intention. But basing this solely on keyboard input would exclude low-vision mouse users.

I think for now we can accept this PR the way it is, hopefully this workaround improves the outcome most of the time. For users on slower computers (or under-load or with different tooltip settings) the timeout may not be appropriate. Perhaps one step better is to make the timeout an advanced configuration.

There is a certain argument that problems like this should be left exposed so they are more obvious and get fixed in the 3rd party application (Visual Studio in this case), however we should be able to replicate this issue with accEvent and request a fix from Microsoft.

2020-11-26 09:04 UTC, leonardder commented
> There is a certain argument that problems like this should be left exposed so they are more obvious and get fixed in the 3rd party application (Visual Studio in this case), 

Agreed, but it is pretty irritating for daily users.

> however we should be able to replicate this issue with accEvent and request a fix from Microsoft.

I will try to contact Dante Gange about this.

2020-11-27 07:17 UTC, feerrenrut requested changes

2020-11-27 07:17 UTC, feerrenrut commented on source/NVDAObjects/UIA/VisualStudio.py
> +		super().event_UIA_toolTipOpened()
I'd like to clarify this block.
```suggestion
	_lastToolTipOpenedInfo = (None, None)  #: Keeps track of the last ToolTipOpened event (text, time)
	_preventDuplicateToolTipSeconds = 0.2 #: The duplicate tooltip events will be dropped within this time window

	def event_UIA_toolTipOpened(self):
		oldText, oldTime = self._lastToolTipOpenedInfo
		newText = self.name
		newTime = time.time()
		self.__class__._lastToolTipOpenedInfo = (newText, newTime)
		withinPossibleDupToolTipTimeWindow = (
			oldTime is not None
			and (newTime - oldTime) < _preventDuplicateToolTipSeconds
		)
		if newText == oldText and withinPossibleDupToolTipTimeWindow:
			# Tool-tip event suspected to be a duplicate, drop the event.
			# - Users attempting to rapidly re-announce tool-tips may
			#   have the announcement erroneously  suppressed
			# - Users on slower systems (or systems under load) may still
			#   receive duplicate announcements
			return
		super().event_UIA_toolTipOpened()
```

2020-11-27 08:16 UTC, feerrenrut submitted a review, later dismissed
Thanks @leonardder

2020-11-27 08:49 UTC, feerrenrut submitted a review, later dismissed

2020-11-27 09:01 UTC, feerrenrut approved these changes

2020-11-27 09:44 UTC, merged