Update liblouis to 3.16.0
nvaccess/nvda pull request #11888
Opened 2020-12-01 14:13 UTC by Andre9642

### Link to issue number:
Fixes #11013
Fixes #11754

### Summary of the issue:
[Liblouis 3.16.0 has just been released](https://github.com/liblouis/liblouis/tree/v3.16.0).

### Description of how this pull request fixes the issue:
- Updates the liblouis submodule (commit 10eda61).
- Changes the readme.
- Adds the following braille tables to the interface:
  - Bashkir grade 1
  - Russian grade 1
  - Russian grade 1 (detailed)
- Removes the ru-ru-g1.utb entry

### Testing performed:
Tested from source.

### Known issues with pull request:
None

### Change log entry:
* Changes
  - Updated liblouis braille translator to [3.16.0](https://github.com/liblouis/liblouis/releases/tag/v3.16.0)

2020-12-01 14:31 UTC, zstanecic commented
@leonardder

Please give a review to this. I remember, when Russian eight dots table was added in the past, that the mentioned removed entry was needed, due to the upgrade from the older NVDA releases.

Sorry for being so brutal, but I think that in the future something needs to be done, so that NVDA can automatically discover liblouis tables. Now we have a problem in which we need to do this manually for every table, which is not so good.

 

From: André-Abush Clause <notifications@github.com> 
Sent: Tuesday, December 1, 2020 3:14 PM
To: nvaccess/nvda <nvda@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: [nvaccess/nvda] Update liblouis to 3.16.0 (#11888)

 


Link to issue number:


Fixes #11013 <https://github.com/nvaccess/nvda/issues/11013> 
Fixes #11754 <https://github.com/nvaccess/nvda/issues/11754> 


Summary of the issue:


Liblouis 3.16.0 has just been released <https://github.com/liblouis/liblouis/tree/v3.16.0> .


Description of how this pull request fixes the issue:


*	Updates the liblouis submodule (commit 10eda61).
*	Changes the readme.
*	Adds the following braille tables to the interface: 

*	Bashkir grade 1
*	Russian grade 1
*	Russian grade 1 (detailed)

*	Removes the ru-ru-g1.utb entry


Testing performed:


Tested from source.


Known issues with pull request:


None


Change log entry:


*	Changes 

*	Updated liblouis braille translator to 3.16.0 <https://github.com/liblouis/liblouis/releases/tag/v3.16.0> 

  _____  


You can view, comment on, or merge this pull request online at:


  https://github.com/nvaccess/nvda/pull/11888


Commit Summary


*	Update liblouis to 3.16.0


File Changes


*	M include/liblouis <https://github.com/nvaccess/nvda/pull/11888/files#diff-d1bd0c73c6ef0713c79cd78381549978a4f2ed14cbe19d6098bdf830038c1671>  (2) 
*	M readme.md <https://github.com/nvaccess/nvda/pull/11888/files#diff-5a831ea67cf5cf8703b0de46901ab25bd191f56b320053be9332d9a3b0d01d15>  (2) 
*	M source/brailleTables.py <https://github.com/nvaccess/nvda/pull/11888/files#diff-4c2d7b76d745a3e0037b5dd1d8faebb85299f5c2e481a24e2dddb71ad5e9451c>  (9) 


Patch Links:


*	https://github.com/nvaccess/nvda/pull/11888.patch
*	https://github.com/nvaccess/nvda/pull/11888.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub <https://github.com/nvaccess/nvda/pull/11888> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/ACVCDE5KFV2FK4N2Y6T2OBTSST2ZLANCNFSM4UJCU6KA> .  <https://github.com/notifications/beacon/ACVCDE6PMFAMVCMW5VRTH53SST2ZLA5CNFSM4UJCU6KKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4LHXVSPA.gif>

2020-12-01 14:34 UTC, leonardder commented
> 
> ### Link to issue number:
> 
> Fixes #11013
> Fixes #11754
> ### Summary of the issue:
> 
> [Liblouis 3.16.0 has just been released](https://github.com/liblouis/liblouis/tree/v3.16.0).
> ### Description of how this pull request fixes the issue:
> 
>     * Updates the liblouis submodule (commit 10eda61).
> 
>     * Changes the readme.
> 
>     * Adds the following braille tables to the interface:
>       
>       * Bashkir grade 1
>       * Russian grade 1
>       * Russian grade 1 (detailed)
> 
>     * Removes the ru-ru-g1.utb entry
> 
> 
> ### Testing performed:
> 
> Tested from source.
> ### Known issues with pull request:
> 
> None
> ### Change log entry:
> 
>     * Changes
>       
>       * Updated liblouis braille translator to [3.16.0](https://github.com/liblouis/liblouis/releases/tag/v3.16.0)

2020-12-01 14:35 UTC, leonardder commented
Ugh, I"m sorry for going so wild on my keyboard

2020-12-01 14:37 UTC, leonardder commented
> Sorry for being so brutal, but I think that in the future something needs to be done, so that NVDA can automatically discover liblouis tables. Now we have a problem in which we need to do this manually for every table, which is not so good.

I think you're not brutal at all but bringing up a fair point. There's an issue for that, see #11298 
There is #290 as well, which is slightly related.

2020-12-01 14:43 UTC, leonardder requested changes
1. Why is input disabled for the russian tables? I think it would be good to have a rationale in a comment.
2. Given this release fixes two issues related to crashes and doesn't contain many additional changes to the core, I think we should consider shipping this with 2020.4. The beta period should be long enough to revert if it really breaks. cc @feerrenrut

2020-12-01 15:03 UTC, Andre9642 commented
> 1. Why is input disabled for the russian tables? I think it would be good to have a rationale in a comment.

I simply used provided metadata to add these tables:

```
(0)$ cat ru-litbrl.ctb | grep "#+"
#+locale: ru
#+type: literary
#+dots: 6
#+contraction: no
#+direction: forward
(0)$ cat ru-litbrl-detailed.utb|grep "#+"
#+locale: ru
#+type: literary
#+dots: 6
#+contraction: no
#+direction: forward
#+variant: detailed
(0)$ ```

Any thought @Futyn-Maker?

> 2. Given this release fixes two issues related to crashes and doesn't contain many additional changes to the core, I think we should consider shipping this with 2020.4. The beta period should be long enough to revert if it really breaks.

👍

2020-12-01 15:13 UTC, Futyn-Maker commented
Hello contributers! Iwas waiting for this PR. The couple of words about Russian tables:

1. At the moment I'm not ready to develop the back translation according to rules of the Russian literary braille, it's quite difficult, so this table only for reading now, it's all right.
2. I recommend to add all tables - `ru-litbrl.ctb` and `ru-litbrl-detailed.utb` to provide user's choice.

Andrey

2020-12-01 20:03 UTC, Futyn-Maker commented
I also would like to know if it is possible to replace "grade 1" with "literary braille" in the UI, or it can be done separate for the Russian localization. The reason is that we don't use contracted braille almost at all, so names "computer braille" and "literary braille" can be more understandable for end users than "grade 1", because there's no any gradation in fact. But it's not super important.

2020-12-01 21:41 UTC, Futyn-Maker commented
Thanks. As for me, looks good.

2020-12-04 15:23 UTC, leonardder commented
Added milestone 2020.4 for @feerrenrut or @michaelDCurran to triage.

2020-12-04 15:23 UTC, leonardder submitted a review, later dismissed

2020-12-04 18:52 UTC, zstanecic commented
Hi,

My review comment

Please add a Coptic table in scope of this PR. The maintainer asked about this on the mailing list.

 

From: Leonard de Ruijter <notifications@github.com> 
Sent: Friday, December 4, 2020 4:24 PM
To: nvaccess/nvda <nvda@noreply.github.com>
Cc: zstanecic <zvonimirek222@yandex.com>; Mention <mention@noreply.github.com>
Subject: Re: [nvaccess/nvda] Update liblouis to 3.16.1 (#11888)

 

Added milestone 2020.4 for @feerrenrut <https://github.com/feerrenrut>  or @michaelDCurran <https://github.com/michaelDCurran>  to triage.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub <https://github.com/nvaccess/nvda/pull/11888#issuecomment-738843692> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/ACVCDE7WHBCVX6ICJNX5NETSTD5HJANCNFSM4UJCU6KA> .  <https://github.com/notifications/beacon/ACVCDE2AS6PSVTNKBEVLOS3STD5HJA5CNFSM4UJCU6KKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFQE5YLA.gif>

2020-12-04 20:04 UTC, Andre9642 commented
@zstanecic In my opinion, Leonard should have added this braille table in #11537.
Although I think it's out of scope for this PR, I am in favor of adding it. Should we make another pull request?

2020-12-04 23:36 UTC, lukaszgo1 commented
Changelog entry for this one should probably mention the newly added tables.

2020-12-05 10:17 UTC, codeofdusk commented
I support merging this into 2020.4, so that the NVDA and Liblouis stable versions become once again in sync.

2020-12-08 01:00 UTC, michaelDCurran submitted a review, later dismissed

2020-12-08 01:30 UTC, feerrenrut commented
If we want this in 2020.4, it will need to be retargeted to beta

2020-12-08 03:51 UTC, michaelDCurran approved these changes

2020-12-08 05:01 UTC, merged