Fix isCurrent errors for Internet Explorer
nvaccess/nvda pull request #12066
Opened 2021-02-11 04:58 UTC by feerrenrut

### Link to issue number:
Fixes #12055

### Summary of the issue:
Errors raised after unhandled value of 'None' for aria-current

### Description of how this pull request fixes the issue:
Handles None value, mapping to isCurrent.No

### Testing strategy:
Manually tested with http://test-cases.tink.uk/aria-current/
In browse mode and focus mode

### Known issues with pull request:
None

### Change log entry:
None

### Code Review Checklist:

This checklist is a reminder of things commonly forgotten in a new PR.
Please do a self-review to check these items.
Reviewers will not approve the PR until these are met.

- [ ] Pull Request description is up to date.
- [ ] Unit tests.
- [ ] System (end to end) tests.
- [ ] Manual tests.
- [ ] User Documentation.
- [ ] Change log entry.
- [ ] Context sensitive help for GUI changes.

2021-02-12 11:03 UTC, lukaszgo1 approved these changes, later dismissed
Many thanks for this PR!

2021-02-13 09:39 UTC, feerrenrut commented
There is still some underlying issue. When an exception is thrown here there is some kind of cyclic reference created. I haven't tracked down the cause of it yet. 

This PR can be merged, but there will need to be a follow up to find the true cause of the issue.

2021-02-14 22:05 UTC, michaelDCurran requested changes

2021-02-14 22:05 UTC, michaelDCurran commented on source/virtualBuffers/MSHTML.py
> +			log.debugWarningdebugWarning(f"Unknown aria-current value: {ariaCurrentValue}")
Typo here:
```suggestion
			log.debugWarning(f"Unknown aria-current value: {ariaCurrentValue}")
```

2021-02-21 21:35 UTC, michaelDCurran approved these changes

2021-02-23 02:49 UTC, merged