Fixed an issue preventing chat message to be reported in some versions of Skype for Business.
nvaccess/nvda pull request #12122
Opened 2021-03-04 23:02 UTC by CyrilleB79

### Link to issue number:

Fixes #9295

### Summary of the issue:

In Skype for Business (at least Office 2016, version 16.0.5095.1000), the incoming messages are not reported and an error occurs in the log instead.
This error show that the message has a value set to None whereas the code expects a string in order to parse it.
(cf. https://github.com/nvaccess/nvda/issues/9295#issuecomment-785114245 for more details)

### Description of how this pull request fixes the issue:

* If the message value is None, parse only the message name to split the content from author and timestamp parts. For this, we just look at ", , " separators.
* If the message is not None, use as previously the message name and the message value to split author, content and timestamp of the message.

I suppose that the message value may be None or not according to Skype / Lync version. I do not had the opportunity to check however on other Skype / Lync version.

I did not remove the old way to do because of the following comment:
> `# Example string: "Michael Curran : , , Hello\r\n\r\nThis is a test , 10:45 am."`
In this comment, we can see that there is no ', , ' separator between content and timestamp. Did it change between various versions of Skype / Lync? Or is the example in the comment just not correct? Since I do not know, I have kept the two paths.

### Testing strategy:

* Tested on Skype for Business, Office 2016, version 16.0.5095.1000).
* Would need to be tested on other versions: Lync (Office 2013), Office 365
* It does not seem to me that unit tests are required for such modifications.
* I do not think that we have an environment to perform system tests on Skype for Business or more generally Office.

### Known issues with pull request:

TO DO:
Missing tests on other versions of Office.

### Change log entry:

Section: Bug fixes
`The incoming messages in the chat of Skype for Business are reported again. (#9295)`

### Code Review Checklist:

This checklist is a reminder of things commonly forgotten in a new PR.
Authors, please do a self-review and confirm you have considered the following items.
Mark items you have considered by checking them.
You can do this when editing the Pull request description with an x: `[ ]` becomes `[x]`.
You can also check the checkboxes after the PR is created.

- [x] Pull Request description is up to date.
- [x] Unit tests.
- [x] System (end to end) tests.
- [ ] Manual tests.
- [x] User Documentation.
- [x] Change log entry.
- [x] Context sensitive help for GUI changes.

2021-03-04 23:06 UTC, CyrilleB79 commented
Looking for other people that may test this PR in other versions of Office:
* Office 2013 / Lync
* Office 2016 more recent than mine
* Office 365
Thanks!
Also cc @fernando-jose-silva:

Could you test on your side that the build in this PR resolves #9295?

2021-03-10 14:22 UTC, CyrilleB79 commented
@Qchristensen would you be able to test it?
Or could you Cc people that may be able to do this test on various versions of Office?
Thanks.

2021-03-10 20:49 UTC, CyrilleB79 commented
Also a reminder for @fernando-jose-silva: if you can test [this build](https://ci.appveyor.com/api/buildjobs/qv6b2h08do65mbtt/artifacts/output%2Fnvda_snapshot_pr12122-21816%2C35ac424f.exe) and indicate your version of Office/Skype. Thanks.

2021-03-10 21:57 UTC, fernando-jose-silva commented
I'm sorry, unfortunately I no longer use Skype for business where I work, the organization has already moved to teams, I have no way to test it.
Thanks.

Enviado do Email para Windows 10

De: Cyrille Bougot
Enviado:quarta-feira, 10 de março de 2021 17:49
Para: nvaccess/nvda
Cc:fernando-jose-silva; Mention
Assunto: Re: [nvaccess/nvda] Fixed an issue preventing chat message to bereported in some versions of Skype for Business. (#12122)

Also a reminder for @fernando-jose-silva: if you can test this build and indicate your version of Office/Skype. Thanks.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-04-22 14:19 UTC, CyrilleB79 commented
@michaelDCurran: since you are the original author of the Lync app module (in #7287) could you please do the tests made when introducing #7287 in order to check that this PR does not break anything.

Marking this PR as ready since everything is made on my side.
If some additional tests are required, just let me know if you know someone else that could do it.
Thanks.

2021-05-10 04:00 UTC, seanbudd requested changes
Thanks for this and sorry for the delay in reviewing. I think this is a relatively safe change as content where `self.value is None` is going to be broken right now regardless and this will only improve handling. It would be good to log some information though so if an issue still arises on some versions of Lync we can follow up on it better and figure out how to extract `content` in that version's formatting.

2021-05-10 04:00 UTC, seanbudd commented on source/appModules/lync.py
> +			content = self.name[contentStartIndex:contentEndIndex].replace('\r\n\r\n', '\n').strip()
could this be replaced with a regex match, and an logged error if this can't be found properly?

2021-11-15 13:23 UTC, lukaszgo1 commented
@CyrilleB79  Is this still on your radar?

2021-11-23 08:49 UTC, CyrilleB79 commented
@lukaszgo1 thanks for the reminder. I must confess that I had not imagined that this issue would have impacted other people that may have updated their version of Office. Thus I had let it apart...

I will perform the corrections and do the tests when I have the opportunity.

2021-11-26 16:04 UTC, CyrilleB79 commented
@seanbudd your comments should be addressed now. Sorry for the delay.

2021-11-29 01:06 UTC, seanbudd approved these changes
Thanks @lukaszgo1

2021-11-29 01:43 UTC, merged