recreate or abort if Python virtual environment has been moved from where it was originally located
nvaccess/nvda pull request #12171
Opened 2021-03-14 23:47 UTC by michaelDCurran

### Link to issue number:
Closes #12166 

### Summary of the issue:
When creating a Python virtual environment, Python's venv package hard-codes the absolute path where the environment was created, in its activation script. This therefore means that it is impossible to use a Python virtual environment if it has been copied or moved to a different location. This is a limitation in venv, and there really is nothing that NvDA can do to work around this.
However, NvDA should at least offer to recreate the virtual environment at the new location if it has been moved or copied. 
As currently, executing runnvda.bat or other scripts while in this state cause hard to understand errors such as NVDA thinking that there is no virtual environment at all.
 
### Description of how this pull request fixes the issue:
ensureVenv.py detects if the Python virtual environment has been moved by temporarily activating it, and capturing the content of the VIRTUAL_ENV environment variable, and then comparing that against the physical venv path.
 If they differ, the user is asked if the virtual environment should be recreated. Saying no causes the script to abort.

### Testing strategy:
* Executed runnvda.bat from a non-moved location, confirming that ensureVenv runs without errors and NVDA starts.
* Renamed the NVDA repository directory, and performed the above step again. This time confirmed that the script asked if the virtual environment should be recreated. Saying no aborted. Running again and saying yes recreated the environment and then ran NVDA.

### Known issues with pull request:
None known.

### Change log entry:
None needed.

### Code Review Checklist:

This checklist is a reminder of things commonly forgotten in a new PR.
Authors, please do a self-review and confirm you have considered the following items.
Mark items you have considered by checking them.
You can do this when editing the Pull request description with an x: `[ ]` becomes `[x]`.
You can also check the checkboxes after the PR is created.

- [ ] Pull Request description is up to date.
- [ ] Unit tests.
- [ ] System (end to end) tests.
- [ ] Manual tests.
- [ ] User Documentation.
- [ ] Change log entry.
- [ ] Context sensitive help for GUI changes.

2021-03-14 23:49 UTC, michaelDCurran commented
@CyrilleB79 could you please test this branch and confirm this detects your situation and allows you to recreate the environment or abort?

2021-03-14 23:57 UTC, lukaszgo1 requested changes

2021-03-14 23:57 UTC, lukaszgo1 commented on venvUtils/ensureVenv.py
> +	# Activate the Python virtual environement and capture the content of the VIRTUAL_ENV environment variable.
environement -> environment

2021-03-14 23:57 UTC, lukaszgo1 commented on venvUtils/ensureVenv.py
> +			"A Python virtual environement cannot be activated from a different location "
Also here.

2021-03-14 23:57 UTC, lukaszgo1 commented on venvUtils/ensureVenv.py
> +	).decode('utf8').rstrip()
Windows console isn't Unicode by default. It'll probably work fine as long as there is no characters outside of the ASCI range in the path but to be safe this should be decoded using `oem`

2021-03-15 09:36 UTC, feerrenrut requested changes
Thanks @michaelDCurran, this approach looks good.

2021-03-15 09:36 UTC, feerrenrut commented on venvUtils/ensureVenv.py
> +	).decode('oem').rstrip()
Please could you add a comment here to show an example of the output for this command? If the output changes, this will make it easier to verify.

2021-03-15 11:48 UTC, CyrilleB79 commented
Hi
I have tested this branch and confirm that the location change has been detected and I am asked if I want to re-generate the environment. Thus the error I get is clearer and it allows me to understand the issue; also the dev doc gives information for this. Thanks.

Unfortunately for me, it does not solve the situation that led me to open #12166.
Before #12075, it was possible to run NVDA from source on a computer that does not have Visual Studio installed: for this, I had to compile NVDA source code on PC1 (with Visual studio installed), copy the source code tree to PC2 (without Visual Studio installed) and run NVDA from source on PC2.
Now this does not seem to be possible anymore.
If this impossibility is unfortunately confirmed and that nothing can be done for this, please at least indicate this new limitation in the known issues of this PR since this only partly solves #12166.

2021-03-15 11:55 UTC, lukaszgo1 commented
> Unfortunately for me, it does not solve the situation that led me to open #12166.
> Before #12075, it was possible to run NVDA from source on a computer that does not have Visual Studio installed: for this, I had to compile NVDA source code on PC1 (with Visual studio installed), copy the source code tree to PC2 (without Visual Studio installed) and run NVDA from source on PC2.
> Now this does not seem to be possible anymore.
> If this impossibility is unfortunately confirmed and that nothing can be done for this, please at least indicate this new limitation in the known issues of this PR since this only partly solves #12166.


Why it is impossible i.e what happens if you try?

2021-03-15 23:44 UTC, michaelDCurran commented
We could consider either providing our own version of activate.bat (it 
does not look that complicated) which uses relative paths. Or, we could 
programmatically rewrite activate.bat after it is generated, changing 
the absolute paths to relative paths.

I think I prefer the first option.

2021-03-16 09:35 UTC, CyrilleB79 commented
In activate.bat, I have tried to change manually the path stored in VIRTUAL_ENV variable. This should work if the folder is just moved/renamed on the same computer.
This would already be something good to implement.

However, when trying to copy the source tree to another computer and execute runnvda.bat, Python complained that it did not find the pythonw.exe.
That was because Python was not installed at the same place on the second computer.

After having manually modified Python location in pyvenv.cfg, I have finally succeeded in executing runnvda.bat on the second computer.
If something can be done to find the Python 3.8-32 location and update the pyvenv.cfg file, this would be very nice.

If not, modifying the activate.bat file is already a good thing.

Thanks!

2021-03-16 23:05 UTC, michaelDCurran commented
Closing in favor of #12184

2021-03-16 23:05 UTC, closed without merging