use wx.Accessible to improve accessibility of our settings panels and checkable list controls
nvaccess/nvda pull request #12215
Opened 2021-03-23 12:31 UTC by leonardder

### Link to issue number:
Closes #12209 

### Summary of the issue:
To fix some accessibility issues in our settings panel and checkable lists, we had to use a custom com server with comtypes. However, wx has built-in functionality to manipulate accessibility properties.

### Description of how this pull request fixes the issue:
This pr removes our own accprop server in favour of wx' native support.

### Testing strategy:
Tested that:

- [ ] Settings panels still have the role of property page
- [ ] Settings panels with a description have it set on the accessible object
- [ ] Check boxes for the NVDA modifier key list items are still read correctly
- [ ] Check boxes for the list of incompatible add-ons are still read correctly
- [ ] 
### Known issues with pull request:
None known

### Change log entry:
* Changes for developers
    + the gui.accPropServer module as well as the AccPropertyOverride and ListCtrlAccPropServer classes from the gui.nvdaControls module have been removed in favor of WX' native support for overriding accessibility properties. When enhancing accessibility of WX controls, implement [wx.Accessible](https://wxpython.org/Phoenix/docs/html/wx.Accessible.html) instead

### Code Review Checklist:

This checklist is a reminder of things commonly forgotten in a new PR.
Authors, please do a self-review and confirm you have considered the following items.
Mark items you have considered by checking them.
You can do this when editing the Pull request description with an x: `[ ]` becomes `[x]`.
You can also check the checkboxes after the PR is created.

- [ ] Pull Request description is up to date.
- [ ] Unit tests.
- [ ] System (end to end) tests.
- [ ] Manual tests.
- [ ] User Documentation.
- [ ] Change log entry.
- [ ] Context sensitive help for GUI changes.

2021-03-24 03:56 UTC, michaelDCurran requested changes

2021-03-24 06:39 UTC, leonardder commented on source/gui/nvdaControls.py
> +			return super().GetState(childId)
See https://wxpython.org/Phoenix/docs/html/wx.Accessible.html#wx.Accessible.GetRole

WX uses PascalCase for method names.

2021-03-24 07:00 UTC, michaelDCurran commented on source/gui/nvdaControls.py
> +			return super().GetState(childId)
No, I mean that you're calling super's GetState but you're actually in GetRole.

2021-03-24 07:36 UTC, leonardder commented on source/gui/nvdaControls.py
> +			return super().GetState(childId)
Ough, I"m sorry, I somehow thought you commented on the `def GetRole` line. Looks like a bad copy/paste.

```suggestion
			return super().GetRole(childId)
```

2021-03-25 03:24 UTC, michaelDCurran approved these changes

2021-03-25 04:46 UTC, merged