WinVersion class follow-up: remove ease of access is supported flag
nvaccess/nvda pull request #12222
Opened 2021-03-25 11:10 UTC by josephsl

### Link to issue number:
Follow-up to PR #11909

### Summary of the issue:
NVDA requires Windows 7/Server 2008 R2 SP1 or later, therefore Ease of Access is available.

### Description of how this pull request fixes the issue:
Removes easeOfAccess.isSupported flag.

### Testing strategy:
Code review (Grep used), manual testing to make sure easeOfAccess.isSupported raises AttributeError.

### Known issues with pull request:
None

### Change log entry:
Changes for developers:

easeOfAccess.isSupported has been removed.

### Code Review Checklist:

This checklist is a reminder of things commonly forgotten in a new PR.
Authors, please do a self-review and confirm you have considered the following items.
Mark items you have considered by checking them.
You can do this when editing the Pull request description with an x: `[ ]` becomes `[x]`.
You can also check the checkboxes after the PR is created.

- [x] Pull Request description is up to date.
- [x] Unit tests.
- [x] System (end to end) tests.
- [x] Manual tests.
- [x] User Documentation.
- [x] Change log entry.
- [x] Context sensitive help for GUI changes.

Thanks.

2021-04-20 05:26 UTC, seanbudd requested changes
Thanks @josephsl. Looks good to me, can also confirm there are no other usages after merging in master (e019a243271a45816223c5f4fa661cda4b75d9fe).

2021-04-20 05:26 UTC, seanbudd commented on source/config/__init__.py
> +	# so we only need to deal with EoA here.
```suggestion
```

I don't think these comments make sense now that the else condition is removed

2021-04-20 05:35 UTC, josephsl commented
Hi, I see. I’ll address this as early as upcoming weekend. Thanks.

2021-04-21 04:12 UTC, josephsl commented
Hi,

Review comments addressed.

Thanks.

2021-04-21 05:10 UTC, seanbudd approved these changes
Thanks @josephsl , LGTM

2021-04-21 05:40 UTC, merged