Focus chrome after starting in system tests
nvaccess/nvda pull request #12352
Opened 2021-04-29 04:33 UTC by seanbudd

### Link to issue number:

None

### Summary of the issue:

As discussed in #12293, our systems fail randomly. Usually this is due to another window stealing focus, such as the taskbar or Docker. As system tests are run locally, we shouldn't be killing these processes. 

### Description of how this pull request fixes the issue:

- Use windows API to make the chrome window gain focus
- Adds logging that lists the foreground window and open windows if chrome doesn't gain focus
- Removes extra sleep time after starting NVDA 

### Testing strategy:

Run the system tests locally, and prevent chrome from gaining focus by using `alt+tab` or having another window veto it. 

Here's an example log from a local test:

```
checkbox labelled by inner element :: A checkbox labelled by an in... | FAIL |
Unable to focus Chrome.
Foreground Window: speechSpyGlobalPlugin.py (Working Tree) - nvda - Visual Studio Code.
Open Windows: ['speechSpyGlobalPlugin.py (Working Tree) - nvda - Visual Studio Code', 'NVDA Browser Test Case - Google Chrome', 'C:\\nvda\\testOutput\\system', 'Calculator', 'Calculator', 'Settings', 'Settings', 'Microsoft Text Input Application', 'Program Manager']
```

### Known issues with pull request:

None

### Change log entries:

None

### Code Review Checklist:

- [x] Pull Request description is up to date.
- [x] Unit tests.
- [x] System (end to end) tests.
- [x] Manual tests.
- [x] User Documentation.
- [x] Change log entry.
- [x] Context sensitive help for GUI changes.

2021-04-29 09:21 UTC, lukaszgo1 commented on tests/system/libraries/ChromeLib.py
> +		E.G. "htmlTest   Google Chrome", "html – Google Chrome" or perhaps no applcation name at all.
applcation -> application

2021-04-29 09:21 UTC, lukaszgo1 commented on tests/system/libraries/ChromeLib.py
> +		If this continues to be unreliable we could use solenium or similar to start chrome and inform us
solenium -> Selenium

2021-04-30 00:32 UTC, michaelDCurran requested changes
It may be an idea to add some kind of per-test unique value to testCaseTitle, because at the moment it is just "NVDA Browser Test Case". There is a small possibility  the code could focus the wrong Chrome window, if one happened to be left arrround.

2021-04-30 01:57 UTC, michaelDCurran approved these changes, later dismissed

2021-05-05 05:56 UTC, michaelDCurran approved these changes

2021-05-05 06:02 UTC, merged