Announce deselection when jumping to top/bottom
nvaccess/nvda pull request #12374
Opened 2021-05-06 23:01 UTC by keyan

### Link to issue number:

Fixes #5549

### Summary of the issue:

Movement to the top/bottom of page using ctrl+home/end causes deselection of text but this deselection is not announced.

### Description of how this pull request fixes the issue:
This pull-request modifies `caretMovementScriptHelper` so that movement to the top or bottom of the page sets the `isCollapsed` field when there was a prior text selection. This results in announcing the deselection of text.

### Testing strategy:
I first reproduced the bug in question, video: https://www.youtube.com/watch?v=R1362g2nRYE

Then I applied this patch and tested again. In this video the same movement is applied but the text deselection is announced: https://www.youtube.com/watch?v=v5iOY-_augE

### Known issues with pull request:
It was not clear to me how to add unit tests for this case.

### Change log entries:
Bug fixes

### Code Review Checklist:
- [x] Pull Request description is up to date.
- [ ] Unit tests.
- [ ] System (end to end) tests.
- [x] Manual tests.
- [ ] User Documentation.
- [ ] Change log entry.
- [ ] Context sensitive help for GUI changes.

2021-05-07 11:00 UTC, leonardder requested changes
Thanks for your contribution. Honestly, this looks a bit like a workaround to me (i.e. changing the isCollapsed property while the textInfo itself is still collapsed.
I need to look into this more carefully before I give a final review.

2021-05-10 01:51 UTC, keyan commented
Hi Leonard, thanks for the review!

Understandable. I'm happy to try another solution if you have some suggestions for a better approach. I meant to just open the discussion with this initial solution.

2021-05-14 02:58 UTC, seanbudd requested changes
Thanks @keyan,

>It was not clear to me how to add unit tests for this case.

A system test for this could be added in chromeTests. It would be good to select some text then test:

- a selection change is announced when moving the caret 
- a selection change is announced when jumping to the bottom of the page
- a selection change is announced when jumping to the top of the page

2021-05-14 02:58 UTC, seanbudd commented on source/cursorManager.py
>  		if self.isTextSelectionAnchoredAtStart and not oldInfo.isCollapsed:
Is this going to be affected and should it be? What happens if you jump to the start/end of the page while the text selection is anchored at the start? Could this be included in the system test?

If this shouldn't be affected, maybe we should have `hasSelectionChanged = oldInfo.isCollapsed or (not oldSelection.isCollapsed and isJumpToTopOrBottom)` and use that boolean to check whether to `speakSelectionChange`

2021-05-22 12:00 UTC, leonardder commented
I think it should be ok to do something like this:

```python
		oldInfo = self.makeTextInfo(posConstant)
		oldSelection = (
			oldInfo
			if posConstant == textInfos.POSITION_SELECTION else
			self.makeTextInfo(textInfos.POSITION_SELECTION)
		)
		...
		if not oldSelection.isCollapsed:
			speech.speakSelectionChange(oldSelection, selection)
```

2021-05-26 06:25 UTC, michaelDCurran requested changes
I think that it should be fixed as follows:
* oldInfo should always be initialized as self.makeTextInfo(textInfos.POSITION_SELECTION) rather than using posConstant, as oldInfo is always and only ever used to start from the existing selection/caret and speak the selection difference.
* info should be initialized as oldInfo.copy() if posConstant is textInfos.POSITION_SELECTION (the default) otherwise initialized as self.makeTextInfo(posConstant)

In other words, oldInfo should always represent the original selection/caret. info on the other hand should start at posConstant (selection or otherwise) and possibly move by a number of units.

2021-05-26 06:27 UTC, michaelDCurran commented on source/cursorManager.py
> +		oldInfo = self.makeTextInfo(posConstant)
```suggestion
		oldInfo = self.makeTextInfo(textInfos.POSITION_SELECTION
```

2021-10-16 19:38 UTC, lukaszgo1 commented
@keyan  Are you planning to work further on this?

2022-06-30 03:52 UTC, closed without merging