Fix-up of PR #11402: Redeem the copyright holders' names for `source/gui/inputGestures.py` after its split from `source/gui/settingsDialogs.py`
nvaccess/nvda pull request #12386
Opened 2021-05-10 00:25 UTC by JulienCochuyt

### Link to issue number:

Fix-up of PR #11402

### Summary of the issue:

In PR #11402, part of `source/gui/settingsDialogs.py` has been extracted to the new `source/gui/inputGestures.py` for good reasons.
However, in the process, the name of the copyright holders for this portion of the code has not been reported to the header of the new file.

### Description of how this pull request fixes the issue:

Extracted the names of the committers as of 39606f145 (the previous commit on the file) by running the following command:
`git blame -L3975,+368 settingsDialogs.py | sed -E 's/ [0-9]{4}\).*//;s/ \(/ /' | sed -E 's/(.+)(20[0-9][0-9]-.+)/\2 \1/' | sort | uniq`

Result:
```
2013-08-23 11:21:40 +1000 8470bd4676 James Teh
2013-08-28 13:21:32 +1000 23c95d437d James Teh
2013-08-28 14:00:19 +1000 716d4040f9 James Teh
2013-08-29 10:51:30 +1000 44d55637e7 James Teh
2013-08-29 12:15:45 +1000 c24f41f8a0 James Teh
2013-09-05 16:20:17 +1000 74c1df1c39 James Teh
2013-09-05 20:46:30 +1000 84a7433796 James Teh
2013-10-23 10:01:01 +1000 6182d7c112 James Teh
2013-10-23 14:59:28 +1000 0776a1b697 James Teh
2014-12-03 14:28:30 +1000 2fcf0fcd08 Zahari Yurukov
2014-12-07 08:26:02 -0800 ac15e5a2df Joseph Lee
2016-10-13 14:55:17 +0800 87ed4d17fe Reef Turner
2017-03-29 16:45:38 +1000 8f853cec88 James Teh
2018-07-17 22:47:13 -0700 d40488ceec Joseph Lee
2019-09-13 10:27:18 +0200 866cc7eec8 Julien Cochuyt
2019-10-07 23:16:30 +0200 0e12e8a526 Julien Cochuyt
2020-02-12 07:30:41 +0100 35ae4d4a17 CyrilleB79
2020-07-02 18:19:03 +0200 02c481db39 Julien Cochuyt
2020-07-06 09:10:44 +0200 0358e7ffe5 Julien Cochuyt
2020-07-06 09:29:03 +0200 daa7907940 CyrilleB79
```

### Testing strategy:

### Known issues with pull request:

### Change log entries:

I really don't think this deserves a change log entry.

### Code Review Checklist:

- [x] Pull Request description is up to date.
- [ ] Unit tests.
- [ ] System (end to end) tests.
- [ ] Manual tests.
- [ ] User Documentation.
- [x] Change log entry.
- [ ] Context sensitive help for GUI changes.

2021-05-10 01:23 UTC, seanbudd requested changes
Thanks for catching this, I've referenced this with the contributors list on settingsDialog as well and looks good. I've suggested to remove the 2 NV Access developers though.

2021-05-10 01:23 UTC, seanbudd commented on source/gui/inputGestures.py
> +# Julien Cochuyt, Cyrille Bougot
```suggestion
# Copyright (C) 2013-2020 NV Access Limited, Zahari Yurukov, Joseph Lee, Julien Cochuyt, Cyrille Bougot
```

@feerrenrut and James Teh come under "NV Access Limited"

2021-05-16 17:53 UTC, lukaszgo1 commented on source/gui/inputGestures.py
> +# Julien Cochuyt, Cyrille Bougot
> On second thought, it's worth using the whole list of contributors from settingsDialogs at the time. Unless we check the entire git blame history for the function, 

I believe @JulienCochuyt did exactly that judging  by the git blame invocation from the initial comment.

2021-05-17 04:02 UTC, seanbudd commented on source/gui/inputGestures.py
> +# Julien Cochuyt, Cyrille Bougot
git blame only shows the information of the previous commit that changed the line. Using this method, previous work someone may have done on the line would be erased if another person changed it.

2021-05-17 04:16 UTC, JulienCochuyt commented
With admittedly low priority, I'm working on a script to try blame all the revisions of the given range, including those eventually fully superseded.

2022-06-20 19:09 UTC, lukaszgo1 requested changes
@seanbudd Since as part of different PR I've verified that the list of contributors is accurate here can we consider applying my suggestion below and merge this? While I agree that having completely precise copyright headers for moved code is not horribly important if we have an complete list it seems a waste not to use it and prefer to use an entire (likely also not completely accurate) header from gui\settingsDialogs.

2022-06-20 19:09 UTC, lukaszgo1 commented on source/gui/inputGestures.py
> +# Copyright (C) 2013-2020 NV Access Limited, James Teh, Zahari Yurukov, Joseph Lee, Reef Turner,
When working on #13294 I've verified that the copyright header herer is accurate, though it seems we don't include names of NV Access employees.
```suggestion
# Copyright (C) 2013-2020 NV Access Limited, Zahari Yurukov, Joseph Lee,
```

2022-06-21 01:39 UTC, seanbudd commented on source/gui/inputGestures.py
> +# Julien Cochuyt, Cyrille Bougot
@lukaszgo1 - see this initial suggestion. There's no need to use a script like Julien proposed, this suggestion is fine

2022-06-21 01:40 UTC, seanbudd approved these changes

2022-06-21 08:41 UTC, merged