UI Automation in Windows Console: Cache isImprovedTextRangeAvailable and infrastructure for UIA by default
nvaccess/nvda pull request #12453
Opened 2021-05-22 07:07 UTC by codeofdusk

### Link to issue number:
Split from #10964.

### Summary of the issue:
In UIA consoles:
* If UIA support is disabled but UIA console somehow starts, the custom overlay class is not applied.
* Consoles are added to `badWindowClassNames` dynamically, which is inconsistent with other UIA implementations.
* `isImprovedTextRangeAvailable` is queried many times, resulting in excessive cross-process calls.

### Description of how this pull request fixes the issue:
This PR:
* Removes the setting check when applying the overlay class (this shouldn't have been there).
* Removes `_UIAHandler._isBadWindowClassName` (added for UIA console), making the list of bad names once again static.
* Adds `UIAUtils._isImprovedConhostTextRangeAvailable` which checks the number of visible ranges in a console at a given `hwnd`. This function is decorated with [functools.lru_cache](https://docs.python.org/3/library/functools.html#functools.lru_cache).
* Adds `UIAUtils._shouldUseUIAConsole` which currently just checks the config as before (#10964 will add a call to `_isImprovedConhostTextRangeAvailable` to this function).

### Testing strategy:
Tested that the use UIA console checkbox in advanced settings works as expected.

Ran Windows Console, moved the review cursor over a few words/lines, then connected and disconnected from another system over `ssh`:

```python console
>>> UIAUtils._isImprovedConhostTextRangeAvailable.cache_info()
CacheInfo(hits=84, misses=1, maxsize=10, currsize=1)
```

### Known issues with pull request:
None

### Change log entries:
None

### Code Review Checklist:

- [x] Pull Request description is up to date.
- [x] Unit tests.
- [x] System (end to end) tests.
- [x] Manual tests.
- [x] User Documentation.
- [x] Change log entry.
- [x] Context sensitive help for GUI changes.

2021-05-22 21:59 UTC, codeofdusk commented
PR ready for review (system tests were failing). Thanks. CC @feerrenrut, @michaelDCurran, @seanbudd.

2021-05-24 06:09 UTC, seanbudd commented on source/UIAUtils.py
> +def _shouldUseUIAConsole(hwnd):
`hwnd` is unused

2021-05-24 06:45 UTC, seanbudd requested changes
Thanks @codeofdusk, this strategy makes sense to me. I have some further notes

>Consoles are added to badUIAWindowClassNames dynamically, which is inconsistent with other UIA implementations.
>Removes _UIAHandler._isBadWindowClassName (added for UIA console), making the list of bad names once again static.

I don't see this occurring in the NVDA codebase at current master. Converting these to tuples makes sense regardless though.

2021-05-24 06:45 UTC, seanbudd commented on source/UIAUtils.py
> +		from logHandler import log
can this import be moved to the top of the file?

2021-05-24 06:45 UTC, seanbudd commented on source/UIAUtils.py
> +def _isImprovedConhostTextRangeAvailable(hwnd):
Please add typing information to this function header

2021-05-24 07:02 UTC, codeofdusk commented on source/UIAUtils.py
> +def _shouldUseUIAConsole(hwnd):
`_hwnd` is inconsistent with the argument to `_UIAHandler._isUIAWindowHelper`. The arg is intentionally used in this PR, but a follow-up PR will make it look something like:
```python
def _shouldUseUIAConsole(hwnd):
	"""Determines whether to use UIA in the Windows Console."""
	setting = config.conf['UIA']['winConsoleImplementation']
	if setting == "UIA":
		return True
	elif setting == "legacy":
		return False
	else:  # setting == "auto"
		return _shouldUseUIAConsole(hwnd)
```
I'll add a comment to clarify.

2021-05-24 07:22 UTC, seanbudd requested changes
Thanks @codeofdusk. I've fixed up the PR description as well. I've left a further question for clarification but otherwise I think this is ready to merge.

2021-05-24 07:22 UTC, seanbudd commented on source/UIAUtils.py
> +		# with a call to _shouldUseUIAConsole.
Do you mean the following or is this a recursive call?
```suggestion
		# with a call to _isImprovedConhostTextRangeAvailable.
```

2021-05-24 07:32 UTC, codeofdusk commented
OK. I think all review items have been satisfied. I also included another small change to newer implementations and updated the description accordingly.

2021-05-24 07:38 UTC, seanbudd approved these changes

2021-05-24 07:44 UTC, merged