Fix empty edit fields not speaking in Microsoft Edge
nvaccess/nvda pull request #12475
Opened 2021-05-28 08:45 UTC by leonardder

### Link to issue number:
Fixes #12474 

### Summary of the issue:
Empty edit fields aren't spoken in Edge. There's a bug in the UIA implementation that causes expand to line to fail when there is no text content in the object

### Description of how this pull request fixes the issue:
1. Use the ChromiumUIA object overlay for text boxes in the Chrome/Edge interface. For Edge, this applies by default. For Chrome, this only applies to cases where experimental UIA support is enabled, but this is far from stable in Chrome itself.
2. On the ChromeUIATextInfo, ensure we get a backup of the range before expanding, and if the range after expanding is broken, restore the backup. I'm not sure whether it is really only line that's affected by this bug, so that's why I applied this check in general, and not only when expanding to line.
3. Make sure to invalidate the NVDA property cache when overlays are added on top of an object. This is really necessary because auto properties can be used to find out what overlays to add on an object. Before, if a property was used during overlay class initialization and an overlay changed that property's value, the new value wasn't reflected. This caused speakObject to use UIATextInfo on focus instead of ChromiumUIATextInfo

### Testing strategy:
Tested that the address bar of Edge is read correctly when empty and focused.

### Known issues with pull request:
None known.

### Change log entries:
Bug fixes
* In the new Chromium based Microsoft Edge, text fields such as the address bar are now announced when empty. (#12474)

### Code Review Checklist:

- [ ] Pull Request description is up to date.
- [ ] Unit tests.
- [ ] System (end to end) tests.
- [ ] Manual testing.
- [ ] User Documentation.
- [ ] Change log entry.
- [ ] Context sensitive help for GUI changes.
- [ ] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers

2021-05-28 11:20 UTC, leonardder commented
I actually think that this pr will mean a significant improvement for Edge users, therefore I'd like to request to have this merged into beta instead.

2021-05-28 12:37 UTC, cary-rowen commented
This is a significant improvement and hope to be merged into Beta

2021-05-28 13:06 UTC, alexarnaud commented
Thanks a lot @leonardder for fixing this.

I have two questions : 
* Do you still reproduce with Edge version 91 released today?
* Is it possible for you to report the UIA issue against Edge?

Best regards.

2021-05-28 13:12 UTC, leonardder commented
@alexarnaud  wrote:

> I have two questions :
> 
> * Do you still reproduce with Edge version 91 released today?

Yes.

> * Is it possible for you to report the UIA issue against Edge?

If I knew where to do that, I'd certainly would. DO I need to do it against Edge or Chromium? Thoughts @michaelDCurran?

2021-05-28 13:18 UTC, josephsl commented
Hi, I recommend contacting Microsoft Edge team (hopefully through Feedback hub if possible) and also ask that Chromium/Chrome team look into this issue (because this could also impact other Chromium based browsers). Thanks.

2021-05-28 13:20 UTC, leonardder commented
I think it would be better if NV Access pokes their Microsoft contacts about this.

2021-05-28 13:29 UTC, josephsl commented
Hi, and Google, too.

2021-05-28 13:40 UTC, leonardder commented
Well, as long as Google's implementation is experimental, I guess it's up to Microsoft to push fixes upstream.

2021-05-28 13:46 UTC, Brian1Gaff commented
If one could trace it directly to the Chrome team, surely then it would be 
on all and fixed with the same patch otherwise you might end up with a 
different work around for every browser if one is not careful.
 Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message ----- 
From: "Joseph Lee" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Friday, May 28, 2021 2:30 PM
Subject: Re: [nvaccess/nvda] Fix empty edit fields not speaking in Microsoft 
Edge (#12475)


> Hi, and Google, too.
>
>
>
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/pull/12475#issuecomment-850420209

2021-05-30 23:45 UTC, michaelDCurran requested changes
I am concirned that this may introduce performance issues, Especially also as these days it is important to try and keep the number of cross-process calls in UIA to a minimum with scenarios such as WDAG and RAIL.

In ChromiumUIATextInfo.expand: instead of the added calls to clone and compare, why not just call GetText(1) to fetch the first 1 characters and check if it is the empty string or not. If it is empty, then simply don't call expandToEnclosingUnit.
 
Although in general you are probably correct that we should call obj.invalidateCache after applying overlay classes, I would prefer this to be in its own pr, where we can very carefully consider and track any performance issues this may cause. This change obviously affects code across NVDA, not just the Edge address bar.
However, to address the specific issue of TextInfos incorrectly being cached here, perhaps we can at least set `_cache_TextInfo = False` on the UIA NVDAObject which will stop the TextInfo property from being cached. All the major calls it makes internally are cached properties themselves, so this would have no real performance impact, but it would still allow the current value of `_TextInfo` to be used, thus an overlay with a different TextInfo class would correctly be reflected in speakObject after overlay classes were applied but still in the same core cycle.

2021-05-31 06:05 UTC, leonardder commented
> In ChromiumUIATextInfo.expand: instead of the added calls to clone and compare, why not just call GetText(1) to fetch the first 1 characters and check if it is the empty string or not. If it is empty, then simply don't call expandToEnclosingUnit.

Is that going to work? I assume GetText returns text in the range and doesn't return anything when the range is collapsed, therefore if the range is collapsed, it will never expand.

2021-05-31 06:07 UTC, michaelDCurran commented
Ah, sorry, I mean self.obj.UIATextPattern.documentRange.GetText(1)

2021-05-31 06:17 UTC, leonardder commented
Ah, yeah that makes sence. I changed this as requested.
I also tested every UIA unit and it turns out that it only fails when expanding to line as I originally thought. Therefore I changed the code to only apply when expanding to line. I will change the description accordingly.

2021-05-31 10:23 UTC, michaelDCurran approved these changes

2021-05-31 10:24 UTC, merged