Update bdDetect.py
nvaccess/nvda pull request #12607
Opened 2021-07-02 14:19 UTC by Tobias-Team-Visiobraille

### Link to issue number:

### Summary of the issue:

### Description of how this pull request fixes the issue:

### Testing strategy:

### Known issues with pull request:

### Change log entries:
New features
Changes
Bug fixes
For Developers

### Code Review Checklist:

- [ ] Pull Request description is up to date.
- [ ] Unit tests.
- [ ] System (end to end) tests.
- [ ] Manual testing.
- [ ] User Documentation.
- [ ] Change log entry.
- [ ] Context sensitive help for GUI changes.
- [ ] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers

2021-07-02 14:21 UTC, Tobias-Team-Visiobraille commented
@ the first commit the VID wasn´t correcht 0409 is right...the Alias VisioBraille should be used is that possible? @michaelDCurran

2021-07-02 23:15 UTC, XLTechie commented
Do you think you might fill out the pull request template?

2021-07-05 01:52 UTC, seanbudd commented
I've converted this to a draft, let us know when the template has been filled out and this is ready for review.

2021-07-21 05:41 UTC, feerrenrut commented
On first inspection this looks like a duplicate of #12606, however the "VID" (vender ID) is different `VID_0483` vs `VID_0904` in #12606 vs #12607 respectively.

The only information given at the top of #12606 is:
> Want to insert our new Braille line "Vario 4" 6301 the lenght will be communicate after connection is esthablished. Hope this works with BT too.

Since these two PR's are so similar, I'm going to close #12606.
@Tobias-Team-Visiobraille we'll need more information and confirmation of testing results before we can include this change.

2021-07-26 01:34 UTC, seanbudd requested changes
I've updated the title and the PR description.

You can test that this works using the build link you have added to the Pull Request description.

This pull request is currently targeting master, likely to be included in the 2021.3 release, if you wish this to be included in 2021.2 please test this and update the target branch for this request to `beta`.

>the Alias VisioBraille should be used is that possible? 

Is this something that is also blocking the request from being merged?

2021-07-26 01:34 UTC, seanbudd commented on source/bdDetect.py
> +	"VID_0904&PID_6301", # Vario 4
This will make our linter happy

```suggestion
	"VID_0904&PID_6301",  # Vario 4
```

2021-08-03 23:49 UTC, seanbudd approved these changes

2021-08-04 00:10 UTC, merged

2021-08-06 08:43 UTC, Tobias-Team-Visiobraille commented
Hello Sean, is there any possibility to include the Vario 4 device support into Update 2021.2 instead of 2021.3?
Thanks Tobias

2022-04-21 14:48 UTC, Dirk-Team-VisioBraille commented
Hello Sean, 
this is Dirk from the VisioBraille Team. Since Tobias left the company its my job to organize the integration of the Braille displays into the screenreaders. I'm no software guy at all and I don't know how to manage this. Can you pleas help me?

What do I have to do for the integration of the Vario464 and the Vario480? 

Many thanks in advance for helping me.
Dirk

2022-04-27 10:55 UTC, Dirk-Team-VisioBraille commented
@seanbudd 
Can you please help me?
Kind regards 
Dirk

2022-04-27 23:34 UTC, seanbudd commented
@Dirk-Team-VisioBraille

Hi Dirk,
This is a fairly complicated request. I'd like to avoid discussing this on an unrelated pull request. Please send an email to info@nvaccess.org.

2022-04-28 11:17 UTC, Dirk-Team-VisioBraille commented
Thanks for responding. I sent a mail for you to info@nvaccess.org. Will you respond it?