Move tech design overview from wiki into repo
nvaccess/nvda pull request #12601
Opened 2021-07-02 00:51 UTC by michaelDCurran

### Link to issue number:
None.

### Summary of the issue:
The technical design overview document currently on the wiki should be added to the NVDA repository so it can reflect the state of the commit it is read in.
 
### Description of how this pull request fixes the issue:
Coped the technical design overview from the NVDA wiki to devDocs/technicalDesignOverview.md. Reformatted to break lines between sentences.

### Testing strategy:
None

### Known issues with pull request:
Should continue to review the document and ensure it is up to date.

### Change log entries:
New features
Changes
Bug fixes
For Developers

### Code Review Checklist:

- [ ] Pull Request description is up to date.
- [ ] Unit tests.
- [ ] System (end to end) tests.
- [ ] Manual testing.
- [ ] User Documentation.
- [ ] Change log entry.
- [ ] Context sensitive help for GUI changes.
- [ ] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers

2021-07-02 06:46 UTC, CyrilleB79 commented
Maybe a point should be added in the "Code Review Checklist" item of the PR template:
`* [] Developer Documentation`

Or generalize the "User documentation" item as follows:
``* [] Documentation (user documentation, developer documentation, other?)`

2021-07-02 09:05 UTC, lukaszgo1 requested changes

2021-07-02 09:05 UTC, lukaszgo1 commented on devDocs/technicalDesignOverview.md
> +For example, this is necessary to seemlessly handle complex documents which consist of many objects.
seemlessly -> seamlessly

2021-07-02 09:09 UTC, lukaszgo1 commented
Since we're  moving many pages from the wiki to the repository has it been considered to remove them from the wiki? This would not only avoid duplication of the content but also ensure that there is only one source of information which needs to be kept uptodate.

2021-07-13 03:54 UTC, seanbudd approved these changes
LGTM. I've noted a couple of typos, and a clarification on what is meant by (...)

2021-07-13 03:54 UTC, seanbudd commented on devDocs/technicalDesignOverview.md
> +NvDA allows third-parties to extend NvDA's functionality through plugins and add-ons.
```suggestion
NVDA allows third-parties to extend NVDA's functionality through plugins and add-ons.
```

2021-07-13 03:54 UTC, seanbudd commented on devDocs/technicalDesignOverview.md
> +Browse mode documents are a subclass of `TreeInterceptor` that provide scripts that allow navigating the document in a linea fassion.
```suggestion
Browse mode documents are a subclass of `TreeInterceptor` that provide scripts that allow navigating the document in a linear fashion.
```

2021-07-13 03:54 UTC, seanbudd commented on devDocs/technicalDesignOverview.md
> +* The next found global plugin...
```suggestion
* The next found global plugin (until no more are found)
```

2021-07-13 03:54 UTC, seanbudd commented on devDocs/technicalDesignOverview.md
> +* The next found global plugin...
```suggestion
* The next found global plugin (until no more are found)
```

2021-07-14 05:58 UTC, merged

2021-07-14 09:38 UTC, feerrenrut commented on devDocs/technicalDesignOverview.md
> +Sometimes, it is necessary to intercept events and scripts for an entire hierarchy (or tree) of [NVDA objects](#nvda-objects).
This leaves me wondering, intercept between which two points? Where is the event "coming from", and where is it "going"?

2021-07-14 09:41 UTC, feerrenrut commented on devDocs/technicalDesignOverview.md
> +This is called inter-process communication (IPC).
It would be helpful if the specific IPC approaches used by NVDA were described.