Expand checkPot to warn about messages which were marked as not having translator comments but are no longer present in the translations template
nvaccess/nvda pull request #12705
Opened 2021-07-31 14:55 UTC by lukaszgo1

### Link to issue number:
None
### Summary of the issue:
Currently `checkPot` has a list of messages which are translatable but don't have commends for translators. While it warns about messages in this list for which comments are added it does not warn about these which are no longer present in the .pot template.

### Description of how this pull request fixes the issue:
I've modified `checkPot` so that if there are messages in `EXPECTED_MESSAGES_WITHOUT_COMMENTS` which were removed from the source code it lists them and fails similarly to the case in which a new message has no comments for translators.
### Testing strategy:
Ensured that 12 messages which are in `EXPECTED_MESSAGES_WITHOUT_COMMENTS` which are not in source code any longer were properly flagged and the build failed. I'll remove them from the list as soon as the build fiales on AppVeyor.
### Known issues with pull request:
None known
### Change log entries:
None needed - this just improves our tests.

### Code Review Checklist:

- [ ] Pull Request description is up to date.
- [ ] Unit tests.
- [ ] System (end to end) tests.
- [ ] Manual testing.
- [ ] User Documentation.
- [ ] Change log entry.
- [ ] Context sensitive help for GUI changes.
- [ ] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers

2021-08-01 23:53 UTC, seanbudd requested changes
Thanks @lukaszgo1, this is a helpful check. I've made a suggestion to rephrase a message, and fix a typo. Would you also be able to add a unit test for this check, like the other checkPot tests? It would also be good if the other tests have `len(removedTranslatableMessages) == 0`, so that only one test fails if the check is inaccurate.

2021-08-01 23:53 UTC, seanbudd commented on tests/checkPot.py
> +			"The following messages arre no longer present in the source code "
```suggestion
			"The following messages are no longer present in the source code "
```

2021-08-01 23:53 UTC, seanbudd commented on tests/checkPot.py
> +		f"{len(removedTranslatableMessages)} messages marked as expected failures removed from the source code"
```suggestion
		f"{len(removedTranslatableMessages)} messages marked as expected errors not present in the source code"
```

2021-08-02 11:48 UTC, lukaszgo1 commented
> 
> 
> Thanks @lukaszgo1, this is a helpful check. I've made a suggestion to rephrase a message, and fix a typo. 

Thanks for these - applied now.


> Would you also be able to add a unit test for this check, like the other checkPot tests? 

This is being tested implicitly by all other tests. I'm not really sure if adding separate tests for aspects of `checkPot` which are going to be removed as soon as all messages in the source have comments for translators is a good use of anyone's time.

> It would also be good if the other tests have `len(removedTranslatableMessages) == 0`, so that only one test fails if the check is inaccurate.


It is of course doable but it would require a complete rewrite of the test data and therefore each and every unittest for the `checkPot`  which I'm not sure is a good direction to take - see above w.r.t parts of `checkPot` being hopefully temporary.

2021-08-03 00:24 UTC, seanbudd approved these changes
That is fair, in the meantime these aspects will be tested implicitly. 
Thanks again for your work here.

2021-08-03 00:25 UTC, merged