Linting updates
nvaccess/nvda pull request #12773
Opened 2021-08-24 18:52 UTC by TheQuinbox

### Link to issue number:
None
### Summary of the issue:
I know we've been trying to cut back on linting issues. I tried to tackle this a few months back, but didn't really know what I was doing. Let me know how it looks now.
### Description of how this pull request fixes the issue:
I linted a few files (buildVersion.py, XMLFormatting.py, wincon.py, and a few others). I've also created a new branch (lintingUpdates), if people wish to use it for future changes such as these.
### Testing strategy:
NVDA runs from source with no issues.
### Known issues with pull request:
None
### Change log entries:
B=None
### Code Review Checklist:
- [x] Pull Request description is up to date.
- [x] Unit tests.
- [x] System (end to end) tests.
- [x] Manual testing.
- [x] User Documentation.
- [x] Change log entry.
- [x] Context sensitive help for GUI changes.
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers

2021-08-24 20:42 UTC, lukaszgo1 commented on tests/lint/flake8.ini
> -continuation-style = hanging
Why you've removed this line?

2021-08-24 20:44 UTC, lukaszgo1 commented on source/vkCodes.py
> +# vkCodes.py
This line, and all lines which just contains the file name should be removed according to the copyright header standards on the Wiki. Also it feels a bit weird  to me to modify the file just to reformat its copyright header so this should probably be reverted.

2021-08-24 22:10 UTC, TheQuinbox commented
Ah, my bad. Fixing both now. :)

2021-08-24 22:19 UTC, TheQuinbox commented
Hi, this should all be fixed now. :)

2021-08-25 09:43 UTC, lukaszgo1 commented on tests/lint/flake8.ini
> -continuation-style = hanging
This one is still unanswered.

2021-08-25 15:49 UTC, TheQuinbox commented
Aaaah, my bad. Should be fixed now.

2021-08-26 00:56 UTC, seanbudd requested changes

2021-08-26 13:24 UTC, closed without merging