Ensure documents always scroll to exact browse mode position
nvaccess/nvda pull request #12803
Opened 2021-09-03 00:29 UTC by michaelDCurran

### Link to issue number:
Fixes #9611

### Summary of the issue:
tbd

### Description of how this pull request fixes the issue:
tbd

### Testing strategy:
Try build: https://ci.appveyor.com/api/buildjobs/bsjf2a8c6t9879wf/artifacts/output%2Fnvda_snapshot_try-i9611-23673%2C38a7b5ac.exe

### Known issues with pull request:

### Change log entries:
New features
Changes
Bug fixes
For Developers

### Code Review Checklist:

- [ ] Pull Request description is up to date.
- [ ] Unit tests.
- [ ] System (end to end) tests.
- [ ] Manual testing.
- [ ] User Documentation.
- [ ] Change log entry.
- [ ] Context sensitive help for GUI changes.
- [ ] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers

2021-09-04 13:00 UTC, lukaszgo1 reviewed
There are some unrelated changes in this PR. Can it be rebased on master?

2021-09-09 06:01 UTC, seanbudd approved these changes

2021-09-09 06:02 UTC, seanbudd requested changes

2021-09-09 06:02 UTC, seanbudd commented on source/virtualBuffers/__init__.py
> +			return
Should these cases be logged? `if not obj` used to be

2021-09-09 06:09 UTC, seanbudd approved these changes

2021-09-09 06:10 UTC, michaelDCurran commented
I added back the logging for `not obj` but, the equal to rootNVDAObject 
should not be logged as this is very common and deliberately should be 
ignored.

2021-09-09 06:53 UTC, merged

2021-09-09 07:23 UTC, leonardder commented
Ah, a pity I missed this. There seems to be some overlap with #9919 which I abandoned. Some thoughts:

1. This pr does not implement scrolling for MSHTML. It does support scrolling at the text range level, though.
2. I implemented an allignToTop parameter in #9919 since most API's support specifying this. It was used in browse mode because otherwise, some implementations (I don't remember which) tent to scroll all the time, even when not necessary.
3. IAccessible2 ScrollSubstringTo sometimes fails when the object is entirely out of view.

@michaelDCurran  I assume you didn't know about #9919. May be it could be helpful to have a look at it and see what can be incorporated?

2021-09-09 07:34 UTC, michaelDCurran commented
Ah sorry, I totally missed #9919.

It seems to be more complete. I'll take a proper look and decide what to do.

2021-09-09 08:41 UTC, michaelDCurran commented
@leonardder Although #9919 is much more complete, I believe this pr is enough of a subset for what is required for MS Word with UIA to scroll, without breaking anything else.
True that MSHTML is not implemented, but currently nothing would call it anyway. Any browse mode implementation we currently have for MSHTML is a virtualBuffer.
I'd be happy to take a look at what can be taken from #9919 at a later date. But for now I'd only be interested in real-world regressions caused by this PR.
I think the only one that might exist is scrolling in Amazon Kindle for PC -- this is the only browse mode implementation that uses IAccessible2 directly, and it is possible scrollToSubstring may have the limitation you noted in #9919. Though that would need to be tested.