Dont report description in browse mode with reportObjectDescriptions
nvaccess/nvda pull request #12917
Opened 2021-10-08 04:59 UTC by feerrenrut

### Link to issue number:
Fixes: #12750

### Summary of the issue:
Historically the option "Object presentation: Report Object Descriptions" (default: true) has been limited to focus mode and object navigation.
In Report aria-description always #12500 this was changed to report descriptions always.
Historically, the word "object" in the settings category, and the name of this option was supposed to imply "focus mode / object nav specific behavior".

### Description of how this pull request fixes the issue:
- Introduces a way to test braille (not dots, raw text) output.
- Reverts changes from #12500 that aimed to make the reportObjectDescriptions behavior consistent between browse and focus modes.
- Updates the user docs to specify that options in the Object Presentation category don't apply to browse mode.

### Testing strategy:
System tests with examples inspired by #12750.
- Browse mode (nav by down arrow) with reportObjectDescriptions True and False
- Focus mode (nav by tab) with reportObjectDescriptions True and False

### Known issues with pull request:
None

### Change log entries:

For Developers:
```
- Braille output can now be checked in system tests.
```

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

2021-10-11 00:43 UTC, michaelDCurran commented
I have not yet looked at the exact changes in this pr. But, I want to clarify that report object descriptions was originally created for when reporting focus or object navigation. As opposed to controlFields in text content. So, I don't see this as a simple disctinction between browse and focus mode. Rather it is text verses objects. 
The reason this is very important is that contenteditable (focus mode) and browse mode should (where ever possible) report the same thing. But I'll look at the diff now.

2021-10-11 02:58 UTC, feerrenrut commented
>So, I don't see this as a simple disctinction between browse and focus mode. Rather it is text verses objects.

What is an object from a user's perspective? It's very developer centric terminology, and even then quite overloaded.

2021-10-11 07:42 UTC, michaelDCurran requested changes

2021-10-11 17:42 UTC, lukaszgo1 commented
Have you tested specifically STR from #12750 and can confirm that content of the title attribute is no longer shown in braille? If so this should be mentioned in the PR description.

2021-10-13 03:33 UTC, michaelDCurran approved these changes

2021-10-13 08:33 UTC, merged