Prefer Difflib in scrolling LiveText objects
nvaccess/nvda pull request #12974
Opened 2021-10-21 20:14 UTC by codeofdusk

### Link to issue number:
[Twitter thread](https://twitter.com/destructatron04/status/1451082893917409280).

### Summary of the issue:
In `LiveText` objects that are constrained to onscreen text (i.e. where text scrolls off the screen), DMP is sometimes unable to correctly calculate new text, leading to choppy and inconsistent new text reporting.

### Description of how this pull request fixes the issue:
Prefer Difflib in pre-`FORMATTED` UIA console (including legacy mode) and `DisplayModelLiveText` objects. Users can override this choice in advanced settings for testing or if DMP really provides a supperior experience in their situation.

### Testing strategy:
Tested the following scenarios:

Application | User setting | Algorithm used
--- | --- | ---
`FORMATTED` Windows Console | Automatic | DMP
`FORMATTED` Windows Console | Diff Match Patch | DMP
`FORMATTED` Windows Console | Difflib | Difflib
`IMPROVED` Windows Console | Automatic | Difflib
`IMPROVED` Windows Console | Diff Match Patch | DMP
`IMPROVED` Windows Console | Difflib | Difflib
`END_INCLUSIVE` Windows Console | Automatic | Difflib
`END_INCLUSIVE` Windows Console | Diff Match Patch | DMP
`END_INCLUSIVE` Windows Console | Difflib | Difflib
Legacy Windows Console | Automatic | Difflib
Legacy Windows Console | Diff Match Patch | DMP
Legacy Windows Console | Difflib | Difflib
Windows Terminal | Automatic | DMP
Windows Terminal | Diff Match Patch | DMP
Windows Terminal | Difflib | Difflib
PuTTY | Automatic | Difflib
PuTTY | Diff Match Patch | DMP
PuTTY | Difflib | Difflib

### Known issues with pull request:
None known.

### Change log entries:
== Bug Fixes ==
- Improved consistency of output reading in terminal programs.
    - Note that in some situations, when inserting or deleting characters in the middle of a line, the characters after the caret may again be read out.

== Changes for Developers ==
- `diffHandler.get_dmp_algo` and `diffHandler.get_difflib_algo` renamed `diffHandler.prefer_dmp` and `diffHandler.prefer_difflib` respectively.

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

2021-10-27 03:41 UTC, seanbudd requested changes

2021-10-27 04:23 UTC, seanbudd approved these changes
@Qchristensen - what are your thoughts on the docs changes?

2021-11-04 00:54 UTC, Qchristensen approved these changes
Makes sense, good work.

2021-11-04 03:03 UTC, seanbudd approved these changes

2021-11-04 03:37 UTC, merged