Add a script to report locationText for the position of the system caret
nvaccess/nvda pull request #13060
Opened 2021-11-15 12:26 UTC by lukaszgo1

### Link to issue number:
Closes #9147
Related to #7314

### Summary of the issue:
Currently it is impossible to report locationText for the current caret position only for the position of the review cursor. This is problematic in several cases:
- As described in #9147 there are cases in which it is useful to query  the name of the current sheet in MS Excel
- In edit controls and / or web browsers sighted people can simply glance at the scroll bar to determine their position in the text

While for people working with review cursor following system caret current NVDA+Numpad delete is sufficient for these use cases when review cursor does not follow caret you need  to move it to focus every time when you need to check your current position which wastes time, and more importantly makes your review position lost.

### Description of how this pull request fixes the issue:
- NVDA+numpad delete reports location of the caret or focused  object if there is no caret by default.
- Script for reporting review cursor position has been reassigned to NVDA+shift+Numpad delete - for most users there is no change as navigator follows focus and review follows caret by default.
- The modified scripts are splitted into separate ones for querying location of the text / object as discussed in #7314.
### Testing strategy:
Ensured that modified scripts works.
### Known issues with pull request:
None known
### Change log entries:
Changes
- NVDA+Numpad delete reports location of the caret / focused object by default - add shift to report location of the review cursor.

### Code Review Checklist:

- [X] Pull Request description:
  - description is up to date
  - change log entries
- [X] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [X] API is compatible with existing add-ons.
- [X] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [X] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

2021-11-15 22:16 UTC, seanbudd requested changes
Thanks @lukaszgo1, generally looks good to me. I've added a few whitespace and other minor fixes.

2021-11-15 22:16 UTC, seanbudd commented on source/globalCommands.py
> +	def _getTIAtCaret(fallbackToPOSITION_FIRST=False, reportFailure=True):
```suggestion
	def _getTIAtCaret(fallbackToPOSITION_FIRST: bool = False, reportFailure: bool = True) -> None:
```

2021-11-15 22:16 UTC, seanbudd commented on source/globalCommands.py
> +			"Reports information about the location of the text or object at the positionn of system caret "
```suggestion
			"Reports information about the location of the text or object at the position of system caret. "
```

2021-11-15 22:16 UTC, seanbudd commented on source/globalCommands.py
> +			"or  location of the  currently focused object if there is no caret."
```suggestion
			"or location of the currently focused object if there is no caret."
```

2021-11-15 22:16 UTC, seanbudd commented on source/globalCommands.py
> +	def _reportLocationText(objs) -> None:
Could `objs` get a type hint?

2021-11-15 22:16 UTC, seanbudd commented on source/globalCommands.py
> +			# review cursor falling back to the location of navigator object if needed.
```suggestion
			# review cursor, falling back to the location of navigator object if needed.
```

2021-11-15 22:16 UTC, seanbudd commented on source/globalCommands.py
> +			"or  location of the  navigator object if there is no text under review cursor."
```suggestion
			"or location of the navigator object if there is no text under review cursor."
```

2021-11-16 09:01 UTC, lukaszgo1 commented
@seanbudd  I believe all changes you've requested are now addressed.

2021-11-16 23:22 UTC, seanbudd approved these changes
Thanks @lukaszgo1, looks good to me.
Going to wait for @Qchristensen to check the user guide changes before merging.

2021-11-23 01:03 UTC, Qchristensen approved these changes
Looks good, great work!

2021-11-23 02:47 UTC, merged