Switch to browse mode if read-only list items and their list parents are focusable and have focus
nvaccess/nvda pull request #13357
Opened 2022-02-17 12:11 UTC by MarcoZehe

### Link to issue number:

Fixes #13221

### Summary of the issue:

In the Microsoft Edge Downloads manager (CTRL+J), as well as in the channel and DM outputs of the Slack app, HTML lists and list items are used to display the items. These are made focusable via either aria-activedescendant, or the rowing tabIndex pattern. The reason is that for compatibility, these can be used to host rich content, such as whole sub documents or controls. Until now, NVDA would not automatically switch to focus mode when focus lands on such a focusable list item.

### Description of how this pull request fixes the issue:

This PR adds a rule for enabling passthrough mode if a list item that is read-only, has state focused, and at the same time its paarent is of role list and is focusable.

### Testing strategy:

1. Run NVDA.
2. Go into Microsoft Edge.
3. Press Control+J to invoke Downloads Manager.
4. Focus should be on the first downloaded item, and passthrough mode should automatically be enabled.

### Known issues with pull request:

None known.

### Change log entries:
New features
Changes
Bug fixes

* In the Microsoft Edge downloads manager, NVDA will now automatically switch to focus mode once the list item with the most recent download gains focus.

For Developers

### Code Review Checklist:

- [X] Pull Request description:
  - description is up to date
  - change log entries
- [ ] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [X] API is compatible with existing add-ons.
- [ ] Documentation: Not needed since expected behavior is introduced where user would previously have to manually switch pass-through mode on.
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [X] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

2022-02-17 13:13 UTC, TheQuinbox commented
Nice, looks good to me. In NVDA changelog entries though, it's typical to link to the issue that it solves (if applicable).

2022-02-17 13:46 UTC, MarcoZehe commented
Thanks @TheQuinbox, I just updated the initial description with that, as well as the checkbox for the testing part, since the manual check checks out nicely.

2022-02-17 14:47 UTC, CyrilleB79 commented
Typo to fix in the change log:
#13321 -> #13221

2022-02-17 16:02 UTC, lukaszgo1 commented
Have you considered adding Chrome system test demonstrating the behavior based on the code snippet in #13221?

2022-02-17 17:29 UTC, MarcoZehe commented
Thanks @CyrilleB79, corrected the typo.

@lukaszgo1 I'll try that system test thing, but this is all still very confusing, so may take a while. And it's made difficult by the fact that I can't currently even run local builds, and that includes tests. See my message in the nvda-devel mailing list. But I'll try nevertheless.

2022-02-17 18:49 UTC, leonardder commented
Thanks Marco, this is a nice improvement! One question: Isn't it just enough that a list item has focus? Why check the focusable state on the parent list as well??

2022-02-17 19:43 UTC, MarcoZehe commented
@leonardder I was going with @michaelDCurran's statement from https://github.com/nvaccess/nvda/issues/13221#issuecomment-1039904489:

> We will switch to focus mode if a listItem gets focus, but only if the list itself is also focusable. I.e. the list has at least tabindex of -1.

This is how MS Edge's Download Manager list works, and it means that @kloots will have to make a slight adjustment in Slack to put tabindex="-1" on the actual list, which Slack currently doesn't do yet.

2022-02-17 22:35 UTC, michaelDCurran commented
For reference, the reasoning behind requiring focusable on the list is to limit where this code will apply.
1. Making ul (or role="list) and (li or role="listitem") interactive like this does not quite fit standards as really these are presentational read-only lists. Interactive lists should be role="listbox" and role="option".
2. There may already exist some web pages that deliberately set focus to a presentational list item when the page is scrolled to an arbitrary location. In this case switching to focus mode would be annoying and inappropriate.

But, it has been made clear that the standard does not really fit some particular use cases, and therefore this change is needed. Therefore it is being added, but with the limitation that the list must also be focusable. This idea was proposed by Slack themselves.

2022-02-17 22:45 UTC, michaelDCurran requested changes

2022-02-17 22:45 UTC, michaelDCurran commented on tests/system/robot/chromeTests.robot
> +	[Documentation]Focused list items with a focusable list container should cause focus mode to be turned on automatically.
Missing tab character after `[Documentation]`
```suggestion
	[Documentation]	Focused list items with a focusable list container should cause focus mode to be turned on automatically.
```

2022-02-17 22:46 UTC, michaelDCurran commented
I think the title of this pr should refer to Focus mode, not Browse mode.

2022-02-18 03:33 UTC, MarcoZehe commented
> I think the title of this pr should refer to Focus mode, not Browse mode.

Done.

2022-02-18 07:05 UTC, MarcoZehe commented
Sorry this is going so slowly. I cannot run the tests on my local machine because it is not an English language Windows, and therefore all NVDA tests fall on their face. So I have to peel this like an onion.

2022-02-18 07:40 UTC, MarcoZehe commented
@michaelDCurran I don't understand this error message. The previous test failures were clear, but this one confuses me. It says:

> Error message:
focus mode - focus link in document and turn off focus mode
speech Actual != Expected: message
Todd Kloots  link !=   message
Todd Kloots  link
Browse mode

Any help is appreciated.

2022-02-18 10:18 UTC, MarcoZehe commented
@michaelDCurran I went with your suggestion of simplifying the test case after all, and it now passes. I can't clear the "changes requested" flag from the issue even though I applied your suggested code change, and also updated the PR title. So, tossing this back for review in hopes that things look good so far. I'd also be happy to help out with #12896 if that's desired.

2022-02-18 11:10 UTC, michaelDCurran commented
Thanks for your work on this @MarcoZehe.
I shall review this  sometime in the next couple of days.

2022-02-19 07:55 UTC, brunoprietog commented
This is great! Can you think of a way to fix #12266? It's a similar list focus problem. Thanks!

2022-02-19 08:16 UTC, MarcoZehe commented
I just commented on the issue: It is a different bug, which will not be fixed by this pull request. The bug is in the Chromium engine, not NVDA in that case. The markup is also radically different from what is being used here.

2022-02-20 23:21 UTC, michaelDCurran approved these changes

2022-02-20 23:52 UTC, merged

2022-03-01 00:26 UTC, kloots commented
@michaelDCurran I see this has been added to the 2022.1 release milestone. Does the team have a release date spec'd for 2022.1?

2022-03-01 01:06 UTC, michaelDCurran commented
@kloots  perhaps end of March / early April.

2022-04-18 20:32 UTC, kloots commented
@michaelDCurran curious about the release date for this fix: any update as to when this will go out to production?

2022-04-18 22:22 UTC, michaelDCurran commented
It is currently in NVDA 2022.1beta3. There are plans for a beta4 in the 
coming week or so, and then the release will most likely be 3 or so 
weeks after that. So rough guess is mid May.

2022-04-18 22:23 UTC, kloots commented
Great. Thanks @michaelDCurran. Dumb question: how do I get the beta?

2022-04-18 22:32 UTC, michaelDCurran commented
Link to beta3 post: https://www.nvaccess.org/post/nvda-2022-1beta3/

2022-04-18 23:15 UTC, kloots commented
Thanks @michaelDCurran. One last question, do you have a sense for how quickly NVDA users upgrade?

2022-04-18 23:25 UTC, michaelDCurran commented
Users upgrade pretty slowly I'm sorry to say.
NVDA 2021.3.5 has been out for about 3 weeks now, and only 30% of users 
have upgraded. The rest are all on random older versions. The next most 
popular version is 2021.3.1 at just under 10%.

We alert users of updates within NVDA when ever they are available.