No longer use fileinput when generating COMInterfaces as it breaks parallel builds
nvaccess/nvda pull request #13367
Opened 2022-02-19 19:37 UTC by lukaszgo1

### Link to issue number:
Fixes #13290
Related to [this thread on nvda-devel](https://groups.io/g/nvda-devel/topic/89208225#46086) by @MarcoZehe 
### Summary of the issue:
PR #13226 started building nVDA in parallel. While this offers significant speed improvements the way in which we were generating COMInterfaces was not thread safe. The issue was caused by the `fileinput` module which redirects stdout to a given file and this cannot be done in multiple threads at the same time. Also, as discovered by @MarcoZehe in the thread linked above when stdout is redirected to a file some other build step which is executing in a separate thread can write to it and the text which should be shown on screen ends up in the COMInterface file.
### Description of how this pull request fixes the issue:
Were not using `fileinput` anymore - the IDE friendly content is generated in memory and then written to the file afterwards.
### Testing strategy:
Made sure that COMInterfaces can be generated from a clean checkout.
### Known issues with pull request:
None known
### Change log entries:
None needed.
### Code Review Checklist:

- [X] Pull Request description:
  - description is up to date
  - change log entries
- [X] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [X] API is compatible with existing add-ons.
- [X] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [X] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

2022-02-21 02:11 UTC, seanbudd commented
We are also considering reverting #13226

2022-02-21 06:04 UTC, lukaszgo1 commented
Note that even if #13226 gets reverted this PR should still be merged since, as @michaelDCurran  said, allowing people to build in parallel is still beneficial.

2022-02-21 07:38 UTC, leonardder requested changes
Thanks for taking this!

2022-02-21 07:38 UTC, leonardder commented on source/comInterfaces_sconscript
> +		interfaceFile.write("".join(IDEFriendlyContent))
```suggestion
		interfaceFile.writelines(IDEFriendlyContent)
```

2022-02-21 15:47 UTC, lukaszgo1 commented
@leonardder  All addressed.

2022-02-21 18:27 UTC, leonardder approved these changes

2022-03-10 06:34 UTC, michaelDCurran approved these changes

2022-03-10 06:35 UTC, merged