Implement API changes for gui.message
nvaccess/nvda pull request #13376
Opened 2022-02-22 06:59 UTC by seanbudd

### Link to issue number:

Relates to #13007, as the new design should be backwards compatible, we can implement the API changes as-is for 2022.1.
Commits to the API proposed in #12984

### Summary of the issue:

The API for `gui.message` had not yet been determined for 2022.1, as per #13007.
As the future API is intended to be backwards compatible, this PR commits to the API proposed in #12984.

### Description of how this pull request fixes the issue:

Commits to the API proposed in #12984

Changes logic `gui/message.py` to be safer with locking and handling errors.

### Testing strategy:
Alpha/beta testing of messageBoxes 

### Known issues with pull request:
None

### Change log entries:
See PR diff

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

2022-02-24 09:26 UTC, feerrenrut requested changes
if `isInMessageBox` is still used as a bool variable, it will always be true. I think a new name should be used, so that that code that doesn't get updated throws an error, rather than doing the wrong thing. Consider:

``` python
def isInMessageBox():
	return False
print(bool(isInMessageBox))  # prints True

# contrived example of addon code that has not been updated.
if isInMessageBox:  # always true, instead it should error "name 'isInMessageBox' is not defined"
    log.debug("in the message box")
```

2022-02-24 09:26 UTC, feerrenrut commented on user_docs/en/changes.t2t
> +- ``gui.isInMessageBox`` is now a function which returns a boolean. (#12984, #13376)
What was it before?

2022-02-24 09:26 UTC, feerrenrut commented
Could you update this PR to make the title more descriptive of the change, and describe the changes that are part of this PR. Issue https://github.com/nvaccess/nvda/pull/12984 contains lots of suggestions, what does this PR do?

2022-02-28 04:18 UTC, feerrenrut reviewed
Don't forget to update the API plan. 

Thinking about what is important to point out in the plan:
- This function can only tell you if 1 or more message boxes are active.
- If, in the future, there can be multiple (non-modal) message boxes active, the API will need to be extended, perhaps with "getActiveMesageBoxes()". This is fine.

This second point makes me think this method should be specific to modal message boxes, I.E. rename to `isModalMessageBoxActive()`. With docs explicitly stating "only one modal message box may be active at once"

What do you think?

2022-02-28 04:18 UTC, feerrenrut commented on user_docs/en/changes.t2t
> +- ``gui.isInMessageBox`` is removed, please use ``gui.message.isMessageBoxActive`` instead. (#12984, #13376)
```suggestion
- Boolean ``gui.isInMessageBox`` is removed, please use function ``gui.message.isMessageBoxActive()`` instead. (#12984, #13376)

```

2022-02-28 04:28 UTC, seanbudd commented
>With docs explicitly stating "only one modal message box may be active at once"

I don't believe this is true, as per https://github.com/nvaccess/nvda/pull/12984#issuecomment-952561745.

I think the name `isModalMessageBoxBlocking` might even be better. In the future API we might want to ignore non-blocking message boxes.

2022-03-01 03:35 UTC, feerrenrut commented
Yes, I'd forgotten that case, thought it is arguable that even in that case only one is active at a time. I.E. only one of them is processing messages.

> I think the name isModalMessageBoxBlocking might even be better.

It raises the question, what is it blocking?

2022-03-02 05:56 UTC, feerrenrut requested changes

2022-03-02 23:22 UTC, seanbudd commented on source/gui/message.py
> +	messageBox is a function which blocks the calling thread,
fixed, by changing this to `gui.message.messageBox`

2022-03-02 23:23 UTC, seanbudd commented on source/gui/message.py
> +	`IsInMessageBox` should be used when an answer is required before proceeding.
This should actually refer to `isModalMessageBoxActive`, which has been fixed and the sentence reworded to be clearer.

```
`gui.message.messageBox` is a function which blocks the calling thread,
until a user responds to the modal dialog.
`isModalMessageBoxActive` should be used when an answer from a `gui.message.messageBox`
is required before proceeding.
```

2022-03-02 23:23 UTC, seanbudd commented on source/gui/message.py
> +	This function may prevent this from happening.
fixed

2022-03-02 23:23 UTC, seanbudd commented on source/gui/message.py
> +	Consider using a custom subclass of a wxDialog if an answer is not required.
added

2022-03-02 23:23 UTC, seanbudd commented on source/gui/message.py
> +	Before opening a new messageBox, use isModalMessageBoxResponsePending
fixed

2022-03-02 23:44 UTC, feerrenrut commented on source/gui/message.py
> +	`IsInMessageBox` should be used when an answer is required before proceeding.
> `isModalMessageBoxActive` should be used when an answer from a `gui.message.messageBox`
is required before proceeding.

I don't think it's obvious why you would call `isModalMessageBoxActive` if an answer is required. You'd call it to ensure there isn't already a modal message box open.

2022-03-02 23:45 UTC, feerrenrut commented on source/gui/message.py
> +	`IsInMessageBox` should be used when an answer is required before proceeding.
The current sentence makes it sound like calling `isModalMessageBoxActive` makes the answer required.

2022-03-03 00:00 UTC, seanbudd commented on source/gui/message.py
> +	`IsInMessageBox` should be used when an answer is required before proceeding.
>I don't think it's obvious why you would call isModalMessageBoxActive if an answer is required. You'd call it to ensure there isn't already a modal message box open.

These two things are the same, no? This doesn't answer the question as to why you should ensure at modal message box isn't currently open. To safely proceed with shutdown, you need an answer from pending messageBoxes. To safely proceed with opening certain dialogs and other messageboxes, you need an answer from pending messageBoxes.

How about:

>`isModalMessageBoxActive` should be used when an answer from an open `gui.message.messageBox`
is required before proceeding.

2022-03-03 00:10 UTC, seanbudd commented on source/gui/message.py
> +	`IsInMessageBox` should be used when an answer is required before proceeding.
Without this sentence, I think it is unclear on the purpose of this function, and when to use it.

2022-03-03 02:39 UTC, feerrenrut commented on source/gui/message.py
> +	`IsInMessageBox` should be used when an answer is required before proceeding.
It still make it sound like it is `isModalMessageBoxActive` that makes the answer a requirement.

Instead:
```
When some action (E.G. Quitting NVDA) should be prevented due to any active modal/blocking message box,
even if unrelated, use `isModalMessageBoxActive` to check before triggering the action, 
```

2022-03-03 02:52 UTC, seanbudd commented on source/gui/message.py
> +	`IsInMessageBox` should be used when an answer is required before proceeding.
amended in 8f28274

2022-03-03 08:00 UTC, feerrenrut approved these changes

2022-03-03 22:59 UTC, merged