Only remove XML tags if JAB widget's text starts with <html> tag
nvaccess/nvda pull request #13531
Opened 2022-03-24 17:03 UTC by mwhapples

### Link to issue number:
#13102 
### Summary of the issue:
NVDA was incorrectly stripping text from Java widgets if the text looked like an XML tag. According to the Oracle Java docs, when using HTML in a Java widget you should start the text with the &lt;html&gt; tag.
### Description of how this pull request fixes the issue:
This change gets NVDA to check if the text starts with &lt;html&gt; and only then will remove any text which appears to be XML tags.
### Testing strategy:
Manually tested.
### Known issues with pull request:
I haven't checked exactly what the regular expression does, but I suspect it does not handle entity substitution (eg. &amp;lt; with &lt; and such like). Ideally this should also be fixed, but we may want to track that as a separate issue as its something slightly different to the original issue this is designed to fix.
### Change log entries:
New features
Changes
Bug fixes
Fix issue where NVDA may incorrectly remove text from Java widgets when presenting to the user.
For Developers

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date Yes
  - change log entries Done
- [x] Testing:
  - Unit tests Unsure how to unit test this. I could write tests for the function to remove the HTML tags.
  - System (end to end) tests Not done, unsure how to do for this issue.
  - Manual testing Yes
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation N/A
  - Developer / Technical Documentation N/A
  - Context sensitive help for GUI changes N/A
- [x] UX of all users considered:
  - Speech Yes
  - Braille Yes
  - Low Vision Yes
  - Different web browsers N/A
  - Localization in other languages / culture than English N/A

2022-03-24 22:59 UTC, michaelDCurran requested changes
The actual change looks fine to me.
But, Some unit tests would be great for testing _processHTML. Especially a unit test at very least for the label content in the issue. And perhaps a plain text label, and of course a label with valid html.
Add a new file to tests/unit
Name it something like test_javaAccessBridge.py
You could use a file like test_winVersion.py as an example, so you can see how to write the test class and methods.
Then you can run `rununittests` and ensure all of them pass.

2022-03-25 10:21 UTC, mwhapples commented
I am on creating a test for this now. In fact I realised that by refactoring out to _processHTML would help me test it as it separates the logic for detecting and removing HTML tags from the accessibility API stuff. Also testing this in the future would be more important should we do things like replacing character entities and such like as the code could become more involved.

2022-03-25 11:00 UTC, mwhapples commented
Tests now written.

2022-03-27 22:17 UTC, michaelDCurran commented on tests/unit/test_javaAccessBridge.py
> +# Copyright (C) 2021 NV Access Limited, American Printing House for the Blind
```suggestion
# Copyright (C) 2022 NV Access Limited, American Printing House for the Blind
```

2022-03-27 22:23 UTC, michaelDCurran approved these changes
Great work, thanks :)

2022-03-27 22:52 UTC, merged