Fix a number of (java Access Bridge issues
nvaccess/nvda pull request #13744
Opened 2022-05-27 21:10 UTC by mwhapples

### Link to issue number:
Fix #9184 and fix #9728 
### Summary of the issue:
A number of features in (java Access Bridge were not working optimally.
* Toggle buttons were not read correctly.
* Various commands like read window and read window title were not working when java applications have multiple windows.
* Unnecessary spaces when HTML tags removed from Java controls.
* Provide position information for (java tab controls.

### Description of how this pull request fixes the issue:
* Java toggle buttons use the checked state for pressed, correctly map this. The value should be ingored for a toggle button.
* According to Java documentation https://docs.oracle.com/en/java/javase/17/docs/api/java.desktop/javax/accessibility/AccessibleContext.html#getAccessibleIndexInParent() when getAccessibleIndexInParent returns -1 there is no parent. So in NVDA if indexInParent is None we should treat it as if parent is not set.
* Updated the regular expression processing for HTML tags to check if the tags are at the start or end or have surrounding whitespace, in which case the tag is stripped. If there is only non-whitespace characters around the tag then replace the tag with a space to prevent words being joined.
* For (java controls with Role.TAB use indexInParent and parent.childCount to find the position information.

### Testing strategy:
Manual following steps in issue #9728 and unit tests for HTML processing.
### Known issues with pull request:
None known.
### Change log entries:
New features
Changes
* NVDA now gives position information for tab controls in (java applications.
Bug fixes
* Correctly report state of Java toggle buttons.
* Correctly identify the window in a (java application with multiple windows.
* Better removal of HTML tags in (java controls.
For Developers

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests Not sure how to do such tests for java applications.
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

2022-05-28 00:02 UTC, cary-rowen commented
@mwhapples 
Thanks for your efforts, Could you take a look at #13039
, is this also relevant for Java applications.
Thanks

2022-05-28 10:38 UTC, mwhapples commented
> @mwhapples Thanks for your efforts, Could you take a look at #13039 , is this also relevant for Java applications. Thanks

IntelliJ, Android Studio, PyCharm and other JetBrains IDEs use Java Access Bridge. I also use those tools daily so am interested in fixing issues with those. I will take a look at that and other related issues. However for the purposes of this pull request, I think #13039 is out of scope and should be dealt with in another pull request. I prefer to keep pull requests small and targeted so that functionality/fixes do not get blocked by other fixes.

2022-06-01 04:38 UTC, seanbudd requested changes
generally LGTM, some minor changes needed

2022-06-01 04:38 UTC, seanbudd commented on source/NVDAObjects/JAB/__init__.py
> +def _subHtmlTag(match):
Can this please get type definitions and a doc string?

```suggestion
def _subHtmlTag(match: re.match) -> str:
```

2022-06-01 04:38 UTC, seanbudd commented on source/NVDAObjects/JAB/__init__.py
>  def _processHtml(text):
```suggestion
def _processHtml(text: str) -> str:
```

2022-06-01 04:38 UTC, seanbudd commented on source/NVDAObjects/JAB/__init__.py
> +		and not self._JABAccContextInfo.accessibleText:
Using parentheses improves readability and means you don't have to escape the newlines

```suggestion
		if (
			self.role not in [
				controlTypes.Role.TOGGLEBUTTON, controlTypes.Role.CHECKBOX,
				controlTypes.Role.MENU, controlTypes.Role.MENUITEM,
				controlTypes.Role.RADIOBUTTON, controlTypes.Role.BUTTON
			]
			and self._JABAccContextInfo.accessibleValue
			and not self._JABAccContextInfo.accessibleText
		):
```

2022-06-01 04:38 UTC, seanbudd commented on source/NVDAObjects/JAB/__init__.py
> +			controlTypes.Role.TREEVIEWITEM, controlTypes.Role.LISTITEM, controlTypes.Role.TAB):
Another linting change for readability 

```suggestion
		if (
			isinstance(parent, JAB)
			and self.role in (
				controlTypes.Role.TREEVIEWITEM,
				controlTypes.Role.LISTITEM,
				controlTypes.Role.TAB
			)
		):
```

2022-06-01 04:40 UTC, seanbudd commented
This PR description is quite hard to follow. 
Would it be possible to split this PR to address fixing each issue individually?

2022-06-01 12:57 UTC, mwhapples commented
> This PR description is quite hard to follow. Would it be possible to split this PR to address fixing each issue individually?

I could improve the description if that would help. I tend to rely upon the referenced issue providing the detail, but I could supply more detail in this case to help clarify what were the bugs.
I created this PR to mirror the issue #9728 and I noticed it overlapped with #9184. I prefer to keep 1 pull request for 1 issue for ease of tracking when the issue can be closed. The exception being where the work will take some time and in stages, but even in that case it then raises the question whether the original issue ticket should be split into multiple issues as well.
To split this into multiple pull requests now I feel would not be an effective use of time due to the amount of time it may take to reorganise the commits.

2022-06-02 00:38 UTC, seanbudd approved these changes
Thanks @mwhapples - I can tidy up the PR description

2022-06-02 01:54 UTC, merged