For SysListViews, map first column to first column when no known column order array
nvaccess/nvda pull request #13761
Opened 2022-06-02 02:51 UTC by seanbudd

### Link to issue number:
Fixes #13659, #13735 

### Summary of the issue:

Certain applications don't provide a column order array. This is generally because they are a single column list view, and as such, want developers to assume that the column order array is `[0]` in this case.

### Description of how this pull request fixes the issue:

Assume that the column order array is `[0]` in the case of a column order array is not provided. 

### Testing strategy:

Manual testing
- [x] Test reading start menu items with StartAllBack/StartIsBack (STR in #13659)
- [ ] Test STR in #13735 (thanks @cary-rowen)

### Known issues with pull request:
For list views that have multiple columns, only the leftmost items in the UX will be able to be read, and the contents may be incorrectly mapped to a different index.
This is preferable to not reading any information, and in both cases the fault is on the developer for not implementing the column order array correctly.

### Change log entries:
Not needed, fixing rare behaviour

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

2022-06-02 06:45 UTC, CyrilleB79 commented
@seanbudd, if I understand correctly, there has been a regression for some applications (StartisBack and the one in 13735) between 2021.3.5 and 2022.1.
From a user point of view, it would be worth to have a change log item to indicate that this issue has been fixed (or worked around).

2022-06-02 07:30 UTC, cary-rowen commented
Just curious, why isn't CI generating the build?

2022-06-02 10:39 UTC, leonardder commented
> Just curious, why isn't CI generating the build?

Because this pr is made against another branch (not beta, rc, master)

2022-06-03 03:57 UTC, seanbudd commented
@cary-rowen - you can test this build: https://ci.appveyor.com/api/buildjobs/tinlr9qek2w5cd8b/artifacts/output%2Fnvda_snapshot_try-fixSingleColumnSysListViews-25504%2Ccff35796.exe

Sorry for the delay - we had to fix the build system

2022-06-03 05:01 UTC, cary-rowen commented
Hi, @seanbudd 

I tested #13735 with the build you provided and it has been fixed.
thanks for your efforts.

Best

2022-06-03 07:04 UTC, feerrenrut requested changes
Overall looks good.

2022-06-06 00:38 UTC, seanbudd commented on source/NVDAObjects/IAccessible/sysListView32.py
> +	def _getColumn(self, column: int) -> Optional[int]:
I've changed the name to `getMappedColumn` and added a docstring.

2022-06-06 05:01 UTC, cary-rowen commented
Will NV Access consider creating an NVDA2022.1.1?

2022-06-08 09:47 UTC, feerrenrut approved these changes
Looks good.

2022-06-09 00:49 UTC, seanbudd commented on source/NVDAObjects/IAccessible/sysListView32.py
> +		"""
Fixed this: note that `presentationIndex` is actually a one based index, not zero based.

2022-06-09 02:52 UTC, merged