Move some global vars to private variables
nvaccess/nvda pull request #14037
Opened 2022-08-19 07:13 UTC by seanbudd

### Link to issue number:

### Summary of the issue:
Add-on API authors may mistakenly use objects cached in `globalVars` directly, instead of through `api.get/set` methods.
This means that insecure objects could be set or returned to the user.

### Description of user facing changes
None

### Description of development approach
Removed variables from `globalVars`:
  - The following have been made removed and made private.
  Instead, set and get these variables via the equivalent `api.get/set` method:
    - `desktopObject`
    - `focusAncestors`
    - `focusObject`
    - `focusDifferenceLevel`
    - `foregroundObject`
    - `mouseObject`
    - `navigatorObject`
    - `reviewPosition`
    -
  - The following have been removed. These variables were previously unset and used:
    - `mouseOldY`
    - `mouseOldX`
    - `lastProgressValue`
    -
  - `reviewPositionObj` has been removed as it was unused. It can be accessed with the equivalent `getReviewPosition().obj`.
  -

### Testing strategy:

### Known issues with pull request:
API breaking change

### Change log entries:
For Developers

```t2t
- Removed variables from ``globalVars``:
  - The following have been made removed and made private.
  Instead, set and get these variables via the equivalent ``api.get/set`` method:
    - ``desktopObject``
    - ``focusAncestors``
    - ``focusObject``
    - ``focusDifferenceLevel``
    - ``foregroundObject``
    - ``mouseObject``
    - ``navigatorObject``
    - ``reviewPosition``
    -
  - The following have been removed. These variables were previously unset and used:
    - ``mouseOldY``
    - ``mouseOldX``
    - ``lastProgressValue``
    -
  - ``reviewPositionObj`` has been removed as it was unused. It can be accessed with the equivalent ``getReviewPosition().obj``.
  -
```

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [ ] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] Security precautions taken.

2022-08-19 08:51 UTC, feerrenrut requested changes
This will need to be changed to preserve backwards compatibility.
We don't advise reading / writing to these variables, a deprecation warning is fine. Note 2023.3 may be too soon to remove these.

2022-08-19 13:03 UTC, Brian1Gaff commented
Why have this little flotilla of emails ended up in my inbox. Normally this 
sort of stuff ends up in a folder. Has the name of a mail list changed 
suddenly?
 Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message ----- 
From: "Reef Turner" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Friday, August 19, 2022 9:51 AM
Subject: Re: [nvaccess/nvda] Move some global vars to private variables (PR 
#14037)


> @feerrenrut requested changes on this pull request.
>
> This will need to be changed to preserve backwards compatibility.
> We don't advise reading / writing to these variables, a deprecation 
> warning is fine. Note 2023.3 may be too soon to remove these.
>
>
>
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/pull/14037#pullrequestreview-1078500859
> You are receiving this because you are subscribed to this thread.
>
> Message ID: ***@***.***>

2022-08-22 00:58 UTC, seanbudd commented
@feerrenrut I'm uncertain how to preserve backwards compatibility here. While it is easy to preserve "getting" these values with `__getattr__`, I'm not sure how we can maintain setting these attributes.

2022-08-22 00:59 UTC, seanbudd commented
@Brian1Gaff please keep discussions on topic, we have no control over the subscription settings you have set up with GitHub

2022-08-22 03:30 UTC, feerrenrut commented
```python
>>> class test:
...     def __init__(self):
...             self._a = 42
...     def __getattr__(self, attrName):
...             if attrName == "a":
...                     return self._a
...             raise AttributeError("bloop")
...     def printA(self):
...             print(self._a)
...     def __setattr__(self, attrName, value):
...             if attrName == 'a':
...                     self._a = value
...             super().__setattr__(attrName, value)
...
>>> t = test()
>>> t.a
42
>>> t.printA()
42
>>> t.a = 54
>>> t.printA()
54
```

You might also want to look at ["Descriptors"](https://docs.python.org/3/howto/descriptor.html#dynamic-lookups) which might provide a helpful way to solve this issue generically:

```python
class DeprecatedAttribute:

   def __init__(self, getAlternative, setAlternative):
        self._getAlt = getAlternative
        self._setAlt = setAlternative

    def __set_name__(self, owner, name):
        self.private_name = '_' + name

    def __get__(self, obj, objtype=None):
        log.warning(f"getting a deprecated attribute, use {self._getAlt} instead")
        return getattr(obj, self.private_name)

    def __set__(self, obj, value):
        log.warning(f"setting a deprecated attribute, use {self._setAlt} instead")
        setattr(obj, self.private_name, value)

class Owner: 
    focus = DeprecatedAttribute("api.getFocus", "api.setFocus")
    foreground = DeprecatedAttribute("api.getForeground", "api.setForeground")

    def __init__(self, initialFocus, initialForeground):
        self._focus = initialFocus
        self._foreground = initialForeground
```

2022-08-23 02:06 UTC, seanbudd commented
Due to the inability to retain backwards compatibility here (refer to #14049), this is closed in favour of #14050, which outlines a longer term strategy to eventually deprecate these variables.

2022-08-23 02:06 UTC, closed without merging