Add theoretical security checks to every script available on the lock screen
nvaccess/nvda pull request #14211
Opened 2022-10-04 05:10 UTC by seanbudd

### Link to issue number:
None

### Summary of the issue:

NVDA may cache or directly access objects below the lock screen while Windows is locked.
As a result, without security checks, secure information may be leaked while Windows is locked.
"Secure objects" refer to `NVDAObjects` which may contain secure information: i.e. objects below the lock screen while Windows is locked.

In 2022.2.4, additional security checks were added to `api.setReviewCursor` to prevent secure objects from being set as the review cursor.
The results of `api.setReviewCursor` are not acknowledged, meaning theoretically a cached secure object may be announced.

Similar issues exist for other scripts available on the lock screen.
A thorough review of every script available on the lock screen is required.

There are no known exploits related to the theoretical issues that this PR attempts to solve.

### Description of user facing changes

### Description of development approach
A thorough review of every script available on the lock screen was performed.

Additional security checks were added to ensure that no secure objects or text from secure objects are cached or announced when activating a script available on the lock screen.

### Testing strategy:

Test on alpha for an extensive period, as these changes are minor but widespread and hard to test manually.

### Known issues with pull request:

None

### Change log entries:
None required

### Code Review Checklist:

- [ ] Pull Request description:
  - description is up to date
  - change log entries
- [ ] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [ ] API is compatible with existing add-ons.
- [ ] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [ ] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [ ] Security precautions taken.

2022-10-04 05:31 UTC, seanbudd commented
cc @CyrilleB79

2022-10-07 05:01 UTC, feerrenrut requested changes
Overall this looks good.

I didn't comment all changes, but it would be good to have an accurate log mesage when the scripts fail due to security. Additionally, for the user, it may be more friendly to supply a specific UI message. 

Additionally, the consistency of the security explainer comments is good, perhaps link them all back to the set of safescripts.

2022-10-14 03:21 UTC, seanbudd commented on source/NVDAObjects/__init__.py
> +			return
Logging on failure should be covered in the call to `objectBelowLockScreenAndWindowsIsLocked`.

`ui.message`s will be added where relevant.

2022-10-14 03:22 UTC, seanbudd commented on source/globalCommands.py
> +			or objectBelowLockScreenAndWindowsIsLocked(curObject)
Logging on failure should be covered in the call to `objectBelowLockScreenAndWindowsIsLocked`.

`ui.message`s will be added where relevant.

2022-10-14 03:22 UTC, seanbudd commented on source/globalCommands.py
> +			and objectBelowLockScreenAndWindowsIsLocked(reviewPosition.obj)
Logging on failure should be covered in the call to `objectBelowLockScreenAndWindowsIsLocked`.

`ui.message`s will be added where relevant.

2022-10-14 03:25 UTC, seanbudd commented on source/globalCommands.py
> +			and objectBelowLockScreenAndWindowsIsLocked(reviewPosition.obj)
yes, fixed

2022-10-19 04:47 UTC, feerrenrut requested changes
I think it's best to be explicit when that the script is expected to return after checking whether the info can be exposed. Trying to prevent future regressions by making the intent explicit.
I didn't mark all the cases where `return` in missing. It would be safest to ensure every `ui.reviewMessage(gui.blockAction.Context.WINDOWS_LOCKED.translatedMessage)` should be followed by a `return`, and if not comment on why a different pattern is followed.

2022-10-27 02:55 UTC, seanbudd commented on source/globalCommands.py
> +			and not objectBelowLockScreenAndWindowsIsLocked(obj)
I have tested reporting the title on the lock screen. "Lock Screen Window" and "Magnifier" were reported correctly from the lock screen and sign-in screen. I'm not sure how gracefully this fails.

2022-10-31 08:42 UTC, feerrenrut approved these changes

2022-11-02 00:14 UTC, merged