Handle Firefox annotation with unknown role, fix typing
nvaccess/nvda pull request #14526
Opened 2023-01-10 00:06 UTC by seanbudd

### Link to issue number:
Follow up of #14507, #14480

### Summary of the issue:
Firefox incorrectly throws an error when browsing annotated content with an unsupported role.
Instead an unknown role should be reported: i.e. "has details".

The typing for annotation data structures were incorrect.

### Description of user facing changes
When browsing content in firefox with an annotation with unsupported role, "has details" is reported instead of throwing an error.

### Description of development approach
Update typing to be more accurate for annotation data structures, log and return None in the Firefox case to match Chromium behaviour.

### Testing strategy:
 Manual testing on Chrome and Firefox with: https://codepen.io/reefturner/pen/poKLQyj

### Known issues with pull request:

### Change log entries:
N/A unreleased bug

### Code Review Checklist:

- [ ] Pull Request description:
  - description is up to date
  - change log entries
- [ ] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [ ] API is compatible with existing add-ons.
- [ ] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [ ] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [ ] Security precautions taken.

2023-01-10 00:07 UTC, seanbudd commented
cc @nvdaes, who reported this privately

2023-01-10 00:24 UTC, michaelDCurran requested changes
Changing the raise to return None looks good.
But I notice that you have changed typing of all the properties from iterator to Generator. This may more correctly reflect the truth, but it does then raise  (most likely an existing issue) that returning generators from cachable properties may be problematic. If the property is called once then a new generator is fetched, and code may iterate over some or all of it. But if the property is again fetched within the same core cycle, that same generator will be returned, which has already be partially or fully exhausted. these properties really should only return lists or tuples...

2023-01-10 01:06 UTC, seanbudd commented
>This may more correctly reflect the truth, but it does then raise (most likely an existing issue) that returning generators from cachable properties may be problematic.

The code which handles all these properties ensures to consider this by turning them into lists or sets.
I don't believe any of these generators are cached properties, only the reference to the parent object i.e. `AnnotationOrigin` is cached.
I think the main concern is one of performance, it might be slower to generate the summary of all the annotation targets at once, as opposed to doing it on the fly.

2023-01-12 23:46 UTC, michaelDCurran approved these changes

2023-01-13 00:52 UTC, merged