Use Word object model to report distances when available
nvaccess/nvda pull request #14575
Opened 2023-01-19 23:01 UTC by CyrilleB79

### Link to issue number:
Fixes #14542

### Summary of the issue:
For Chinese people, paragraph indent is reported in number of characters when using Word object model but in centimeter when using UIA.

### Description of user facing changes

The option "Show measurements in character width" in Word advanced options is now honoured also when using UIA to access Word documents.

### Description of development approach
The only way I've found to know how distances are reported in Word (according to this option) is to use Word object model. When object model is not available, Windows regional setting is used as a fallback as it was before this PR.

### Testing strategy:
TBD
### Known issues with pull request:
None
### Change log entries:
New features
Changes
Bug fixes
For Developers
TBD
### Code Review Checklist:

- [ ] Pull Request description:
  - description is up to date
  - change log entries
- [ ] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [ ] API is compatible with existing add-ons.
- [ ] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [ ] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [ ] Security precautions taken.

2023-01-19 23:02 UTC, CyrilleB79 commented
@cary-rowen would you mind using the test build of this PR when it is ready to check if it fixes #14542? Thanks.

2023-01-20 03:27 UTC, cary-rowen commented
Hi @CyrilleB79 
Thanks for trying to fix this, the CI build seems to be failing, I'll be the first to test it if it works, thanks.

2023-01-20 10:24 UTC, cary-rowen commented
@CyrilleB79 
I tested the build of this PR and it can follow MS Word's "Show measurements in character widt" located in the advanced settings.
But I found another situation, I don't know if I should discuss it separately at the moment:
Checked "Show measurements in character widt": NVDA +F is still reported as characters when the user manually specifies the first line indent as XX cm instead of xx characters in the paragraph formatting dialog.
Ideally, should it also be reported as a manually specified value by the user - XX cm, Because manually changing the unit is allowed for ms Word.

2023-01-20 21:29 UTC, CyrilleB79 commented
> @CyrilleB79 I tested the build of this PR and it can follow MS Word's "Show measurements in character widt" located in the advanced settings. But I found another situation, I don't know if I should discuss it separately at the moment: Checked "Show measurements in character widt": NVDA +F is still reported as characters when the user manually specifies the first line indent as XX cm instead of xx characters in the paragraph formatting dialog. Ideally, should it also be reported as a manually specified value by the user - XX cm, Because manually changing the unit is allowed for ms Word.

I confirm that the user can use any unit in the paragraph formatting dialog. But internally Word stores it in the preferred unit, i.e. the one defined in Word's advanced options. To view an evidence of it, you can do as follows:
* While your unit is set to "character" in Word's advanced options, open paragraph formatting options
* Enter a value in "cm" and validate
* Reopen the paragraph formatting options.
You will see that the unit in this dialog is in the unit of Word's advanced options, i.e. character for you.

So IMO, this makes no sense for NVDA to report the distance with a unit other than the preferred option in any case. Also, keep in mind that the preferred unit option is the one that sighted people will see on the rulers on the side of the pages when Word is in page mode.

2023-01-21 04:42 UTC, cary-rowen commented
Hello, I saw the following two setting items in the advanced options of MS Word:
## Show measurements in units of:
- Centimeters
- Millimeters
- Points
- Picas

This option includes the following items, Centimeters is selected by default but does not contain the character (ch)


## Show measurements in width of characters
The checkbox is checked


---

> 1. Enter a value in "cm" and validate
> 2. Reopen the paragraph formatting options.
> You will see that the unit in this dialog is in the unit of Word's advanced options, i.e. character for you.

No, since the units in the advanced options don't contain characters, it still shows centimeters even though I also ticked "Show measurements in width of characters".

2023-01-22 16:15 UTC, CyrilleB79 commented
OK, I have not been extra clear. Let me rephrase the explanations and the steps.

Word uses only one unit internally to store distances such as the one shown in paragraph formatting settings. This unit is controlled by 2 options in Word advanced options:
* "Show measurements in width of characters": if this checkbox is checked, the paragraph formatting settings show indent in characters. If it is unchecked (or not present if no east Asian language is installed), "Show measurements in units of:" option is looked at. width of characters"
* "Show measurements in units of:": it is used in paragraph formatting dialog only if "Show measurements in width of characters" is unchecked.

Steps to see which unit Word uses internally:
* While "Show measurements in width of characters" is checked in Word's advanced options, open paragraph formatting options
* Enter a value in "cm" and validate
* Reopen the paragraph formatting options.
You will see that the unit in this dialog is in character, which match the checkbox "Show measurements in width of characters" in Word's advanced options.

So it makes sense for NVDA to report distances in the units as defined in Word's advanced option. In case the checkbox "Show measurements in width of characters" is checked in the advanced options, the preferred unit is thus characters and not the one defined in "Show measurements in units of:", which has no effect in the paragraph formatting dialog when the checkbox "Show measurements in width of characters" is checked.

2023-01-24 03:25 UTC, cary-rowen commented
Hi,

Thanks for your patience in clarifying.
But it seems something different in my case, please let me explain.
You wrote:
> 1. While "Show measurements in width of characters" is checked in Word's advanced options, open paragraph formatting options
> 2. Enter a value in "cm" and validate
> 3. Reopen the paragraph formatting options.
> 4. You will see that the unit in this dialog is in character, which match the checkbox "Show measurements in width of characters" in Word's advanced options.

---
### The actual situation:

* I can successfully set to cm when I perform step 2.
* When I do step 4, I still see 'cm' instead of 'character' in the paragraph formatting options.

## A question arises from this:
* If I set the first line indent to 1.8 cm
* When I tested with this snapshot from that PR, NVDA reported 4.86 characters, which is so confusing.
* Please note, Now the first line indent in the paragraph format option is displayed as 1.8cm

2023-01-24 10:42 UTC, cary-rowen commented
Thank you for your efforts, Let's wait for what NV Access thinks.
I should add that my Office version information is as follows:
Microsoft 365MSO (version 2212 Build 16.0.15928.20196) 64 Bit

2023-01-24 14:33 UTC, ABuffEr commented
Hi,

I'm heavily working on Word in these days, with object model and even with C++ part. So, this discussion caught my curiosity

The point, I think, is that method getLocalizedMeasurementTextForPointSize take care of Word options, but has no check on current paragraph in any way. I won't suggest a coded solution (I appreciate a lot Cyrille's participation), but observe this test:

1. ensure to have UIA disabled, a language like simplified Chinese of Taiwan installed in Word, "Show measurements in character width" checked, "Show measurements in units of:" set on centimeters (for testing, it should not matter);
2. close and re-open a new Word document, and write something, i.e. "Test";
3. open NVDA Python console with NVDA+ctrl+z;
4. write following instructions:

```
p=focus.WinwordSelectionObject.Paragraphs(1)`
p.CharacterUnitFirstLineIndent
# it should be 0.0
p.FirstLineIndent
# 0.0 again
```

5. now, without closing console, return to document, open paragraph settings, and set first line indent to 2 (without measure) or 2 characters;
6. return to console and re-check:

```
p.CharacterUnitFirstLineIndent
# it should be 2.0
p.FirstLineIndent
# it should be 22.0
```

7. again, document, paragraph settings, but this time set 3 cm;
8. again, from console:

```
p.CharacterUnitFirstLineIndent
# it should be 0.0
p.FirstLineIndent
# oh yes, it should be 85 and cents
```

So, with a bit of if-elif-else to decide whether a conversion is needed, there could be a solution.

If this will be considered too slow, I could look to get these information via C++ component.

Hth.

2023-01-24 14:58 UTC, CyrilleB79 commented
Yes I agree that there is a solution and that's what I had in mind when writing:
> If we want the information of the unit from the paragraph formatting dialog, it's probably available via the document's object model.

On my side, the questions still open are:
* Does it make sense to use Word document object model when UIA is checked (and will NVAccess accept it) ?
* Does it make sense to use the unit specified in the paragraph formatting dialog to report indent? Especially when (I guess) sighted people do not have it; I guess that sighted people just have the rulers on the side of the page graduated with the unit defined by both Word's advanced options; to be checked by good eyes if possible.

I can still change my mind in the future, but for now, I would answer "No" to these two questions and keep this PR as is.

2023-01-24 16:07 UTC, ABuffEr commented
>     * Does it make sense to use Word document object model when UIA is checked (and will NVAccess accept it) ?

Sure, this is a good point, and I'm interested too.

Personally, now I discovered it, I'd like to keep measurements in character width even with UIA enabled, so I'm favorable to this PR effects, regardless of the second question or technical details.

2023-02-09 22:04 UTC, michaelDCurran requested changes

2023-02-09 22:04 UTC, michaelDCurran commented on source/NVDAObjects/UIA/wordDocument.py
> +		super()._getIndentValueDisplayString(val)
The return was forgotten. After committing this suggestion, please ensure to clearly test the scenario where the object model is unavailable. Even if this is just by temporarily changing the if conndition in this method to `if False:`.
```suggestion
		return super()._getIndentValueDisplayString(val)
```

2023-02-09 22:04 UTC, michaelDCurran commented on source/NVDAObjects/UIA/__init__.py
> +	# @staticmethod
No need to keep the commented line.
```suggestion
```

2023-02-10 21:46 UTC, CyrilleB79 commented
Thanks @michaelDCurran for your review. I have accepted your modifications and tested the case when Word object model is unavailable (on commit 63a5319a7bab335c1a8fd4731b28432e61c8120b) by forcing manually the if statement of `_getIndentValueDisplayString` to be False. I have no opportunity to test real-life use case where object model is unavailable.

2023-02-15 22:21 UTC, michaelDCurran approved these changes

2023-02-15 22:24 UTC, merged