Rewrote the user guide section about the settings dialog
nvaccess/nvda pull request #14937
Opened 2023-05-19 09:54 UTC by XLTechie

### Link to issue number:

Fixes #14927 

### Summary of the issue:

The issue asked that Ctrl+Tab and Shift+Ctrl+Tab be listed in the user guide section regarding the settings dialog, since many users don't know they can use those to move between categories.

### Description of user facing changes

While editing the section, I found some awkward and seemingly redundant wording, and some unclear portions.

* Reworded the initial paragraph to be more clear about categories and settings.
* Added a note that Ctrl+Tab and Shift+Ctrl+Tab can move between settings categories.
* Clarified a sentence about what shortcut keys for categories do.
* Made the note about adding shortcut keys for categories more clear.  As it was written previously, it implied that adding shortcut keys might be the ONLY way to access those categories.

### Description of development approach

I tried to imagine myself in the position of a user who didn't know much about manipulating settings or their dialogs; and rewrote a bit from that prospective.

### Testing strategy:

The test will be whether @Qchristensen still talks to me after reading this.

### Known issues with pull request:

### Change log entries:

Changes
Clarified the user guide section describing the settings dialog.

### Code Review Checklist:

There is no code.

2023-05-31 04:15 UTC, seanbudd reviewed
Generally looks good to me, thanks @XLTechie

2023-05-31 04:15 UTC, seanbudd commented on user_docs/en/userGuide.t2t
> +From anywhere in the dialog., you may also move forward one category by pressing ``ctrl+tab``, or back one category by pressing ``shift+ctrl+tab``.
Fix up punctuation

```suggestion
From anywhere in the dialog, you may also move forward one category by pressing ``ctrl+tab``, or back one category by pressing ``shift+ctrl+tab``.
```

2023-05-31 04:35 UTC, Qchristensen requested changes
Just one small suggestion (Change "a list with several configuration categories", to "a list of configuration categories" - since there are more than "several" now.  Otherwise, all good.

2023-05-31 04:35 UTC, Qchristensen commented on user_docs/en/userGuide.t2t
> +To make it easier to find the kind of settings you want to change, the dialog displays a list with several configuration categories to choose from.
```suggestion
To make it easier to find the kind of settings you want to change, the dialog displays a list of configuration categories to choose from.
```

The list contains 15 items now, not counting any extras added by add-ons.  That seems like more than "several" categories

2023-06-01 03:40 UTC, seanbudd approved these changes

2023-06-01 03:41 UTC, merged