Albatross: gesture for move system caret when routing review cursor
nvaccess/nvda pull request #15122
Opened 2023-07-11 07:04 UTC by burmancomp

### Link to issue number:
none
### Summary of the issue:
Gesture for move system caret when routing review cursor
### Description of user facing changes
| Cycle the braille move system caret when routing review cursor states | ``f1+f3``, ``f9+f11`` |
### Description of development approach

### Testing strategy:
Tested with 80 model.
### Known issues with pull request:
none
### Change log entries:
New features
Changes
Gesture for move system caret when routing review cursor
Bug fixes
For Developers

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] Security precautions taken.

2023-07-11 07:44 UTC, seanbudd approved these changes

2023-07-11 10:50 UTC, Brian1Gaff commented
Who is the bloke Albert Ross? grin

Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message ----- 
From: "burmancomp" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Tuesday, July 11, 2023 8:05 AM
Subject: [nvaccess/nvda] Albatross: gesture for move system caret when 
routing review cursor (PR #15122)


> &lt;!-- Please read and fill in the following template, for an explanation 
> of the sections see:
> https://github.com/nvaccess/nvda/blob/master/devDocs/githubPullRequestTemplateExplanationAndExamples.md
> Please also note that the NVDA project has a Citizen and Contributor Code 
> of Conduct which can be found at 
> https://github.com/nvaccess/nvda/blob/master/CODE_OF_CONDUCT.md. NV Access 
> expects that all contributors and other community members read and abide 
> by the rules set out in this document while participating or contributing 
> to this project. This includes creating or commenting on issues and pull 
> requests.
>
> Please initially open PRs as a draft.
> When you would like a review, mark the PR as &quot;ready for review&quot;.
> See https://github.com/nvaccess/nvda/wiki/Contributing.
> --&gt;
>
> ### Link to issue number:
> none
> ### Summary of the issue:
> Gesture for move system caret when routing review cursor
> ### Description of user facing changes
> | Cycle the braille move system caret when routing review cursor states | 
> ``f1+f3``, ``f9+f11`` |
> ### Description of development approach
>
> ### Testing strategy:
> Tested with 80 model.
> ### Known issues with pull request:
> none
> ### Change log entries:
> New features
> Changes
> Gesture for move system caret when routing review cursor
> Bug fixes
> For Developers
>
> ### Code Review Checklist:
>
> &lt;!--
> This checklist is a reminder of things commonly forgotten in a new PR.
> Authors, please do a self-review of this pull-request.
> Check items to confirm you have thought about the relevance of the item.
> Where items are missing (eg unit / system tests), please explain in the 
> PR.
> To check an item `- [ ]` becomes `- [x]`, note spacing.
> You can also check the checkboxes after the PR is created.
> A detailed explanation of this checklist is available here:
> https://github.com/nvaccess/nvda/blob/master/devDocs/githubPullRequestTemplateExplanationAndExamples.md#code-review-checklist
> --&gt;
>
> - [x] Pull Request description:
>  - description is up to date
>  - change log entries
> - [x] Testing:
>  - Unit tests
>  - System (end to end) tests
>  - Manual testing
> - [x] API is compatible with existing add-ons.
> - [x] Documentation:
>  - User Documentation
>  - Developer / Technical Documentation
>  - Context sensitive help for GUI changes
> - [x] UX of all users considered:
>  - Speech
>  - Braille
>  - Low Vision
>  - Different web browsers
>  - Localization in other languages / culture than English
> - [x] Security precautions taken.
>
> You can view, comment on, or merge this pull request online at:
>
>  https://github.com/nvaccess/nvda/pull/15122
>
> -- Commit Summary --
>
>  * gesture for move system caret when routing review cursor
>
> -- File Changes --
>
>    M source/brailleDisplayDrivers/albatross/gestures.py (1)
>    M user_docs/en/userGuide.t2t (1)
>
> -- Patch Links --
>
> https://github.com/nvaccess/nvda/pull/15122.patch
> https://github.com/nvaccess/nvda/pull/15122.diff
>
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/pull/15122
> You are receiving this because you are subscribed to this thread.
>
> Message ID: ***@***.***&gt;
>

2023-07-12 05:16 UTC, Qchristensen requested changes
I think the User Guide change:
Cycle the braille move system caret when routing review cursor states
should have quotes around the option:
Cycle the "braille move system caret when routing review cursor" states

(This would mean the other pre-existing option lines should be updated, but this one particularly looked out of place as one statement otherwise).

2023-07-12 05:19 UTC, XLTechie commented
Shouldn't it be "braille moves system caret when routing review cursor"

2023-07-12 07:53 UTC, merged