Fixup Eurobraille docs
nvaccess/nvda pull request #15194
Opened 2023-07-26 01:41 UTC by seanbudd

### Link to issue number:
Follow up to #14690 

### Summary of the issue:
The docs for the eurobraille display aren't entirely clear and could use some rewording

### Description of user facing changes
Fix up docs

### Description of development approach
Fix up docs

### Testing strategy:
N/a
### Known issues with pull request:
n/a
### Change log entries:
New features
Changes
Bug fixes
For Developers

### Code Review Checklist:

- [ ] Pull Request description:
  - description is up to date
  - change log entries
- [ ] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [ ] API is compatible with existing add-ons.
- [ ] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [ ] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [ ] Security precautions taken.

2023-07-26 01:42 UTC, seanbudd commented
cc @FalkoBabbage - can you please review these changes?

2023-07-26 04:40 UTC, FalkoBabbage commented
I have passed this on to Eurobraille since they provided the documentation.  I'll call them today as well.

2023-07-26 08:43 UTC, FalkoBabbage commented
Eurobraille agrees with the changes. 
Below is the answer I got:
> The changes are consistent with the documentation I sent you.
>
> 
> To add clarity to this documentation regarding key assignments we can add :
>
> ------------------------------
> 
> The Eurobraille driver is a generic driver for all its devices.
> 
> It is for this is why the driver key mapping refers keys L1 to L8 of Esytime.
> For Esys and b.note these keys does not exists.
> For b.book : L1 is backward key, L8 is forward key and L2 to L7 are the keys named C1 to C6.
> 
> For the same reason the driver key mapping refers Joystick1 and Joystick2 but on b.note these joysticks are 2 keypads of 4 keys.
>
> ------------------------------
> 
> I think a keyboard description for each braille devices is not necessary in NVDA documentation because users have a complete description in device documentation, but if it seems necessary to you or NVDA teams I can send you a short face description for each display ?

2023-07-26 23:41 UTC, Qchristensen requested changes
All looks fine (with the note on capitalisation of braille)

2023-07-26 23:41 UTC, Qchristensen commented on user_docs/en/userGuide.t2t
> +These devices have a Braille keyboard with 10 keys.
The word "Braille" only needs to be capitalised when referring to the inventor of the reading system.  Referring to the code itself, lowercase is usual (as is done in the rest of this PR).  Ref: https://www.brailleauthority.org/capitalization/capitalization.html

2023-07-27 00:56 UTC, seanbudd commented
Thanks @FalkoBabbage 

Further information isn't necessary, but we would welcome any extra documentation which helps:
- a user use the braille device with NVDA
- a developer understand the braille driver and how it talks to the braille device

2023-07-27 00:57 UTC, merged