Use GitHub forms for issues
nvaccess/nvda pull request #15320
Opened 2023-08-22 04:01 UTC by seanbudd

### Link to issue number:
None

### Summary of the issue:
[GitHub issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates#issue-templates) provide an easier and more clear way for users to report issues on the NVDA project.

Currently, when filling out an issue form, inline comments and an external guide is required to understand how to fill out an issue.

### Description of user facing changes
When reporting an issue to NVDA, users can use the simpler GitHub forms interface.
Information from inline comments and the [issue guide](https://github.com/nvaccess/nvda/blob/master/devDocs/githubIssueTemplateExplanationAndExamples.md) have been merged into this form, so that it is easier to understand the requirements.

Additionally, a new "custom issue" has been created, as we disable opening blank issues.
This should be used in the rare circumstance when the bug report or feature request template is not appropriate

### Description of development approach
N/A

### Testing strategy:
These changes have been pushed to a test repository

The new issue interface can be tested here: https://github.com/nvaccess/nvda-test/issues/new/choose

Example issues filled out using the form are as follows:
- https://github.com/nvaccess/nvda-test/issues/1
- https://github.com/nvaccess/nvda-test/issues/2
- https://github.com/nvaccess/nvda-test/issues/3

### Known issues with pull request:
The current information for the bug report may be overly verbose.
However, it is rare that an issue reporter reads our external guide for reporting issues, and as such, inline information is preferred.

### Change log entries:
N/A

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] Security precautions taken.

2023-08-22 04:02 UTC, seanbudd commented
Note: re-opened take of https://github.com/nvaccess/nvda/pull/15182, refer to comments and reviews there as well

2024-02-21 00:24 UTC, SaschaCowley reviewed
The current order of issue types seems off to me, so I've suggested renaming the files to [change the order of forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#changing-the-order-of-templates) to a more intuitive (to me) order.

2024-02-21 00:24 UTC, SaschaCowley commented on projectDocs/issues/githubIssueTemplateExplanationAndExamples.md
> +This page is meant to serve as an explanation for how to fill out our [GitHub issues](https://github.com/nvaccess/addon-datastore/issues/new/choose).
```suggestion
This page is meant to serve as an explanation for how to fill out our [GitHub issues](https://github.com/nvaccess/nvda/issues/new/choose).

```

2024-02-21 00:24 UTC, SaschaCowley commented on .github/ISSUE_TEMPLATE/bug_report.yml
Suggest renaming to `1-bug_report.yml`.

2024-02-21 00:24 UTC, SaschaCowley commented on .github/ISSUE_TEMPLATE/custom_issue.yml
Suggest renaming to `3-custom_issue.yml`.

2024-02-21 00:24 UTC, SaschaCowley commented on .github/ISSUE_TEMPLATE/feature_request.yml
Suggest renaming to `2-feature_request.yml`.

2024-04-24 08:00 UTC, Adriani90 commented
@seanbudd could we wait for our call next week before merging this? I have some proposals / ideas that we could discuss there.

2024-04-24 08:27 UTC, seanbudd commented
@Adriani90 - this PR is still blocked by work from GitHub

2024-05-13 19:14 UTC, Adriani90 commented
I've tested the forms and yeah, I think the most annoying part is that the labels of the fields are dissociated from the fields when the focus lands on them. I think this is still a showstopper. But also the edit fields seem to be smaller in height, at least that's what I read in some forums. This might be very annoying for people with some vision ability.

@seanbudd did you explore the possibility of providing accessible landing pages for the issue templates with the ability of creating githug issues from those pages?

Or maybe there is an alternative tool for customizing the github issue interface? I found this one but it seems inactive:
https://github.com/wei/new-issue

2024-09-05 09:37 UTC, bramd commented
It seems fields can be filled by passing GET parameters to the URL. It would be nice to add a "Report a bug" and "Request a feature" options in the NVDA menu, where we can prefill things like the Windows version, NVDA version etc. We could also provide a native GUI there for the now partly accessible fields, so people only have to activate the Create issue button on the webpage that opens.

2024-09-05 10:03 UTC, XLTechie commented
@bramd How would that work with respect to GitHub authentication?

If the user doesn't have an account, it fails until they create one, at which point they have to fill them again.

If they do, NVDA would have to go through a per-user oauth2 process, I believe, to authenticate the user with NVDA.

If you mean to just pass the information as query string parameters, we return to the first problem, but with the added wrinkle that it needs to open in a browser with an already active session cookie.
For the average user, that is unlikely to be the case.

Or am I missing something in your idea?

2025-01-16 17:42 UTC, LeonarddeR commented
Now it looks like the Github UI for filing issues has been revamped in a major way, should this be revisited/reinvestigated?

2025-01-16 22:30 UTC, SaschaCowley commented
Testing with the linked repo, the UX is still worse. Each issue field takes up 3 tab stops. The questions are not read when landing in the edit fields, though the descriptions are. That's as much as I tested, but there may well be other issues still.

2025-01-16 23:47 UTC, seanbudd commented
@LeonarddeR it seems that the multi-select control label has been fixed, but the other 2 labelling issues are still a problem https://github.com/orgs/community/discussions/61696

I think once the multi-line edit issue is fixed we can move over to the new issue forms

2025-06-04 02:06 UTC, seanbudd commented
Update: there is only 1 issue blocking this now. The label for multi-line edit fields is still incorrect as discussed here https://github.com/orgs/community/discussions/61696#discussioncomment-12999489

2025-08-07 04:51 UTC, seanbudd commented
The blocking issues appear to be resolved now, this just needs to be updated with the latest form formatting from master

2025-08-08 03:19 UTC, seanbudd commented
pre-commit.ci run

2025-08-08 09:44 UTC, LeonarddeR commented on .github/ISSUE_TEMPLATE/1-bug_report.yaml
> +        This can be copied from the about dialog, from the NVDA help menu.
How ought one copy this? Something like ctrl+c in the about dialog doesn't work. It might have worked in the past.

2025-08-08 09:44 UTC, LeonarddeR commented on .github/ISSUE_TEMPLATE/1-bug_report.yaml
> +  - type: input
Should this possibly be a checkbox instead? Or may be a drop down, since a check box can't be validated. In any case having an input for a yes/no question feels a bit cumbersome.

2025-08-08 09:44 UTC, LeonarddeR commented on .github/ISSUE_TEMPLATE/1-bug_report.yaml
> +  - type: input
Should this possibly be a check box?

2025-08-08 09:44 UTC, LeonarddeR commented on .github/ISSUE_TEMPLATE/1-bug_report.yaml
> +  - type: input
Same as above

2025-08-08 09:44 UTC, LeonarddeR commented on .github/ISSUE_TEMPLATE/1-bug_report.yaml
> +        Thus, it is recommended to run the fixing tool whenever focus problems, performance problems on websites or navigation problems in focus or browse mode on different interfaces are encountered
I think it makes sense to mention that running the tool also happens during installation. There's no need to rerun the tool just after an update or install. It is also an extra point to prove that running the tool won't impose any harm.
```suggestion
        Thus, it is recommended to run the fixing tool whenever focus problems, performance problems on websites or navigation problems in focus or browse mode on different interfaces are encountered.
        Note that running the tool is part of NVDA's installation process.
```

2025-08-08 09:44 UTC, LeonarddeR commented on .github/ISSUE_TEMPLATE/1-bug_report.yaml
> +        *Example:*
Have you considered putting this in `value` or `placeholder`?

2025-08-08 09:44 UTC, LeonarddeR commented on .github/ISSUE_TEMPLATE/5-bug_report.md
> +name: (Advanced) Bug report
I'd personally keep the html commented disclaimer that is at the top of the current templates.

2025-08-11 02:21 UTC, seanbudd commented on .github/ISSUE_TEMPLATE/1-bug_report.yaml
> +        *Example:*
I think this would be better in `placeholder`. Do you think we should move all examples there?

2025-08-11 02:49 UTC, seanbudd commented on .github/ISSUE_TEMPLATE/1-bug_report.yaml
> +        This can be copied from the about dialog, from the NVDA help menu.
https://github.com/nvaccess/nvda/pull/18667

2025-08-11 02:53 UTC, seanbudd commented on .github/ISSUE_TEMPLATE/5-bug_report.md
> +name: (Advanced) Bug report
I'm not sure how much value it provides in the advanced report.
It's initial main purpose was to provide a reference to the guide on how to fill out the template, but we've moved most of that information into the issue forms.
Unless you're filling out the issue form, or we restore the information to the guide, there's no real useful guide to filling out this form.
If people are filling out this template improperly, we will just close the issue and tell them to use the issue form to ensure it's filled out properly.

To me, eliminating the inline comment is much more useful for those who are advanced reporters.

2025-08-11 02:53 UTC, seanbudd commented on .github/ISSUE_TEMPLATE/1-bug_report.yaml
> +        Thus, it is recommended to run the fixing tool whenever focus problems, performance problems on websites or navigation problems in focus or browse mode on different interfaces are encountered
I agree, and have also opened https://github.com/nvaccess/nvda/issues/18666, something I've been meaning to do for a while

2025-08-11 02:54 UTC, seanbudd commented on .github/ISSUE_TEMPLATE/1-bug_report.yaml
> +        Thus, it is recommended to run the fixing tool whenever focus problems, performance problems on websites or navigation problems in focus or browse mode on different interfaces are encountered
```suggestion
        Thus, it is recommended to run the fixing tool whenever focus problems, performance problems on websites or navigation problems in focus or browse mode on different interfaces are encountered.
        Note that when installing NVDA, this tool is ran automatically.
```

2025-08-11 03:19 UTC, seanbudd commented on .github/ISSUE_TEMPLATE/1-bug_report.yaml
> +        *Example:*
I've moved these to placeholder

2025-08-11 03:20 UTC, seanbudd commented on .github/ISSUE_TEMPLATE/1-bug_report.yaml
> +  - type: input
I've made this a dropdown to encapsulate more answers than a checkbox

2025-08-11 03:20 UTC, seanbudd commented on .github/ISSUE_TEMPLATE/1-bug_report.yaml
> +  - type: input
I've made this a dropdown to encapsulate more answers than a checkbox

2025-08-11 03:20 UTC, seanbudd commented on .github/ISSUE_TEMPLATE/1-bug_report.yaml
> +  - type: input
I've made this a dropdown to encapsulate more answers than a checkbox

2025-08-11 05:38 UTC, LeonarddeR commented on .github/ISSUE_TEMPLATE/5-bug_report.md
> +name: (Advanced) Bug report
That's fine with me.

2025-08-11 05:40 UTC, LeonarddeR commented
I've seen the placeholder in action now. A problem with placeholders in NVDA is that they aren't navigable in browse mode, neither are they visible in Braille. May be that should be fixed first.

2025-08-11 06:04 UTC, seanbudd commented
I think the navigating in browse mode issue might be fine and not blocking, you just need to be able to read them. It seems these can be read in browse mode in braille. I'm not sure why they can't be read in focus mode in braille since [the w3c sample for placeholder works](https://www.w3schools.com/tags/att_input_placeholder.asp).

2025-08-11 06:54 UTC, LeonarddeR commented
Ah never mind, I expected the placeholder to pop up at the cursor, but it is added before it, so you'd have to scroll back. That's fine.

2025-08-13 05:31 UTC, Qchristensen approved these changes
This will hopefully be a positive change for users, great work.

2025-08-29 04:01 UTC, SaschaCowley requested changes

2025-08-29 04:01 UTC, SaschaCowley commented on .github/ISSUE_TEMPLATE/2-feature_request.yaml
> +        Please also note that the NVDA project has a [Citizen and Contributor Code of Conduct](https://github.com/nvaccess/nvda/blob/master/CODE_OF_CONDUCT.md).
```suggestion
        Issues may be closed if the required information is not present.
        
        Please also note that the NVDA project has a [Citizen and Contributor Code of Conduct](https://github.com/nvaccess/nvda/blob/master/CODE_OF_CONDUCT.md).
```

2025-08-29 04:01 UTC, SaschaCowley commented on projectDocs/issues/githubIssueTemplateExplanationAndExamples.md
> +The "Advanced" version of these templates listed when [choosing templates for new issues](https://github.com/nvaccess/nvda/issues/new/choose) ask for the same information, but in a more free-form man
```suggestion
The "Advanced" version of these templates listed when [choosing templates for new issues](https://github.com/nvaccess/nvda/issues/new/choose) asks for the same information, but in a more free-form manner, with less supporting information.
```

2025-08-29 04:01 UTC, SaschaCowley commented on projectDocs/issues/githubIssueTemplateExplanationAndExamples.md
> +* In multi-line edit boxes, consider swapping to the preview tab in order to read through the details and confirm the formatting reads as expected.
```suggestion
* In multi-line edit boxes, consider switching to the preview tab in order to read through the details and confirm the formatting reads as expected.
```

2025-08-29 04:01 UTC, SaschaCowley commented on projectDocs/issues/githubIssueTemplateExplanationAndExamples.md
> +While we welcome **images/screenshots** to help explain a problem, be aware that many of the developers of NVDA are blind and will greatly appreciate this image being described in text.
Does this really require a reason in 2025?
```suggestion
While we welcome **images/screenshots** to help explain a problem, all images must be described in text.
```

2025-08-29 04:01 UTC, SaschaCowley commented on .github/ISSUE_TEMPLATE/1-bug_report.yaml
> +        Please also note that the NVDA project has a [Citizen and Contributor Code of Conduct](https://github.com/nvaccess/nvda/blob/master/CODE_OF_CONDUCT.md).
```suggestion
        Issues may be closed if the required information is not present.
        
        Please also note that the NVDA project has a [Citizen and Contributor Code of Conduct](https://github.com/nvaccess/nvda/blob/master/CODE_OF_CONDUCT.md).
```

2025-08-29 04:01 UTC, SaschaCowley commented on .github/ISSUE_TEMPLATE/1-bug_report.yaml
> +        for some users and not others.
```suggestion
        This helps us to be able to reproduce the issue, or help us to investigate why this issue occurs for some users and not others.
```

2025-08-29 04:01 UTC, SaschaCowley commented on .github/ISSUE_TEMPLATE/1-bug_report.yaml
> +        "I have not restarted NVDA with add-ons disabled",
I think people who don't use add-ons might get confused.
```suggestion
        "I have restarted NVDA with add-ons disabled and the issue still occurs",
        "I have restarted NVDA with add-ons disabled and the issue no longer occurs",
        "I have not restarted NVDA with add-ons disabled",
        "I do not have any NVDA add-ons installed",
```

2025-08-29 04:01 UTC, SaschaCowley commented on .github/ISSUE_TEMPLATE/1-bug_report.yaml
> +        Note that when installing NVDA, this tool is ran automatically.
```suggestion
        Note that when installing NVDA, this tool is run automatically.
```

2025-08-29 04:01 UTC, SaschaCowley commented on .github/ISSUE_TEMPLATE/3-special_case_issue.yaml
> +        ## Attenion!
```suggestion
        ## Attention!
```

2025-08-29 04:01 UTC, SaschaCowley commented on .github/ISSUE_TEMPLATE/3-special_case_issue.yaml
> +        Please read [this guide](https://github.com/nvaccess/nvda/blob/master/projectDocs/issues/githubIssueTemplateExplanationAndExamples.md) for guidance on how to fill in this template, including
```suggestion
        Please read [our guide to creating issues on the NVDA project](https://github.com/nvaccess/nvda/blob/master/projectDocs/issues/githubIssueTemplateExplanationAndExamples.md) for guidance on how to fill in this template, including how to provide the required files.
```

2025-08-29 04:01 UTC, SaschaCowley commented on .github/ISSUE_TEMPLATE/3-special_case_issue.yaml
> +        - [Feature Request Template](https://github.com/nvaccess/nvda/issues/new?template=2-feature_request.yaml)
```suggestion
        Before proceeding, please review the existing templates to ensure that those do not better suit your needs:
        
        * [Bug Report Template](https://github.com/nvaccess/nvda/issues/new?template=1-bug_report.yaml)
        * [Feature Request Template](https://github.com/nvaccess/nvda/issues/new?template=2-feature_request.yaml)
```

2025-08-29 04:01 UTC, SaschaCowley commented on .github/ISSUE_TEMPLATE/3-special_case_issue.yaml
> +        >1. Press Enter
```suggestion
      placeholder: |
        1. Open Chrome
        2. Browse to www.google.com
        3. Type "Hello"
        4. Press Enter
```

2025-08-29 04:01 UTC, SaschaCowley commented on .github/ISSUE_TEMPLATE/3-special_case_issue.yaml
> +        for some users and not others.
```suggestion
        This helps us to be able to reproduce the issue, or find out why this issue occurs for some users and not others.
```

2025-08-29 04:01 UTC, SaschaCowley commented on .github/ISSUE_TEMPLATE/3-special_case_issue.yaml
> +        If this or the following sections are not applicable, write "N/A." or leave blank.
```suggestion
        
        If this or the following sections are not applicable, write "N/A." or leave blank.
```

2025-08-29 04:01 UTC, SaschaCowley commented on .github/ISSUE_TEMPLATE/3-special_case_issue.yaml
> +        > * NVDA 2018.2 - has error sound
```suggestion
      placeholder: |
        * NVDA 2018.1 - no error sound
        * NVDA 2018.2 - has error sound
```

2025-08-29 04:01 UTC, SaschaCowley commented on .github/ISSUE_TEMPLATE/3-special_case_issue.yaml
> +        You can copy this from the "System Information" application:
```suggestion
        You can copy this from the "System Information" application:
        
```

2025-08-29 04:01 UTC, SaschaCowley commented on .github/ISSUE_TEMPLATE/3-special_case_issue.yaml
> +        > Windows 10 Version 1607 Build 14393.1066
```suggestion
      placeholder: "Windows 10 Version 1607 Build 14393.1066"
```

2025-08-29 04:01 UTC, SaschaCowley commented on .github/ISSUE_TEMPLATE/3-special_case_issue.yaml
> +        > Chrome version: 67.0.3396.87
```suggestion
      placeholder: Chrome version: 67.0.3396.87
```

2025-08-29 04:01 UTC, SaschaCowley commented on .github/ISSUE_TEMPLATE/3-special_case_issue.yaml
> +        > Running Windows 10 in a VM
```suggestion
      placeholder:  Running Windows 10 in a VM
```

2025-08-29 04:01 UTC, SaschaCowley commented on .github/ISSUE_TEMPLATE/4-developer_facing_changes.yaml
> +name: Developer facing changes
All of the IDs in this form seem to be kebab-case, whereas the other templates use camelCase. Can we pick a standard and stick to it?

2025-08-29 04:03 UTC, SaschaCowley requested changes
Could we rename the form versions to have a leading 0 and the "advanced" versions to have a leading 1, so that the final digit is the same? Would make matching up templates easier, as well as giving us room if we want to add more templates later.

2025-08-29 06:20 UTC, CyrilleB79 commented on projectDocs/issues/githubIssueTemplateExplanationAndExamples.md
> +While we welcome **images/screenshots** to help explain a problem, be aware that many of the developers of NVDA are blind and will greatly appreciate this image being described in text.
Still recently, we have seen new reporters opening issues with screenshots and only few or no description of the images provided.
IMO, this precision is still needed.

2025-08-29 07:00 UTC, SaschaCowley commented on projectDocs/issues/githubIssueTemplateExplanationAndExamples.md
> +While we welcome **images/screenshots** to help explain a problem, be aware that many of the developers of NVDA are blind and will greatly appreciate this image being described in text.
I was more questioning if we need to justify the requirement for alt text. But point taken.

2025-09-19 00:16 UTC, SaschaCowley approved these changes
Thanks, @seanbudd

2025-09-19 00:18 UTC, merged