Create a friendlier system of project documentation
nvaccess/nvda pull request #15337
Opened 2023-08-28 03:34 UTC by seanbudd

### Known issues with pull request:
This PR is incomplete, several documents are yet to be written/completed.
The unfinished work is in untracked changes, so the current submitted files are ready for a preliminary review on structure.

### Summary of the issue:

There are a few issues with the current project documentation:
* The README is quite long, and focused largely on configuring the developer environment.
Instead, it should be a homepage for the various aspects of the project. Detailed information should be split into their own documents.
* `contributing.md` is quite long and should be split similarly into the ways one can contribute to NVDA.
* There is a lot of missing information in terms of how to get started with various ways of contributing.

### Description of user facing changes

`README.md` is now split into
- Community information
  - support / getting help
  - getting add-ons
  - Issue reporting
  - General community information

`Contributing.md` is now split into
  - testing
  - translating
  - Issue triage
  - Development
    - Design
  - add-on dev
    - add-on distribution

Guides have been updated or added when missing.

### Change log entries:
For Developers
The NVDA project documentation has been updated...

2023-08-28 06:03 UTC, seanbudd commented
this is now ready for review

2023-08-28 07:09 UTC, michaelDCurran requested changes

2023-08-28 07:09 UTC, michaelDCurran commented on projectDocs/testing/contributing.md
> +Testing alpha / beta / and release candidates help to ensure the quality of the NVDA.
```suggestion
Testing alpha / beta / and release candidates help to ensure the quality of the NVDA project.
```

2023-08-28 07:09 UTC, michaelDCurran commented on projectDocs/testing/contributing.md
> +You can the latest alpha snapshots [here](https://www.nvaccess.org/files/nvda/snapshots/).
```suggestion
You can find the latest alpha snapshots [here](https://www.nvaccess.org/files/nvda/snapshots/).
```

2023-08-28 23:14 UTC, dpy013 commented
Recommended Use[gpl-2.0.md](https://www.gnu.org/licenses/old-licenses/gpl-2.0.md)
update
copying.txt

2023-08-28 23:16 UTC, seanbudd commented
Could you please explain a bit more @dpy013 ? Note that this isn't a PR to update our licence. If you'd like to discuss our licence, I suggest opening a separate issue or discussion

2023-08-30 03:40 UTC, Qchristensen approved these changes
Great job on this, thank you.

2023-08-30 04:38 UTC, seanbudd commented on projectDocs/community/readme.md
> +* NV Access has several ways you can contact us and keep up to date on the latest of NVDA.
Fix typo
```suggestion
* NV Access has several ways you can contact us and keep up to date on the latest on NVDA.
```

2023-08-30 05:06 UTC, seanbudd commented
Community feedback would be great here!
This is a big change, so feedback on structure as well as content would be welcome.
We'd like to make the content as accessible, logically compiled and easy to navigate as possible.

It might be easier to review the documents directly:
- [the new readme](https://github.com/nvaccess/nvda/blob/splitReadme/readme.md)
- [the new contributing file](https://github.com/nvaccess/nvda/blob/splitReadme/.github/CONTRIBUTING.md)
- [the new project docs folder](https://github.com/nvaccess/nvda/tree/splitReadme/projectDocs)

We've also updated the [wiki home page](https://github.com/nvaccess/nvda/wiki) to include a clearer contents index and migrated content from the [other wiki repository `nvda-community`](https://github.com/nvaccess/nvda-community/wiki)

2023-08-31 05:58 UTC, nvdaes commented
In [Community readme](https://github.com/nvaccess/nvda/blob/splitReadme/projectDocs/community/readme.md), I wonder if the community add-ons website should be mentioned in addition to  the store:

- Personally, I'm not sure about if it's well maintained.
- - Imo, downloading add-ons from the store itself is more secure than installing them from external sources when possible, since checsum is used to ensure that releases are inmutable and that, when an add-on installed, the manifest contains NVDA API versions.
Then, if the community website is mentioned, I suggest to add a brief note about differences between the store and the website, for example: add-on store (recommended) or something.

2023-08-31 06:22 UTC, seanbudd commented
The community add-ons website is still being supported by NV Access for now, and is the source of some add-ons that aren't available from the add-on store.

I agree that it's probably worth a note that this website is towards end of life and the add-on store is preferred

2023-09-01 05:49 UTC, nvdaes requested changes

2023-09-01 05:49 UTC, nvdaes commented on projectDocs/community/readme.md
> +* [Other sources including groups and profiles on social media channels, language-specific websites and mailing lists etc.](https://github.com/nvaccess/nvda/wiki/Connect)
```suggestion
#### Managed by the community, not supported by NV Access ####
* [Other sources including groups and profiles on social media channels, language-specific websites and mailing lists etc.](https://github.com/nvaccess/nvda/wiki/Connect)

```

2023-09-01 05:51 UTC, nvdaes commented
Imo, maybe useful to inform what channels are supported by NV Access. Sometimes we, community members, may say that our website, mailing list or whatever resource is official, without clarifying the meaning of the "official" word. So I sugest to inform people what channels are supported by NV Access.

2023-09-03 23:09 UTC, seanbudd commented
@nvdaes -I've added some subheaders to indicate this

2023-09-03 23:47 UTC, merged