Fix some issues where an NVDAObject is used where a Window is expected
nvaccess/nvda pull request #15400
Opened 2023-09-08 04:34 UTC by seanbudd

### Link to issue number:
Fixes #15395 

### Summary of the issue:
There are many instances in NVDA where we implicitly or explicitly (with typing) expect an `NVDAObject` but code uses properties only available for a `NVDAObjects.window.Window`.
This is because most objects are `Window`s and usually these implicit expectations are safe.
This PR attempts to catch some known instances where these expectations are not safe.

### Description of user facing changes
Fix error when switching to the secure desktop

### Description of development approach
Improve typing and catch some likely cases where a `Window` should not be expected

### Testing strategy:
Test using the secure desktop, check log for errors

### Known issues with pull request:
There are other instances where this is the case.
Future work such as improved typing will help weed out these problems.

### Change log entries:
None, unreleased regression

### Code Review Checklist:

- [ ] Pull Request description:
  - description is up to date
  - change log entries
- [ ] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [ ] API is compatible with existing add-ons.
- [ ] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [ ] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [ ] Security precautions taken.

2023-09-08 06:10 UTC, leonardder requested changes

2023-09-08 06:10 UTC, leonardder commented on source/keyboardHandler.py
> +				not isinstance(focus, Window)
I think this one is wrong.

```suggestion
				isinstance(focus, Window)
```

2023-09-08 06:10 UTC, leonardder commented on source/keyboardHandler.py
> +				or focus.windowClassName.startswith('Windows.UI.Core')
```suggestion
				and focus.windowClassName.startswith('Windows.UI.Core')
```

2023-09-20 23:20 UTC, michaelDCurran approved these changes

2023-09-21 00:54 UTC, merged