Re-add audio device combo box to synth select dialog
nvaccess/nvda pull request #15486
Opened 2023-09-20 22:46 UTC by codeofdusk

### Link to issue number:
Partially reverts #15472.

### Summary of the issue:
The "output device" option has been removed from the <kbd>NVDA</kbd>+<kbd>Control</kbd>+<kbd>s</kbd> dialog. This breaks muscle memory for long-time NVDA users and makes it very hard to blindly (without audible speech or connected Braille) change sound devices in the event of unexpected device switching.

### Description of how this pull request fixes the issue:
Selectively reverts the change in #15472 that removes the option from the synth selection dialog.

### Testing strategy:
Verified that the "output device" option in both dialogs works as expected

### Known issues with pull request:
* There is a small amount of code duplication.
* The same dialog appears when clicking the "change..." button in voice settings and when invoking the gesture, but it doesn't make as much sense for the "audio device" option to appear in the first scenario since it's just as easy to find under audio settings. In a follow-up, consider making the option appear only when accessing the synth change dialog via gesture.

### Change log entry:
None needed, unreleased regression

### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

2023-09-20 23:42 UTC, codeofdusk commented
Some lint errors (especially re string formatting) appear to be false-positives, and this was compliant as originally present.

2023-09-21 00:29 UTC, cary-rowen commented
> This breaks muscle memory for long-time NVDA users and makes it very hard to blindly (without audible speech or connected Braille) change sound devices in the event of unexpected device switching.

Regarding the second concern you mentioned, I think implementing #8801 may be a long-term solution.

As for what you mentioned about destroying muscle memory, I think it is not the most important, because it will not lead to any terrible consequences.

2023-09-21 02:06 UTC, codeofdusk commented
> Regarding the second concern you mentioned, I think implementing #8801 may be a long-term solution.

Yes, though likely not in 2023.3. Worth considering for 2024.1!

2023-09-21 02:09 UTC, cary-rowen commented
#15472 was also a change introduced during the beta cycle. What does NV Access think about this?
cc @seanbudd

2023-09-21 03:28 UTC, seanbudd requested changes

2023-09-21 03:28 UTC, seanbudd commented on source/gui/settingsDialogs.py
> -			_synthWarningDialog(newSynth.name)
please use the synth warning dialog

2023-09-21 03:28 UTC, seanbudd commented on source/gui/settingsDialogs.py
> +		config.conf["speech"]["outputDevice"]=self.deviceList.GetStringSelection()
please lint your changes

2023-09-21 03:28 UTC, seanbudd commented on source/gui/settingsDialogs.py
> +		self.deviceList.SetSelection(selection)
I think a single release cycle is enough time to transfer knowledge of the location of this.
Could you also please create a helper function to remove code duplication?
Please use the code from the audio panel as it has been linted/improved.
can you also wrap this in the following if statement?


```py
if version_year < 2024:
	_AddAudioOutput(self, sHelper)
```

2023-09-21 03:30 UTC, seanbudd commented
>>Regarding the second concern you mentioned, I think implementing https://github.com/nvaccess/nvda/issues/8801 may be a long-term solution.

>Yes, though likely not in 2023.3. Worth considering for 2024.1!

agreed, the beta period is for completing work and fixing regressions not new features.
#15472 is the completion of WASAPI work that now appears stable and has had alpha and limited beta testing.

2023-09-21 05:00 UTC, seanbudd commented on user_docs/en/changes.t2t
> +    -
Can you move this to the line "The settings to change audio output device and toggle audio ducking have been moved to the new Audio settings panel from the Select Synthesizer dialog. (#8711)" in changes?

Perhaps just adding the clarification "They will be removed from the "select synthesizer" dialog in 2024.1" as a new line in the same bullet point.

2023-09-21 05:03 UTC, codeofdusk commented on source/gui/settingsDialogs.py
> +		if version_year < 2024 and NVDAState._allowDeprecatedAPI():
It was useful for testing but I can remove it.

2023-09-21 05:04 UTC, Adriani90 commented
I think if the audio settings category will have a shortcut as well or am I wrong?
To be honnest, if the user guide and the change log document properly that the audio settings category contains this setting, then there is no reason why long term users should not get used to it.
Long term nvda users will certainly be able to adapt this change in the day to day use as long as the documentation is clear about this.change.
In my view this setting suits better in the audio settings category but maybe I don‘t understand completely the issue here.

2023-09-21 05:57 UTC, leonardder commented
I'm not sure about this proposal. I really like a separate settings category, as long as it has a dedicated shortcut to open. In that case, audio output device would be the first item in the dialog and it would instantly gain focus, which is an improvement over the current sequence. That definitely needs to be added regardless of what happens with this pr.
Furthermore, since I introduced RD Access, I always found it a bit weird that the audio device combobox was situated in the synthesizer selection dialog since a synthesizer doesn't necessarily need an audio device locally.

However, I'm also slightly concerned that removing the audio device selection from the synthesizer dialog causes unexpected behavioral changes in case where NVDA is somehow stuck to a nonexistent sound device. In the past, changing synth would also reinitialize audio in this case since the selected device would automatically fall back to sound mapper, but now, this no longer happens.

2023-09-21 07:28 UTC, CyrilleB79 commented
Agree with @leonardder and @Adriani90: A shortcut to open audio settings could be added for the audio panel and the audio device would be the first item, directly focused. @codeofdusk, could you explain if and why this solution is not satisfying?

IMO the fact that people are used to NVDA+control+S then tab to blindly change their audio device is not a good reason to revert. Things may be changed provided that they are well documented in User Guide and in the Change log; an article in In-process could also be worth it if needed (Cc @Qchristensen)

> However, I'm also slightly concerned that removing the audio device selection from the synthesizer dialog causes unexpected behavioral changes in case where NVDA is somehow stuck to a nonexistent sound device. In the past, changing synth would also reinitialize audio in this case since the selected device would automatically fall back to sound mapper, but now, this no longer happens.

@leonardder could you please be more specific: use case description in detail and step to recover from non-existing sound device situation?

2023-09-21 08:26 UTC, leonardder commented
> @leonardder could you please be more specific: use case description in detail and step to recover from non-existing sound device situation?

I must admit that this is slightly hypothetical, and I need to test it to gain some proof, but up until now, synthesizer and audio device selection have been that intertwined that there is likely a interdependence that we might be missing. It is not without reason that the audio device is part of the speech category in the config spec.
I'm not saying we shouldn't move the audio device to a dedicated audio setting. However given we're already at beta 2, introducing a change like this in beta 3 concerns me. I'd rather see this ripen in Alpha for a while.

2023-09-21 20:17 UTC, codeofdusk commented
> @codeofdusk, could you explain if and why this solution is not satisfying?

The solution is satisfying, but given the length of time for which we've had audio devices in <kbd>NVDA</kbd>+<kbd>Control</kbd>+<kbd>s</kbd> (well over 10 years) announcing a change like this (especially given the possibility of unforseen interdependence pointed out by @leonardder) with very little warning presents a poor user experience. Target the change for 2024.1 and use the intervening time to warn users/think of a good UX for this.

2023-09-21 22:26 UTC, Adriani90 commented
> Target the change for 2024.1 and use the intervening time to warn users/think of a good UX for this.

This sounds like a reasonable request.

2023-09-22 04:46 UTC, seanbudd commented
>I must admit that this is slightly hypothetical, and I need to test it to gain some proof, but up until now, synthesizer and audio device selection have been that intertwined that there is likely a interdependence that we might be missing. It is not without reason that the audio device is part of the speech category in the config spec.

@leonardder, please check the code changes in #15472.
We perform the same reinitialization of the synthesizer and tones when changing the audio output device from the audio panel. As long as the `onOk/onSave` handling matches correctly there shouldn't be an issue.

2023-09-22 05:13 UTC, seanbudd commented on source/gui/settingsDialogs.py
> +def _addAudioCombos(panel, sHelper):
any thoughts on making this a static method? it will greatly simplify the diff and also simplify reverting in 2024.1

2023-09-22 05:40 UTC, leonardder commented
I think I'm convinced now. I just tried the following:

1. Set audio device to a specific soundcard
2. Disconnect that soundcard.
3. Select another synth.

The new synth happily ignores the configured nonexistent device and chooses the sound mapper. This is great.

2023-09-22 06:40 UTC, seanbudd approved these changes, later dismissed

2023-09-22 06:40 UTC, seanbudd commented on source/gui/settingsDialogs.py
> +		"#15486: temporarily re-add audio options to synth dialog for 2023.3."
This doesn't really need to be here now

```suggestion
```

2023-09-24 23:55 UTC, seanbudd commented
@codeofdusk - there is no need to bump CI. If the failures are unrelated they can be ignored

2023-09-25 05:15 UTC, seanbudd approved these changes

2023-09-25 05:16 UTC, merged