Update and move release process
nvaccess/nvda pull request #15511
Opened 2023-09-25 06:08 UTC by seanbudd

### Summary of the issue:
NV Access is intending to move most of the wiki into the repository, so changes are tracked better and easier to propose.
The release process wiki page is a prime candidate for migration.
The release process wiki is out of date, it also contains some information that is better suited to or duplicated in other documents.

### Description of user facing changes
[The release process wiki page](https://github.com/nvaccess/nvda/wiki/ReleaseProcess) is migrated to the repository.

The process is updated to include more information on the timing of the stages.
Information for testers, and developers are moved to the appropriate contributing docs.

2023-09-25 07:10 UTC, michaelDCurran requested changes

2023-09-25 07:10 UTC, michaelDCurran commented on projectDocs/dev/contributing.md
> +	- A lead developer may specifically requested the pull request be made against `beta` or `rc` in the case of addressing bugs introduced in the current release cycle.
```suggestion
	- A lead developer may specifically request the pull request be made against `beta` or `rc` in the case of addressing bugs introduced in the current release cycle.
```

2023-09-25 07:10 UTC, michaelDCurran commented on projectDocs/community/releaseProcess.md
> +   - Once a week passes with a stable beta, the 2 week [translation freeze begins](#translatable-string-freeze)
```suggestion
   - Once a beta has been stable for one week (no issues reported), the 2 week [translation freeze begins](#translatable-string-freeze)
```

2023-09-25 07:10 UTC, michaelDCurran commented on projectDocs/community/releaseProcess.md
> +   - Once a week passes with a stable RC, the final release is created
```suggestion
   - when an RC has been stable for one week (no issues reported), the final release is created
```

2023-09-25 07:10 UTC, michaelDCurran commented on projectDocs/community/releaseProcess.md
> +* As appropriate new tagged beta releases will be published.
```suggestion
* As appropriate new tagged beta releases will be published once a week.
```

2023-09-26 02:44 UTC, michaelDCurran approved these changes

2023-09-26 03:18 UTC, Qchristensen approved these changes
Reads well, good work.

2023-09-26 04:07 UTC, merged