Update UIAutomationClient comInterfaces
nvaccess/nvda pull request #15522
Opened 2023-09-26 05:23 UTC by seanbudd

### Summary of the issue:
We plan to update all dependencies where possible in 2024.1.
The comInterfaces for UIAutomationClient are manually maintained compared to other comInterfaces.
This is due to the regression risk of this being automatically updated on appveyor.
In preparation for python 3.11, and potentially as a result of #15513, an updated to UIAutomationClient is ideal.
Performing this early allows for maximal alpha testing.

### Description of user facing changes
None, ideally just performance enhancements

### Description of development approach
Follow steps in `source/comInterfaces/readme.md`

### Testing strategy:
Significant lpha testing is required

### Known issues with pull request:
It might be worth adding regenerating `UIAutomationClient` to the release process like updating eSpeak.

### Code Review Checklist:

- [ ] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [ ] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [ ] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [ ] API is compatible with existing add-ons.
- [ ] Security precautions taken.

2023-09-27 23:41 UTC, seanbudd commented
Instead, we are going to let AppVeyor build these files rather than manually updating, as regression risk is much lower now

2023-09-28 22:11 UTC, lukaszgo1 requested changes
I disagree with the approach here. The main reason not to generate UIA com interface on AppVeyor is not the fact that it can be updated out of our control, but the fact that it is generated from the version of Windows used in AppVeyor image, which is severely outdated. They are still running Windows Server 2019, so their UIA interface is almost 5 years old at this point. NVDA is using much newer interface for a long time, so this would be functionally a downgrade. This also creates a huge difference between automatic builds, and developer's environment, forcing contributors to either  build on a vm, or testing with a try builds created on AppVeyor. While I certainly see an appeal in not having to update these interfaces by hand, the only way which seems reasonable for me would be to generate them with a known version of UIA Interface from Windows SDK, which guarantees that interface is recent enough, and also that builds can be reproducible.

2023-10-02 01:08 UTC, dpy013 commented
> I disagree with the approach here. The main reason not to generate UIA com interface on AppVeyor is not the fact that it can be updated out of our control, but the fact that it is generated from the version of Windows used in AppVeyor image, which is severely outdated. They are still running Windows Server 2019, so their UIA interface is almost 5 years old at this point. NVDA is using much newer interface for a long time, so this would be functionally a downgrade. This also creates a huge difference between automatic builds, and developer's environment, forcing contributors to either build on a vm, or testing with a try builds created on AppVeyor. While I certainly see an appeal in not having to update these interfaces by hand, the only way which seems reasonable for me would be to generate them with a known version of UIA Interface from Windows SDK, which guarantees that interface is recent enough, and also that builds can be reproducible.

Maybe we can use github actions to build the UIA?
The windows version of github actions is new enough

2023-10-09 04:45 UTC, michaelDCurran approved these changes

2023-10-09 04:51 UTC, merged