Update detours, ia2, sonic, w3c, wil
nvaccess/nvda pull request #15695
Opened 2023-10-27 04:58 UTC by seanbudd

### Link to issue number:
None

### Summary of the issue:
Update various dependences to their latest commit on master

### Description of user facing changes

### Description of development approach
Updated detours, ia2, sonic, w3c, wil to master.
Created a build to test.

### Testing strategy:
General smoke testing

### Known issues with pull request:
None

### Code Review Checklist:

- [ ] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [ ] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [ ] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [ ] API is compatible with existing add-ons.
- [ ] Security precautions taken.

2023-10-27 05:59 UTC, leonardder commented on projectDocs/dev/createDevEnvironment.md
> +* brlapi Python bindings, version 0.8.5 or later, distributed with [BRLTTY for Windows](https://brltty.app/download.html), version 6.1
```suggestion
* brlapi Python bindings, version 0.8.5 or later, distributed with [BRLTTY for Windows](https://brltty.app/download.html), version 6.6
```

2023-10-27 06:00 UTC, seanbudd commented on projectDocs/dev/createDevEnvironment.md
> +* brlapi Python bindings, version 0.8.5 or later, distributed with [BRLTTY for Windows](https://brltty.app/download.html), version 6.1
Thanks!

2023-10-27 11:11 UTC, lukaszgo1 commented
Would it be possible to describe testing you have done some more? In particular:
- Have you verified that display model works by following [our testing steps](https://github.com/nvaccess/nvda/blob/master/projectDocs/design/displayModel.md#testing-gdi-applications)
- Are our Chrome system tests compatible with the new version of ARIA practices? As an aside is there any plan for reenabling these on AppVeyor?

2023-10-30 05:13 UTC, michaelDCurran approved these changes, later dismissed

2023-10-31 05:10 UTC, michaelDCurran requested changes

2023-10-31 05:10 UTC, michaelDCurran commented on include/readme.md
> +Test using [the steps here](../projectDocs/design/displayModel.md).
This testing is necessary for Detours, rather than IA2. DisplayModel code relies on Detours to hook GDI text out calls.

2023-10-31 05:10 UTC, michaelDCurran commented on include/readme.md
> +The fork specifically adds support for CallExtension / IsExtensionSupported to the high-level API, see PR microsoft/microsoft-ui-uiautomation#84 and #95.
pr 84 was already merged to master. But:
```suggestion
The fork specifically adds support for connection bound objects to the high-level API, see PR microsoft/microsoft-ui-uiautomation#95.
```

2023-10-31 05:58 UTC, michaelDCurran approved these changes

2023-10-31 06:20 UTC, merged