replace mktemp usages with mkstemp
nvaccess/nvda pull request #16260
Opened 2024-03-04 23:39 UTC by seanbudd

### Link to issue number:
Fixes https://github.com/nvaccess/nvda/security/code-scanning/2
Fixes https://github.com/nvaccess/nvda/security/code-scanning/3
Fixes https://github.com/nvaccess/nvda/security/code-scanning/4
Fixes https://github.com/nvaccess/nvda/security/code-scanning/5

### Summary of the issue:
From CodeQL: "Functions that create temporary file names (such as `tempfile.mktemp` and `os.tempnam`) are fundamentally insecure, as they do not ensure exclusive access to a file with the temporary name they return. The file name returned by these functions is guaranteed to be unique on creation but the file must be opened in a separate operation. There is no guarantee that the creation and open operations will happen atomically. This provides an opportunity for an attacker to interfere with the file before it is opened.

Note that mktemp has been deprecated since Python 2.3."

### Description of user facing changes
None

### Description of development approach
Replace usages of `tempfile.mktemp` with the secure alternative `tempfile.mkstemp`.

- https://docs.python.org/3/library/tempfile.html#tempfile.mktemp
- https://docs.python.org/3/library/tempfile.html#tempfile.mkstemp

### Testing strategy:
- [ ] Manually tested the installer
- [ ] Manually tested removing add-ons

### Known issues with pull request:
None

### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [ ] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

2024-03-05 19:31 UTC, lukaszgo1 requested changes
This currently does not work. In particular when uninstalling add-ons the following errors are shown:
```
ERROR - addonHandler._getAvailableAddonsFromPath (20:26:00.944) - MainThread (8572):
Failed to remove noBeepsSpeechMode add-on
Traceback (most recent call last):
  File "addonHandler\__init__.py", line 578, in completeRemove
    os.rename(self.path,tempPath)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'D:\\my_repos\\nvda\\source\\userConfig\\addons\\noBeepsSpeechMode' -> 'D:\\my_repos\\nvda\\source\\userConfig\\addons\\tmpiy7bnxzr.delete'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "addonHandler\__init__.py", line 358, in _getAvailableAddonsFromPath
    a.completeRemove()
  File "addonHandler\__init__.py", line 580, in completeRemove
    raise RuntimeError("Cannot rename add-on path for deletion")
RuntimeError: Cannot rename add-on path for deletion

```

Since we need name of the file which does not exist and don't use the created file as such I'm not sure `mkstemp` will work well for our purposes, unless we create the file, delete it and reuse its name.

2024-03-05 21:19 UTC, seanbudd commented
@lukaszgo1 - please note this is a draft

2024-03-06 03:10 UTC, seanbudd commented
@lukaszgo1 - the PR is now ready and the description is up to date

2024-03-06 19:06 UTC, lukaszgo1 approved these changes

2024-03-07 21:08 UTC, michaelDCurran reviewed
The usage of `tempfile.mkstemp` seems a little awkward as we always need to manually close the file descriptor. Have you considered using 
```
with tempfile.NamedTempraryFile(dir=blah, delete=False) as tmp:
	tempPath = tmp.name
```

To be honest I'm not too sure which one is a better pattern, but just an alternative to consider. I think it important that we settle on a pattern that makes good sense if it is going to be used everywhere. Either that, or at least abstract thia pattern of renaming to a temprary file into its own function for all of NVDA.

2024-03-11 21:08 UTC, michaelDCurran approved these changes

2024-03-11 22:50 UTC, merged