Added security and privacy note for add-ons to the user guide
nvaccess/nvda pull request #16311
Opened 2024-03-15 19:32 UTC by Adriani90

### Link to issue number:
n/a
### Summary of the issue:
In many discussions, especially in corporate environments but also when users of other screen readers change to NVDA, there is no common perception of security and privacy status when using add-ons throughout the community of NVDA users.
### Description of user facing changes
Users will get a common sense for the perception of the status of security and privacy when using add-ons.
### Description of development approach
Discussion #16241 provides more details and current developments.

### Testing strategy:
Tested that the formating of the text appears correctly in the user guide, including the link to the community review section.

### Known issues with pull request:
None

### Code Review Checklist:

- [x] Documentation:
  - User Documentation
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [ ] API is compatible with existing add-ons.
- [x] Security precautions taken.

2024-03-16 13:03 UTC, lukaszgo1 requested changes
Not related to the content of the PR, but please don't submit PR's from the master branch of your fork. This will inevitably introduce difficulties for you later on.

2024-03-16 13:03 UTC, lukaszgo1 commented on user_docs/en/userGuide.t2t
> +The review process of add-ons is still in development, so most of add-ons are not officially reviewed yet.
'officially' here implies 'by NV Access', which was never the case and probably never would.

2024-03-16 13:03 UTC, lukaszgo1 commented on user_docs/en/userGuide.t2t
> +- Web browser vulnerabilities
This risk seems irrelevant to NVDA add-ons.

2024-03-17 09:31 UTC, Adriani90 commented
Closing this one in favor of #16316.

2024-03-17 09:31 UTC, closed without merging