Added description of core dev
nvaccess/nvda pull request #16647
Opened 2024-06-04 04:33 UTC by gerald-hartig

### Link to issue number:
n/a

### Summary of the issue:
Update to product vision to clarify which features NVDA supports in core.

### Description of user facing changes
Addition of text to Product Vision -> Product description

### Description of development approach
n/a

### Testing strategy:
n/a

### Known issues with pull request:
None

### Code Review Checklist:

- [ ] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [ ] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [ ] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [ ] API is compatible with existing add-ons.
- [ ] Security precautions taken.

2024-06-04 04:59 UTC, michaelDCurran requested changes
I think I would prefer this to be a subsection like all others. Having this new text at the top feels a bit like it is floating in an island with no context.
Perhaps place it as a final section: 16: Relevance? or maybe Utility?

2024-06-19 01:39 UTC, SaschaCowley requested changes

2024-06-19 01:39 UTC, SaschaCowley commented on projectDocs/product_vision.md
> +        * Is a necessity for a small subset of our users, without which NVDA would not be functional for them,
Rewrite this to agree in number ("NVDA provides solutions [...] that [...] Is a necessity" doesn't make sense)
```suggestion
        * Are a necessity for a small subset of our users, without which NVDA would not be functional for them,
```

2024-06-19 01:39 UTC, SaschaCowley commented on projectDocs/product_vision.md
> +        *  Providing this support through an add-on is not practical due to the essential nature of the feature or its widespread use (see "Extendable" above).
Not sure this is necessary.

2024-06-19 05:57 UTC, gerald-hartig commented on projectDocs/product_vision.md
> +        * Is a necessity for a small subset of our users, without which NVDA would not be functional for them.
```suggestion
        * Are a necessity for a small subset of our users, without which NVDA would not be functional for them.
```

2024-06-19 06:17 UTC, seanbudd approved these changes

2024-06-19 06:17 UTC, seanbudd commented on projectDocs/product_vision.md
> +        * Are a necessity for a small subset of our users, without which NVDA would not be functional for them.
To match above indentation and styling

```suggestion
    * provide utility to a significant proportion of users in day-to-day use.
    * are a necessity for a small subset of our users, without which NVDA would not be functional for them.
```

2024-07-03 05:43 UTC, seanbudd approved these changes

2024-07-03 06:41 UTC, michaelDCurran approved these changes

2024-07-03 06:50 UTC, SaschaCowley approved these changes

2024-07-03 23:15 UTC, merged