add validation of update mirror urls
nvaccess/nvda pull request #17310
Opened 2024-10-20 11:21 UTC by christopherpross

### Link to issue number:
#17205 

### Summary of the issue:
Users could configure an invalid update mirror URL, which would only be discovered when attempting to check for updates. This PR implements a validation mechanism that ensures the specified update mirror is valid before allowing it to be set in the settings.

### Description of user facing changes
A new validation process has been added when setting an update mirror URL in NVDA's settings. Users will now receive feedback if the URL they provide is not a valid update mirror. The "Test" button in the settings will now ensure that the mirror responds with the expected format, preventing invalid configurations.

### Description of development approach
- Refactored parsing logic for update responses into a new function: `parseUpdateCheckResponse`.
- Defined the minimum schema for an update mirror response based on the following required keys:
  - `version`
  - `launcherUrl`
  - `apiVersion`
- Implemented a new function `_isResponseUpdateMirrorValid` in `settingsDialogs.py`, which calls `parseUpdateCheckResponse` to validate the mirror's response.
- Added `_isResponseUpdateMirrorValid` as the `responseValidator` in the `_SetURLDialog` for update mirrors.

### Testing strategy:
- Ran NVDA from source.
- Ensured the update mirror URL was set to "no Mirror".
- Test 1: Set the URL to "https://www.nvaccess.org/nvdaUpdateCheck".
  - Pressed the "Test" button and verified that the URL was marked as valid.
- Test 2: Set the URL to "https://google.de".
  - Pressed the "Test" button and verified that the URL was marked as invalid.
- Test 3: Set the URL to "https://github.com".
  - Pressed the "Test" button and verified that the URL was marked as invalid.
- Test 4: Set the URL to the Chinese NVDA Community Update Mirror (https://nvaccess.mirror.nvdadr.com/nvdaUpdateCheck).
  - Verified that this URL was marked as valid.
- Additional tests with random strings to ensure that invalid URLs are correctly marked as invalid.

### Known issues with pull request:
No known issues.

### Code Review Checklist:

- [ ] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [ ] API is compatible with existing add-ons.
- [x] Security precautions taken.

@coderabbitai summary

2024-10-20 22:11 UTC, seanbudd approved these changes

2024-10-20 22:11 UTC, seanbudd commented on source/updateCheck.py
> +def parseUpdateCheckResponse(data: str) -> Optional[Dict[str, str]]:
```suggestion
def parseUpdateCheckResponse(data: str) -> dict[str, str] | None:
```

2024-10-28 00:01 UTC, SaschaCowley requested changes
Thanks @christopherpross. A couple of minor adjustments, plus I think you may have forgotten to push the schema validation.

2024-10-29 18:22 UTC, christopherpross commented on source/gui/settingsDialogs.py
> +def _isResponseUpdateMirrorValid(response: requests.Response) -> bool:
@SaschaCowley  Hey, sorry I see. While merging, there is a change not applied. So this is lost. In the next few days, I will fix that. Sorry for the inconvinience.

2024-12-02 00:05 UTC, seanbudd commented
Hi @christopherpross - just confirming you've seen Sascha's review and intend to still work on this?

2024-12-27 00:18 UTC, christopherpross commented
@seanbudd  and @SaschaCowley  sorry for the delay, my real life comes in the way. I am so sorry. If you have a deathline for this fix, someone can, if they want take this and fix the remaining missing code. I has forgotten something to push and deleted my local repo. So in the next few days I will try to get into this. But I understand fully if you have a deathline and you have to fix this issue fast. Sorry for the inconventience.

2025-01-09 03:38 UTC, SaschaCowley requested changes
Thanks @christopherpross. A few suggestions to improve the quality of the update check code while you're here. Please also update the copyright headers of the files you have touched to reflect that they have been modified in 2025, and add yourself to the list of copyright holders, if you like

2025-01-09 03:38 UTC, SaschaCowley commented on source/updateCheck.py
> +def parseUpdateCheckResponse(data: str) -> dict[str, str] | None:
To make the code more self-documenting and easier to debug, could you create a new class to hold update information (perhaps as a [`dataclasses.dataclass`](https://docs.python.org/3/library/dataclasses.html) or [`typing.NamedTuple`](https://docs.python.org/3/library/typing.html#special-types))?

2025-01-09 03:38 UTC, SaschaCowley commented on source/updateCheck.py
> +			log.debug(f"Retrying update data fetch from {url}")
```suggestion
			log.debug(f"Retrying update check from {url}")
```

2025-01-09 03:38 UTC, SaschaCowley commented on source/gui/settingsDialogs.py
> +def _isResponseUpdateMirrorValid(response: requests.Response) -> bool:
Could you rename this to be a little clearer? Perhaps something like `isResponseUpdateMetadata`

2025-01-10 08:30 UTC, christopherpross commented
@SaschaCowley 
Done, I have implemented all the suggested changes.

2025-01-13 05:30 UTC, SaschaCowley requested changes
A few minor tweaks

2025-01-13 05:30 UTC, SaschaCowley commented on source/updateCheck.py
> +def parseUpdateCheckResponse(data: str) -> Optional[UpdateInfo]:
Can you:
* Raise appropriate exceptions when parsing fails, and handle them gracefully when calling this function?
* Make this a classmethod of `UpdateInfo`?

2025-01-13 05:30 UTC, SaschaCowley commented on source/updateCheck.py
> +	if not isValidUpdateMirrorResponse(data):
This is duplicating work. Instead, this function should raise errors, and `isValidUpdateMirrorResponse` should try calling this class and returning `False` if it fails. When making this change, the call to `isValidUpdateMirrorResponse` will need to be removed, or you'll get infinite recursion.

2025-01-13 05:30 UTC, SaschaCowley commented on source/updateCheck.py
> +def isValidUpdateMirrorResponse(responseData: str) -> bool:
Re-implement per above

2025-01-13 05:30 UTC, SaschaCowley commented on source/updateCheck.py
> +def checkForUpdate(auto: bool = False) -> Optional[UpdateInfo]:
```suggestion
def checkForUpdate(auto: bool = False) -> UpdateInfo | None:
```

2025-01-13 05:30 UTC, SaschaCowley commented on source/updateCheck.py
> +	:param auto: Whether this is an automatic check for updates.
```suggestion
	:param auto: Whether this is an automatic check for updates, defaults to False.
```

2025-01-13 05:30 UTC, SaschaCowley commented on source/updateCheck.py
> +
This is tripling work
```suggestion
```

2025-01-13 05:30 UTC, SaschaCowley commented on source/updateCheck.py
> +	def _result(self, info: Optional[UpdateInfo]) -> None:
```suggestion
	def _result(self, info: UpdateInfo | None) -> None:
```

2025-01-13 05:30 UTC, SaschaCowley commented on source/updateCheck.py
> +	def __init__(self, parent, updateInfo: Optional[UpdateInfo], auto: bool) -> None:
```suggestion
	def __init__(self, parent, updateInfo: UpdateInfo | None, auto: bool) -> None:
```

2025-01-13 05:30 UTC, SaschaCowley commented on source/updateCheck.py
> +		:type updateInfo: UpdateInfo
We don't include type info in docstrings when that type info is fully described by type annotations.
```suggestion
```

2025-01-25 19:37 UTC, christopherpross commented
@SaschaCowley  Ok, done I have implemented all suggested changes. I have also resolved a conflict in settingsDialog.py

2025-02-06 02:25 UTC, SaschaCowley requested changes
Some suggestions on how to make this more maintainable and performant, as well as on keeping to our coding standards.

2025-02-06 02:25 UTC, SaschaCowley commented on source/updateCheck.py
> +				metadata[key] = val
If we use a similar approach to above, we can grab all good keys, and silently drop bad keys, so we only need to unpack `metadata` to initialise `cls`. We can also remove keys from `requiredKeys` to make checking for all required keys easier later.
```suggestion
				if key in recognizedKeys:
					metadata[key] = val
					requiredKeys.difference_update(key)
				else:
					log.debug(f"Dropping unknown key {key} = {val}.")
```

2025-02-06 02:25 UTC, SaschaCowley commented on source/updateCheck.py
> +		if missing_keys:
If you decide to use the approach suggested above, this can be simplified to
```suggestion
		if requiredKeys:
```

2025-02-06 02:25 UTC, SaschaCowley commented on source/updateCheck.py
> +		)
It would probably be easier to do
```suggestion
		return cls(**metadata)
```
The further suggestions above should help to make this fairly bullet-proof,, but if you wanted to you could wrap this in a try/except, except `TypeError`, and re-raise it as a `ValueError` since that's more appropriate here.

2025-02-06 02:25 UTC, SaschaCowley commented on source/updateCheck.py
> +def checkForUpdate(auto: bool = False) -> Optional[UpdateInfo]:
```suggestion
def checkForUpdate(auto: bool = False) -> UpdateInfo | None:
```

2025-02-06 02:25 UTC, SaschaCowley commented on source/updateCheck.py
> +	def _result(self, info: Optional[UpdateInfo]) -> None:
```suggestion
	def _result(self, info: UpdateInfo | None) -> None:
```

2025-02-06 02:25 UTC, SaschaCowley commented on source/updateCheck.py
> +	def __init__(self, parent, updateInfo: Optional[UpdateInfo], auto: bool) -> None:
```suggestion
	def __init__(self, parent, updateInfo: UpdateInfo | None, auto: bool) -> None:
```

2025-02-06 02:25 UTC, SaschaCowley commented on user_docs/en/changes.md
Please document API breaking changes (by my count, `checkForUpdate`, `UpdateResultDialog.__init__`, `UpdateDownloader.__init__`)

2025-02-10 04:18 UTC, christopherpross commented
@SaschaCowley Ok, I have applied the suggestions and documented the breaking changes.

2025-02-18 05:24 UTC, SaschaCowley requested changes

2025-03-06 22:52 UTC, SaschaCowley approved these changes

2025-03-07 07:55 UTC, merged