Add commands to move the review cursor to the first and last character of selected text
nvaccess/nvda pull request #17393
Opened 2024-11-11 16:00 UTC by nvdaes

### Link to issue number:
Fixes #17299
### Summary of the issue:
NVDA doesn't have commands to move the review cursor to start and end of selection, which may be useful to review the selected text.
### Description of user facing changes
`NVDA+alt+home` and `NVDA+alt+end` can be used to move the review cursor to the first and last carácter of selected text.
### Description of development approach
In globalCommands.py, GlobalCommands class, a staticmethod has been added to get the current selection. This is used to scripts added to move the review cursor to start and end of selection, similar to other scripts used to move the review cursor.
### Testing strategy:
Tested manually in a webpage and in Notepad.
### Known issues with pull request:
None.
### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

@coderabbitai summary

2024-11-12 17:07 UTC, nvdaes commented
@burmancomp , please, feel free to test again in MS Word with UIA enabled only when needed or with other configurations and applications. I think that now this is fixed, according to my tests. Now we move the end of the selection info one character back before collapsing, instead of collapsing and then moving back one character.

2024-11-13 09:57 UTC, nvdaes commented
Then let's mark this as ready for review.

2024-11-19 01:11 UTC, SaschaCowley requested changes
Thanks @nvdaes. Mostly cosmetic changes requested, but I think you have accidentally deleted the move to end of line in review gesture.

2024-11-19 01:11 UTC, SaschaCowley commented on user_docs/en/userGuide.md
> +|Move to end of selection |NVDA+alt+end |NVDA+alt+end |none |Moves the review cursor to the last character of the selected text|
Can we include that these are review cursor gestures in the descriptions?
```suggestion
|Move to start of selection in review |NVDA+alt+home |NVDA+alt+home |none |Moves the review cursor to the first character of the selected text|
|Move to end of selection in review |NVDA+alt+end |NVDA+alt+end |none |Moves the review cursor to the last character of the selected text|
```

2024-11-19 04:41 UTC, nvdaes commented on source/globalCommands.py
Done

2024-11-19 05:12 UTC, nvdaes commented
@SaschaCowley , think that all your suggestions are addressed now.
Thanks for your review, and thanks all reviewers.

2024-11-21 06:34 UTC, SaschaCowley approved these changes
Thanks @nvdaes

2024-11-21 06:37 UTC, merged