Remove winmm support from NVDA
nvaccess/nvda pull request #17496
Opened 2024-12-10 06:30 UTC by SaschaCowley

### Link to issue number:

Closes #16080

### Summary of the issue:

The support for WASAPI (and Windows' Core Audio APIs more broadly) in NVDA is now quite mature, and maintenance of our winmm support is becoming untenable.

### Description of user facing changes:

The option to use WASAPI for audio output has been removed from NVDA's advanced settings. This has been on by default for some time, so it is unlikely to affect most users.

As the Mmdevice API does not have the concept of an ID to refer to the default output device, "Microsoft Sound Mapper" is no longer an option in the output device selection in Audio Settings. Users can instead choose "Default output device".

### Description of development approach

Removed all references to winmm in `nvwave.py`. Rewrote the device enumeration to use the Mmdevice API, via pycaw. Slightly modified the device selection logic in the settings GUI in light of Mmdevice not having an equivalent to Microsoft Sound Mapper.

### Testing strategy:

System and unit tests, as well as running NVDA, and changing output devices, including plugging and unplugging headphones while NVDA was running.

### Known issues with pull request:

None

### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [ ] API is compatible with existing add-ons.
- [x] Security precautions taken.

@coderabbitai summary

2024-12-10 06:31 UTC, SaschaCowley commented
@coderabbitai please open an issue related to this one, for switching to using endpoint IDs rather than friendly names for identifying the selected output device in user configuration.

2024-12-10 12:12 UTC, CyrilleB79 requested changes
This PR seems incomplete:
* Various audio features (e.g. sound split, mute other apps, etc.) only work if WASAPI is enabled:
  * in settings dialog, the check of WASAPI to enable or disable controls for such settings should be removed (see (`nvwave.usingWasapiWavePlayer` calls)
  * in the User Guide, the documentation of these settings mention WASAPI requirement; this should be removed
* In config spec, `WASAPI` should be removed from `audio` section, and this removal should be documented in API-breaking changes. Or in case you want to keep it as a no-effect parameter, you should at least document it in the change log and remove all of its usage in NVDA's code.
* I also wonder if the removal of `AdvancedPanelControls.wasapiComboBox` should be documented in the API-breaking changes.

2024-12-11 03:43 UTC, SaschaCowley commented
@CyrilleB79 thanks for the thorough notes. I believe I've addressed all of your points now.

2024-12-11 04:03 UTC, seanbudd reviewed
Thanks @SaschaCowley - mostly looks good to me!

2024-12-11 04:03 UTC, seanbudd commented on source/nvwave.py
> +fileWavePlayerThread = None
can this get a type hint?

2024-12-11 04:03 UTC, seanbudd commented on source/nvwave.py
>  def getOutputDeviceNames():
can this get a return type added?

2024-12-11 04:03 UTC, seanbudd commented on source/nvwave.py
>  def _getOutputDevices():
can this get a return type?

2024-12-11 05:45 UTC, seanbudd approved these changes

2024-12-11 05:45 UTC, seanbudd commented on source/nvwave.py
> +def _getOutputDevices() -> Iterator[tuple[str, str]]:
I'd suggest using the Generator type as their handling can be different

```suggestion
def _getOutputDevices() -> Generator[tuple[str, str], None, None]:
```

2024-12-11 05:45 UTC, seanbudd commented on source/nvwave.py
> +def outputDeviceNameToID(name: str, useDefaultIfInvalid: bool = False) -> str:
as this return type is changing, can this be listed as an API breaking change?

2024-12-12 01:41 UTC, seanbudd approved these changes
Thanks @SaschaCowley

2024-12-12 21:52 UTC, CyrilleB79 approved these changes

2024-12-13 00:21 UTC, Qchristensen approved these changes
Reads well, good work.

2024-12-13 00:25 UTC, merged

2024-12-13 00:49 UTC, Adriani90 commented
Thanks Sascha this is very appreciated cleanup.

2024-12-13 09:29 UTC, CyrilleB79 commented
@SaschaCowley, after this PR, if I plug an USB headset, but select my PC speaker for NVDA audio output, the sound still comes in the headset rather than from PC sdpeakers.

2024-12-14 00:00 UTC, Adriani90 commented
@SaschaCowley it seems the NVWave advanced logging channel is still there, I mean the one introduced in #11582  and  #11614. Does it have to be removed as well? Or is it not related?