NLS eReader Zoomax braille driver
nvaccess/nvda pull request #17509
Opened 2024-12-12 11:23 UTC by florin-trutiu

This is the NVDA driver for the NLS eReader Zoomax braille display.
It supports both USB and Bluetooth automatic detection.

2024-12-13 02:10 UTC, seanbudd commented
Thanks for opening this PR @florin-trutiu !

- Please fill out the PR template
- Please remove this line from the userGuide: https://github.com/nvaccess/nvda/blob/c17b4230fde8a1d9cb811181bc4f4e8c19dc8234/user_docs/en/userGuide.md#L4284
- Please add a changelog entry in changes.md noting that support for this braille device has been added

2024-12-13 02:14 UTC, seanbudd commented
pre-commit.ci autofix

2024-12-13 14:06 UTC, florin-trutiu commented
> Thanks for opening this PR @florin-trutiu !
> 
> * Please fill out the PR template
> * Please remove this line from the userGuide: https://github.com/nvaccess/nvda/blob/c17b4230fde8a1d9cb811181bc4f4e8c19dc8234/user_docs/en/userGuide.md#L4284
> * Please add a changelog entry in changes.md noting that support for this braille device has been added

Removed the required line.
I noticed that the line was in that section because of a confusion, there are two NLS eReader braille displays. one is manufactured by Humanware and one by Zoomax.
So to avoid confusion I appended the Humanware name to the NLS eReader device mentioned in the Humanware displays section.

In the user guide I have now added a section for the NLS eReader Zoomax braille display.

2024-12-13 15:03 UTC, CyrilleB79 commented
@florin-trutiu, you have added the template, but for completeness, could you please writing the required information in its sections rather than writing before it? Thanks!

2025-01-10 06:32 UTC, SaschaCowley reviewed
Thanks for submitting this, @florin-trutiu! A lot of questions and stylistic questions on this to begin with

2025-01-10 06:32 UTC, SaschaCowley commented on source/brailleDisplayDrivers/nlseReaderZoomax.py
> +		typeErrorString = "Expected param '{}' to be of type '{}', got '{}'"
Could you change this to use named rather than positional fields?
```suggestion
		TYPE_ERROR_TEMPLATE = "Expected parameter '{paramName}' to be of type '{expectedType}', got '{actualType}'"
```

2025-01-10 06:32 UTC, SaschaCowley commented on source/brailleDisplayDrivers/nlseReaderZoomax.py
> +		arg = arg.replace(ESCAPE, ESCAPE * 2)
Can you please explain why you are doing this?

2025-01-10 06:32 UTC, SaschaCowley commented on source/brailleDisplayDrivers/nlseReaderZoomax.py
> +			log.debugWarning("Ignoring byte before escape: %r" % data)
Please use an f-string instead

2025-01-10 06:32 UTC, SaschaCowley commented on source/brailleDisplayDrivers/nlseReaderZoomax.py
> +			arg = sum(byte << offset * 8 for offset, byte in enumerate(arg))
Why not
```suggestion
			arg = int.from_bytes(reversed(arg))
```

2025-01-10 06:32 UTC, SaschaCowley commented on source/brailleDisplayDrivers/nlseReaderZoomax.py
> +				del self._keysDown[command]
I'm having a lot of trouble following what's going on here. Could you please comment a bit more on what's going on?

2025-01-10 06:32 UTC, SaschaCowley commented on source/brailleDisplayDrivers/nlseReaderZoomax.py
> +			if group == LOC_BRAILLE_KEYS and len(keysDown) == 1 and not groupKeysDown & 0xF8:
Why `0xf8`?

2025-01-10 06:42 UTC, SaschaCowley requested changes

2025-01-10 06:42 UTC, SaschaCowley commented on user_docs/en/changes.md
> +* NLS eReader Zoomax driver has been added. Previously it was available only as a separate addon.
```suggestion
* Support for the NLS eReader Zoomax braille display has been added. (#17509, @florin-trutiu)
```

2025-01-10 06:42 UTC, SaschaCowley commented on user_docs/en/userGuide.md
> +For computers where the Internet connection is disabled or not available, for the USB connection, a driver can be download from the USB to serial CH340 chip manufacturer  (https://www.wch-ic.com/down
```suggestion
For computers where the Internet connection is disabled or not available, you can manually [download and install the USB to serial CH340 chip driver](https://www.wch-ic.com/downloads/CH341SER_EXE.html) to support this display over USB.
```

2025-01-21 18:37 UTC, florin-trutiu commented on source/brailleDisplayDrivers/nlseReaderZoomax.py
> +ESCAPE = b"\x1b"
@SaschaCowley 
The nlseReaderZoomax.py driver uses code from the baum.py driver that is already part of the NVDA source code.
This is done so because the NLS eReader Zoomax has a protocol similar with the one used by the Baum Braille displays.
So the plan was to provide a separate driver file but to not change the functionality that was already working and approved by the NVDA team.

2025-01-21 18:39 UTC, florin-trutiu commented on source/brailleDisplayDrivers/nlseReaderZoomax.py
> +				"VID_1A86&PID_7523",  # CH340
@SaschaCowley 
CH340 is an USB to serial chip used in the device, and those are it's VID and PID values.

2025-01-21 19:13 UTC, florin-trutiu commented on source/brailleDisplayDrivers/nlseReaderZoomax.py
> +ESCAPE = b"\x1b"
I discussed with my manager and I will make the also the rest of the changes your requested but it will take more time as I have a high priority project that needs to be done first.

2025-03-03 00:30 UTC, seanbudd commented
@florin-trutiu - Is this ready for re-review? I noticed you pushed some changes in January, but this was never marked as ready for review again

2025-05-22 22:57 UTC, Adriani90 commented
it seems @florin-trutiu is not quite active anymore on this repo. Should we mark this as abandoned? Or should we ask within the community whether someone else wants to take it over?

2025-05-23 05:04 UTC, florin-trutiu commented
> it seems @florin-trutiu is not quite active anymore on this repo. Should we mark this as abandoned? Or should we ask within the community whether someone else wants to take it over?
@seanbudd 
The NLS eReader Zoomax braille driver is/was similar with the rest of the Braille display drivers already present in the NVDA sources.
The problem appeared when I was requested by @SaschaCowley to make multiple changes to the driver, although, like I mentioned, the driver was similar with the rest of the drivers and those drivers work and do not have the changes I was requested to make.
At that time I replied to @SaschaCowley and told him that I talked with my manager and that I will make the changes, but as it required major changes, I could not find the time to do it..
I will discuss again the issue with those in charge to see if I can move it higher in my priorities list.

2025-06-16 09:01 UTC, closed without merging