Add "Only in edit controls" mode for typing echo
nvaccess/nvda pull request #17505
Opened 2024-12-11 23:26 UTC by cary-rowen

### Link to issue number:
Fixes #16848, related #10331, #3027

### Summary of the issue:
Currently NVDA can only toggle typing echo (characters and words) on or off globally. Users want more granular control to only have typing feedback in edit controls, while keeping it off in other contexts like listss or non-edit areas.
### Description of user facing changes
- Added a new option "Only in edit controls" for both "Speak typed characters" and "Speak typed words" settings in Keyboard Settings
- Instead of checkboxes, these are now combo boxes with three options:
  - Off: No typing echo
  - On: Echo all typed text
  - Only in edit controls: Only echo text typed in edit fields
- Updated relevant documentation in the user guide

### Description of development approach
The implementation:
1. Added a TypingEcho enum in configFlags.py with values:
   - OFF (0)
   - ON (1) 
   - EDIT_CONTROLS (2)
2. Changed keyboard typing echo configuration from boolean to integer values
3. Updated speech.py, behaviors.py and inputComposition.py to use the new enum
4. Modified settings dialog to use combo box instead of checkbox
5. Updated documentation

### Testing strategy:
Tested the following scenarios:
1. Basic functionality:
- Open Notepad (edit control)
  - Set to "Only in edit controls"
  - Type text - should be announced
  - Verify both character and word echo settings
- Explorer file lists(non-edit control)
  - Type text - should not be announced
- Test all three modes (Off, On, Only in edit controls)
2. Different contexts:
- Web browser input fields
- Rich text editors
- Read-only text areas
- Terminal windows

### Known issues with pull request:
None identified.

### Code Review Checklist:

- [X] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [X] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [X] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [ ] API is compatible with existing add-ons.
- [ ] Security precautions taken.

@coderabbitai summary

2024-12-11 23:37 UTC, Adriani90 commented
Great work on this, thank you.

2024-12-11 23:40 UTC, Adriani90 commented
I think this needs a changelog entry as well.

2024-12-12 09:28 UTC, CyrilleB79 commented
Very nice addition @cary-rowen! Thanks.

I have some questions:
1. Shouldn't there be a config upgrade? I.e. a value in the old config should remain in the new one.
2. I think that "Only in edit controls" should become the default behaviour; I guess that most people would be happy and moreover, it's a security fix as described in #10331.
3. If NV Access reviewers (@SaschaCowley or @seanbudd) do not accept the new behaviour to be the default for now, should we use a feature flag to be able to change the default in the future?
4. With the new option, can typing be heard when typing in an edit field but when text is not actually written, e.g.:
   * In cmd, when initiating an ssh connection, typing the password outputs no visible character
   * In a read-only edit field, e.g. the synth field of NVDA speech settings panel.

2024-12-12 20:05 UTC, nvdaes reviewed
@cary-rowen , thanks for this.
I think that you may add a helper function in globalCommands, similar to the `toggleBooleanValue` function, for config flags, and use it for toggling typed characters and words.
For reference, see `toggleBooleanValue` in `globalCommands.py`, introduced in PR #16994

2024-12-12 23:13 UTC, cary-rowen commented
Hi @CyrilleB79 
Thank you for your review! I'd like to clarify your last point about special input scenarios. Are you asking whether the new "Only in edit controls" option works as expected in these cases:
1. When typing passwords in cmd during SSH connection:
  - Should typed characters be announced in this case?
2. In read-only edit fields (like the synthesizer field in NVDA speech settings):
  - Though it looks like an edit field, it's read-only
  - I've tested that typed characters are not announced here with the new option, as no text can be entered
  - Is this the expected behavior?

Could you please confirm if these behaviors are what you're asking about, and what the expected behavior should be in these cases?

Many thanks

2024-12-12 23:16 UTC, cary-rowen commented
Regarding default settings, I'd also love to hear suggestions from NV Access, I'd personally like to see new options provided as defaults for the same reasons as @CyrilleB79.

@nvdaes 
Thanks for your suggestion, I will implement a helper method to simplify the code.

2024-12-13 07:02 UTC, CyrilleB79 commented
@cary-rowen IMO, the expected behaviour with the new option in ssh password case and in read-only edit fields such as synthesizer is that NVDA should not speak anything since nothing is actually visible on the screen.

2024-12-13 12:07 UTC, amirmahdifard commented
thaaaaanks! should I really beleave that from now on we can get rid of the t. This pc 10 of 18, or space. playback stopped, and space. Playback resumed, with out needing to install the best ever addon made by @cary-rowen that addon was the best, because I alwayes liked and needed to keep typed characters and words, but I hated how they are announced everywhere, I was thinking, how stupid, the option it self is called speeck ('"typed"') characters and words, but why whe were hearing it everywhere? whe are not typing anything! whe are using our keyboard to use and explor our computer! but from now on, at least we don't have to use an addon to solv this really annoying this. And, really thank you @cary-rowen for resolving such problem for us until now. befor your addon releace on the stor, I was using an old and less buggy vertion of an unknown addon called typing settings to solv this for my self. greate feature!

2024-12-13 12:54 UTC, Adriani90 commented
@cary-rowen speaking typed characters outside of edit fields does not make sense anyway, because they are not typed, but only pressed. For that we have the input help feature already if people need to learn the keyboard layout outside of edit fields.
So unless there is a valid use case for having characters being spoken outside of edit fields,
Why don't you just change the current setting when enabled to be valid only for edit fields?
In this case we could let it be a checkbox and don't need three options.

2024-12-13 15:09 UTC, amirmahdifard commented
@Adriani90 hi. No, I also don't agree for removal of that in my opinion because, input help is a thing, but this is stil needed for some people where they need to press some keys and need to be announced for them what they've preased and what came up, or what happened as a result, while some newbie people need to turn on input help, press a fue keys that they need, and turn of input help, and make sure they've pressed or pressing the correct key. Also, for a groupe of users with old habit, better to not remove it but rename it instead for example, from on, to everywhere. so the options are as folows. off, in edit boxes only, everywhare.

2024-12-17 02:52 UTC, cary-rowen commented
@CyrilleB79 
wrote:
> the expected behaviour with the new option in ssh password case and in read-only edit fields such as synthesizer is that NVDA should not speak anything since nothing is actually visible on the screen.

I agree that there shouldn't be any feedback in the read-only edit box after enabling the new options introduced by this PR. This is currently as expected.
However, I would like to have feedback when typing the password in ssh, unlike other password fields, in the normal password field NVDA will report 'star' when typing the password.
In the SSH password field, the characters are actually entered, they are just not displayed, unlike read-only fields (which do not produce any input)

cc @seanbudd

2024-12-17 02:53 UTC, cary-rowen commented
I agree with @amirmahdifard I am totally not in favor of removing the original mode.

2024-12-17 07:55 UTC, CyrilleB79 commented
> I agree that there shouldn't be any feedback in the read-only edit box after enabling the new options introduced by this PR. This is currently as expected. However, I would like to have feedback when typing the password in ssh, unlike other password fields, in the normal password field NVDA will report 'star' when typing the password. In the SSH password field, the characters are actually entered, they are just not displayed, unlike read-only fields (which do not produce any input)

It's worth noting that visually, nothing appears on the screen. It's quite a bad design IMO, because users cannot know if and how many characters they enter (or delete) when pressing a key. Though, sighted people and blind ones are equally impacted in this case. IMO, this issue should not be a reason to hold off this PR.

2024-12-17 13:07 UTC, amirmahdifard commented
@cary-rowen but, if you haven't allready, please rename the "on" to everywhere" because on does not have any meaning anymore in this cace, because both ways are on, but we are only indicating where to announce the characters and words. In edit boxes only, everywhere, or off "do not announce anywhere at all". Thanks. Once that's done, this pr is completely done and ok like the addons which were tryed to impliment this feature. this is ready to go and i'm gonna excitedly wait for the next releace which I can uninstall addon and have this feature natively with in nvda it self.

2024-12-21 09:20 UTC, XLTechie commented
Not very important, but
Rather than "Everywhere", I would probably call it "Always" to contrast with the "Only" of "Only in edit controls".

I personally agree with the suggestion to make "only" the new default, or upgraded version of the current "enabled" state.

By far, I think this is what users would have wanted "enabled" to mean all along, and it doesn't seem to be a very harmful change even if someone dislikes it.

2024-12-21 09:37 UTC, XLTechie commented
> However, I would like to have feedback when typing the password in ssh

Doesn't the "Speak passwords in all enhanced terminals" setting in Advanced, already cover this situation?

2025-01-01 14:31 UTC, cary-rowen commented
@XLTechie 
I agree using "Always" which is also more common in NVDA.
> Doesn't the "Speak passwords in all enhanced terminals" setting in Advanced, already cover this situation?

Yes, I guess it makes intuitive sense that we should report passwords in this mode as long as the user explicitly enables the Report Passwords option in the advanced settings.

2025-01-06 06:22 UTC, SaschaCowley requested changes
Could the "everywhere" mode be renamed to "always" as others have suggested, too?

2025-01-06 06:22 UTC, SaschaCowley commented on source/speech/speech.py
>  		placeholder value. (False, []) if text for obj was not considered empty.
```suggestion
	:return: `(True, SpeechSequence)` if text for obj was considered empty and we attempted to get speech for the
		placeholder value. `(False, [])` if text for obj was not considered empty.
```

2025-01-06 06:22 UTC, SaschaCowley commented on source/speech/speech.py
> +			):
In general, you should perform the most expensive checks first when using `or`, as Python knows that if the first condition is true, it doesn't need to check the second condition. While this check shouldn't be too costly, it is run so often that this may make a measurable difference over time.
Also added an extra set of brackets for readability.
```suggestion
			if (
				typingEchoMode == TypingEcho.EVERYWHERE.value
				or (
					typingEchoMode == TypingEcho.EDIT_CONTROLS.value
					and is_editableControl()
				)
			):
```

2025-01-06 06:22 UTC, SaschaCowley commented on source/speech/speech.py
> +	if not suppress and typingEchoMode > TypingEcho.OFF.value and ch >= FIRST_NONCONTROL_CHAR:
```suggestion
	if not suppress and typingEchoMode != TypingEcho.OFF.value and ch >= FIRST_NONCONTROL_CHAR:
```

2025-01-06 06:22 UTC, SaschaCowley commented on source/speech/speech.py
> +			or typingEchoMode == TypingEcho.EVERYWHERE.value
As above

2025-01-06 06:22 UTC, SaschaCowley commented on source/speech/speech.py
> +def is_editableControl() -> bool:
Can this get a more descriptive name and a docstring?
```suggestion
def isFocusEditable() -> bool:
```

2025-01-06 06:22 UTC, SaschaCowley commented on source/gui/settingsDialogs.py
> +		charsLabelText = _("Speak typed &characters:")
Can the `charsX` and `wordsX` identifiers get more descriptive names? Something like `speakCharsList`.

2025-01-07 13:43 UTC, CyrilleB79 commented on source/gui/settingsDialogs.py
> +		except:  # noqa: E722
Idem

2025-01-07 13:43 UTC, CyrilleB79 commented on source/speech/speech.py
> +		if typingEchoMode > TypingEcho.OFF.value and not typingIsProtected:
Could you be consistent with what is done later for characters, i.e. use `!=` instead of `>`? I also feel it's slightly easier to read/understand since with this syntax, you do not need to know the numeric values of each `TypingEcho` member.

```suggestion
		if typingEchoMode != TypingEcho.OFF.value and not typingIsProtected:
```

2025-01-08 04:06 UTC, cary-rowen commented
Thanks @SaschaCowley and @CyrilleB79 for the review.
For the upgrade step I'm wondering do I need to create a separate upgrade method?
For example, `upgradeConfigFrom_14_to_15`

As @CyrilleB79 commented:

> Should the removal of  		self.charsCheckBox  be documented in the API breaking changes of the change log? Idem for words?
> Though, I am not sure that we have always respected the API when modifying the GUI in non-.1 releases in the past...


I'm not sure about this.

2025-01-08 08:51 UTC, CyrilleB79 commented on source/config/profileUpgradeSteps.py
> +	# """Convert keyboard typing echo configuration from boolean to integer values."""
You should rather do your own profile upgrade IMO, i.e. 14 to 15. Indeed, in the following cases, the upgrade of typing echo will not be done:
* If the user is on alpha channel and has upgraded each day, i.e. has already executed profile upgrade from 13 to 14 but without the typing echo upgrade code
* overall, even upgrading from 2024.4.1 to 2025.1 (stable channel), if no output device is present in config, because the function `upgradeConfigFrom_13_to_14` will return early without evaluating typing eco code.

2025-01-08 08:51 UTC, CyrilleB79 commented on source/config/profileUpgradeSteps.py
> +			profile["keyboard"]["speakTypedCharacters"] = new_value
A `KeyError` here (if any) should not be caught. Could you rather use a try/except/else structure, putting in the except clause only one line of code? And same for typed words upgrade below.

2025-01-08 09:18 UTC, cary-rowen commented on source/config/profileUpgradeSteps.py
> +			profile["keyboard"]["speakTypedCharacters"] = new_value
Regarding the use of the try/except/else structure:  I understand you recommend placing the code that may raise a  KeyError  within the  try  block, keeping only one line in the  except  block to handle the exception, and moving the main logic to the  else  block. Is this correct?

2025-01-08 22:27 UTC, CyrilleB79 commented on source/config/profileUpgradeSteps.py
> +			profile["keyboard"]["speakTypedCharacters"] = new_value
Yes that's correct.
Sorry my initial wording was not clear nor completely correct since there is already one line in the except block. I rather mean:
A `KeyError` here (if any) should not be caught. Could you rather use a try/except/else structure, putting in the try block only one line of code? And same for typed words upgrade below.

2025-01-09 04:43 UTC, SaschaCowley requested changes
Please also update the copyright headers of any files you have touched to reflect that they have been modified in 2025.

2025-01-09 04:43 UTC, SaschaCowley commented on source/config/configSpec.py
> +	speakTypedWords = integer(default=2,min=0,max=2)
Please change this back to defaulting to off (`0`).

2025-01-09 04:43 UTC, SaschaCowley commented on source/config/configSpec.py
Please bump the schema version to 15 so that alpha users don't get hit with a corrupt config.

2025-01-09 04:43 UTC, SaschaCowley commented on source/globalCommands.py
> +		description=_("Cycle the reporting of typed characters: Off, Always, and Only in edit controls."),
```suggestion
		description=_("Cycles through options for when to speak typed characters."),
```

2025-01-09 04:43 UTC, SaschaCowley commented on source/globalCommands.py
> +		description=_("Cycle the reporting of typed words: Off, Always, and Only in edit controls."),
```suggestion
		description=_("Cycles through options for when to speak typed words."),
```

2025-01-09 04:43 UTC, SaschaCowley commented on source/gui/settingsDialogs.py
> -		self.charsCheckBox = sHelper.addItem(wx.CheckBox(self, label=charsText))
I think we should do this to be safe.

2025-01-09 04:43 UTC, SaschaCowley commented on source/gui/settingsDialogs.py
> -		self.wordsCheckBox = sHelper.addItem(wx.CheckBox(self, label=speakTypedWordsText))
Please also document the removal of this checkbox in the changes for developers.

2025-01-09 04:43 UTC, SaschaCowley commented on source/speech/speech.py
> +	"""
Please rewrite this to be in sphinx style
```suggestion
	"""Check if the currently focused object is editable.
	:return: ``True`` if the focused object is editable, ``False`` otherwise.
	"""
```

2025-01-09 04:43 UTC, SaschaCowley commented on user_docs/en/changes.md
> +* The keyboard settings for "Speak typed characters" and "Speak typed words" now have three options: Off, Always, and Only in edit controls. (#17505, @Cary-rowen)
Can you please document that the new default is "Only in edit controls"?

2025-01-09 04:43 UTC, SaschaCowley commented on user_docs/en/changes.md
Please document the change of config spec, and the removal of the speak typed characters/words checkboxes from the GUI, in the changes for developers.

2025-01-09 04:43 UTC, SaschaCowley commented on user_docs/en/userGuide.md
>  Key: NVDA+2
```suggestion
Key: `NVDA+2`
```

2025-01-09 04:43 UTC, SaschaCowley commented on user_docs/en/userGuide.md
>  Key: NVDA+3
```suggestion
Key: `NVDA+3`
```

2025-01-09 14:17 UTC, cary-rowen commented on source/config/configFlags.py
> +	EDIT_CONTROLS = 2
Makes sense

2025-01-10 04:05 UTC, SaschaCowley requested changes
This is looking good, just a few small things to go

2025-01-10 04:05 UTC, SaschaCowley commented on user_docs/en/changes.md
> +* Changed keyboard typing echo configuration from boolean to integer values. (#17505, @Cary-rowen)
This is an API breaking change

2025-01-10 05:36 UTC, cary-rowen commented
Thanks @SaschaCowley 
learned a lot

2025-01-10 11:48 UTC, wmhn1872265132 commented on user_docs/en/changes.md
> +* The keyboard settings for "Speak typed characters" and "Speak typed words" now have three options: Off, Always, and Only in edit controls. (#17505, @Cary-rowen)
The order here·Does it need to be adjusted?
```suggestion
* The keyboard settings for "Speak typed characters" and "Speak typed words" now have three options: Off, Only in edit controls, and Always. (#17505, @Cary-rowen)
```

2025-01-10 11:48 UTC, wmhn1872265132 commented on user_docs/en/userGuide.md
> +* Only in edit controls: NVDA will only announce characters typed in edit controls and other areas where text can be typed.
The order here·Does it need to be adjusted?

2025-01-10 11:48 UTC, wmhn1872265132 commented on user_docs/en/userGuide.md
> +* Only in edit controls: NVDA will only announce words typed in edit controls and other areas where text can be typed.
The order here·Does it need to be adjusted?

2025-01-10 13:24 UTC, cary-rowen commented on user_docs/en/userGuide.md
> +* Only in edit controls: NVDA will only announce words typed in edit controls and other areas where text can be typed.
Yes, Done

2025-01-11 06:10 UTC, nvdaes requested changes
@cary-rowen  I've reviewed changes in globalCommands.py.
Looks good to me, except for minor inconsistencies in comments for translators.

2025-01-11 06:10 UTC, nvdaes commented on source/globalCommands.py
> +		# Translators: Input help mode message for cycling the reporting of typed words.
```suggestion
		# Translators: Input help mode message for cycling the reporting of typed characters.
```

2025-01-11 06:10 UTC, nvdaes commented on source/globalCommands.py
>  		# Translators: Input help mode message for toggle speak typed words command.
```suggestion
# Translators: Input help mode message for cycling the reporting of typed words.
```

2025-01-13 06:05 UTC, SaschaCowley commented on source/globalCommands.py
> +			messageTemplate=_("Speak typed characters: {mode}"),
```suggestion
			messageTemplate=_("Speak typed characters {mode}"),
```

2025-01-13 06:05 UTC, SaschaCowley commented on source/globalCommands.py
> +			messageTemplate=_("Speak typed words: {mode}"),
```suggestion
			messageTemplate=_("Speak typed words {mode}"),
```

2025-01-13 06:08 UTC, SaschaCowley approved these changes
Thanks @cary-rowen , looks good!

2025-01-15 04:44 UTC, cary-rowen commented
I've updated the original description with the latest changes. If there is anything else I need to do before merging please let me know.
cc @SaschaCowley @seanbudd

2025-01-16 05:32 UTC, SaschaCowley commented
Thanks @cary-rowen, we're just waiting on @Qchristensen to look over the documentation changes.

2025-01-20 05:19 UTC, Qchristensen approved these changes
Looks good, thanks.

2025-01-20 22:21 UTC, SaschaCowley commented
@cary-rowen please resolve merge conflicts

2025-01-22 04:11 UTC, merged