MS Word: The result of Word commands to expand or collapse a heading is now reported
nvaccess/nvda pull request #17545
Opened 2024-12-17 22:16 UTC by CyrilleB79

### Link to issue number:
None
Related to #17499, but independent of it.

### Summary of the issue:
In MS Word, `control+alt+plus` and `control+alt+-` allow to expand and collapse the content below a heading. NVDA does not report the result of this action.

### Description of user facing changes
NVDA now reports the result of the Word commands to expand and collapse headings.
### Description of development approach
Use Word object model (if available) as done for many Word gestures, no matter if UIA is enabled or not

### Testing strategy:
Tested with and without UIA.

### Known issues with pull request:
None
### Code Review Checklist:

- [ ] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

@coderabbitai summary

2024-12-17 22:40 UTC, CyrilleB79 commented
Test OK in French system/Word, remapping the gesture as needed, i.e. mapping alt+shift+6, which collapse a heading. Note: it has been done so, because the dash is on the same key as the 6.

But strangely, setting my Word (Office) and my keyboard layout to English, I cannot collapse a heading with `alt+shift+-` as documented [here](https://support.microsoft.com/en-us/office/keyboard-shortcuts-in-word-95ef89dd-7142-4b50-afb2-f762f663ceb2). Could someone with a real English Word/system confirm that this shortcut is the one to collapse a heading?

2024-12-18 01:17 UTC, wmhn1872265132 commented
It has been tested in the Chinese version of Word. This function works normally. The Chinese version of Word has the same shortcut keys as the English version.

2024-12-18 01:41 UTC, wmhn1872265132 commented
After further testing, I found that there seems to be a problem with this function in the Outline view of Word. Regardless of pressing Alt+Shift+Plus sign (+) or Alt+Shift+Minus sign (-), NVDA prompts Expanded, but the operation has been performed correctly.

2025-01-26 21:16 UTC, CyrilleB79 commented
Finally, I have had to exclude such reporting in Outline mode because I have not been able to get the paragraph state in this mode (see also related #17645). Also, I have excluded Draft mode which has no possibility to collapse headings.

2025-02-06 00:29 UTC, SaschaCowley requested changes

2025-02-06 00:29 UTC, SaschaCowley commented on source/appModules/winword.py
> +wdOutlineLevelBodyText = 10
This either needs to be marked const
```suggestion
WD_OUTLINE_LEVEL_BODY_TEXT: int = 10
```
Or refactored to be an enum for future extensibility
```suggestion
class WdOutlineLevel(IntEnum):
	BODY_TEXT = 10
```

2025-02-06 00:29 UTC, SaschaCowley commented on source/appModules/winword.py
> +# See https://learn.microsoft.com/fr-fr/office/vba/api/word.wdoutlinelevel
```suggestion
# See https://learn.microsoft.com/en-us/office/vba/api/word.wdoutlinelevel
```

2025-02-06 07:30 UTC, CyrilleB79 commented on source/appModules/winword.py
> +class WdOutlineLevel(IntEnum):
@SaschaCowley I have accepted your suggestion.

Though, thinking again to it, I should probably move this enum to `NVDAObjects/window/winword.py` since it is supported both in Word and Outlook. And because 10 (BODY_TEXT) is used in `_iterHeadings`.

I'll refactor my code.

2025-02-10 06:56 UTC, CyrilleB79 commented
@SaschaCowley the PR is ready again.

2025-02-18 06:11 UTC, SaschaCowley commented on source/NVDAObjects/window/winword.py
> +	BODY_TEXT = 10
Documentation as part of enum, please
```suggestion
class WdOutlineLevel(IntEnum):
	"""Outline level of a paragraph.

	.. seealso:: ```WdOutlineLevel`` enumeration <https://learn.microsoft.com/en-us/office/vba/api/word.wdoutlinelevel>`_
	"""
	
	BODY_TEXT = 10
```

2025-02-18 06:12 UTC, SaschaCowley approved these changes
Thanks, @CyrilleB79

2025-02-20 07:28 UTC, CyrilleB79 commented
@SaschaCowley or @seanbudd are you waiting for me to do something here?

If possible, it would be nice to merge this one for 2025.1, even if not mandatory, to be consistent with #17499: both enhance the support of Word's feature to collapse/expand headings.

2025-02-20 22:39 UTC, SaschaCowley commented
@CyrilleB79 no, just waiting on checks to complete before merging. Thanks for your patience.

2025-02-20 22:40 UTC, merged