I5848
nvaccess/nvda pull request #5858
Opened 2016-04-05 15:08 UTC by nvdaes

#5848: Add support for Azardi

2017-08-07 04:51 UTC, feerrenrut requested changes
Thanks for submitting this PR, sorry that its taken a long time for someone to look at it.

Could you please merge in the latest changes from master and resolve the conflicts?

2017-08-07 04:51 UTC, feerrenrut commented on source/appModules/azardi-2_0.py
> +#Copyright (C) 2016 Noelia Ruiz Martínez
Could you please update the copyright to match https://github.com/nvaccess/nvda/wiki/Copyright-headers

2017-08-07 04:51 UTC, feerrenrut commented on source/appModules/azardi-2_0.py
> +		winUser.mouse_event(winUser.MOUSEEVENTF_LEFTDOWN,0,0,None,None)
For these scripts, it would be really useful if we had a comment to describe why this needs to be done.

2017-08-07 05:30 UTC, nvdaes commented
Hi, I'm not too much available, but I can do small changes. Anyway, I
think it's more useful to priorize the VitalSource Bookshelf issue,
since it's considered more accessible than Azardi:
https://github.com/nvaccess/nvda/issues/7155

Cheers.

2017-08-07 6:51 GMT+02:00, Reef Turner <notifications@github.com>:
> feerrenrut requested changes on this pull request.
>
> Thanks for submitting this PR, sorry that its taken a long time for someone
> to look at it.
>
> Could you please merge in the latest changes from master and resolve the
> conflicts?
>
>> @@ -0,0 +1,46 @@
> +# -*- coding: UTF-8 -*-
> +#appModules/azardi-2_0.py
> +#A part of NonVisual Desktop Access (NVDA)
> +#Copyright (C) 2016 Noelia Ruiz Martínez
>
> Could you please update the copyright to match
> https://github.com/nvaccess/nvda/wiki/Copyright-headers
>
>> +import controlTypes
> +import winUser
> +import api
> +from NVDAObjects.IAccessible.mozilla import Document
> +from NVDAObjects.IAccessible.sysTreeView32 import TreeViewItem
> +
> +class AzardiDocument(Document):
> +
> +	role = controlTypes.ROLE_DOCUMENT
> +
> +class AzardiTreeViewItem(TreeViewItem):
> +
> +	def script_enter(self, gesture):
> +		api.moveMouseToNVDAObject(self)
> +		api.setMouseObject(self)
> +		winUser.mouse_event(winUser.MOUSEEVENTF_LEFTDOWN,0,0,None,None)
>
> For these scripts, it would be really useful if we had a comment to describe
> why this needs to be done.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/pull/5858#pullrequestreview-54562496

2017-08-07 09:40 UTC, nvdaes commented
Hi, it's ready to be reviewed. Please, note that:

- The book contents (documents of ePUB files) is located on a frame (quick nav: m).
- It's needed to toggle focus/browse mode for interacting with the tree (list of books) and when a book is opened from this tree.

Note: I will send a PR for VitalSource Bookshelf, in case you want to give it a greater priority. You can compare the evaluation between Azardi and Bookshelf here:

http://epubtest.org/testsuite/accessibility/

2017-08-08 03:39 UTC, feerrenrut approved these changes

2017-08-08 04:01 UTC, nvdaes commented
Thanks, for me this PR is finished.
Cheers

2017-08-08 5:39 GMT+02:00, Reef Turner <notifications@github.com>:
> feerrenrut approved this pull request.
>
>
>
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/pull/5858#pullrequestreview-54828150

2017-09-20 09:22 UTC, merged