Various fixes for 2016.4 what's new and user guide. re #6517, #6519, #6520
nvaccess/nvda pull request #6521
Opened 2016-10-28 18:20 UTC by josephsl

Linguistic fixes and clarifications:

* #6517: entries clarified, grammar fixes, linguistic fixes.
* #6519: document the fact that audio ducking isn't supported on temporary copies nad on portable ones on Windows 8 and later.
* #6520: changed label for indentation reporting combo box.

Thanks.

2016-10-28 18:21 UTC, josephsl commented
Hi @feerrenrut, may I request a review of these fixes please? Thanks.

2016-10-31 02:19 UTC, feerrenrut requested changes
Thanks for looking at this!

2016-10-31 02:19 UTC, feerrenrut commented on user_docs/en/changes.t2t
> +- Fixed a rare issue when exiting NVDA while the speech viewer is open which caused an error. (#5050)
Suggestion: "Fixed a rare error when exiting NVDA while the speech viewer is open. (#5050)"

2016-10-31 02:19 UTC, feerrenrut commented on user_docs/en/changes.t2t
> +- Fixed an issue causing a warning in the NVDA log file when caps lock is toggled. (#6127)
You can remove "Fixed an issue causing a warning in the NVDA log file when caps lock is toggled. (#6127)". Thinking about it now, its not a user visible error and therefore does not need to be in the change log.

2016-11-02 01:28 UTC, feerrenrut approved these changes

2016-11-04 05:56 UTC, closed without merging

2016-11-04 05:57 UTC, jcsteh commented
Thanks. I applied these changes and some other changes of my own.