Add support for wx.SpinCtrlDouble to guiHelper
nvaccess/nvda pull request #6531
Opened 2016-11-03 16:31 UTC by leonardder

There is a separate SpinCtrlDouble in wx which wasn't covered by guiHelper yet. Since I need this one for an add-on I'm working on on behalf of @babbagecom, here is a pull request.

2016-11-03 19:17 UTC, leonardder commented
For clarity, wx.SpinCtrlDouble covers floats and allows one to set the step size.

N.B. Sent on behalf of @BabbageCom

> Op 3 nov. 2016 om 17:31 heeft Leonard de Ruijter <notifications@github.com> het volgende geschreven:
> 
> There is a separate SpinCtrlDouble in wx which wasn't covered by guiHelper yet. Since I need this one for an add-on I'm working on on behalf of @babbagecom, here is a pull request.
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/nvaccess/nvda/pull/6531
> 
> Commit Summary
> 
> Added support for wx.SpinCtrlDouble to gui.guiHelper.associateElements
> File Changes
> 
> M source/gui/guiHelper.py (4)
> Patch Links:
> 
> https://github.com/nvaccess/nvda/pull/6531.patch
> https://github.com/nvaccess/nvda/pull/6531.diff
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-01-06 09:20 UTC, feerrenrut commented
For the integer spin control we have extended the wx implementation to provide automatic selection of the value when the control gains focus. For consistency it would be good to do that for `SpinCtrlDouble` as well. See the class `SelectOnFocusSpinCtrl` in `source/gui/nvdaControls.py`.

2017-03-31 03:59 UTC, feerrenrut requested changes
@leonardder just wondering if you are still working on this? There are some unaddressed review comments, I was wondering whether you might have missed them.

2017-04-01 07:51 UTC, leonardder commented
@feerrenrut: Thanks for reminding me of this. I'm afraid there's another issue to handle, since I noticed cases where the content of the edit field is entirely blank, even when you set an initial value. Might be able to look into this later, but I guess it doesn't not have much priority. unless you are interested in adding this to the core gui somewhere?

2017-04-03 08:37 UTC, feerrenrut commented
There aren't any cases I can think of (without going and looking through the GUI) that require this. However, if you are aware of some part of the GUI that would be improved through the use of this control, please raise an issue and mention me on it. Then we can assess how urgently it needs to be updated. In terms of this pull request, I'll leave it open, mention me, or assign it to me for code review when you feel it is ready. Thanks for your contributions!

2017-04-11 05:01 UTC, leonardder commented
@feerrenrut: It seems there are more issues than I initially thought. Most important, it seems a SpinCtrlDouble is not associated properly to a preceding label. In other words, the label isn't read when tabbing through a dialog. This is a real showstopper.

2017-06-02 11:36 UTC, leonardder commented
Closing this for now, there is too little demand for this and there are too many open ends in this implementation. Keeping the branch, though

2017-06-02 11:36 UTC, closed without merging