Excel: ensure that set column and row headers are remembered on copied sheets.
nvaccess/nvda pull request #6629
Opened 2016-12-08 06:28 UTC by michaelDCurran

Fixes #6628

2016-12-08 06:30 UTC, michaelDCurran commented
@qchristensen: when the appveyor build is complete for this branch, could you please give it a test, especially on Excel 2007 if you have it. Now column and row headers set by this build of NVDA or newer will be remembered when a sheet is copied.

2016-12-13 02:38 UTC, feerrenrut requested changes

2016-12-13 02:38 UTC, feerrenrut commented on source/NVDAObjects/window/excel.py
> +	re_definedName=re.compile(u'^((?P<sheet>(\'[^\']+\'|[^!]+))!)?(?P<name>\w+)(\.(?P<minAddress>[a-zA-Z]+[0-9]+)?(\.(?P<maxAddress>[a-zA-Z]+[0-9]+)?(\..*)*)?)?$')
As we discussed could we try and split this up to comment each part of this (or at least comment what we can). I think examples of the edge cases that we are trying to match are quite helpful too. In the absence of automated tests, this at least gives us a suite of manual test cases to use the next time that we find we have to modify this.

2017-01-06 02:29 UTC, michaelDCurran commented
@feerrenrut: I have made the requested change.

2017-01-06 03:41 UTC, feerrenrut approved these changes

2017-01-23 00:42 UTC, merged