addonHandler: Added getTranslatedMessage function.
nvaccess/nvda pull request #6747
Opened 2017-01-17 10:17 UTC by nvdaes

Based on the message method created by @ABuffEr, letting add-ons to use messages translated in NVDA's core.

2017-01-18 06:26 UTC, michaelDCurran commented
@nvdaes can you explain why exactly this is needed? For instance, explain why the add-on developer can't just call 
```
_(message)
```

2017-01-18 06:43 UTC, nvdaes commented
Hello. When we just call _(message), if the Python file containing the 
message calls addonHandler.initTranslation(), the message is included in 
the nvda.po for the add-on and translators have to translate it.
With getTranslatedMessage, if it's included in NVDA's core, translators:
1. Can avoid to translate the text again.
2. This can make translated messages more consistent avoiding different 
translations for the same message.

One recent example is the word "Error", used in the Emoticons add-on. As 
it's in NVDA's core, we use a sfunction similar to 
getTranslatedMessage("error") instead of _("Error").
Cheers.

El 18/01/2017 a las 7:26, Michael Curran escribió:
> @nvdaes <https://github.com/nvdaes> can you explain why exactly this is
> needed? For instance, explain why the add-on developer can't just call
>
> |_(message) |
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nvaccess/nvda/pull/6747#issuecomment-273394824>, or
> mute the thread
> <https://github.com/notifications/unsubscribe-auth/APE65OEWlDZQggzXFbfSVo4546_3K5rGks5rTbCKgaJpZM4LldIC>.
>

2017-01-18 23:53 UTC, michaelDCurran requested changes

2017-01-18 23:53 UTC, michaelDCurran commented on source/addonHandler.py
> +def getTranslatedMessage(translatedMessage):
A docstring for this function please.

2017-01-19 06:46 UTC, nvdaes commented
Done in c75c263
Thanks.

El 19/01/2017 a las 0:53, Michael Curran escribió:
> *@michaelDCurran* requested changes on this pull request.
>
> ------------------------------------------------------------------------
>
> In source/addonHandler.py
> <https://github.com/nvaccess/nvda/pull/6747#pullrequestreview-17355490>:
>
>> @@ -437,6 +437,9 @@ def initTranslation():
>  	finally:
>  		del callerFrame # Avoid reference problems with frames (per python docs)
>
> +def getTranslatedMessage(translatedMessage):
>
> A docstring for this function please.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nvaccess/nvda/pull/6747#pullrequestreview-17355490>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/APE65G8aIu8MiB61h8QmTQscgPjbLyCjks5rTqXmgaJpZM4LldIC>.
>

2017-01-19 06:57 UTC, jcsteh commented
@MichaelDCurran and I discussed this. One concern we have is that there's no guarantee that a message won't get removed from or changed in core. If that happens, the message in your add-on will be mysteriously untranslated in some versions of NVDA but not others, which could become difficult to manage.

Are there exammples other than "Error" that might be more compelling? Otherwise, I don't think we should go ahead with this for the above reason.

2017-01-19 07:00 UTC, nvdaes commented
Other messages can be on, off, etc.
But your concern is true.
Other concern is that messages can be translated in some languages and 
not in others.
Perhaps this should be add-ons territory.
This have advantages and drowbacks.


El 19/01/2017 a las 7:57, James Teh escribió:
> @MichaelDCurran <https://github.com/MichaelDCurran> and I discussed
> this. One concern we have is that there's no guarantee that a message
> won't get removed from or changed in core. If that happens, the message
> in your add-on will be mysteriously untranslated in some versions of
> NVDA but not others, which could become difficult to manage.
>
> Are there exammples other than "Error" that might be more compelling?
> Otherwise, I don't think we should go ahead with this for the above reason.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nvaccess/nvda/pull/6747#issuecomment-273696649>, or
> mute the thread
> <https://github.com/notifications/unsubscribe-auth/APE65NIqUi3tThfSis135YoL8oUFBI75ks5rTwlkgaJpZM4LldIC>.
>

2017-02-02 00:41 UTC, jcsteh commented
Are you happy to close this for now given the above reasoning? Happy to reconsider if there's a really compelling use case, but it seems like a lot of the messages we're talking about here are quite small anyway and are relatively low effort to translate.

2017-02-02 05:12 UTC, nvdaes commented
I think you can close this: Your reasoning is good for me.
Anyway, I prefer that translators don't translate messages contained in 
NVDA's core when possible, also for consistency.
For instance in an add-on named placeMarkers, which extends the Find 
dialog in browse mode.
But I agree in your reasoning and for me you can close this.
Thanks.

El 02/02/2017 a las 1:41, James Teh escribió:
> Are you happy to close this for now given the above reasoning? Happy to
> reconsider if there's a really compelling use case, but it seems like a
> lot of the messages we're talking about here are quite small anyway and
> are relatively low effort to translate.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nvaccess/nvda/pull/6747#issuecomment-276830532>, or
> mute the thread
> <https://github.com/notifications/unsubscribe-auth/APE65I3VCR0GFsnzSa8juUifAIpFkcZAks5rYSYlgaJpZM4LldIC>.
>

2017-02-06 06:55 UTC, jcsteh commented
Closing as per https://github.com/nvaccess/nvda/pull/6747#issuecomment-273696649. We can reopen this if there's a more compelling case in future. Despite this decision, we do appreciate your work. Thanks.

2017-02-06 06:55 UTC, closed without merging