Add "No message timeout" braille setting
nvaccess/nvda pull request #6777
Opened 2017-01-21 16:50 UTC by dkager

In #6669 we discussed two corner cases for the braille message timeout:
1. To completely disable messages.
2. To show messages indefinitely.

In the end I decided to leave the original behavior alone: a message timeout of 0 disables messages altogether.
There is now an extra checkbox "No message timeout" to show messages indefinitely. It seemed most logical to add this checkbox after the edit field. Of course, enabling the checkbox disables the edit field.
This approach avoids having to add a config profile upgrade step and won't be confusing to users who currently have the timeout set to 0.

2017-04-25 04:08 UTC, feerrenrut requested changes
Thanks, overall this looks really good. What happens when the there is a message currently being displayed "indefinitely" and the setting is changed to a timeout?

2017-04-25 04:08 UTC, feerrenrut commented on source/gui/settingsDialogs.py
> +		if self.noMessageTimeoutCheckBox.GetValue():
This causes an exception, since `self.noMessageTimeoutCheckBox` is not created until line 1575

2017-04-25 14:00 UTC, dkager commented
@feerrenrut Pushed some new stuff.

2017-04-26 10:11 UTC, feerrenrut commented
I have had a look at this, the alignment of the controls looks good. Could you please talk about what kind of testing you have done on this?

2017-04-26 10:21 UTC, dkager commented
> Could you please talk about what kind of testing you have done on this?

Tested this with one display (since the code isn't driver-specific).
This was in early February, but from what I recall I used something like NVDA+t to have a quick message appear, then:
- Left it alone and verified that it stayed on the display.
- Focused another GUI element to make sure the message was cleared immediately.
- Used braille display keys to read the message and ensured it stayed on the display.
- Unselected the checkbox to make sure the message cleared (it does, because saving that setting causes the GUI to update which clears the message).

Also tested this with an actual use case, reading messages in Skype without having to rush.

2017-04-27 09:21 UTC, feerrenrut approved these changes

2017-05-30 09:48 UTC, merged