Display model: Try to provide the correct background color for transparent text drawing (issue #6467)
nvaccess/nvda pull request #6844
Opened 2017-02-04 16:18 UTC by mwcampbell

As described in issue #6467, the NVDA display model doesn't provide the correct background color for text that is drawn in transparent mode. A complete solution for this problem is difficult, but a good enough fix for some instances of the problem is to get the previous color at the origin (X, Y) coordinates before calling the original `TextOut` or `ExtTextOut` function. Note that this implementation only applies to the `TextOut` and `ExtTextOut` functions, since other cases such as `PolyTextOut` are more difficult.

THe motivating use case, and the only one I've tested, is the Dragon NaturallySpeaking vocabulary editor. In that editor's list view, without this fix, the highlighted line is reported as being white on white. With this fix, it's correctly reported as white on aqua blue.

2017-02-05 00:17 UTC, michaelDCurran requested changes
A part from documenting the new argument in the docstring above the function, this looks good to me.

2017-02-05 00:17 UTC, michaelDCurran commented on nvdaHelper/remote/gdiHooks.cpp
>    */
Please document prevColor in the comment above the function.

2017-02-05 00:19 UTC, derekriemer commented on nvdaHelper/remote/gdiHooks.cpp
> +void ExtTextOutHelper(displayModel_t* model, HDC hdc, int x, int y, const RECT* lprc,UINT fuOptions,UINT textAlign, BOOL stripHotkeyIndicator, const wchar_t* lpString, const int codePage, const int*
Mind putting documentation on the color parameter, like done above?

2017-02-05 00:42 UTC, derekriemer reviewed
Mind updating copyright info 
Copyright 2006-2010 NVDA contributers.
to 
Copyright 2006-2017 NV Access Limited, (you)

2017-02-05 00:42 UTC, derekriemer commented on nvdaHelper/remote/gdiHooks.cpp
> +void ExtTextOutHelper(displayModel_t* model, HDC hdc, int x, int y, const RECT* lprc,UINT fuOptions,UINT textAlign, BOOL stripHotkeyIndicator, const wchar_t* lpString, const int codePage, const int*
While you're here, if you get a moment, mind putting a space between the comma and u after lprc,UINT

2017-02-05 00:42 UTC, derekriemer commented on nvdaHelper/remote/gdiHooks.cpp
>    */
Please put an @param if possible.

2017-02-05 00:42 UTC, derekriemer commented on nvdaHelper/remote/gdiHooks.cpp
> +void ExtTextOutHelper(displayModel_t* model, HDC hdc, int x, int y, const RECT* lprc,UINT fuOptions,UINT textAlign, BOOL stripHotkeyIndicator, const char* lpString, const int codePage, const int* lpd
Mind putting the space here again? You didn't introduce this, but might as well clean it up while here.

2017-02-05 15:53 UTC, mwcampbell commented
I made the documentation change that @MichaelDCurran requested. I'm not sure if the copyright notice should be updated as @derekriemer requested, since other source files don't include contributors' names in the copyright notice.

2017-02-05 23:05 UTC, michaelDCurran commented
In most of the NVDA source, we've been moving to a joint copyright 
statement between NV Access Limited and external contributors e.g.

Copyright (C) 2006-2017 NV Access Limited, Mat Campbell


Granted though it seems we seem to be only doing this for our Python 
files and forgetting all the c++. :)


So, you are welcome to change it or not as you please.

2017-02-07 02:36 UTC, michaelDCurran approved these changes

2017-03-14 22:09 UTC, merged

2017-06-07 05:06 UTC, jcsteh commented
Unfortunately, this needs to be backed out due to serious performance regressions experienced in certain apps. See #7251.

It's possible that using BitBlt and GetDIBits might be more performant, though this is just a guess. We did see some performance problems in the past with GetPixel (see 18b3933), though that could just have been due to multiple calls.