translate excel sheet name reporting message
nvaccess/nvda pull request #6866
Opened 2017-02-09 17:15 UTC by feerrenrut

fixes #6848

2017-02-09 23:51 UTC, michaelDCurran requested changes

2017-02-09 23:51 UTC, michaelDCurran commented on source/NVDAObjects/window/excel.py
> +		return _(u"Sheet {0}, {1}").format(sheet, rowAndColumn)
You need a translator comment above this explaining what the string is.
E.g. 
```
# Translators: blah blah blah
```

2017-02-10 11:33 UTC, feerrenrut commented on source/NVDAObjects/window/excel.py
> +		return _(u"Sheet {0}, {1}").format(sheet, rowAndColumn)
oops of course I do. Not sure how I forgot that.

2017-02-12 23:15 UTC, michaelDCurran approved these changes

2017-03-14 06:26 UTC, merged