Fixes to reportCurrentLine's spelling functionality
nvaccess/nvda pull request #6894
Opened 2017-02-17 13:06 UTC by tspivey

* Fixes #6726 by using speech.spellTextInfo.
* Fixes #6893 by matching what review_currentLine does with useCharacterDescriptions.

2017-02-22 06:58 UTC, jcsteh requested changes
In addition to the inline comment:

Please update the User Guide for this command to reflect the triple press action.

Thanks!

2017-02-22 06:58 UTC, jcsteh commented on source/globalCommands.py
> +﻿# -*- coding: UTF-8 -*-
Your editor seems to have added a Unicode BOM here. That will break gettext (which is silly, but such is life). Please remove it.

2017-03-20 00:15 UTC, jcsteh approved these changes

2017-04-05 02:37 UTC, merged

2017-07-17 04:04 UTC, feerrenrut commented
Also fixed: #4551