added chart support for word and powerpoint in addition to excel
nvaccess/nvda pull request #7046
Opened 2017-04-03 06:47 UTC by dineshkaushal

This fixes partially #1541. 
This is a common implementation for office charts that works for Excel, word, and powerpoint.
Earlier implementation for excel chart #1987 worked on event based model, but this one provides keyboard navigation which is much more structured. 
excelChart.py is redundent, but I have still not removed it just in case users want event based implementation back.

2017-04-12 03:41 UTC, michaelDCurran commented
It looks like you have not committed _msOfficeChart.py

2017-04-12 03:42 UTC, michaelDCurran requested changes

2017-04-12 03:42 UTC, michaelDCurran commented on source/NVDAObjects/window/winword.py
> +		chartNVDAObj = WordChart(windowHandle=self.document.rootNVDAObject.windowHandle, wordApplicationObject=self.rangeObj.Document.Application, wordShapeObject=self.collectionItem)
I think this needs to be changed to OfficeChart

2017-04-17 23:39 UTC, dineshkaushal commented
Oops, I missed that file. I have also made another correction. This is regarding using formula to get text directly from the cell for xValues when formula property has series formula

2017-04-18 04:47 UTC, michaelDCurran requested changes

2017-04-18 04:47 UTC, michaelDCurran commented on source/NVDAObjects/window/_msOfficeChart.py
> +#Copyright (C) 2014-2015 James Teh, Michael Curren, NV Access Limited
Fix the copyright statement.  Something like Copyright (C) 2014-2017 NV access Limited, Dinesh Kaushal

2017-04-18 04:47 UTC, michaelDCurran commented on source/NVDAObjects/window/_msOfficeChart.py
> +    # Translators: A type of chart in Microsoft Excel.
Change this and all other comments to mention Microsoft Office, not Microsoft Excel specifically.

2017-04-18 04:47 UTC, michaelDCurran commented on source/NVDAObjects/window/_msOfficeChart.py
> +	def getChartSegment(self):
Is this different to OfficeChartElementBase.getChartSegment? if not then this can be removed.

2017-04-18 04:47 UTC, michaelDCurran commented on source/NVDAObjects/window/_msOfficeChart.py
> +class OfficeChartElement(OfficeChartElementList):
I find the name of this particular class confusing. I'm assuming that this element represents all the stuff that is not a series? perhaps call it OfficeChartElementMeta or something? saying OfficeChartElement makes it look too generic.

2017-06-08 05:10 UTC, michaelDCurran commented
@dineshkaushal: a reminder to change the copyright line in _msOfficeChart.py to remove Michael Curran and James Teh (NV Access Limited) is enough. Also, can you merge master and fix conflicts again please. thanks :) Otherwise this is looking good.
Finally, it would be great if you could provide some sample office files with charts in them if you have not already. e.g. a Powerpoint slide deck, Excel workbook, and Word doc, all with charts. This will help me do some final testing.

2017-12-12 20:24 UTC, michaelDCurran approved these changes

2017-12-13 23:26 UTC, Adriani90 commented
Dear all,

before creating a new issue, I wanted to ask, is it possible to report if a diagram is concav or convex by signal tones? So when I navigate from value a to b and the diagram is concav, the sound should go higher and NVDA should just read the actual value. We could take the signal tones from reporting progress bars for example.

2017-12-14 07:41 UTC, dineshkaushal commented
Thanks Mick,

2017-12-14 07:43 UTC, dineshkaushal commented
In the current implementation we are not reporting the information with tones, but that could be a good thing to try!

2018-01-01 23:41 UTC, merged