ALlow quick navigation for spelling and grammatical errors in MS Word using w and shift+w
nvaccess/nvda pull request #7258
Opened 2017-06-06 05:23 UTC by leonardder

### Link to issue number:
#6942

### Summary of the issue:
Currently, there is no effective way in MS Word to list and navigate spelling errors. There is the alt+f7 key stroke, but activating that automatically pop ups the context menu to change the particular error.

### Description of how this pull request fixes the issue:
This pull request adds a new quick navigation command for errors, bound to the letter w. Consult the discussion in #6942 for more details about how we made this decision.

The error command navigates to spelling and grammatical errors in Word. Also, errors have been added to the Word elements list and can be listed there.

### Testing performed:
Purposely made some grammar and spelling mistakes. I was able to jump through those with w (forwards) and shift+w (backwards). Also, I was able to list them in the elements list. Spelling errors which are part of grammatical errors are shown at a sub level in the elements list tree, as expected.

### Known issues with pull request:
Spelling and grammar checking while typing should have been enabled in Word for this feature to work correctly. Spelling error checking is enabled by default, for grammar, this doesn't seem to be the case. should we document this?

### Change log entry:
* New features
	+ In Microsoft Word, it is now possible to navigate to spelling and grammatical errors using quick navigation (w and shift+w) (#6942)

2017-06-07 04:18 UTC, michaelDCurran requested changes
Code looks good. But:
In the past we added support for reportting gramma errors in Microsoft Word. But from the change log:
Removed reporting of grammar errors, as this causes crashes in Microsoft Word. (#5954, #5877) 
It is possible that this usage out-of-process will not cause a crash, but this must be tested on Windows XP to make sure.
The safest option would be for now to only  support spelling errors.

2017-06-07 04:18 UTC, michaelDCurran commented on source/NVDAObjects/window/winword.py
> +			return GraphicWinWordCollectionQuicknavIterator(nodeType,self,direction,rangeObj,includeCurrent).iterate()
Why did this line change?

2017-06-07 04:18 UTC, michaelDCurran commented on source/NVDAObjects/window/winword.py
> +			return TableWinWordCollectionQuicknavIterator(nodeType,self,direction,rangeObj,includeCurrent).iterate()
Why did this line change?

2017-06-07 05:50 UTC, leonardder commented
> It is possible that this usage out-of-process will not cause a crash, but this must be tested on Windows XP to make sure.

What has Windows Xp to do with this, if I may ask? I don't see any references to XP in #5954

> The safest option would be for now to only support spelling errors.

I agree, however that would mean we'd never test this properly.

How about an incubation in Next and asking people (e.g. on NVDA devel) to specifically test this feature with multiple versions of Office? We'd make sure that this has been tested somewhat more thoroughly before merging. A try build might be a viable alternative.

Of course I'd be happy to remove support for grammatical errors if desired, but it feels a bit like choosing de path of least resistance here, which doesn't necessarily have to be bad of course.

2017-06-07 05:52 UTC, leonardder commented on source/NVDAObjects/window/winword.py
> +			return TableWinWordCollectionQuicknavIterator(nodeType,self,direction,rangeObj,includeCurrent).iterate()
This was, probably by accident, indented with two tabs and one space, I removed the space to bring this in line with other return statements here.

2017-06-07 05:53 UTC, leonardder commented on source/NVDAObjects/window/winword.py
> +			return GraphicWinWordCollectionQuicknavIterator(nodeType,self,direction,rangeObj,includeCurrent).iterate()
See above, another extra space here which shouldn't exist

2017-06-07 06:25 UTC, michaelDCurran commented
True, the comment about XP is irrelevant, I remembered the issue 
incorrectly.
However, as we do not report grammar errors currently, adding quicknav 
to them would be confusing.
Therefore, until we have the time to properly research a new and safe 
way to implement grammar errors, we only want to take the PR if the 
grammar support is removed.

2017-06-07 06:34 UTC, leonardder commented
No problem.

Do you want me to remove the 
GrammaticalErrorWinWordCollectionQuicknavIterator and 
WordDocumentGrammaticalErrorQuickNavItem classes altogether, or should I 
add a comment to them saying that they are currently not in use?

2017-06-07 06:38 UTC, michaelDCurran commented
Please remove it all for now. Obviously branches can be kept around if 
we want to use the code at a later date.

2017-06-07 06:49 UTC, leonardder commented
@MichaelDCurran: re https://github.com/nvaccess/nvda/pull/7258/commits/07309725f6b4be97c6320965a72c9f467b7f802c

I think this approach is a bit nicer than the one I used before with super, but if you disagree, I'm happy to roll this back.

2017-06-08 03:20 UTC, michaelDCurran approved these changes

2017-06-23 05:12 UTC, merged

2017-10-09 16:20 UTC, dkager commented
The "errors" radio button in the elements list in Word is missing a capital "E". Seems worth fixing for cosmetic reasons, but not worth a PR.