Always report object states in same order, regardless whether positive or negative
nvaccess/nvda pull request #7279
Opened 2017-06-13 08:15 UTC by leonardder

### Link to issue number:
fixes #7076

### Summary of the issue:
When reporting object states to the user in speech or braille, the positive object states are processed before the negative states. This creates the following problem as reported by @dkager:

> Can be reproduced in many lists with checkable items in Windows 10, e.g. the disk clean-up utility.
> Unchecked items are brailled as  Foo sel ( ) chk , checked ones as  Foo (x) sel chk .

### Description of how this pull request fixes the issue:
1. For both speech and braille, de positive and negative states sets are merged and numerically sorted. When looping through this merged, sorted list of states, we check whether the state is positive or negative and the appropriate label will be spoken or brailled.
2. The negative state for controlTypes.STATE_DROPTARGET (Done dragging) is moved from speech.py to controlTypes.py

### Testing performed:
In disk clean up, the selected state is now always spoken before the checked state, regardless whether positive or negative

### Known issues with pull request:
1. As I noted in https://github.com/nvaccess/nvda/issues/7076#issuecomment-307720826, This changes the order of presentation people are accustomed to in some situations. E.g. invalid entry required will change to required invalid entry. Do we care about this, or do we want to have a certain order of priority as @JCSTeh suggested in https://github.com/nvaccess/nvda/issues/7076#issuecomment-305350599?
2. We probably want to test whether the "done dragging" case still works correctly.

2017-06-22 14:48 UTC, dkager reviewed
Looks good to me. Quite a bit of code duplicaion, but I guess the states for braille and speech are not guaranteed to be identical?

2017-06-22 14:48 UTC, dkager commented on source/braille.py
> +				# 			and, if no braille abbreviations are provided, we fall back to the defined state labels in ControlTypes,
Slightly more spaces than necessary. :)

2017-06-23 16:50 UTC, leonardder commented on source/speech.py
> -	if negativeStates is not None or (reason != controlTypes.REASON_CHANGE and states is not None):
@JCSTeh: Could you clarify this line? Was there a particular reason why if negativeStates is not None wasn't enough?

2017-06-23 16:56 UTC, leonardder commented on source/controlTypes.py
> +def processAndLabelStates(role, states, reason, positiveStates, negativeStates, positiveStateLabelDict={}, negativeStateLabelDict={}):
I'm happy to provide a Doc-string for this, but processPositiveStates and processNegativeStates don't have a doc string yet. May be the initial author of these functions can provide some explanation (e.g. about why we both have states and positiveStates parameters for processPositiveStates)? We can add doc strings for these in this pr as well.

2017-06-29 06:02 UTC, jcsteh commented on source/speech.py
> -	if negativeStates is not None or (reason != controlTypes.REASON_CHANGE and states is not None):
> Could you clarify this line? Was there a particular reason why if negativeStates is not None wasn't enough?

The `negativeStates` argument is only provided for `REASON_CHANGE`. It specifies states that have just changed from positive to negative. However, for other reasons (e.g. `REASON_FOCUS`), we still want to report certain states if they aren't present; e.g. "not checked".

2017-06-29 06:06 UTC, jcsteh commented on source/controlTypes.py
> +def processAndLabelStates(role, states, reason, positiveStates, negativeStates, positiveStateLabelDict={}, negativeStateLabelDict={}):
> why we both have states and positiveStates parameters for processPositiveStates

`states` contains the current states for the object. For REASON_CHANGE, `positiveStates` contains only those states that just got added. In other words, `positiveStates` contains only the states we want to possibly be reported at this time, but we might need the "unfiltered" states for the object, so we provide `states` as well.

2017-06-29 13:02 UTC, leonardder commented
@JCSTeh: Apart from doc strings, I think this is ready for review.

2017-06-29 13:04 UTC, leonardder commented on source/speech.py
> -	if negativeStates is not None or (reason != controlTypes.REASON_CHANGE and states is not None):
Thanks. In the new code, it seems this check is no longer necessary as I provide empty sets as default

2017-09-08 09:32 UTC, leonardder commented
This now contains doc strings as well. @Dkager: Would you like to review them? Your grammar is better than mine. :)

2017-09-20 10:54 UTC, dkager requested changes
Looks pretty good.

2017-09-20 10:54 UTC, dkager commented on source/braille.py
> +		textList.extend(controlTypes.processAndLabelStates(role, states, controlTypes.REASON_FOCUS, states,None,positiveStateLabels,negativeStateLabels))
Inconsistent use of space after comma. Maybe pull this function out into two lines to improve readability?

2017-09-20 10:54 UTC, dkager commented on source/controlTypes.py
> +	# This is only reported for objects which support accessible drag and drop.
I think "that support" is the correct form here.

2017-09-20 10:54 UTC, dkager commented on source/controlTypes.py
> +	For example, if C{STATE_CHECKED} is among the returned states, it means that the processed object is checked.
Trivial I guess, but "in the returned states" is a bit closer to what you'd actually write in a program to check this.

2017-09-20 10:54 UTC, dkager commented on source/controlTypes.py
> +	@param states: Usually the raw states for an object to process.
This implies there are exceptions. What are they?

2017-09-20 10:54 UTC, dkager commented on source/controlTypes.py
> +	@param reason: The reason to process the states for (e.g. C{REASON_FOCUS}.
I think "for" should be removed.

2017-09-20 10:54 UTC, dkager commented on source/controlTypes.py
> +	For example, if C{STATE_CHECKED} is among the returned states, it means that the processed object is not checked.
Same stuff as above.

2017-09-20 10:54 UTC, dkager commented on source/controlTypes.py
> +def processAndLabelStates(role, states, reason, positiveStates, negativeStates, positiveStateLabelDict={}, negativeStateLabelDict={}):
In another PR @jcsteh cautioned against using empty dicts as default function parameters. I wonder if that applies here.

2017-09-20 10:54 UTC, dkager commented on source/controlTypes.py
> +	@param states: Usually the raw states for an object to process.
Same stuff as above.

2017-09-20 10:54 UTC, dkager commented on source/controlTypes.py
> +			# Translators: Indicates that a particular state on an object is negated.
"of an object"

2017-10-12 19:05 UTC, leonardder commented
@dkager: Could you review my most recent commits?

2017-10-13 10:52 UTC, dkager approved these changes

2017-12-03 11:13 UTC, dkager commented
As far as small changes bringing big joy go, this is still one of my favorites.

2017-12-12 04:54 UTC, michaelDCurran approved these changes

2018-01-01 23:49 UTC, merged