Include application and dialog elements en audio and video tags for embedded object navigation in browse mode
nvaccess/nvda pull request #7290
Opened 2017-06-15 08:13 UTC by leonardder

### Link to issue number:
fixes #7239

### Summary of the issue:
Embedded objects based on the html object tag are getting more rare these days, while we see increasing occurrence of applications, dialogs and audio and video tags inside web pages.

### Description of how this pull request fixes the issue:
This adds applications and dialogs as well as audio/video tags for Internet Explorer, Firefox and Chrome. For Edge, I was unable to cover audio/video tags (see below)

### Testing performed:
I tried navigating http://www.mediaelementjs.com/ with o using all the browsers above. I also created a test html document with alertdialog, dialog and application roles, which also navigated fine.

### Known issues with pull request:
In Edge, audio and video tags are regarded to as embedded object. Technically, they have the group UIA control type. In NVDAObjects.uia.edge.EdgeTextInfo._getControlFieldForObject, groupings are made to report as embedded object in certain situations, but I have not yet found a reliable way to throw the required information to do this reliably in a UIA Multi Property Condition.

### Change log entry:
* Changes
    + In browse mode, the quick navigation command for embedded objects (o and shift+o) now includes audio and video elements as well as elements with the aria roles application and dialog (#7239

2017-06-22 14:38 UTC, dkager requested changes

2017-06-22 14:38 UTC, dkager commented on user_docs/en/userGuide.t2t
> +Pages can include rich content using technologies such as Adobe Flash, Oracle Java and HTMl5, as well as applications and dialogs.
Slight typo in 'HTMl5'.

2017-06-22 14:38 UTC, dkager commented on user_docs/en/userGuide.t2t
> +to interact with these objects, you can press enter on them.
Missing capital at the beginning of the sentence.

2017-07-12 11:20 UTC, leonardder commented
@dkager: I assume you are ok with the current state of this branch?

2017-07-12 11:22 UTC, dkager approved these changes

2017-07-26 06:43 UTC, michaelDCurran approved these changes

2017-09-05 00:26 UTC, merged