Support the HTML5 required attribute in MSHTML documents
nvaccess/nvda pull request #7321
Opened 2017-06-24 13:39 UTC by leonardder

### Link to issue number:
As far as I know, this pr has no dedicated issue for itself. This pr is based on findings in https://github.com/nvaccess/nvda/issues/7320#issuecomment-310827282

### Summary of the issue:
NVDA does not report the required state of a html element when the HTML5 required attribute is used for this.

### Description of how this pull request fixes the issue:
Added support for required in de NVDAHelper MSHTML vbuf backend and associated python code.

### Testing performed:
For required

```
<input id="name" required type="text" />
```

For not required

```
<input id="name" type="text" />
```

Note that required="false" will still result in required state being added, but this is no bug according to [the spec](https://www.w3schools.com/tags/att_input_required.asp). I've seen the same behaviour in Firefox.

### Change log entry:
* New features
    + In MSHTML documents, the HTML5 required attribute is now supported to indicate the required state of a form field

2017-06-28 03:54 UTC, michaelDCurran commented
This looks good so far, but can you please also support this in focus mode. See aria-required in ```NVDAObjects\IAccessible\MSHTML.py```

2017-06-28 05:48 UTC, leonardder commented
Hmm, good point. However, it seems this is going to be more difficult than I thought

```
<input type="text" required="required" name="cheese" />
```

```
>>> nav.HTMLNode.getAttribute('type')
u'text'
>>> nav.HTMLNode.getAttribute('name')
u'cheese'
>>> type(nav.HTMLNode.getAttribute('required'))
<type 'NoneType'>
```

It seems the node doesn't expose the required attribute correctly.

2017-06-28 05:58 UTC, leonardder commented
A, it turns out that I can use HTMLNode.hasAttribute('required')

2017-06-28 06:54 UTC, leonardder commented
@michaelDCurran: this is now working.

I added a __contains__ method to the HTMLAttribCache to support stuff like 'required' in self.HTMLAttributes. I decided to give it a separate cache, as I didn't want to change the behaviour of __getitem__. This nieuw _contains__ method fixes a bug where 'attribute' in HTMLAttributes resulted in a freeze of NVDA.

2017-07-05 05:37 UTC, michaelDCurran requested changes

2017-07-05 05:37 UTC, michaelDCurran commented on source/NVDAObjects/IAccessible/MSHTML.py
> +		self.containsCache={}
This can be a set rather than a dictionary

2017-07-05 05:37 UTC, michaelDCurran commented on source/NVDAObjects/IAccessible/MSHTML.py
> +			return self.containsCache[item]
Then change this to  return item in self.containsCache

2017-07-05 05:37 UTC, michaelDCurran commented on source/NVDAObjects/IAccessible/MSHTML.py
> +		value = self[item]
I would perhaps  only check item in self.containsCache, then item in self.cache, and if none of them then node.hasattribute(item) and add the answer to containsCache.  hasattribute should work for any value that getattribute would work for.

2017-07-05 05:38 UTC, michaelDCurran commented
Make sure to test on several versions of Internet Explorer. At very least what ever Internet Explorer comes with Windows 7.

2017-07-05 06:04 UTC, leonardder commented on source/NVDAObjects/IAccessible/MSHTML.py
> +		self.containsCache={}
Mm, not sure whether we're on the same track here. Changing this to a set means that we lose track of the attributes for which hasAttribute has returned False in the past, so in other words, False evaluations won't get cached. We either need a dictionary for this, or have two sets for hasAttribute True and hasAttribute False. Could it be that you overlooked this, or is it your intention not to cache the Falses?

2017-07-05 06:05 UTC, leonardder commented on source/NVDAObjects/IAccessible/MSHTML.py
> +			return self.containsCache[item]
If we do this, the block below that actually runs hasAttribute never gets executed.

2017-07-05 06:09 UTC, leonardder commented
This is a good point. I hope I have a proper vm around for this.

2017-07-18 06:06 UTC, leonardder commented
@michaelDCurran: Would you be able to explain why you belief containsCache should be a set rather than a dictionary? See https://github.com/nvaccess/nvda/pull/7321#discussion_r125560509

If you agree with containsCache being a dictionary anyway, this is ready for another review.

2017-07-19 01:35 UTC, michaelDCurran approved these changes

2017-07-19 01:35 UTC, michaelDCurran commented
This looks good to me. Ignore the set/dictionary comment.

2017-07-19 01:37 UTC, michaelDCurran commented
@leonardder  If you are finnished with this I'll incubate it?

2017-07-19 04:08 UTC, leonardder commented
[**@michaelDCurran**](https://github.com/michaelDCurran) commented on [19 jul. 2017 03:37 CEST](https://github.com/nvaccess/nvda/pull/7321#issuecomment-316246838 "2017-07-19T01:37:04Z - Replied by Github Reply Comments"):
> @leonardder  If you are finnished with this I'll incubate it?

Yes, go ahead. Thanks a lot!

2017-09-05 00:22 UTC, merged