Pressing Enter to close Start menu in Windows 10 no longer results in NVDA announcing search field text. re #7370.
nvaccess/nvda pull request #7375
Opened 2017-07-11 03:20 UTC by josephsl

Resolves the following:

* #7370: In Windows 10's start menu, pressing Enter to close the menu after entering search term results in NVDA announcing search field text.
Suggested what's new entry:

section: bug fixes

In start menu in Windows 10, pressing Enter to close the start menu after a search no longer causes NVDA to announce search text.

Thanks.

2017-07-11 03:29 UTC, derekriemer reviewed
Questions

2017-07-11 03:29 UTC, derekriemer commented on source/NVDAObjects/UIA/__init__.py
> +		self.announceNewLineText = self.appModule.appName != "searchui"
Would creating a new overlay just for this be better?

2017-07-11 06:16 UTC, michaelDCurran requested changes
I agree with Derek. Either make this into its own overlay class in searchUI, or perhaps even just place this variable on the SearchField class no matter if it is searchUI or not. For now at least, this class is only used for single-line edit fields where  speaking on enter makes no sense. Obviously I do acknowledge that in the future this may change.

2017-07-11 06:41 UTC, josephsl commented
Hi, when I set announceNewlineText inside SearchField class, it returns True even though I said False, yet the app module method works. Modification on the way.

 

From: Michael Curran [mailto:notifications@github.com] 
Sent: Monday, July 10, 2017 11:16 PM
To: nvaccess/nvda <nvda@noreply.github.com>
Cc: Joseph Lee <joseph.lee22590@gmail.com>; Author <author@noreply.github.com>
Subject: Re: [nvaccess/nvda] Pressing Enter to close Start menu in Windows 10 no longer results in NVDA announcing search field text. re #7370. (#7375)

 

@michaelDCurran requested changes on this pull request.

I agree with Derek. Either make this into its own overlay class in searchUI, or perhaps even just place this variable on the SearchField class no matter if it is searchUI or not. For now at least, this class is only used for single-line edit fields where speaking on enter makes no sense. Obviously I do acknowledge that in the future this may change.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub <https://github.com/nvaccess/nvda/pull/7375#pullrequestreview-49101882> , or mute the thread <https://github.com/notifications/unsubscribe-auth/AHgLkGp82D7_yBa5NijKxufZ5tppoiuKks5sMxM0gaJpZM4OTrW3> .

2017-07-12 07:30 UTC, michaelDCurran approved these changes

2017-07-25 23:42 UTC, merged