UIA/ToastWin10/build 15063 and later: before announcing toasts, consult last toast message in case a repeat event was fired. re #7128
nvaccess/nvda pull request #7376
Opened 2017-07-11 04:06 UTC by josephsl

Resolves the following:

* #7128: NVDA repeats toast messages if UWP's were used for a while. Noted by @MichaelDCurran as caused by possible issue with UIA Core in build 15063 and later. The issue is specific to Creators Update and later.
Suggested what's new entry:

Section: bug fixes

In Windows 10 Creators Update, NVDA will no longer announce toasts multiple times.

Thanks.

2017-07-11 04:08 UTC, josephsl commented
Hi,

This pull request was tested on Windows 10 builds 10586, 14393, 15063 and 16232 and passes the test (tests involved plugging a USB flash drive and seeing if NVDA repeats auto-play messages).

Thanks.

2017-07-11 06:11 UTC, michaelDCurran requested changes
I would prefer to store the time and the UIAElement's runtimeID, rather than the name. Only allow the event if the runtimeIDs do not match or the time is greater than a second. These duplicate windowOpen events happen  extremely fast, but just not fast enough to catch duplicates in one core cycle. We still want to allow duplicate events that are far away from each other as it is reasonable to think that Windows may show duplicate notifications deliberately, which the user should know about.

2017-07-11 07:43 UTC, josephsl commented
Hi, at least in build 16232, toasts have the same runtime ID, so both conditions must be inverted (leave the event if ID’s match and timestamp is less than a second). Modification on its way. Thanks.

 

From: Michael Curran [mailto:notifications@github.com] 
Sent: Monday, July 10, 2017 11:11 PM
To: nvaccess/nvda <nvda@noreply.github.com>
Cc: Joseph Lee <joseph.lee22590@gmail.com>; Author <author@noreply.github.com>
Subject: Re: [nvaccess/nvda] UIA/ToastWin10/build 15063 and later: before announcing toasts, consult last toast message in case a repeat event was fired. re #7128 (#7376)

 

@michaelDCurran requested changes on this pull request.

I would prefer to store the time and the UIAElement's runtimeID, rather than the name. Only allow the event if the runtimeIDs do not match or the time is greater than a second. These duplicate windowOpen events happen extremely fast, but just not fast enough to catch duplicates in one core cycle. We still want to allow duplicate events that are far away from each other as it is reasonable to think that Windows may show duplicate notifications deliberately, which the user should know about.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub <https://github.com/nvaccess/nvda/pull/7376#pullrequestreview-49101362> , or mute the thread <https://github.com/notifications/unsubscribe-auth/AHgLkAkustZHMLojRXfaMN-JLMnHGxrLks5sMxILgaJpZM4OTs8J> .

2017-07-12 07:23 UTC, michaelDCurran requested changes

2017-07-12 07:23 UTC, michaelDCurran commented on source/NVDAObjects/UIA/__init__.py
> +			if toastRuntimeID == self._lastToastRuntimeID and toastTimestamt-self._lastToastTimestamp < 1.0:
Typo: toastTimestamt -> toastTimestamp

2017-07-12 07:43 UTC, michaelDCurran approved these changes

2017-07-25 23:34 UTC, merged