FF/Chrome/IE browseMode quicknav includes rich text widgets (contentEditable) in edit and formField commands
nvaccess/nvda pull request #7461
Opened 2017-07-31 20:12 UTC by michaelDCurran

### Link to issue number:
Fixes #5534

## Summary of the issue:
Rich text editors are becoming more prevalent on the web. Users expect that they can jump to these fields with NVDA quicknav commands they already know, such as e (edit) and f (formField).
These rich text editors are usually implemented either by a div with contentEditable="true" or sometimes an iframe with an embedded document  set to design mode.
 
### Description of how this pull request fixes the issue:
This PR makes it possible to jump to these rich text widgets  with quick navigation in Firefox, Chrome and Internet Explorer.
In simple terms, quick navigation needs to locate the next element that is contentEditable, but whos parent is not contentEditable, as we do not wish to locate all descendants of the editable container.
To enable matching in this way, virtualBuffer searching attributes can now be prefixed with "parent::" which tells the buffer to check the parent node for that particular attribute, rather than the node it is actually looking at in the search. Which now means it is possible to construct a search that checks for contentEditable on a node, but a lack of contentEditable on its parent.
The quicknav search rules for Gecko and mshtml were updated to make use of this new parent prefix, so that they can locate top-most contentEditable nodes.

## Testing performed:
Tested in Firefox, Chrome and IE [testcases.zip](https://github.com/nvaccess/nvda/files/1188711/testcases.zip): 
* content_editable.html: made sure that both e and f found the editable section.
* designMode.html: made sure that both e and f found the editable document.
* formFields.html: made sure that e and f found all the edit fields, including the read-only one.

### Known issues with pull request:
This is not supported in Edge due to contentEditables not getting their own text pattern.

### Change log entry:
What's new:
* In Firefox, Chrome and Internet Explorer, quick navigation to edit fields and form fields now includes editable rich text content (I.e. contentEditable). (#5534)

2017-08-01 07:22 UTC, feerrenrut requested changes

2017-08-01 07:22 UTC, feerrenrut commented on source/virtualBuffers/MSHTML.py
> +				{"IAccessible::role":[oleacc.ROLE_SYSTEM_TEXT],"IAccessible::state_%s"%oleacc.STATE_SYSTEM_FOCUSABLE:[1]},
As discussed I found this a little confusing to read. Specifically that `STATE_SYTEM_FOCUSABLE` belongs  to the format string, and is the key to the value `[1]`. You could consider doing `"IAccessible::state_{}".format(oleacc.STATE_SYSTEM_FOCUSABLE) : [1]` instead.

2017-08-01 07:22 UTC, feerrenrut commented on source/virtualBuffers/MSHTML.py
> +				{"IAccessible::role":[oleacc.ROLE_SYSTEM_TEXT],"IAccessible::state_%s"%oleacc.STATE_SYSTEM_FOCUSABLE:[1]},
Since `"IAccessible::state_%s"%oleacc.STATE_SYSTEM_FOCUSABLE` is evaluated twice, could it instead be stored in a named variable?

2017-08-01 11:42 UTC, michaelDCurran commented
I have done all the requested changes for storage.cpp.


However, I am reluctant to make the changes to the Python attribute 
searching dictionaries, although I do agree in principle with them. We 
have written those rules in that specific coding style for many years, 
and I wouldn't want to change it only in one or two places. In the long 
term I would be happy to consider a better coding style which we could 
use for all of the rules.

2017-08-02 06:10 UTC, feerrenrut approved these changes

2017-08-11 15:19 UTC, derekriemer commented
Might we give an example editor, I.E. in wordpress in the whats new?

2017-08-29 06:48 UTC, merged