Fix cursor routing for the MDV Lilli display driver
nvaccess/nvda pull request #7472
Opened 2017-08-03 14:58 UTC by leonardder

### Link to issue number:
Fixes #7469 

### Summary of the issue:
For MDV Lilli displays, using a cursor routing key moves the cursor one position ahead of the actual cell it should be positioned.

### Description of how this pull request fixes the issue:
The routing indexes started at 1, but they should be zero based. Subtracted an additional 1 in index calculation. Also, converted some decimal values to hexadecimal values to improve readability

### Testing performed:
@dreinn commented tested this, see https://github.com/nvaccess/nvda/issues/7469#issuecomment-319910224

2017-08-09 10:27 UTC, dkager requested changes

2017-08-09 10:27 UTC, dkager commented on source/brailleDisplayDrivers/lilli.py
> +			if (key <= 0x40) or ((key >= 0x101) and (key <= 0x128)):
You don't need parentheses around the comparisons.

Also, the second half could be written more compactly:
`0x101 <= key <= 0x128`
I find that a bit more readable. Also, this means you can remove all parentheses.

There is trailing whitespace here.

2017-08-09 10:27 UTC, dkager commented on source/brailleDisplayDrivers/lilli.py
> +			if (key >= 0x101) and (key <= 0x128):
All three comments from above apply here as well.

2017-08-09 10:27 UTC, dkager commented on source/brailleDisplayDrivers/lilli.py
> +				inputCore.manager.executeGesture(InputGesture(LILLI_KEYS[65],key-0x101))
I would replace 65 by a constant, e.g. `LILLI_ROUTING`.

2017-08-09 10:27 UTC, dkager commented on source/brailleDisplayDrivers/lilli.py
> +			elif (key <= 0x40):
Parentheses. Yes, being very picky. :)

2017-08-17 15:32 UTC, leonardder commented
@dkager: Are you willing to do these changes?

2017-08-21 14:42 UTC, dkager approved these changes

2017-08-21 21:57 UTC, michaelDCurran approved these changes

2017-09-05 00:16 UTC, merged