Add the ability to automatically tether to focus or review
nvaccess/nvda pull request #7489
Opened 2017-08-11 13:45 UTC by leonardder

### Link to issue number:
Fixes #2385

### Summary of the issue:
Currently, using the review cursor requires one to explicitly tether to review and back. See also https://github.com/nvaccess/nvda/issues/2385#issue-116030751

### Description of how this pull request fixes the issue:
This adds the ability to the GUI to enable auto tethering. If set, NVDA will automatically tether to review for review cursor changes, and tethers back to focus when changing the focus or caret.

The following implementation is used, based on the proposal in https://github.com/nvaccess/nvda/issues/2385#issuecomment-312564697

1. Ad a new boolean option to the config spec, autoTether
2. Replace the getter and setter for braille.BrailleHandler.tether with getTether and setTether methods. This is because setTether needs an additional keyword argument to determine whether it was an automatic or manual tether action. Of course, keep the old tether auto property for backwards compatibility, but deprecate it
3. Always show ui.reviewMessage in braille when auto tethering is on
4. Tether to review for several scripts in globalCommands, namely:

	* reviewMode_next
	* reviewMode_previous
	* review_currentLine
	* review_currentWord
	* review_currentCharacter

5. Add a new shouldAutoTether keyword argument to BrailleHandler.handleGainFocus, handleCaretMove and handleReviewMove. This argument should default to True, and can be set to False in places in the code base where this is explicitly required. Of course, shouldAutoTether should be ignored if the auto tethering option is disabled globally.

After some discussion with @dkager, we decided that using the several previous/next scripts to do auto tethering is ugly. Thus, to keep things in sync nicely, auto tethering is done by handleReviewMove instead. This has the following implications:

A. handleReviewMove should not auto tether when the move is caused due to the review cursor following the focus or the caret. Since most of the review following focus is done using api.setNavigatorObject with the isFocus parameter set to True, api.setNavigatorObject should somehow communicate this to handleReviewMove. However, setNavigatorObject doesn't execute handleReviewMove itself, but executes the becomeNavigatorObject event, which executes handleReviewMove. The isFocus parameter gets lost in this process. This is fixed by creating a caching variable, eventHandler.lastReviewMoveDueToFollowing. This new variable is also set properly by api.setReviewPosition based on a new parameter isCaret. At least for setNavigatorObject, I'd rather pass this info as an event parameter, but that means we break backwards compatibility.
B. There have been some edge cases that needed to be changed in setting the navigatorObject. For example, in the explorer appmodule on the SuggestionListItem class, the navigator object is set for event_UIA_elementSelected. This call of setNavigatorObject now has the extra isFocus parameter set to True.

### Testing performed:
Various internal testing, but this needs to be tested more broadly. I'd like to request an initial review first, though.

### Known issues with pull request:
None I'm currently aware of, except for the implications as noted above.

2017-10-13 19:29 UTC, dkager requested changes
Assuming it actually works (haven't tested this myself) I think it looks quite good. Just one or two small points.

2017-10-13 19:29 UTC, dkager commented on source/NVDAObjects/__init__.py
> +		braille.handler.handleReviewMove(shouldAutoTether=not eventHandler.lastReviewMoveDueToFollowing)
This variable name isn't very clear if you don't have the surrounding context of this PR. Maybe choose another name?

2017-10-13 19:29 UTC, dkager commented on source/api.py
> +def setReviewPosition(reviewPosition,clearNavigatorObject=True, isCaret=False):
Comma police. :) Also, the docstring needs updating.

2017-10-13 19:29 UTC, dkager commented on source/api.py
> +	eventHandler.lastReviewMoveDueToFollowing = isCaret
Can we be sure that this line and the one below it are only ever executed in one thread at a time?

2017-10-13 19:29 UTC, dkager commented on source/braille.py
> +import eventHandler
Not too happy with another circular dependency, but I know we discussed this before and all solutions we came up with were hacky.

2017-10-13 19:29 UTC, dkager commented on source/braille.py
> +		#if reviewPos.obj == api.getFocusObject() and config.conf["reviewCursor"]["followFocus"]:
I would say just remove these two lines.

2017-10-13 19:29 UTC, dkager commented on source/config/configSpec.py
> +	autoTether= boolean(default=false)
Space.

2017-10-14 10:27 UTC, dkager approved these changes

2017-11-23 06:52 UTC, michaelDCurran requested changes
I feel that auto tethering is really what we would want  the majority NVDA user to be using, Therefore we should set autoTether to True by default. 
But something is bothering me a little with this particular option as a checkbox. What happens if it is on, but tetherTo is set to review?
I assume autoTether in this case pretty much has no meaning?

2017-11-23 06:52 UTC, michaelDCurran commented on source/eventHandler.py
> +			return extensionPoints.callWithSupportedKwargs(func, *args, **self.kwargs)
Please log a clear message here  (perhaps warning) so that we catch these issues pretty quick and fix them.

2017-11-23 06:52 UTC, michaelDCurran commented on source/sayAllHandler.py
> +						api.setReviewPosition(updater, isCaret=True)
Should perhaps isCaret be only true if cursor==CURSOR_CARET?

2017-11-23 06:52 UTC, michaelDCurran commented on source/appModules/lockapp.py
> +			api.setReviewPosition(self._oldReviewPos, isCaret=False)
As isCaret is False by default,   explicitly  specifying isCaret=False here is not needed, and is perhaps a little confusing. I'd prefer that anywhere in the codebase that  isCaret is only ever specified if it needs to be set to true. Mirroring that of isFocus for setNavigatorObject.

2017-11-23 13:50 UTC, leonardder commented
> But something is bothering me a little with this particular option as a checkbox. What happens if it is on, but tetherTo is set to review?
> I assume autoTether in this case pretty much has no meaning?

It still has a meaning. When tethering is set to review and auto tethering is on, the initial tethering mode is review until auto tethering triggers focus. However, I agree that this is confusing.

@dkager, @bramd, @jcsteh: thoughts? I'd suggest having three options, focus, review and auto. I recall from one of our braille discussions that @jcsteh preferred separate options for tethering mode focus/review and auto tethering on/off, because it allows you to quickly override the decision made by auto tethering. I belief that's the reason I implemented it as it is now. However, after thought about it a little more, I think i agree with @Mick that it is a bit confusing from an UX perspective.

2017-11-23 22:00 UTC, michaelDCurran commented
As you have explained that autoTether works both ways, I'm now more 
comfortable with the checkbox.
However, I would suggest that:
1. If the checkbox is checked, perhaps we could disable the combobox as 
it has no meaning.
2. It would be nice to perhaps have the tether script toggle between 
focus, review and auto... either that or have a separate script binding, 
though I think this is a bit overkill.

2017-11-23 22:06 UTC, josephsl commented
Hi, I’m thinking a single script will be sufficient, similar to what we have for progress bar output and indentation tones. Thanks.

 

From: Michael Curran [mailto:notifications@github.com] 
Sent: Thursday, November 23, 2017 2:00 PM
To: nvaccess/nvda <nvda@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: Re: [nvaccess/nvda] Add the ability to automatically tether to focus or review (#7489)

 

As you have explained that autoTether works both ways, I'm now more 
comfortable with the checkbox.
However, I would suggest that:
1. If the checkbox is checked, perhaps we could disable the combobox as 
it has no meaning.
2. It would be nice to perhaps have the tether script toggle between 
focus, review and auto... either that or have a separate script binding, 
though I think this is a bit overkill.



—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub <https://github.com/nvaccess/nvda/pull/7489#issuecomment-346702495> , or mute the thread <https://github.com/notifications/unsubscribe-auth/AHgLkO_nXXARaKf3FBKeBtgZXXjJtH-Yks5s5erugaJpZM4O0rNh> .

2017-11-23 22:20 UTC, jcsteh commented
Another way of handling this is to:
1. Have three options in the GUI (focus, review and auto).
2. When auto is enabled, the tether command should just temporarily
override the decision chosen by auto (which, based on your comments, is
what happens now).
I'm not sure it makes sense to have auto as an option for the command,
though. Auto never really stops being the case; the command just
temporarily overrides it until the next switch. So, if auto switched to
focus and you overrode it to review, it's still really in auto mode, so
having an auto option is misleading.
Perhaps we need to somehow indicate that the tether is temporary in auto
mode. "Braille temporarily tethered to review" would do this, but it's
ridiculously verbose.

2017-11-23 22:31 UTC, michaelDCurran commented
I wonder if there really is much of a use case at all for temporarily 
switching with the tether command while auto is enabled?
In the case of say reviewing a dos console window while typing, and 
review follows caret is off, this becomes impossible because the caret 
will still keep forcing tether to focus... I think.

2017-11-23 22:40 UTC, jcsteh commented
Urg. You're right, but that's definitely a use case we need to think about,
since I'd say it's actually fairly common. If temporarily tethered to
review, I wonder if it makes sense to only tether to focus if the focus
moves, not the caret.

2017-11-24 01:36 UTC, michaelDCurran commented
Having spoken to Jamie directly, we both agree that the GUI should just 
be a combo box of auto, focus and review.
We discussed the config also reflecting this in that it is a key with 
one of 3 values, though this would involve an upgrade step to force 
previous configs from focus to auto. I think for this reason, and due to 
the following number 2 point, it should remain as two separate config 
keys as it is right now.
There are a few options for the tether command script:
1. Have it toggle between auto, focus and review. This is my personal 
choice.
2. Leave it as is. I.e. toggles between focus and review When auto is 
off, and temporarily between focus and review when auto is on, allowing 
braille scrolling to control both review or caret, but it to snap back 
when something else occurs.

In future we may want to think about something specific for review in 
consoles, as these seem to be a special case where the user is forced to 
use the review cursor because the caret is unable to move due to 
scrolling etc.

Other peoples' thoughts?

2017-11-24 10:50 UTC, leonardder commented
[**@michaelDCurran**](https://github.com/michaelDCurran) commented on [24 nov. 2017 02:36 CET](https://github.com/nvaccess/nvda/pull/7489#issuecomment-346719661 "2017-11-24T01:36:13Z - Replied by Github Reply Comments"):
> There are a few options for the tether command script:
> 1. Have it toggle between auto, focus and review. This is my personal 
> choice.

I agree.

> 2. Leave it as is. I.e. toggles between focus and review When auto is 
> off, and temporarily between focus and review when auto is on, allowing 
> braille scrolling to control both review or caret, but it to snap back 
> when something else occurs.

This will probably be confusing for the end user.

I'm intending to set the tetherTo config parameter to focus when the autoTether config parameter is True. We can also use the last state of tetherTo before enabling autoTether, but that will result into undefined behavior.

2017-11-24 23:24 UTC, bramd commented
Hmm, I haven't tested this yet, but making a toggle with three options seems the clearest interface to me as well.

Some other thoughts:

Given the use case that you want to read some text in a document or in a console and type at another location in the document or console, it's also needed to disable following of the caret by the review cursor. I know it is a lot of magic, but somehow having a toggle between auto/focus/review, it would make sense to turn review mode in a real review mode without being disturbed by caret/focus changes.

2017-12-04 05:15 UTC, michaelDCurran approved these changes

2017-12-04 05:37 UTC, michaelDCurran commented
This will need an update to the user guide for the tether setting. But looks good other than that.

2017-12-05 03:44 UTC, michaelDCurran approved these changes

2017-12-05 03:52 UTC, michaelDCurran commented
I think this PR broke a unit test:
 ERROR: test_endOfLine (tests.unit.test_cursorManager.TestMove)

2017-12-05 06:17 UTC, leonardder commented
Ugh, I must have slept when I overlooked this failure.

2017-12-07 05:05 UTC, leonardder commented
I just pushed another commit that fixes #5237, tethering from review back to focus failed in browse mode. Also, the braille_toFocus script is now working much more reliably in auto tethering cases.

@derekriemer reported issues with tethering on Gitter, but I can't reproduce them. Note that when using object review, it might look like you are tethered to focus even though you are tethered to review. You can check this by setting focus context representation to "always fill display" which gives you a more clear view of difference between focus and review tethering.

2017-12-08 07:52 UTC, Andre9642 commented
I have a strange behavior since this function is implemented. To reproduce it, the simplest is:
1. open 2 instances of cmd;
2. Enable "braille tether to review" in one of these windows by pressing NVDA+CTRL+t. At this point, we can read the content of the terminal (i.e. result of commands) with backward and forward buttons of braille display.
3. Now, go to the second instance. At this stage, we can't read the contents of this terminal. We are forced to reswitch in review mode By pressing 3 times on CTRL+NVDA+t to find the expected behavior.

2017-12-08 11:44 UTC, leonardder commented
That's a very nice catch there. This, among other similar bugs, should have been fixed in the branch now, and will be visible as soon as review and incubation has taken place.

2017-12-11 01:28 UTC, michaelDCurran approved these changes

2017-12-12 16:21 UTC, Andre9642 commented
I am running on next-14726,ebbd6f4c.
I still have bugs with scrolling in some cases (e.g. in Microsoft Word).

2017-12-12 18:21 UTC, leonardder commented
[**@Andre9642**](https://github.com/Andre9642) commented on [12 dec. 2017 17:21 CET](https://github.com/nvaccess/nvda/pull/7489#issuecomment-351102979 "2017-12-12T16:21:31Z - Replied by Github Reply Comments"):
> I am running on next-14726,ebbd6f4c.
> I still have bugs with scrolling in some cases (e.g. in Microsoft Word).

Could you please provide steps to reproduce?

2017-12-14 08:27 UTC, leonardder commented
@Andre9642 Could you please elaborate on this and provide steps to reproduce?

2017-12-14 11:31 UTC, Andre9642 commented
Sorry for the delayed response. 
> Could you please provide steps to reproduce?
Unfortunately, it's complicated to reproduce and list all cases because sometimes I do not understand the steps that caused the problem...
However, I spotted a case where it happens every time.
1/ Open Word, and choose "blank document".
2/ Type the next content (it is a simple example):
```
111
222
333
```
3/ Restart NVDA with insert+q (with add-ons disabled preferably). Normally, you should fall back on the document.
4/ Go to the top of document (with Control+home). Now, we can read "111" on the braille display.
5/ Try to scroll forward with your braille display.
Expected behavior: you should move on the next line and the braille display should shows "222".
Actual behavior: NVDA switch to review mode (braille cursor = dot 8), cursor has not moved and the braille display shows "111".

I reproduced this on several machines, Word 2016 and NVDA version next-14726,ebbd6f4c.

2017-12-14 15:32 UTC, leonardder commented
[**@Andre9642**](https://github.com/Andre9642) commented on [14 dec. 2017 12:31 CET](https://github.com/nvaccess/nvda/pull/7489#issuecomment-351685626 "2017-12-14T11:31:20Z - Replied by Github Reply Comments"):
> 1. Open Word, and choose "blank document".
> 2. Type the next content (it is a simple example):
> 
>     ```
>     111
>     222
>     333
>     ```
> 
> 3. Restart NVDA with NVDA+q (with add-ons disabled preferably). Normally, you should fall back on the document.
> 4. Go to the top of document (with Control+home). Now, we can read "111" on the braille display.
> 5. Try to scroll forward with your braille display.
> 
> * Expected behavior: you should move on the next line and the braille display should shows "222".
> * Actual behavior: NVDA switch to review mode (braille cursor = dot 8), cursor has not moved and the braille display shows "111".

For me, the result always is as expected. Could you do the following at a python console:
```import config; print config.conf['braille']['tetherTo']```

This parameter is reset to focus when explicitly thetering automatically, however when the tether setting has not been touched after an update and it was initially set to review, auto tethering is on and the config parameter is set to review, which should actually not be the case.
@michaeldcurran/@jcsteh: I think I yet prefer a config upgrade step for this as per the reason above. Furthermore, we can also convert tethering to an option based option in the config spec instead of a string based option. Thoughts? ANother reason is that using both a string based value and the autoTether boolean together feels quite ugly to me.

2017-12-14 16:23 UTC, Andre9642 commented
```
>>> import config; print config.conf['braille']['tetherTo']
focus
```

I have another problem, I'm wondering if it's related: when I start/restart NVDA in a virtual document  (eg: in Firefox, in a message in Thunderbird...), the browse mode is not enabled automatically. I am forced to leave and return to the virtual content.

2017-12-14 16:26 UTC, leonardder commented
Could you test the latter with NVDA master? also, what dissplay are you using and which commands to scroll?

N.B. Sent on behalf of @BabbageCom

> Op 14 dec. 2017 om 17:23 heeft André-Abush Clause <notifications@github.com> het volgende geschreven:
> 
> >>> import config; print config.conf['braille']['tetherTo']
> focus
> I have another problem, I'm wondering if it's related: when I start/restart NVDA in a virtual document (eg: in Firefox, in a message in Thunderbird...), the browse mode is not enabled automatically. I am forced to leave and return to the virtual content.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-12-14 20:10 UTC, leonardder commented
@Andre9642: Also, just to make sure, do you have any configuration profiles active that might override the tethering setting? I've looked at the code again and, apart from what I mentioned in https://github.com/nvaccess/nvda/pull/7489#issuecomment-351744721 , I can't yet think of what might cause this behavior. The fact that I can't reproduce this makes it even more difficult to deal with it properly.

2017-12-14 20:45 UTC, Andre9642 commented
@leonardder I've just tested with the last master version. And... I have the same issue. I'm sorry, so this isn't related to this new feature!

2017-12-15 04:52 UTC, leonardder commented
[**@Andre9642**](https://github.com/Andre9642) commented on [14 dec. 2017 21:45 CET](https://github.com/nvaccess/nvda/pull/7489#issuecomment-351830688 "2017-12-14T20:45:13Z - Replied by Github Reply Comments"):
> @leonardder I've just tested with the last master version. And... I have the same issue. I'm sorry, so this isn't related to this new feature!

Just to make sure, which issue are you now referring to? The browse mode issue or the scrolling issue in Word?

2018-01-01 23:55 UTC, michaelDCurran commented
@leonardder: Are you happy for this to be merged to master and closed? Also, can someone provide a what's new entry in the description?

2018-01-02 07:42 UTC, leonardder commented
@Andre9642: Could you please answer my last question? Are the issues you were experiencing related to auto tethering or not?
@DerekRiemer: What do you think of this? It seems you have found some instability, even though I wasn't able to reproduce.

2018-01-04 00:55 UTC, Andre9642 commented
> Are the issues you were experiencing related to auto tethering or not?

No, I have the same problem with NVDA 2017.4 concerning scrolling issue in word.
Regarding the browse mode issue, I have some instability (very) occasionally and randomly (= hard to reproduce). I don't know if it's related to auto tethering. :/ When this happens, the Braille display no longer follows if I move with arrow keys. I couldn't get this issue with NVDA 2017.4.

2018-01-05 06:27 UTC, leonardder commented
[**@Andre9642**](https://github.com/Andre9642) commented on [4 jan. 2018 01:55 CET](https://github.com/nvaccess/nvda/pull/7489#issuecomment-355170555 "2018-01-04T00:55:38Z - Replied by Github Reply Comments"):
> > Are the issues you were experiencing related to auto tethering or not?
> 
> After all, no. I have the same problem with NVDA 2017.4 concerning the scrolling issue in Word.
> The scroll forward issue is present especially when I scroll a lot of times in a complex document and, sometimes, when the cursor is located on the first character of the document. Tested with addons disabled. If I have more precise details, I'll create an issue. 
> 
> Regarding the browse mode issue, I have some instability (very) occasionally and randomly (= hard to reproduce). I don't know if it's related to auto tethering. :/ When this happens, the Braille display no longer follows if I move with arrow keys. I couldn't get this issue with NVDA 2017.4.

Thanks for the clarification. May be you could answer the following questions?

1. Do you, by any chance, know whether switching between browse mode and focus mode could cause this?
2. What is shown on the display when it does not follow?
3. Does the non-following start after interacting with the review cursor or object navigation, or just randomly?

2018-01-09 14:49 UTC, leonardder commented
[**@michaelDCurran**](https://github.com/michaelDCurran) commented on [2 jan. 2018 00:55 CET](https://github.com/nvaccess/nvda/pull/7489#issuecomment-354685818 "2018-01-01T23:55:34Z - Replied by Github Reply Comments"):
> @leonardder: Are you happy for this to be merged to master and closed? Also, can someone provide a what's new entry in the description?

I just added a what's new entry.

2018-01-15 20:34 UTC, merged