Ensure IAccessible2 remains available in Firefox after restarting NVDA on Windows 10 Creaters update, register ISimpleDOM proxy to allow math in Google Chrome without Firefox installed, and Allow the user to get back a virtualBuffer when restarting NVDA with a Firefox document in focus
nvaccess/nvda pull request #7535
Opened 2017-08-29 06:13 UTC by michaelDCurran

### Link to issue number:
Fixes #7269 
Fixes #7308
Partial fix for #5758

### Summary of the issue:

Originally some users were complaining that when they restarted NVDA while Firefox was in focus, browse mode was no longer available. Alt+tabbing away and back again would also not correct the situation.
Specifically issue #5758 covers this original case. Technically, when NVDA restarts and Firefox is already in focus, There is no focus event for Firefox and therefore NVDA's in-proces injection code is not triggered for the Firefox process. Therefore we have no binding handle  for creating a virtualBuffer. However, as VirtualBuffer.prepare has already set shouldPrepare to false by the time it reaches this error, it is impossible for the virtualBuffer to ever work again, even if a binding handle does become available by shifting focus away and back again.

There was a second issue (#7269) that started appearing in Windows insider builds  approaching the Windows 10 Creaters Update.  In this situation, restarting NVDA and then trying to use Firefox would result in NVDA not being able to ever QueryService to IAccessibleApplication to check the Gecko version number, and therefore NVDA would never provide browse mode. Restarting NVDA would not help. All that could be done was to close and re-open Firefox. There seemed to be some kind of COM proxy stub issue where if a request was made to marshal an interface that had just been deregistered with CoRevokeClassObject, then once that interface was again successfully registered, marshalling would be for ever still broken in the server process.

Finally, Issue #7308 talks about not being able to read / navigate math content in Google chrome. The main reason for this is that Google Chrome does not register ISimpleDOM interfaces which are used between chrome and NVDA to fetch the math content. What confuses the situation is that if the user did have Firefox installed, math content would work in Google chrome as the interfaces were available via Firefox's registration.
 
### Description of how this pull request fixes the issue:
#5758 is partially fixed by simply returning early in VirtaulBuffer.prepare if there is no binding handle yet. This means that on future focus changes, the VirtaulBuffer will again try to prepare. Once there is a binding handle, this will succeeed. In short, restarting NVDA while Firefox is in focus will still result in no browse mode at first, but the user can easily shift focus away and back again to get Browse mode.

#7269 and #7308 together are fixed by a substantial re-write to NVDAHelperRemote's COM proxy registration code.
Firstly, the code has been abstracted so that it is easy to register other COM proxies other than just IAccessible2. Now both IAccessible2 and ISimpleDOM are both built, and registered in all processes we inject into if COM is initialized. The abstraction also allows us to fetch all the interfaces from the dll directly, rather than having to hardcode them.
The COM proxy dlls now contain assembly manifests which aide in us getting COM to load the class objects itself, while manging the life time of the dll, saving us from having to free it on NVDA shutdown, which in 99% of cases never worked.
And, most importantly the specific problem introduced by Windows 10 creaters update where CoRevokeClassObject would break future registration was fixed by pointing the interfaces to the standard marshaller with CoRegisterPSClsid before their class object was revoked. The standard marshaller does not support the interfaces of course, but at least they still point to a valid class object. Microsoft really needs a CoUnregisterPSClsid.
 
### Testing performed:
Multiple restarts of NVDA both using control+alt+n, and the NVDA+q quit dialog (choosing restart), on both Windows 10 Creaters update and Windows 7 64 bit.

### Known issues with pull request:
Issue #5758 is not fully fixed as the user must still alt+tab away and back again to get Browse mode in Firefox when restarting NVDA with Firefox in focus.

### Change log entry:
Bug fixes:
* On windows 10 Creaters Update, NVDA can again access Firefox after a restart of NVDA. (#7269)
* When restarting NVDA with Mozilla Firefox in focus, browse mode  will again be available, though you may need to alt+tab away and back again. (#5758)
* It is now possible to access math content in Google Chrome on a system with out Mozilla Firefox installed. (#7308)

2017-08-29 06:37 UTC, leonardder commented
I assume this doesn't contribute anything to a fix of #7311?

2017-08-29 07:23 UTC, michaelDCurran commented
This won't directly affect the problems in that issue. But all of these 
issues are similar in that COM marshalling is affected. We are planning 
to include some kind of utility in NVDA to fix issues such as #7311 and 
perhaps having it run in the NVDA installer also.

2017-08-29 15:15 UTC, feerrenrut requested changes

2017-08-29 15:15 UTC, feerrenrut commented on nvdaHelper/remote/COMProxyRegistration.cpp
> +		++tempInfoPtr;
Is there some docs you can point to on ProxyFileInfo? I'm a little nervous about this code. So `pProxyInfo` points to the start of a memory block containing `ProxyFileInfo*`. This memory block is null terminated. I cant find any documentation on `Dll_GetProxyDllInfo` How do you know the above is the case?

2017-08-29 15:15 UTC, feerrenrut commented on nvdaHelper/remote/COMProxyRegistration.cpp
> +		LOG_ERROR(L"Error unregistering class object from "<<(reg->dllPath)<<L", code "<<res);
For this (and the other error case on line 156) should the function exit early, why is it ok to continue to `delete reg` and `return true`

2017-08-29 15:15 UTC, feerrenrut commented on nvdaHelper/remote/COMProxyRegistration.h
> +Copyright 2006-2010 NVDA contributers.
See copyright headers https://github.com/nvaccess/nvda/wiki/Copyright-headers

2017-08-30 02:06 UTC, feerrenrut approved these changes

2017-08-30 06:53 UTC, leonardder commented
This seems to cause incidental errors, which I've seen in at least Thunderbird and Spotify when focussing the application

```
ERROR - RPC process 12692 (thunderbird.exe) (08:50:15.348):
Thread 12696, build\x86\remote\COMProxyRegistration.cpp, registerCOMProxy, 69:
GetProxyDllInfo function not found in IAccessible2Proxy.dll

ERROR - RPC process 12692 (thunderbird.exe) (08:50:15.361):
Thread 12696, build\x86\remote\ia2Support.cpp, installIA2Support, 59:
Error registering IAccessible2 proxy
```

2017-08-30 06:56 UTC, michaelDCurran commented
Was this a source or binary copy? If binary, where exactly did you get it?

That error is pretty much suggesting that a different copy of 
IAccessible2Proxy.dll was loaded instead of the one that actually came 
with that version of NVDA.

Very very strange.

At least, does the issue go away if you reboot?

2017-08-30 07:27 UTC, leonardder commented
This was a binary copy, Version next-14364,d19efb8d. Note that I hadn't 
yet rebooted, and I assume a reboot is likely to fix this. I'll report 
back if the problem still persists.

2017-09-04 07:34 UTC, michaelDCurran commented
This PR also fixes #7563,  which was uncovered by other parts of this PR.

2017-09-04 08:57 UTC, feerrenrut approved these changes

2017-09-19 00:29 UTC, merged