Allow the Read status bar command copy its contents on third press
nvaccess/nvda pull request #7577
Opened 2017-09-07 23:04 UTC by ehollig

### Link to issue number:
Fixes #1785

### Summary of the issue:
When pressing the command say window title thrice, the text is copied to the clipboard. This is currently not possible with the report status bar command.

### Description of how this pull request fixes the issue:
This allows for the report status bar command to copy the information to the clipboard, similar to say window title.

### Testing performed:
Opened notepad and performed the report status bar command thrice. Pasted the contents of the status bar into the file.

### Known issues with pull request:
No information was spoken when performing the command three times in Internet Explorer 11.

### Change log entry:
None needed.

2017-09-08 03:10 UTC, bhavyashah commented
@ehollig Whoa, are you coding now? Anyways, I would argue that this is
very much a user-facing feature addition and thus should be documented
in the What's New document.

On 9/8/17, Ethan Holliger <notifications@github.com> wrote:
> ### Link to issue number:
> Fixes #1785
>
> ### Summary of the issue:
> When pressing the command say window title thrice, the text is copied to the
> clipboard. This is currently not possible with the report status bar
> command.
>
> ### Description of how this pull request fixes the issue:
> This allows for the report status bar command to copy the information to the
> clipboard, similar to say window title.
>
> ### Testing performed:
> Opened notepad and performed the report status bar command thrice. Pasted
> the contents of the status bar into the file.
>
> ### Known issues with pull request:
> No information was spoken when performing the command three times in
> Internet Explorer 11.
>
> ### Change log entry:
> None needed.
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/nvaccess/nvda/pull/7577
>
> -- Commit Summary --
>
>   * Allow read status bar command to copy contents on third press to
> clipboard
>   * Allow the Read status bar command copy its contents on third press
>
> -- File Changes --
>
>     M source/globalCommands.py (9)
>
> -- Patch Links --
>
> https://github.com/nvaccess/nvda/pull/7577.patch
> https://github.com/nvaccess/nvda/pull/7577.diff
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/pull/7577
>


-- 
Best Regards
Bhavya Shah

Blogger at Hiking Across Horizons: https://bhavyashah125.wordpress.com/

Contacting Me
E-mail Address: bhavya.shah125@gmail.com
Follow me on Twitter @BhavyaShah125 or www.twitter.com/BhavyaShah125
Mobile Number: +91 7506221750

2017-09-08 03:22 UTC, josephsl commented
Hi, as well as recorded in the user guide. CC @feerrenrut

 

From: bhavyashah [mailto:notifications@github.com] 
Sent: Thursday, September 7, 2017 8:10 PM
To: nvaccess/nvda <nvda@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: Re: [nvaccess/nvda] Allow the Read status bar command copy its contents on third press (#7577)

 

@ehollig Whoa, are you coding now? Anyways, I would argue that this is
very much a user-facing feature addition and thus should be documented
in the What's New document.

On 9/8/17, Ethan Holliger <notifications@github.com> wrote:
> ### Link to issue number:
> Fixes #1785
>
> ### Summary of the issue:
> When pressing the command say window title thrice, the text is copied to the
> clipboard. This is currently not possible with the report status bar
> command.
>
> ### Description of how this pull request fixes the issue:
> This allows for the report status bar command to copy the information to the
> clipboard, similar to say window title.
>
> ### Testing performed:
> Opened notepad and performed the report status bar command thrice. Pasted
> the contents of the status bar into the file.
>
> ### Known issues with pull request:
> No information was spoken when performing the command three times in
> Internet Explorer 11.
>
> ### Change log entry:
> None needed.
> You can view, comment on, or merge this pull request online at:
>
> https://github.com/nvaccess/nvda/pull/7577
>
> -- Commit Summary --
>
> * Allow read status bar command to copy contents on third press to
> clipboard
> * Allow the Read status bar command copy its contents on third press
>
> -- File Changes --
>
> M source/globalCommands.py (9)
>
> -- Patch Links --
>
> https://github.com/nvaccess/nvda/pull/7577.patch
> https://github.com/nvaccess/nvda/pull/7577.diff
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/pull/7577
>


-- 
Best Regards
Bhavya Shah

Blogger at Hiking Across Horizons: https://bhavyashah125.wordpress.com/

Contacting Me
E-mail Address: bhavya.shah125@gmail.com
Follow me on Twitter @BhavyaShah125 or www.twitter.com/BhavyaShah125
Mobile Number: +91 7506221750



—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub <https://github.com/nvaccess/nvda/pull/7577#issuecomment-327987356> , or mute the thread <https://github.com/notifications/unsubscribe-auth/AHgLkLSDkT-3VWlmO7ezDFMgvPn5W9sLks5sgLASgaJpZM4PQf0o> .

2017-09-08 04:01 UTC, leonardder commented on source/globalCommands.py
> +﻿# -*- coding: UTF-8 -*-
Somehow, a weird character ended up at the start of this line. Could you have saved the file as UTF-8 with BOM? You might as well add your name to the copyright line in the process.

2017-09-08 04:02 UTC, leonardder commented
Congratulations with your first code contribution!

2017-09-10 08:58 UTC, derekriemer commented
Suggested whats new entry:

- changes:
- it is now possible to press the report status bar command three times to copy the status bar text to the clipboard.

2017-09-10 08:59 UTC, derekriemer commented
Oh, by the way, congrats on your first code contribution!

2017-09-10 09:03 UTC, derekriemer commented
Nice work. Just one thing I found, which are required.

2017-09-10 09:04 UTC, derekriemer requested changes

2017-09-10 09:04 UTC, derekriemer commented on source/globalCommands.py
> +				ui.message(_("%s copied to clipboard")%text)
You need a translators comment above this line. Something like
#Translators: The message presented when the status bar is copied to the clipboard.

2017-09-10 09:04 UTC, derekriemer commented on user_docs/en/userGuide.t2t
> +﻿NVDA NVDA_VERSION User Guide
unintentional line change? maybe crlf?

2017-09-11 05:00 UTC, derekriemer approved these changes
nice fox

2017-09-11 05:01 UTC, derekriemer commented
rar, I'm dumb. 
Nice fix

2017-09-12 07:34 UTC, feerrenrut approved these changes
Looks good @ehollig, thanks for the contribution! Don't worry about it for this PR, we tend to update the `en/changes.t2t` file directly on `master` when we complete the merge. We do squash merges to `master`, and regular merges to `next` during incubation. This can cause merge conflicts in the changes file. That said, its really handy that the change log entry is provided on the PR (there is a section for it in the PR template). Thanks again!

2017-09-14 05:53 UTC, derekriemer commented
@feerrenrut Ethan isn't in contributers.txt, FYR

2017-09-16 15:49 UTC, dan1982code commented
I noticed that the NVDA insert+1 help message for this command talks about copying the title (not status bar) to the clipboard on third press.

2017-09-16 17:04 UTC, josephsl commented
Hi, yep, confirmed.

 

From: dan1982code [mailto:notifications@github.com] 
Sent: Saturday, September 16, 2017 8:50 AM
To: nvaccess/nvda <nvda@noreply.github.com>
Cc: Joseph Lee <joseph.lee22590@gmail.com>; Comment <comment@noreply.github.com>
Subject: Re: [nvaccess/nvda] Allow the Read status bar command to copy its contents on the third keypress (#7577)

 

I noticed that the NVDA insert+1 help message for this command talks about copying the title (not status bar) to the clipboard on third press.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub <https://github.com/nvaccess/nvda/pull/7577#issuecomment-329976601> , or mute the thread <https://github.com/notifications/unsubscribe-auth/AHgLkJxV9FHD_SXVftKSVMOfe-dMBBK4ks5si-4TgaJpZM4PQf0o> .

2017-09-16 22:07 UTC, ehollig commented
Thank you for pointing this out. It has been corrected. CC @@feerrenrut

2017-09-20 02:46 UTC, feerrenrut approved these changes

2017-10-03 05:15 UTC, merged

2017-10-03 15:18 UTC, leonardder commented
The grammar for the changes entry in the what's new is wrong. "it's" should be "its", and I belief it should be either "its content is", or "its contents are". I'm no expert though.

2017-10-03 15:23 UTC, dan1982code commented
Found another typo in the changes: "compaired with installs of previous NVDA versions."

2017-10-03 15:56 UTC, josephsl commented
Hi, I’ll address documentation issues by end of this month once most of the features are introduced. Thanks.

 

From: dan1982code [mailto:notifications@github.com] 
Sent: Tuesday, October 3, 2017 8:23 AM
To: nvaccess/nvda <nvda@noreply.github.com>
Cc: Joseph Lee <joseph.lee22590@gmail.com>; Comment <comment@noreply.github.com>
Subject: Re: [nvaccess/nvda] Allow the Read status bar command to copy its contents on the third keypress (#7577)

 

Found another typo in the changes: "compaired with installs of previous NVDA versions."

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub <https://github.com/nvaccess/nvda/pull/7577#issuecomment-333877453> , or mute the thread <https://github.com/notifications/unsubscribe-auth/AHgLkI7CoPo94D_c_9_FLFzKD_v6SGjTks5solFhgaJpZM4PQf0o> .