Added translator comments to browseMode.py
nvaccess/nvda pull request #7591
Opened 2017-09-12 00:43 UTC by ehollig

### Link to issue number:
Fixes #5822

### Summary of the issue:
There were not translator comments for browse mode or focus mode.

### Description of how this pull request fixes the issue:
As discussed in #1410, all strings should have translator comments.

### Testing performed:

### Known issues with pull request:
None

### Change log entry:
None

2017-09-15 09:11 UTC, derekriemer commented
This should take about a minute to review. Suggested merging strait to master unless others object. No code is changed but comments.

2017-09-16 06:43 UTC, LeonarddeR requested changes
Agree with Derek about the merge to master. It kinda confuses me that, even though there are no translator comments in current master, the check pot test still passes. CC @michaeldcurran

2017-09-16 06:43 UTC, leonardder commented on source/browseMode.py
> +				# Translators: The mode that presents text in a flat representation that can be navigated with the cursor keys like in a text document
Please split this into two lines

2017-09-16 06:43 UTC, leonardder commented on source/browseMode.py
> +			# But there is no container.
Great you split this into two lines, but i'd make the split before the left paren. You can also safely make the B for the start of this line a lower case letter.

2017-09-18 14:47 UTC, ehollig commented
@leonardder, I believe the changes have been made. @feerrenrut this is ready for review

2017-09-19 00:46 UTC, michaelDCurran commented
tests/checkpot.py contains a list of strings which are known not to have translator comments. Now that browse mode and focus mode do, these should be removed from that list in this PR.  The eventual goal is for there to be no blacklisted strings in checkpot.py

2017-09-19 02:02 UTC, ehollig commented
Thank you @michaelDCurran for letting me know about tests/checkpot.py. I have updated this PR acordingly. I however, was not able to locate browse mode in checkpot.py.

2017-09-19 09:49 UTC, feerrenrut requested changes

2017-09-19 09:49 UTC, feerrenrut commented on source/browseMode.py
> +						# (list, table, etc.) but there is no container.
There are extra indents here.

2017-09-19 09:53 UTC, feerrenrut commented
@ehollig I think the reason that "Browse Mode" did not need to be added, is because it is used in several contexts already, and those usages have translator comments.

See `git grep -iF -C 2 '_("Browse Mode")'`

This alludes to a potential problem, while in this case the context for "Browse Mode" is the same. There could be cases where the context for a certain translated string is quite different.  We ideally should confirm that each translated string has its own independent translator comment. It seems that the current tests do not pick this up?

2017-09-27 00:52 UTC, ehollig commented
@leonardder @feerrenrut, is there anything else I need to do with this PR?

2017-10-12 18:44 UTC, LeonarddeR approved these changes

2017-10-16 02:44 UTC, feerrenrut approved these changes

2017-10-16 02:58 UTC, merged