gecko_ia2 vbuf backend: Support IAccessibleHypertext2 to improve performance for Firefox multi-process.
nvaccess/nvda pull request #7719
Opened 2017-11-02 05:39 UTC by jcsteh

### Link to issue number:
None.

### Summary of the issue:
With Firefox multi-process, rendering a virtual buffer for browse mode now makes cross-process calls, since the content document accessibility tree is now in another process. This has a substantial impact on performance. The more cross-process calls we can reduce, the better. This PR introduces a change which fetches all embedded children at once, rather than fetching each in a separate call.

### Description of how this pull request fixes the issue:
IAccessibleHypertext2::hyperlinks allows all embedded objects to be retrieved at once, rather than retrieving them one at a time.

This improves performance for cross-process renders, which is the case for Firefox multi-process.
IAccessibleHypertext is still supported and will be used if the newer interface is not present.

In addition:

1. Don't bother calling hyperlinkIndex, since in Gecko (and Chrome), hyperlinks correspond with embedded object characters.
2. Use a constant for the embedded object character.

### Testing performed:
confirmed that the World War I Wikipedia article renders as expected in:

1. A build of Firefox which supports IAHypertext2. (This is now in Firefox nightly.)
2. A build that does not.
3. Chrome Canary, which does not support IAHypertext2.

Using IAHypertext2 seems to shave up to a second off the render time for the World War I article, though it's difficult to provide concrete numbers because the time seems to be a little variable.

### Known issues with pull request:
None know.

### Change log entry:
In Bug Fixes:

```
- Slight performance improvement when rendering large amounts of content in Mozilla Firefox 58 and later. (#7719)
```

2017-11-03 06:34 UTC, michaelDCurran requested changes
Could you please move the hyperlink getter classes  into common/ia2utils.cpp/h, as we'll want to use them in ia2liveRegions.cpp as well eventually.  Other than that this all looks fine to me.

2017-11-08 06:59 UTC, derekriemer commented on nvdaHelper/common/ia2utils.h
> + * Create an appropriate HyperlinkGetterto retrieve hyperlinks
HyperlinkGetterto > HyperlinkGetter to

2017-11-17 09:44 UTC, MarcoZehe commented
I ran with both try builds for a day or two now, have been using the second one since it became available, and haven't found anything bad, no missing text or links or such.

2017-11-17 15:46 UTC, PratikP1 commented
Confirmed with FF Nightly and the try builds.

2017-11-22 23:59 UTC, michaelDCurran approved these changes

2017-12-08 06:16 UTC, merged