New, native driver for ALVA 6 series displays. The new alva driver re…
nvaccess/nvda pull request #7884
Opened 2018-01-02 11:28 UTC by leonardder

First of all, many thanks to @dkager for his testing and fixes.

### Link to issue number:
Closes #7733.
Fixes #6731

### Summary of the issue:
The current DLL based ALVA driver has the following limitations:

* No support for raw keyboard input that allows utilizing NVDA's input gesture system and braille input framework
* No support for the Optelec Protocol Converter that allows using older displays with this driver

### Description of how this pull request fixes the issue:
This pull requests implements a new native driver for Optelec 6 series (BC640, BC680, 640 comfort and Protocol Converter). In comparison with the old driver, this changes/adds/fixes the following.

* This driver is completely native, and native is good :) since it is thread safe and allows braille display detection in the near future (#1271)
* When the number of cells reported by the display changes (e.g. due to setting a split point), NVDA's internal cell count is updated accordingly.
* When the time of a device is out of sync by more than 5 seconds, the time is synchronized automatically. This comes in quite handy, as ALVA displays always tend to lose their sense of time when the battery is empty.
* Support for raw keyboard input. When disabling HID keyboard input with the t1+spEnter gesture, this will allow a user to input braille using NVDA's own braille input system.

I've looked briefly at the BRLTTY code to support ALVA satelite displays and similar, and from the current code base, it shouldn't be that difficult to incorporate basic support for these displays. Furthermore, as we added support for the protocol converter, this driver is no longer only for the BC6 series. Therefore, we decided to rename the driver from alvaBc6 to Alva. Old BC6 driver users will be automatically moved to ALVA.

### Testing performed:
Tested two ALVA BC640 devices both over USB and Bluetooth.

### Known issues with pull request:
* The protocol converter hasn't yet been tested. CC @Bamze66, @gregjozk . Also, we haven't been able to test a BC680 or 640 comfort yet.
* Raw input is known to be non-functional on firmware 2.4.0 and older, however, NVDA will clearly state that changing HID input is not possible.

### Change log entry:
* New features
	+ Added support for the Optelec protocol converter, a device that allows one to use Braille Voyager and Satelite displays using the ALVA BC6 communication protocol. (#6731)
	+ It is now possible to use braille input with an ALVA 640 Comfort braille display. (#7733)
		- NVDA's braille input functionality can be used with these as well as other BC6 displays with firmware 3.0.0 and above.

### How to contribute
You can download the new driver [here](https://raw.githubusercontent.com/leonardder/nvda/bc6-native/source/brailleDisplayDrivers/alva.py). This link will always be up to date with the most recent source of the driver. Install by downloading the alva.py file and placing it in NVDA's brailleDisplayDrivers directory, found under %appdata\nvda or under userConfig in a portable copy.
Run NVDA and select this Braille display by opening the NVDA menu then selecting Preferences, Braille Settings, then choosing "Optelec ALVA 6 series/protocol converter". Note that the old driver is still available. If your device is not connected, make sure that you first select the "no braille" option and restart NVDA, in order to have the old driver not claim the display for itself.

2018-01-15 21:12 UTC, michaelDCurran approved these changes
Is it possible to force raw input by default for models that support it? Or if not, perhaps the userGuide entry could be re-worded to be more of a warning. Users would probably expect by default that NVDA's braille input features just work. To me the userGuide reads more as if the user simply does not have to worry as its just not relevent.

2018-01-16 05:06 UTC, leonardder commented
> Is it possible to force raw input by default for models that support it? 

I'm very reluctant to do this, as it changes a setting inside the display without the end user knowing that. It's not just an internal toggle for the driver.

> Or if not, perhaps the userGuide entry could be re-worded to be more of a warning. Users would probably expect by default that NVDA's braille input features just work. To me the userGuide reads more as if the user simply does not have to worry as its just not relevent.

That is something I can do for sure.


@@Bamze66, @gregjozk, would you be able to test this driver with the protocol converter before it lands in next?

2018-01-18 21:01 UTC, michaelDCurran requested changes

2018-01-18 21:01 UTC, michaelDCurran commented on user_docs/en/userGuide.t2t
> +When you have paired your device using this utility and NVDA is unable to detect your device, we recomment you to pair your ALVA display the regular way using the Windows Bluetooth settings.
typo: recomment -> recommend

2018-01-23 02:39 UTC, michaelDCurran approved these changes

2018-01-31 21:42 UTC, merged

2018-04-20 04:51 UTC, michaelDCurran commented
Can alvaw32.dll be removed from miscDeps now this is merged? I'm happy to do it, but just checking.

2018-04-20 08:47 UTC, dkager commented
There is even a PR for that.