Fix problems with ALVA protocol converter and time synchronisation
nvaccess/nvda pull request #8051
Opened 2018-03-01 18:34 UTC by leonardder

### Link to issue number:
Closes #6731

### Summary of the issue:
The ALVA protocol converter does not yet work correctly. This is because NVDA requests a feature report for the current display time. The converter returns a time report padded with zeros. Trying to create a datetime.datetime object with zeros raises a ValueError.

### Description of how this pull request fixes the issue:
1. Return early when interpretting a time report that has a year of 0.
2. The request for the display time is now enclosed in a try/except block, failure is handled gracefully.

### Testing performed:
None. @Adriani90 is again kindly asked to perform testing with [this](https://ci.appveyor.com/api/buildjobs/hrb0i89s01acq35l/artifacts/output%2Fnvda_snapshot_try-alvaFix-14899%2Cfd222ab8.exe). @dkager, could you please test this with your BC640?

### Known issues with pull request:
None

### Change log entry:
Changes since RC1

* The ALVA Protocol Converter should now really work as advertised (#8047)

2018-03-01 18:36 UTC, leonardder commented
@dkager @michaeldcurran, as soon as you both approve this, I think this is considered ready to go into a new rc, regardless of what @adriani90 might report. This pr is much more likely to fix the issue he reported in #6731.

2018-03-01 18:52 UTC, michaelDCurran approved these changes

2018-03-01 18:56 UTC, michaelDCurran commented
Another person separately just emailed me about issues connecting to an Alva display in 2018.1rc1 where it worked in 2017.4. I have provided them this try build as well. Though it looked like they have a BC640 (at least the subject line said Alva 640). I'll hold the next rc back until both of these people can successfully use the Alva driver again.

2018-03-01 19:39 UTC, dkager approved these changes
I wonder if setting the time works even though the protocol converter apparently doesn't have the time feature.

2018-03-02 07:34 UTC, leonardder commented
@dkager: Given other experiences I have with setting unsupported 
features (i.e. trying to enable raw braille input on unsupported 
firmware versions), setting the time will most likely be ignored.

2018-03-02 12:40 UTC, michaelDCurran commented
I saw a log from the other person:  they could not load the 'alvaBC6' driver. There was an entry in renamed_drivers, but its case did not match the old driver's name exactly.  Old driver had  a capital C, but the rename entry had a lowercase c. I have pushed a commit to this pr fixing the case. It would be good if someone with an Alva BC640 could run 2017.4, select the old AlvaBC6 driver and save config. Then run this try build and ensure that it gets ampped to alva.

2018-03-02 12:49 UTC, michaelDCurran commented
New try build: https://ci.appveyor.com/api/buildjobs/7h3fylu2n1u5uuae/artifacts/output%2Fnvda_snapshot_try-alvaFixes-14900%2C8f6ece88.exe

2018-03-02 12:56 UTC, leonardder commented
Sorry for the mistake there.

@dkager, would this be possible for you to do?

2018-03-02 13:42 UTC, michaelDCurran commented
Now having solved the renamed_driver problem, this user is getting ValueError: year is out of range on line310 of the alva driver.
@leonardder: obviously we'll have to catch ValueError here as well. But could you please give me a bit of background as to this particular time feature? I.e. what is the problem this is trying to solve? Is the device unusable if the time drifts too far?
I'm just waying up how much we fiddle with this verses removing the time sync support all together. 
Were you ever able to actually test this? I.e. make an Alva drift out of sync?

2018-03-02 14:29 UTC, michaelDCurran commented
Pushed another commit catching ValueError for datetime.datetime. This allows the alva driver to run on that other person's system. I never got to see a log of the successful run, but I'm assuming that its all 0xff or something for timeStr. At least for 2018.1 we should certainly just return early and not try touching anything else.

2018-03-02 15:30 UTC, leonardder commented
I realised the try/except statement I added around the getFeature should 
also contain the call to handleTime. In that case, we can also make sure 
that handling time doesn't break the initialization process. Actually, 
it is not the feature retrieval that fails. We could place the 
try/except around self._handleTime, or include both the feature 
retrievel and handleTime. @michaeldcurran: which one do you prefer?


I've tested time sync and out of sync time for an ALVA bc640, and I did 
not observe any errors like this. The protocol also states that the year 
ought to be between 1900-3000, which is a time range allowed by 
datetime.datetime. The exceptions that are now taking place are thus 
undocumented.

2018-03-03 01:03 UTC, Adriani90 commented
As requested by @Leonardder here and in #6731, I have tested that try build with Voyyager 44. I am glad to report that it works perfectly now. Thank you.

2018-03-03 08:46 UTC, dkager requested changes
One small change, on top of the refactoring @leonardder suggested.

2018-03-03 08:46 UTC, dkager commented on source/brailleDisplayDrivers/alva.py
> +			log.debugWarning("Invalid time/date of Alva display: %r"%timeStr)
Consistency: Alva should be all caps: ALVA.

2018-03-03 08:46 UTC, dkager commented on source/braille.py
> +	"alvaBC6":"alva"
This fix works for me: if I set display to alvaBC6 and then start the try build, the ALVA display is correctly initialized. On master it is not.

2018-03-03 09:56 UTC, michaelDCurran commented
As I really want to get the next rc out, I think I'm going to leave the 
try accept in handleTime as how I currently have it. We can look at 
moving it post 2018.1... but right now  that code path has been tested 
by several people as is, and fixes the immediate issue reported to me.
I'll fix the debugWarning though.

2018-03-03 10:17 UTC, leonardder commented
Sorry Mick, looks like I missed your reply and started fixing things on 
my own after some discussion with @dkager. Feel free to revert what you 
dislike about my proposed fix, though.

2018-03-03 10:22 UTC, leonardder commented on source/brailleDisplayDrivers/alva.py
>  			timeStr = self._dev.getFeature(ALVA_RTC_REPORT)[1:ALVA_RTC_STR_LENGTH+1]
Note that this part actually never caused an issue. Therefore my initial placement of this line in a try/except block was unnecessary

2018-03-03 10:30 UTC, dkager requested changes
Looks pretty good overall.

2018-03-03 10:30 UTC, dkager commented on source/brailleDisplayDrivers/alva.py
> +		if not 1900 <= year <= 3000:
I would really like these as constants.

2018-03-03 16:14 UTC, dkager approved these changes

2018-03-04 22:33 UTC, merged