Updated app module to work properly with total comander 64bit
nvaccess/nvda pull request #8215
Opened 2018-04-30 18:18 UTC by Adriani90

### Link to issue number:
None

### Summary of the issue:
Creating this pull request on behalf of @novalis7747!
In Total commander 64bit, NVDA does not report the same information compared to Total Commander 32bit. It does not announce selections and left and right panels.

### Description of how this pull request fixes the issue:
The app module "totalcmd64.py" links to "totalcmd.py" which is wrong since total commander 64bit has other class names for list views than the 32bit version. Thus, "totalcmd.py" is mostly copied into "totalcmd64.py" with following exceptions:
1. The classname "TMyListBox" changed to "LCLListBox"
2. The counters to determine if the cursor is on the left or right panel changed from "if counter==2:" to "if counter==3:"

### Testing performed:
Yes, with different versions of Total Commander 64bit.

### Known issues with pull request:
None

### Change log entry:
* Changes

2018-04-30 18:49 UTC, LeonarddeR requested changes
Thanks for the contribution. Personally, I"m a bit reluctant to approve this, as this is basically a copy of the totalcmd module (i.e. it duplicates code). I'd rather keep the current totalcmd64.py and see fixes applied to the totalcmd module. note that within an appModule subclass, you can use self.is64BitProcess to distinguish between a 32 and 64 bit process.

2018-04-30 21:41 UTC, Novalis7747 commented
The 32bit version and the 64bitversion have different program names. That’s why we need a totalcmd.py and a totalcmd64.py to fire up the correct appmodule. The module totalcmd.py wont fire up for the 64bit version.

Cheers,
   Ralf

From: Leonard de Ruijter <notifications@github.com>
Sent: Montag, 30. April 2018 20:50
To: nvaccess/nvda <nvda@noreply.github.com>
Cc: Novalis7747 <novalis7747@live.com>; Mention <mention@noreply.github.com>
Subject: Re: [nvaccess/nvda] Updated app module to work properly with total comander 64bit (#8215)


@leonardder requested changes on this pull request.

Thanks for the contribution. Personally, I"m a bit reluctant to approve this, as this is basically a copy of the totalcmd module (i.e. it duplicates code). I'd rather keep the current totalcmd64.py and see fixes applied to the totalcmd module. note that within an appModule subclass, you can use self.is64BitProcess to distinguish between a 32 and 64 bit process.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnvaccess%2Fnvda%2Fpull%2F8215%23pullrequestreview-116394275&data=02%7C01%7C%7Cbf831355074a4e603fe408d5aecb1df0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636607109751014409&sdata=i7bo8wj5xY83uvJ3hsPzBfbwgBm%2Fp6nomyKlVlOPLd0%3D&reserved=0>, or mute the thread<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAffwnGQSiRTMfEUlRRcQLdabnNn4QvQTks5tt1y-gaJpZM4TtAFP&data=02%7C01%7C%7Cbf831355074a4e603fe408d5aecb1df0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636607109751014409&sdata=umwAqpzmIvzZLLzm%2BxZiOlNVvxivMu1aJX3TGKJcjnA%3D&reserved=0>.

2018-05-01 06:40 UTC, leonardder commented
[**@Novalis7747**](https://github.com/Novalis7747) commented on [30 apr. 2018 23:41 CEST](https://github.com/nvaccess/nvda/pull/8215#issuecomment-385537446 "2018-04-30T21:41:02Z - Replied by Github Reply Comments"):
> The 32bit version and the 64bitversion have different program names. That’s why we need a totalcmd.py and a totalcmd64.py to fire up the correct appmodule.

True. In the current situation (i.e. the situation in master), totalcmd64.py basically imports totalcmd.py. I'd like to keep it that way. totalcmd.py can be adapted to cover both the x86 and x64 version, which means much less duplicated code.

2018-05-01 08:30 UTC, leonardder commented
@Novalis7747: I think it will certainly help, now you're on github, if you create a personal fork of the github repository. Having said that, a big thanks to @Adriani90 for his assistance.

I will close this pr in favour of the new one to be created.

2018-05-01 08:30 UTC, closed without merging

2018-05-05 11:04 UTC, Novalis7747 commented
Moin Adriani,

Ich hab das TotalCMD.py jetzt so angepasst, das es gleichermaßen in der 32bit und 64bit Version von Total Commander arbeitet.
Habs getestet unter Win7, Win10 und mit dem TotalCmd 32 und 64bit.
Ich versuche schon seit 2 Tagen einen pull request zu erstellen, aber es gelingt mir nicht. Warum ist das so verdammt kompliziert?
Hab das ganze von gitup zu mir geclont, hab einen commit erstellt mit dem geänderten totalcmd.py und gepushed. Und nun?
Muss ich erst noch ein Studium absolvieren, um jetzt weiter zu kommen, grins.
Kannst du mir weiterhelfen, oder soll ich dir die geänderte totalcmd.py schicken, damit du einen PR erstellst?

Besten Gruß,
   Ralf

From: Adriani90 <notifications@github.com>
Sent: Montag, 30. April 2018 20:26
To: nvaccess/nvda <nvda@noreply.github.com>
Cc: Novalis7747 <novalis7747@live.com>; Mention <mention@noreply.github.com>
Subject: [nvaccess/nvda] Updated app module to work properly with total comander 64bit (#8215)

Link to issue number:

None

Summary of the issue:

Creating this pull request on behalf of @Novalis7747<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNovalis7747&data=02%7C01%7C%7Cb5085a7310824096472208d5aec7c479%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636607095370927042&sdata=su9z2EgV4exE9N%2FZc1gX38NyCaMyQULWfFdOb%2F6DfMs%3D&reserved=0>!
In Total commander 64bit, NVDA does not report the same information compared to Total Commander 32bit. It does not announce selections and left and right panels.

Description of how this pull request fixes the issue:

The app module "totalcmd64.py" links to "totalcmd.py" which is wrong since total commander 64bit has other class names for list views than the 32bit version. Thus, "totalcmd.py" is mostly copied into "totalcmd64.py" with following exceptions:

  1.  The classname "TMyListBox" changed to "LCLListBox"
  2.  The counters to determine if the cursor is on the left or right panel changed from "if counter==2:" to "if counter==3:"

Testing performed:

Yes, with different versions of Total Commander 64bit.

Known issues with pull request:

None

Change log entry:

  *   Changes

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/nvaccess/nvda/pull/8215<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnvaccess%2Fnvda%2Fpull%2F8215&data=02%7C01%7C%7Cb5085a7310824096472208d5aec7c479%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636607095371083318&sdata=D7BAZI0fMww%2BB5AKEoDZaYSi81oIEEyA%2B891pHCz608%3D&reserved=0>

Commit Summary

  *   Updated app module to work properly with total comander 64bit

File Changes

  *   M source/appModules/totalcmd64.py<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnvaccess%2Fnvda%2Fpull%2F8215%2Ffiles%23diff-0&data=02%7C01%7C%7Cb5085a7310824096472208d5aec7c479%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636607095371083318&sdata=qjJdJqb3%2F8Uy9ltpbjNtYKhj%2FXUsCgi57DFMw9TBxWc%3D&reserved=0> (51)

Patch Links:

  *   https://github.com/nvaccess/nvda/pull/8215.patch<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnvaccess%2Fnvda%2Fpull%2F8215.patch&data=02%7C01%7C%7Cb5085a7310824096472208d5aec7c479%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636607095371083318&sdata=%2Bte1g7cCD75Td02hZ83%2FLQ01l43AzMXduT9bxr1x0y8%3D&reserved=0>
  *   https://github.com/nvaccess/nvda/pull/8215.diff<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnvaccess%2Fnvda%2Fpull%2F8215.diff&data=02%7C01%7C%7Cb5085a7310824096472208d5aec7c479%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636607095371083318&sdata=SLD9WQRXtyGb7p9WUVfosDM%2FjQuDWv5GlBeuOjO%2F3b0%3D&reserved=0>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnvaccess%2Fnvda%2Fpull%2F8215&data=02%7C01%7C%7Cb5085a7310824096472208d5aec7c479%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636607095371083318&sdata=D7BAZI0fMww%2BB5AKEoDZaYSi81oIEEyA%2B891pHCz608%3D&reserved=0>, or mute the thread<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAffwnGANnesW5n4LUKkMwyTOpzC6Woryks5tt1cfgaJpZM4TtAFP&data=02%7C01%7C%7Cb5085a7310824096472208d5aec7c479%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636607095371083318&sdata=J%2Bd%2BcckWQgSVKbCy0EAkyjLo7Tl2M8U6Dy8pdifQc4E%3D&reserved=0>.

2018-05-05 15:13 UTC, Adriani90 commented
Hey,

Erscheint dein commit in deinem Github-Profil? Dann öffne den Commit und gehe auf new Pull Request.

Lg
Adriani


Von meinem iPhone gesendet

> Am 05.05.2018 um 13:04 schrieb Novalis7747 <notifications@github.com>:
> 
> Moin Adriani, 
> 
> Ich hab das TotalCMD.py jetzt so angepasst, das es gleichermaßen in der 32bit und 64bit Version von Total Commander arbeitet. 
> Habs getestet unter Win7, Win10 und mit dem TotalCmd 32 und 64bit. 
> Ich versuche schon seit 2 Tagen einen pull request zu erstellen, aber es gelingt mir nicht. Warum ist das so verdammt kompliziert? 
> Hab das ganze von gitup zu mir geclont, hab einen commit erstellt mit dem geänderten totalcmd.py und gepushed. Und nun? 
> Muss ich erst noch ein Studium absolvieren, um jetzt weiter zu kommen, grins. 
> Kannst du mir weiterhelfen, oder soll ich dir die geänderte totalcmd.py schicken, damit du einen PR erstellst? 
> 
> Besten Gruß, 
> Ralf 
> 
> From: Adriani90 <notifications@github.com> 
> Sent: Montag, 30. April 2018 20:26 
> To: nvaccess/nvda <nvda@noreply.github.com> 
> Cc: Novalis7747 <novalis7747@live.com>; Mention <mention@noreply.github.com> 
> Subject: [nvaccess/nvda] Updated app module to work properly with total comander 64bit (#8215) 
> 
> Link to issue number: 
> 
> None 
> 
> Summary of the issue: 
> 
> Creating this pull request on behalf of @Novalis7747<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNovalis7747&data=02%7C01%7C%7Cb5085a7310824096472208d5aec7c479%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636607095370927042&sdata=su9z2EgV4exE9N%2FZc1gX38NyCaMyQULWfFdOb%2F6DfMs%3D&reserved=0>! 
> In Total commander 64bit, NVDA does not report the same information compared to Total Commander 32bit. It does not announce selections and left and right panels. 
> 
> Description of how this pull request fixes the issue: 
> 
> The app module "totalcmd64.py" links to "totalcmd.py" which is wrong since total commander 64bit has other class names for list views than the 32bit version. Thus, "totalcmd.py" is mostly copied into "totalcmd64.py" with following exceptions: 
> 
> 1. The classname "TMyListBox" changed to "LCLListBox" 
> 2. The counters to determine if the cursor is on the left or right panel changed from "if counter==2:" to "if counter==3:" 
> 
> Testing performed: 
> 
> Yes, with different versions of Total Commander 64bit. 
> 
> Known issues with pull request: 
> 
> None 
> 
> Change log entry: 
> 
> * Changes 
> 
> ________________________________ 
> You can view, comment on, or merge this pull request online at: 
> 
> https://github.com/nvaccess/nvda/pull/8215<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnvaccess%2Fnvda%2Fpull%2F8215&data=02%7C01%7C%7Cb5085a7310824096472208d5aec7c479%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636607095371083318&sdata=D7BAZI0fMww%2BB5AKEoDZaYSi81oIEEyA%2B891pHCz608%3D&reserved=0> 
> 
> Commit Summary 
> 
> * Updated app module to work properly with total comander 64bit 
> 
> File Changes 
> 
> * M source/appModules/totalcmd64.py<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnvaccess%2Fnvda%2Fpull%2F8215%2Ffiles%23diff-0&data=02%7C01%7C%7Cb5085a7310824096472208d5aec7c479%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636607095371083318&sdata=qjJdJqb3%2F8Uy9ltpbjNtYKhj%2FXUsCgi57DFMw9TBxWc%3D&reserved=0> (51) 
> 
> Patch Links: 
> 
> * https://github.com/nvaccess/nvda/pull/8215.patch<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnvaccess%2Fnvda%2Fpull%2F8215.patch&data=02%7C01%7C%7Cb5085a7310824096472208d5aec7c479%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636607095371083318&sdata=%2Bte1g7cCD75Td02hZ83%2FLQ01l43AzMXduT9bxr1x0y8%3D&reserved=0> 
> * https://github.com/nvaccess/nvda/pull/8215.diff<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnvaccess%2Fnvda%2Fpull%2F8215.diff&data=02%7C01%7C%7Cb5085a7310824096472208d5aec7c479%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636607095371083318&sdata=SLD9WQRXtyGb7p9WUVfosDM%2FjQuDWv5GlBeuOjO%2F3b0%3D&reserved=0> 
> 
> — 
> You are receiving this because you were mentioned. 
> Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnvaccess%2Fnvda%2Fpull%2F8215&data=02%7C01%7C%7Cb5085a7310824096472208d5aec7c479%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636607095371083318&sdata=D7BAZI0fMww%2BB5AKEoDZaYSi81oIEEyA%2B891pHCz608%3D&reserved=0>, or mute the thread<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAffwnGANnesW5n4LUKkMwyTOpzC6Woryks5tt1cfgaJpZM4TtAFP&data=02%7C01%7C%7Cb5085a7310824096472208d5aec7c479%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636607095371083318&sdata=J%2Bd%2BcckWQgSVKbCy0EAkyjLo7Tl2M8U6Dy8pdifQc4E%3D&reserved=0>. 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2018-05-06 10:38 UTC, Adriani90 commented
Ok, der Push ist richtig, du musst nur noch aus deinem Profil auf "new Pull Request" gehen, dann wirst du automatisch weitergeleitet zur NV Access branche.

2018-05-06 14:39 UTC, Novalis7747 commented
Ich kriegs trotzdem nicht hin. Wenn ich mal ne Blockade habe, dauert das, lach.

From: Adriani90 <notifications@github.com>
Sent: Sonntag, 6. Mai 2018 12:39
To: nvaccess/nvda <nvda@noreply.github.com>
Cc: Novalis7747 <novalis7747@live.com>; Mention <mention@noreply.github.com>
Subject: Re: [nvaccess/nvda] Updated app module to work properly with total comander 64bit (#8215)


Ok, der Push ist richtig, du musst nur noch aus deinem Profil auf "new Pull Request" gehen, dann wirst du automatisch weitergeleitet zur NV Access branche.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnvaccess%2Fnvda%2Fpull%2F8215%23issuecomment-386869838&data=02%7C01%7C%7C4df19d9d4f2547b070e208d5b33d86fe%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636611999190253441&sdata=dkig87EF6oaJClOdo4TtkO3x1t60wzvr%2BkL2B7zsbGI%3D&reserved=0>, or mute the thread<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAffwnBVjOR4kiSvaeMxAULoPpltp8vDbks5tvtKtgaJpZM4TtAFP&data=02%7C01%7C%7C4df19d9d4f2547b070e208d5b33d86fe%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636611999190253441&sdata=Rt%2B0RqdYf%2FJfYSsSRCrWXIMaG3OfPzAkp73hO%2B6X5wE%3D&reserved=0>.

2018-05-06 15:07 UTC, Adriani90 commented
Hey,

 

kein Problem das ist alles eigentlich realtiv einfach, wenn mans einmal geschafft hat.

 

Also wenn du dein Profil auf Github öffnest, dann hast du ein Repository, nämlich NVDA. Wenn du da rein gehst, dann siehst du deine letzten Commits. Direkt über die Tabelle mit allen anderen Commits.

 

Nun, du brauchst nicht irgend einen Commit zu öffnen. Es gibt dort nämlich einen Link „new Pull Request“. Du kannst den Link z.B. mit der Elementliste finden.

 

Wenn du da drauf gehst, dann öffnet sich eine Seite, wo deine NVDA-Branche und die von NV Access verglichen werden. Dort gibt es einen Schalter namens „create Pull Request“. Wenn du da drauf gehst erscheint die Vorlage für den Pull Request von NV Access.

 

Können gerne über Whats App schnell telefonieren wenn du willst.

 

 

Lg

Adriani

 

 

Von: Novalis7747 <notifications@github.com> 
Gesendet: Sonntag, 6. Mai 2018 16:40
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [nvaccess/nvda] Updated app module to work properly with total comander 64bit (#8215)

 

Ich kriegs trotzdem nicht hin. Wenn ich mal ne Blockade habe, dauert das, lach. 

From: Adriani90 <notifications@github.com> 
Sent: Sonntag, 6. Mai 2018 12:39 
To: nvaccess/nvda <nvda@noreply.github.com <mailto:nvda@noreply.github.com> > 
Cc: Novalis7747 <novalis7747@live.com <mailto:novalis7747@live.com> >; Mention <mention@noreply.github.com <mailto:mention@noreply.github.com> > 
Subject: Re: [nvaccess/nvda] Updated app module to work properly with total comander 64bit (#8215) 


Ok, der Push ist richtig, du musst nur noch aus deinem Profil auf "new Pull Request" gehen, dann wirst du automatisch weitergeleitet zur NV Access branche. 

— 
You are receiving this because you were mentioned. 
Reply to this email directly, view it on GitHub<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnvaccess%2Fnvda%2Fpull%2F8215%23issuecomment-386869838 <https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnvaccess%2Fnvda%2Fpull%2F8215%23issuecomment-386869838&data=02%7C01%7C%7C4df19d9d4f2547b070e208d5b33d86fe%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636611999190253441&sdata=dkig87EF6oaJClOdo4TtkO3x1t60wzvr%2BkL2B7zsbGI%3D&reserved=0> &data=02%7C01%7C%7C4df19d9d4f2547b070e208d5b33d86fe%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636611999190253441&sdata=dkig87EF6oaJClOdo4TtkO3x1t60wzvr%2BkL2B7zsbGI%3D&reserved=0>, or mute the thread<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAffwnBVjOR4kiSvaeMxAULoPpltp8vDbks5tvtKtgaJpZM4TtAFP <https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAffwnBVjOR4kiSvaeMxAULoPpltp8vDbks5tvtKtgaJpZM4TtAFP&data=02%7C01%7C%7C4df19d9d4f2547b070e208d5b33d86fe%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636611999190253441&sdata=Rt%2B0RqdYf%2FJfYSsSRCrWXIMaG3OfPzAkp73hO%2B6X5wE%3D&reserved=0> &data=02%7C01%7C%7C4df19d9d4f2547b070e208d5b33d86fe%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636611999190253441&sdata=Rt%2B0RqdYf%2FJfYSsSRCrWXIMaG3OfPzAkp73hO%2B6X5wE%3D&reserved=0>. 



—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub <https://github.com/nvaccess/nvda/pull/8215#issuecomment-386884236> , or mute the thread <https://github.com/notifications/unsubscribe-auth/Aaon8QiR7ZI8fZu-od_MaqDRjuGVkdDMks5tvwtBgaJpZM4TtAFP> .  <https://github.com/notifications/beacon/Aaon8REPoQ7W8__Du2s-NTeOiFaImcRaks5tvwtBgaJpZM4TtAFP.gif>

2018-05-08 07:45 UTC, Novalis7747 commented
Hier der pull request
https://github.com/nvaccess/nvda/pull/8250
Meine tester haben noch einen Fehler gefunden, den ich bereinigt habe.
From: Adriani90 <notifications@github.com>
Sent: Sonntag, 6. Mai 2018 17:08
To: nvaccess/nvda <nvda@noreply.github.com>
Cc: Novalis7747 <novalis7747@live.com>; Mention <mention@noreply.github.com>
Subject: Re: [nvaccess/nvda] Updated app module to work properly with total comander 64bit (#8215)

Hey,



kein Problem das ist alles eigentlich realtiv einfach, wenn mans einmal geschafft hat.



Also wenn du dein Profil auf Github öffnest, dann hast du ein Repository, nämlich NVDA. Wenn du da rein gehst, dann siehst du deine letzten Commits. Direkt über die Tabelle mit allen anderen Commits.



Nun, du brauchst nicht irgend einen Commit zu öffnen. Es gibt dort nämlich einen Link „new Pull Request“. Du kannst den Link z.B. mit der Elementliste finden.



Wenn du da drauf gehst, dann öffnet sich eine Seite, wo deine NVDA-Branche und die von NV Access verglichen werden. Dort gibt es einen Schalter namens „create Pull Request“. Wenn du da drauf gehst erscheint die Vorlage für den Pull Request von NV Access.



Können gerne über Whats App schnell telefonieren wenn du willst.





Lg

Adriani





Von: Novalis7747 <notifications@github.com>
Gesendet: Sonntag, 6. Mai 2018 16:40
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [nvaccess/nvda] Updated app module to work properly with total comander 64bit (#8215)



Ich kriegs trotzdem nicht hin. Wenn ich mal ne Blockade habe, dauert das, lach.

From: Adriani90 <notifications@github.com>
Sent: Sonntag, 6. Mai 2018 12:39
To: nvaccess/nvda <nvda@noreply.github.com <mailto:nvda@noreply.github.com> >
Cc: Novalis7747 <novalis7747@live.com <mailto:novalis7747@live.com> >; Mention <mention@noreply.github.com <mailto:mention@noreply.github.com> >
Subject: Re: [nvaccess/nvda] Updated app module to work properly with total comander 64bit (#8215)


Ok, der Push ist richtig, du musst nur noch aus deinem Profil auf "new Pull Request" gehen, dann wirst du automatisch weitergeleitet zur NV Access branche.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnvaccess%2Fnvda%2Fpull%2F8215%23issuecomment-386869838 <https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnvaccess%2Fnvda%2Fpull%2F8215%23issuecomment-386869838&data=02%7C01%7C%7C4df19d9d4f2547b070e208d5b33d86fe%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636611999190253441&sdata=dkig87EF6oaJClOdo4TtkO3x1t60wzvr%2BkL2B7zsbGI%3D&reserved=0> &data=02%7C01%7C%7C4df19d9d4f2547b070e208d5b33d86fe%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636611999190253441&sdata=dkig87EF6oaJClOdo4TtkO3x1t60wzvr%2BkL2B7zsbGI%3D&reserved=0>, or mute the thread<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAffwnBVjOR4kiSvaeMxAULoPpltp8vDbks5tvtKtgaJpZM4TtAFP <https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAffwnBVjOR4kiSvaeMxAULoPpltp8vDbks5tvtKtgaJpZM4TtAFP&data=02%7C01%7C%7C4df19d9d4f2547b070e208d5b33d86fe%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636611999190253441&sdata=Rt%2B0RqdYf%2FJfYSsSRCrWXIMaG3OfPzAkp73hO%2B6X5wE%3D&reserved=0> &data=02%7C01%7C%7C4df19d9d4f2547b070e208d5b33d86fe%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636611999190253441&sdata=Rt%2B0RqdYf%2FJfYSsSRCrWXIMaG3OfPzAkp73hO%2B6X5wE%3D&reserved=0>.



—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub <https://github.com/nvaccess/nvda/pull/8215#issuecomment-386884236> , or mute the thread <https://github.com/notifications/unsubscribe-auth/Aaon8QiR7ZI8fZu-od_MaqDRjuGVkdDMks5tvwtBgaJpZM4TtAFP> . <https://github.com/notifications/beacon/Aaon8REPoQ7W8__Du2s-NTeOiFaImcRaks5tvwtBgaJpZM4TtAFP.gif>



—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnvaccess%2Fnvda%2Fpull%2F8215%23issuecomment-386886107&data=02%7C01%7C%7Cfa58800ce06e408913d108d5b36320b0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636612160675151350&sdata=OVXYp8T8yo4TYgiljsmpkbAkVl4FmfbvbNa2ny1SOnE%3D&reserved=0>, or mute the thread<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAffwnOQk6l142Sn38oLvrcqpqRB58oljks5tvxHBgaJpZM4TtAFP&data=02%7C01%7C%7Cfa58800ce06e408913d108d5b36320b0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636612160675151350&sdata=dDobZfL0%2BCqKfBwUMZD6jvHZ3%2F6t0s1yTKtrVVUwQNo%3D&reserved=0>.

2018-05-08 16:38 UTC, Novalis7747 commented
Hello,

I added a new pull request:
https://github.com/nvaccess/nvda/pull/8250

cheers,
  Ralf
From: Leonard de Ruijter <notifications@github.com>
Sent: Dienstag, 1. Mai 2018 10:31
To: nvaccess/nvda <nvda@noreply.github.com>
Cc: Novalis7747 <novalis7747@live.com>; Mention <mention@noreply.github.com>
Subject: Re: [nvaccess/nvda] Updated app module to work properly with total comander 64bit (#8215)


Closed #8215<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnvaccess%2Fnvda%2Fpull%2F8215&data=02%7C01%7C%7Ca1557eed3fd74e7c5f6208d5af3ddf28%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636607602620102210&sdata=gnJJ8ne5eGtifTZLhY%2FhdUaLW63jxcGxnHDPWRk5LcE%3D&reserved=0>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnvaccess%2Fnvda%2Fpull%2F8215%23event-1603044953&data=02%7C01%7C%7Ca1557eed3fd74e7c5f6208d5af3ddf28%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636607602620102210&sdata=0M8nr1bt02WMLc20QpQJI7H1ZhB4Eb9XHkIGkAdmBr4%3D&reserved=0>, or mute the thread<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAffwnB2gduvON9WWKrOkDrLqOanfTmmEks5tuB1EgaJpZM4TtAFP&data=02%7C01%7C%7Ca1557eed3fd74e7c5f6208d5af3ddf28%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636607602620102210&sdata=5klAklFza0bqmDCpB9OCCDjY1KM89F7sCdptb7zkbQY%3D&reserved=0>.

2018-05-19 14:35 UTC, Novalis7747 commented
Hi Adriani,

Danke für deine Erinnerungsmail.
Bitte den letzten commit verwenden, der hat noch einen bugfix drinne mit ftp-connections und links/rechts Ansage. Hatte ja mehrere beta-tester.

Cheers,
  Ralf

From: Adriani90 <notifications@github.com>
Sent: Sonntag, 6. Mai 2018 17:08
To: nvaccess/nvda <nvda@noreply.github.com>
Cc: Novalis7747 <novalis7747@live.com>; Mention <mention@noreply.github.com>
Subject: Re: [nvaccess/nvda] Updated app module to work properly with total comander 64bit (#8215)

Hey,



kein Problem das ist alles eigentlich realtiv einfach, wenn mans einmal geschafft hat.



Also wenn du dein Profil auf Github öffnest, dann hast du ein Repository, nämlich NVDA. Wenn du da rein gehst, dann siehst du deine letzten Commits. Direkt über die Tabelle mit allen anderen Commits.



Nun, du brauchst nicht irgend einen Commit zu öffnen. Es gibt dort nämlich einen Link „new Pull Request“. Du kannst den Link z.B. mit der Elementliste finden.



Wenn du da drauf gehst, dann öffnet sich eine Seite, wo deine NVDA-Branche und die von NV Access verglichen werden. Dort gibt es einen Schalter namens „create Pull Request“. Wenn du da drauf gehst erscheint die Vorlage für den Pull Request von NV Access.



Können gerne über Whats App schnell telefonieren wenn du willst.





Lg

Adriani





Von: Novalis7747 <notifications@github.com>
Gesendet: Sonntag, 6. Mai 2018 16:40
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [nvaccess/nvda] Updated app module to work properly with total comander 64bit (#8215)



Ich kriegs trotzdem nicht hin. Wenn ich mal ne Blockade habe, dauert das, lach.

From: Adriani90 <notifications@github.com>
Sent: Sonntag, 6. Mai 2018 12:39
To: nvaccess/nvda <nvda@noreply.github.com <mailto:nvda@noreply.github.com> >
Cc: Novalis7747 <novalis7747@live.com <mailto:novalis7747@live.com> >; Mention <mention@noreply.github.com <mailto:mention@noreply.github.com> >
Subject: Re: [nvaccess/nvda] Updated app module to work properly with total comander 64bit (#8215)


Ok, der Push ist richtig, du musst nur noch aus deinem Profil auf "new Pull Request" gehen, dann wirst du automatisch weitergeleitet zur NV Access branche.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnvaccess%2Fnvda%2Fpull%2F8215%23issuecomment-386869838 <https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnvaccess%2Fnvda%2Fpull%2F8215%23issuecomment-386869838&data=02%7C01%7C%7C4df19d9d4f2547b070e208d5b33d86fe%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636611999190253441&sdata=dkig87EF6oaJClOdo4TtkO3x1t60wzvr%2BkL2B7zsbGI%3D&reserved=0> &data=02%7C01%7C%7C4df19d9d4f2547b070e208d5b33d86fe%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636611999190253441&sdata=dkig87EF6oaJClOdo4TtkO3x1t60wzvr%2BkL2B7zsbGI%3D&reserved=0>, or mute the thread<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAffwnBVjOR4kiSvaeMxAULoPpltp8vDbks5tvtKtgaJpZM4TtAFP <https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAffwnBVjOR4kiSvaeMxAULoPpltp8vDbks5tvtKtgaJpZM4TtAFP&data=02%7C01%7C%7C4df19d9d4f2547b070e208d5b33d86fe%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636611999190253441&sdata=Rt%2B0RqdYf%2FJfYSsSRCrWXIMaG3OfPzAkp73hO%2B6X5wE%3D&reserved=0> &data=02%7C01%7C%7C4df19d9d4f2547b070e208d5b33d86fe%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636611999190253441&sdata=Rt%2B0RqdYf%2FJfYSsSRCrWXIMaG3OfPzAkp73hO%2B6X5wE%3D&reserved=0>.



—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub <https://github.com/nvaccess/nvda/pull/8215#issuecomment-386884236> , or mute the thread <https://github.com/notifications/unsubscribe-auth/Aaon8QiR7ZI8fZu-od_MaqDRjuGVkdDMks5tvwtBgaJpZM4TtAFP> . <https://github.com/notifications/beacon/Aaon8REPoQ7W8__Du2s-NTeOiFaImcRaks5tvwtBgaJpZM4TtAFP.gif>



—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnvaccess%2Fnvda%2Fpull%2F8215%23issuecomment-386886107&data=02%7C01%7C%7Cfa58800ce06e408913d108d5b36320b0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636612160675151350&sdata=OVXYp8T8yo4TYgiljsmpkbAkVl4FmfbvbNa2ny1SOnE%3D&reserved=0>, or mute the thread<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAffwnOQk6l142Sn38oLvrcqpqRB58oljks5tvxHBgaJpZM4TtAFP&data=02%7C01%7C%7Cfa58800ce06e408913d108d5b36320b0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636612160675151350&sdata=dDobZfL0%2BCqKfBwUMZD6jvHZ3%2F6t0s1yTKtrVVUwQNo%3D&reserved=0>.