Fix getting offsets from points in edit controls when offset numbers exceed 16 bits
nvaccess/nvda pull request #8397
Opened 2018-06-14 07:25 UTC by leonardder

### Link to issue number:
None

### Summary of the issue:
When getting an offset from a point in edit controls, such as notepad, a 32 bit value is returned which contains the offset in the LOWORD and the line number in the HIWORD. UNtil now, NVDA was only using the LOWORD value, which caused issues when the associated offset was higher than 65535 or 0xFFFF.

### Description of how this pull request fixes the issue:
When the length of the text control exceeds 0xffff, we can't simply return the LOWORD of the EM_CHARFROMPOS result, as that might be wrong. Instead, we get the start offset that is associated with the line number and calculate the real offset for the given point based on that start offset.

### Testing performed:
Tested getOffsetFromPoint behavior in Notepad. I also tested Wordpad with the text info forced to EditTextInfo. That code shouldn't have been touched, and it indeed returned the correct result as well.

Furthermore, I covered the case where for example the line start offset would be <= 0xffff whereas the offset belonging to the point ought to be greater than 0xffff.

### Change log entry:
* Bug fixes
    + Mouse tracking is now much more accurate in Notepad and other plain text edit controls when in a document with more than 65535 characters. (#8397)

2018-06-15 11:09 UTC, dkager commented on source/NVDAObjects/window/edit.py
> +					offset+= 0x10000
Space after =

2018-06-15 11:09 UTC, dkager commented on source/NVDAObjects/window/edit.py
> +				lineStartLW = winUser.LOWORD(lineStart)
What is contained in the LOWORD? Could the variable name make this clear?

2018-06-18 00:59 UTC, michaelDCurran requested changes

2018-06-18 00:59 UTC, michaelDCurran commented on source/NVDAObjects/window/edit.py
> +					offset+=0x10000
Can you better explain what these two lines do?

2018-06-18 07:25 UTC, michaelDCurran submitted a review, later dismissed

2018-07-18 23:36 UTC, michaelDCurran approved these changes

2018-07-18 23:44 UTC, merged