Copying settings to secure screens doesn't warn when all add-ons are disabled
nvaccess/nvda pull request #8418
Opened 2018-06-19 05:59 UTC by nvdaes

### Link to issue number:
8274

### Summary of the issue:
NVDA shouldn't give a warning when users choose to copy settings for secure screens, if all add-ons are disabled.

### Description of how this pull request fixes the issue:
We check if globalVars.appArgs.disableAddons is False (not globalVars.appArgs.disableAddons) to see if all add-ons are disabled. In this case, the for loop to check if directories contained in the user configuration folder aren't empty, in order to ask confirmation before copying settings, is not performed.

### Testing performed:
Unit tests and run NVDA master with this pull request from source.
Due to an error with some libraries on the local computer, this snapshot hasn't been installed for a real test.

### Known issues with pull request:
None.
Anyway, this could be improved:
1. Checking if there are or not running add-ons, to copy just them and show their name to the user.
2. Remove old plugins and drivers.
3. Don't warn if they aren't running add-ons though globalVars.appArgs.disableAddons is True (for instance, if they have been disabled individually).

### Change log entry:

* Changes
NVDA doesn't warn before copying settings for secure screens when all add-ons have been disabled.

2018-06-19 06:59 UTC, leonardder commented
Thanks for your pr.

What worries me here is that this creates an inconsistency. When add-ons are force disabled, this code does not copy them at all, while as when some are disabled and others are enabled, all addons are still copied regardless of their state.

2018-06-19 07:16 UTC, nvdaes commented
Yes, I thought about this too, and my idea was that someone could use the feature of disabling add-ons precissely as a temporary way of indicating that they shouldn't be copied, without disabling it the next time NVDA is restarted.
Anyway, for me old plugins should be removed and then a for loop between running add-ons should let to select individual add-ons to copy.

2018-06-19 08:19 UTC, Brian1Gaff commented
This may seem a silly question, but if using settings on secure screens, are 
there any circumstances where anything but a synth add on is actually of any 
consequence to the working of nvda on that screen?
 If so why not disable all add ons which are not synths anyway and make the 
copy smaller and presumably less of a security issue in any case.
 Brian

2018-06-19 11:27 UTC, nvdaes commented
@Brian1Gaff , not just add-ons containing syntesizer drivers could take effect in secure screens and may be copied.

2018-06-19 16:10 UTC, nvdaes commented
Now addonHandler.getRunningAddons() method is used instead.
For each running add-on, its add-on summary is appended to a list named runningAddons. The warning is shown just when there are running add-ons, without looking to app modules, global plugins and drivers, since probably they will be removed and the whole config directory with its subdirs are copied now.
This could be improved, as mentioned in this related issue, where the possibility of selecting what add-ons will be copied to system configuration is requested:
https://github.com/nvaccess/nvda/issues/6305

I have installed this snapshot of NVDA creating a launcher, and have made tests disabling various add-ons and all.
For me results are acceptable. The summary of the running add-ons is shown when the warning is presented.
I think it's better to show summaries and not names, since they are intended to be the name to display and are shown in the list of the add-on manager.
@leonardder and others, if you are interested, please review this or provide more feed-back.
Thanks

2018-06-20 10:47 UTC, nvdaes commented
Last commit not tested yet.

2018-06-21 15:17 UTC, LeonarddeR requested changes

2018-06-21 15:17 UTC, leonardder commented on .github/issue_template.md
> +> Below you will find NVDA's Github issue template. You might consider swapping to the preview tab in order
I don't understand why this is in the diff, could you please merge most recent master?

2018-06-21 15:17 UTC, leonardder commented on source/config/__init__.py
> +				subDirs[:] = subDirs
I don't think this is necessary.

2018-06-21 15:17 UTC, leonardder commented on source/gui/settingsDialogs.py
> +		if len(runningAddons)>0:
You can easily change this into something like:
`if next(addonHandler.getRunningAddons(), None):`

2018-06-21 16:46 UTC, nvdaes commented
Thanks, @leonardder.
I've merged master and simplified the code of gui following your excellent suggestion.
About the config file, are you sure? According to my tests in Python console, I think that the assignment subDirs[:]=subDirs is necessary. Otherwise, when curSourceDir is "addons", the assignment can be changed causing issues, that is, I think the subDir[:] needs to be restored when curSourceDir is not "addons".
But, if you are sure, I will change it.
About addonHandler, it's imported in other function of config/__init__.py, but not at module level. I don't know if this could be simplified importing it just once.
Regards.

2018-06-21 19:36 UTC, nvdaes commented
Now results are as follows:
* When trying to copy settings, list of summaries for running add-ons is shown in the message box requesting confirmation.
* The user config folder is copied, as previously, with all containing subfolders, i.e., non running add-ons are copied, but they can't be enabled on secure screens. This has the dfollowing drawback: it's not useful, the same as other temporary files contained in the user config folder, or possibly dictionaries for synthesizers, which can remain in NVDA even when corresponding voices have been uninstalled, for instance. The advantage could be if NVDA could include a feature for reverting configuration by copying options from system config.
* Drivers intended to be used for testing, like appModules, globalPlugins, etc., are copied too. Since NVDA doesn't have a proper way to provide a name, description or other tasks of management for this, maybe better not to copy them.
* I think this shouldn't be merged until the issue about selecting individual add-ons to copy is addressed. Though disabling individual add-ons before copying settings could be a way of selecting them.

Thanks

2019-07-30 04:44 UTC, josephsl commented
Hi,

Can you rebase this branch to master if possible? Or, we may need to start over from scratch due to #6275 and so many changes since then.

Thanks.

2019-07-30 05:40 UTC, nvdaes commented
@josephsl, for now I see conflicts to fix in various files. I will get a look at this.

2019-07-30 17:01 UTC, nvdaes commented
@josephsl, you can test changes. Just a few lines need to be changed in gui/settingsDialogs after merging master into this branch.
scons tests have passed and NVDA runs well.
Thanks

2019-07-30 17:34 UTC, josephsl commented
Hi,

I think telling users that these add-ons are currently enabled might help, since it now checks if any add-ons are running i.e. enabled. Something to the effect of:

The following add-ons are currently enabled.

Eventually I think a dialog to choose individual add-ons to copy would build on top of this change.

Also, when copying add-ons, copy only add-ons that are running if users said "yes" to the warning, but then again, I think a dialog described above may make things a bit easier.

Thanks.

2019-07-30 19:49 UTC, nvdaes commented
@Josephsl commented:

> Eventually I think a dialog to choose individual add-ons to copy would build on top of this change.

This was suggested by @leonardder in issue #6305.

 > Also, when copying add-ons, copy only add-ons that are running if users said "yes" to the warning.

Maybe discussed, taking account as a drawback that pickle file will contain info for add-ons not copied, and that if the user configuration could be restored to the system configuration, the add-ons not copied couldn't be enabled later.

2020-02-16 10:32 UTC, josephsl commented
Hi,

Are we ready to get this PR going again?

Thanks.

2020-07-03 08:05 UTC, feerrenrut commented
We have decided to close this PR. We would like to see much deeper user control for how add-ons are copied to the system profile. A GUI should be introduced, allowing (but strongly discouraging) users to select which add-ons to use on the system profile. No add-ons should be selected by default.

2020-07-03 08:05 UTC, closed without merging

2020-07-03 08:47 UTC, nvdaes commented
OK, thanks.

2020-07-03 10:05 GMT+02:00, Reef Turner <notifications@github.com>:
> We have decided to close this PR. We would like to see much deeper user
> control for how add-ons are copied to the system profile. A GUI should be
> introduced, allowing (but strongly discouraging) users to select which
> add-ons to use on the system profile. No add-ons should be selected by
> default.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/pull/8418#issuecomment-653413003

2021-06-16 12:41 UTC, cary-rowen commented
@nvdaes 
Do you have any new progress on this PR? Regarding #6305, of course it is not just this closed PR. I hope to see new progress.
Thanks.

2021-06-16 13:52 UTC, nvdaes commented
@cary-rowen, no, there is not any progress for now. Please see issue #11006