What's new: issue number edits, recognize Windows 10 RS5/Server 2019
nvaccess/nvda pull request #8540
Opened 2018-07-23 06:40 UTC by josephsl

### Link to issue number:
None

### Summary of the issue:
Edits to what's new document for NVDA 2018.3.

### Description of how this pull request fixes the issue:
Changed issue numbers where they were previously pointing to pull requests. In case of braille tables, the two entries have been combined into one, as well as capitalized table names. Also, recognize the fact that Windows 10 RS5 has a server variant: Windows Server 2019.

### Testing performed:
Compiled docs from source with no issues.

### Known issues with pull request:
None

### Change log entry:
None

Thanks.

2018-07-23 06:45 UTC, michaelDCurran submitted a review, later dismissed

2018-07-23 06:45 UTC, LeonarddeR requested changes
Just to make sure, could you check that every entry starts with a capital letter? We should actually unit test this somehow.

Furthermore, it might be good to add an entry for 2018.2.1, not that it's super important, but it will make it easier to find out what this release was for in the future.

2018-07-23 06:45 UTC, leonardder commented on user_docs/en/changes.t2t
> +- custom roles via the aria-roledescription attribute are now supported in all web browsers. (#8448)
Please change this line to start with an uppercase c

2018-07-23 06:45 UTC, leonardder commented on user_docs/en/changes.t2t
> +- New braille table: Czech 8 dot, Central Kurdish, Esperanto, Hungarian, Swedish 8 dot computer braille. (#8226, #8437)
table>tables

2018-07-23 06:45 UTC, leonardder commented on user_docs/en/changes.t2t
> +- On Windows 10 rs5 and Server 2019 and above, NVDA no longer fails to track the system focus when an application freezes or floods the system with events. (#7345, #8535)
I wonder whether we should refer to rs5 as the Windows 10 Oktober 2018 update, which will most likely be the name for that update.

2018-07-23 06:49 UTC, josephsl commented
Hi, regarding RS5 name, perhaps that might work, but we don’t want to go through yet another Spring Creators Update debacle like what we saw earlier this year. I’m happy for that to be called October 2018 Update for now. Thanks.

 

From: Leonard de Ruijter <notifications@github.com> 
Sent: Sunday, July 22, 2018 11:46 PM
To: nvaccess/nvda <nvda@noreply.github.com>
Cc: Joseph Lee <joseph.lee22590@gmail.com>; Author <author@noreply.github.com>
Subject: Re: [nvaccess/nvda] What's new: issue number edits, recognize Windows 10 RS5/Server 2019 (#8540)

 

@leonardder requested changes on this pull request.

Just to make sure, could you check that every entry starts with a capital letter? We should actually unit test this somehow.

Furthermore, it might be good to add an entry for 2018.2.1, not that it's super important, but it will make it easier to find out what this release was for in the future.

  _____  

In user_docs/en/changes.t2t <https://github.com/nvaccess/nvda/pull/8540#discussion_r204294706> :

>  - Added scripts for reporting elapsed and total time of current track in Foobar2000. (#6596)
 - The Mac command key symbol (⌘) is now announced when reading text with any synthesizer. (#8366)
-- custom roles via the aria-roledescription attribute are now supported in all web browsers. (#8449)
-- New braille table: Swedish 8 dot computer braille. (#8227)
-- added czech eight dots, central kurdish, esperanto and hungarian braille tables. (#8446)
+- custom roles via the aria-roledescription attribute are now supported in all web browsers. (#8448)

Please change this line to start with an uppercase c

  _____  

In user_docs/en/changes.t2t <https://github.com/nvaccess/nvda/pull/8540#discussion_r204294744> :

>  - Added scripts for reporting elapsed and total time of current track in Foobar2000. (#6596)
 - The Mac command key symbol (⌘) is now announced when reading text with any synthesizer. (#8366)
-- custom roles via the aria-roledescription attribute are now supported in all web browsers. (#8449)
-- New braille table: Swedish 8 dot computer braille. (#8227)
-- added czech eight dots, central kurdish, esperanto and hungarian braille tables. (#8446)
+- custom roles via the aria-roledescription attribute are now supported in all web browsers. (#8448)
+- New braille table: Czech 8 dot, Central Kurdish, Esperanto, Hungarian, Swedish 8 dot computer braille. (#8226, #8437)

table>tables

  _____  

In user_docs/en/changes.t2t <https://github.com/nvaccess/nvda/pull/8540#discussion_r204295005> :

> @@ -41,8 +40,8 @@ What's New in NVDA
 - Pressing sp2 on an ALVA BC6 display to emulate the alt key now works as advertised. (#8360)
 - NVDA no longer announces redundant keyboard layout changes. (#7383)
 - Mouse tracking is now much more accurate in Notepad and other plain text edit controls when in a document with more than 65535 characters. (#8397)
-- NVDA will recognize more dialogs in Windows 10 and other modern applications. (#7473)
-- On windows 10 rs5 and above, NVDA no longer fails to track the system focus when an application freezes or floods the system with events. (#8539)
+- NVDA will recognize more dialogs in Windows 10 and other modern applications. (#8405)
+- On Windows 10 rs5 and Server 2019 and above, NVDA no longer fails to track the system focus when an application freezes or floods the system with events. (#7345, #8535)

I wonder whether we should refer to rs5 as the Windows 10 Oktober 2018 update, which will most likely be the name for that update.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub <https://github.com/nvaccess/nvda/pull/8540#pullrequestreview-139347090> , or mute the thread <https://github.com/notifications/unsubscribe-auth/AHgLkLCWeQ227ksGEGM22uPX2L_DKDu3ks5uJXEmgaJpZM4VacTv> .

2018-07-31 04:51 UTC, michaelDCurran submitted a review, later dismissed

2018-07-31 04:53 UTC, michaelDCurran commented
@leonardder are you happy with this now?

2018-07-31 05:06 UTC, LeonarddeR submitted a review, later dismissed
Go ahead after fixing just one mistake

2018-07-31 05:06 UTC, leonardder commented on user_docs/en/changes.t2t
> +- New braille table: Czech 8 dot, Central Kurdish, Esperanto, Hungarian, Swedish 8 dot computer braille. (#8226, #8437)
table>tables

2018-07-31 05:09 UTC, josephsl commented
Hi, done. Thanks.

 

From: Leonard de Ruijter <notifications@github.com> 
Sent: Monday, July 30, 2018 10:06 PM
To: nvaccess/nvda <nvda@noreply.github.com>
Cc: Joseph Lee <joseph.lee22590@gmail.com>; Author <author@noreply.github.com>
Subject: Re: [nvaccess/nvda] What's new: issue number edits, recognize Windows 10 RS5/Server 2019 (#8540)

 

@leonardder approved this pull request.

Go ahead after fixing just one mistake

  _____  

In user_docs/en/changes.t2t <https://github.com/nvaccess/nvda/pull/8540#discussion_r206395715> :

>  - Added scripts for reporting elapsed and total time of current track in Foobar2000. (#6596)
 - The Mac command key symbol (⌘) is now announced when reading text with any synthesizer. (#8366)
-- custom roles via the aria-roledescription attribute are now supported in all web browsers. (#8449)
-- New braille table: Swedish 8 dot computer braille. (#8227)
-- added czech eight dots, central kurdish, esperanto and hungarian braille tables. (#8446)
+- Custom roles via the aria-roledescription attribute are now supported in all web browsers. (#8448)
+- New braille table: Czech 8 dot, Central Kurdish, Esperanto, Hungarian, Swedish 8 dot computer braille. (#8226, #8437)

table>tables

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub <https://github.com/nvaccess/nvda/pull/8540#pullrequestreview-141801310> , or mute the thread <https://github.com/notifications/unsubscribe-auth/AHgLkCNi8Ssk_7RwRW1vp4RnlNxkTmtyks5uL-XJgaJpZM4VacTv> .

2018-07-31 05:21 UTC, michaelDCurran approved these changes

2018-07-31 05:21 UTC, merged