proof of concept wrt issue #8563
nvaccess/nvda pull request #8571
Opened 2018-07-30 13:58 UTC by didiercolle

### Link to issue number:
  #8563 
### Summary of the issue:

### Description of how this pull request fixes the issue:
Added in EditableText an entry and script for ctrl+a gesture
Have _caretScriptPostMovedHelper in EditableTextWithAutoSelectDetection afterwards also check for possible selection changes.
### Testing performed:

### Known issues with pull request:
It is just a proof of concept.
What other gestures to add?
Now for ctrl+a caret movement considers line unit, not sure what most sensible unit would be in this case. In addition to that spoken output wrt selection comes immediately after spoken output wrt caret movement: how should the spoken output look like in order to become less confusing/more clear?
### Change log entry:

Section: New features, Changes, Bug fixes

2018-07-30 21:52 UTC, didiercolle commented
The reason for this approach:
1) Although I have no other example, I am not sure that it is a npp specific problem. It is not such an erratic behavior from npp: it does not generate a caret event when the caret does not move, and as by the current global design change in selection happens through the caret event handler...
2) I guess same motivations why a global solution for also monitoring caret movement through scripts bound to gestures, also applies here. Why for one a global solution and not for the other?

2018-08-05 06:45 UTC, derekriemer requested changes
I think this might need some description on the implementation. What is the problem being solved. Also, why are you passing None in for something which has a variable being passed in?

2018-08-05 06:45 UTC, derekriemer commented on source/NVDAObjects/behaviors.py
> +                super(EditableTextWithAutoSelectDetection,self)._caretScriptPostMovedHelper(speakUnit, gesture, info=None)
Why are you passing None into the super class here?

2018-08-05 18:10 UTC, dkager commented
It could be interesting to see if the issue you are resolving occurs in other Scintilla-based editors, e.g. SciTE.

2018-12-05 13:12 UTC, leonardder commented
@didiercolle: Do you intend to address the questions raised above?

2019-02-21 12:24 UTC, leonardder commented
@didiercolle: what are your current intentions with this pr? Could you update the initial description and fill up the open gaps, such as the description of the issue you're trying to solve?

2019-04-25 15:12 UTC, leonardder commented
I'm going to close this for now as this is a proof of concept and we haven't received any reactions on our requests. When filing a possible follow up pr, please provide extensive details about what problem you're trying to solve.

2019-04-25 15:12 UTC, closed without merging