Add command line parameter for silent installations to disable NVDA at the logon screen and enhance portable-path command line behavior
nvaccess/nvda pull request #8623
Opened 2018-08-13 09:06 UTC by leonardder

### Link to issue number:
Fixes #8574

### Summary of the issue:
1. In the current situation, it is not possible to specify the start at logon behaviour from the command line. This issue is relevant for system administrators who want to install NVDA silently on a multi user system.
2. When starting NVDA with the "--portable-path" command line parameter and creating a portable copy from the GUI, the provided portable path isn't shown in the gui as one might expect.

### Description of how this pull request fixes the issue:
1. Added a "--disable-start-on-logon" command line parameter.
2. When the "--portable-path" parameter is provided at NVDA start, the provided pat is now pre filled in in the portable copy creation dialog.

### Testing performed:
Ran try build.

1. Just the launcher: in the installation dialog, use NVDA on logon was enabled.
2. launcher with --disable-start-on-logon: in the installation dialog, use NVDA on logon was disabled.
3. launcher with --install-silent and --disable-start-on-logon. IN the copy of NVDA that ran after installation, start on logon was disabled in the general settings.
4. Launcher with --portable-path: the provided portable path showed up in the create portable copy dialog.

### Known issues with pull request:
None

### Change log entry:
Provided in changes.t2t

2018-08-20 02:11 UTC, feerrenrut commented
Hate to question this further at this stage. But, I'm wondering if it might be more future proof to have this option as `--enable-start-on-logon [true|false]`.

This means that the command line option remains useful if we ever change the default. It also allows people to be specific about their expectations on the command line (whether that is to enable or disable), rather than relying on the implicit default behaviour.

2018-08-20 06:07 UTC, leonardder commented
I'm afraid having an enable command line parameter is problematic, as I 
think argparse is able to store either True or False, not True, False or 
None. In my opinion, enable-start-on-logon only makes sense if it really 
enables start on logon in every case. This is certainly something to 
explore though.

2018-08-21 03:36 UTC, feerrenrut commented
If we are able to be concrete about it and say the default is `enable-start-on-logon=True` then I think it would be my preference, but first we have to identify what variations in behaviour exist at the moment (which I think is what you were getting at with your last comment).

Otherwise, it looks like you can use a combination of `default` and `type` to ensure a boolean arg with a default of None:

```
>>> import argparse
>>> p = argparse.ArgumentParser()
>>> p.add_argument('--foo', default=None, type=bool)
_StoreAction(option_strings=['--foo'], dest='foo', nargs=None, const=None, default=None, type=<type 'bool'>, choices=None, help=None, metavar=None)
>>> p.parse_args(['--foo', 'True'])
Namespace(foo=True)
>>> p.parse_args(['--foo', 'False'])
Namespace(foo=True)
>>> p.parse_args([])
Namespace(foo=None)
>>> p.parse_args(['--foo', '"hello"'])
Namespace(foo=True)
>>> p.parse_args(['--foo', '0'])
Namespace(foo=True)
>>> p.parse_args(['--foo', '1'])
Namespace(foo=True)
>>> p.parse_args(['--foo', 0])
Namespace(foo=False)
```

Note that this appears to rely on casting the argument value to bool. But I don't think this should be a problem.

2018-08-21 05:43 UTC, leonardder commented
[**@feerrenrut**](https://github.com/feerrenrut) commented on [21 aug. 2018 05:36 CEST](https://github.com/nvaccess/nvda/pull/8623#issuecomment-414539338 "2018-08-21T03:36:48Z - Replied by Github Reply Comments"):
> Otherwise, it looks like you can use a combination of `default` and `type` to ensure a boolean arg with a default of None:

This works when throwing False or 0 at parse-args, but when providing 0 or False at the command line, it looks like it will still use the bool value of the string "0" or "False".

>>> bool("False")
True

We can probably fix this with an easy function though:

```
def stringToBool(s):
    return s.lower() not in ("0", "false", "off")
```

Then, use stringToBool as the type.

2018-08-26 06:28 UTC, derekriemer commented
If you make it optional, with a default of None what happens?

2018-08-27 06:11 UTC, leonardder commented
[**@derekriemer**](https://github.com/derekriemer) commented on [26 aug. 2018 08:28 CEST](https://github.com/nvaccess/nvda/pull/8623#issuecomment-416017253 "2018-08-26T06:28:56Z - Replied by Github Reply Comments"):
> If you make it optional, with a default of None what happens?

I updated the description of the pr to reflect your question.

2018-12-05 14:40 UTC, leonardder commented
@feerrenrut: I think I've addressed your concerns. A user can now provide enable-start-on-logon=True or --enable-start-on-logon=False to forcefully enable or disable starting at the logon screen when installing or updating. The default for --enable-start-on-logon is None, in which case the old behaviour applies (i.e. if updating, use the current value, else True)

2018-12-13 12:09 UTC, feerrenrut requested changes
Sorry, I forgot all about this PR. I'm generally happy with this, but have a suggestion to improve the user guide.

2018-12-13 12:09 UTC, feerrenrut commented on user_docs/en/userGuide.t2t
> +| None | --enable-start-on-logon=True|False | When installing, enable NVDA's start on the logon screen |
I think we could clarify that the default behaviour for a fresh install is to start NVDA on the logon screen, probably best to put that in the start at windows logon section. Then we link to the `StartAtWindowsLogon` section here:
```suggestion
| None | --enable-start-on-logon=True|False | When installing, enable NVDA's [start on the logon screen #StartAtWindowsLogon] |
```

2018-12-13 12:42 UTC, leonardder commented
Done, thanks for this. I added an additional sentence in the start at logon section.

2018-12-13 13:24 UTC, feerrenrut approved these changes

2018-12-13 13:45 UTC, merged