Improve support for combo boxes in Firefox / Chrome / Internet Explorer
nvaccess/nvda pull request #8687
Opened 2018-08-29 00:46 UTC by michaelDCurran

### Link to issue number:
Fixes #8664 

### Summary of the issue:
Currently in NVDA, the user experience when using combo boxes on the web significantly differs by browser, plus some of the original code written to handle combo boxes has now broken in multiple browsers.
For example:
*In Firefox, collapsing a combo box works, but browseMode is not re-enabled.
* In Chrome 68, focusing a collapsed combo box ends up focusing the active list item within the combo box, even though it is collapsed.
* In Chrome 68 and 70, collapsing a combo box with escape/enter/alt+upArrow simply switches to browseMode and does not collapse the combo box.
 
### Description of how this pull request fixes the issue:
This PR standardizes the way we handle combo boxes in browseMode, so that:
* Anything inside a combo box is treated as not being in the browseMode document. This means that if the combo box is expanded and focus is inside, browseMode completely ignores it.
* Alt+downArrow when in browseMode expands the combo box and switches to focus mode, but also remembers the combo box, so that the next focus event in browseMode (if it is for the combo box), switches back to browseMode again (as this means the combo box has been collapsed). Technically there is no need to toggle focus mode and browseMode at all, but this keeps UX compatible with previous NVDA versions.

This PR also partly works around a bug in Chrome 68 and below where focusing a collapsed combo box focuses the active list item within the combo box. This has been fixed in Chrome 70.

### Testing performed:
Tested a standard HTML select (size=1) in Firefox 52, Firefox Nightly, Chrome 68 and Chrome 70.
Arrowed to the combo box in browse mode. Pressed alt+downArrow. Arrowed through the list. And closed the combo box with either enter, escape or alt+upArrow.

### Known issues with pull request:
Combo boxes in Chrome 68 and below are still not perfect, but no worse than what they were before this PR. 
 
### Change log entry:
Bug fixes:
* Interacting with combo boxes on the web in Firefox, Chrome and Internet Explorer has been improved.

2018-08-29 06:25 UTC, leonardder commented on source/eventHandler.py
> +			obj=obj.focusRedirect
focusRedirect is used in the powerpnt appModule. We might have to make sure that this does not break. Having said that, I really like this being handled on the events level!

2018-08-30 06:54 UTC, LeonarddeR requested changes
I found the following issue in Firefox:

1. Explicitly disable browse mode with NVDA+space
2. Expand and collapse a combo box

Expected: Browse mode stays off
Actual: Browse mode enables after collapsing the combo box.

Also, I wonder whether it would make sense to have the activate script expand a combo box (for example when pressing space on a combo box when in browse mode).

2018-09-03 04:05 UTC, michaelDCurran commented
@leonardder: I fixed the issue you found with  NVDA switching back to browseMode after collapsing a combo box in focus mode. 
In regards to your query on whether we should automatically expand a combobox when pressing enter/space in browseMode: I don't think we should at this point in time as it is certainly valid to press enter/space on a combo box and then use the arrow keys to change the combo box value with out expanding it. This would no longer be possible, unless you explicitly switched to focus mode.

2018-09-03 05:09 UTC, leonardder commented
Your latter point makes sense indeed.

2018-09-03 23:04 UTC, michaelDCurran commented
Is there anything else I have to address?

2018-09-04 08:07 UTC, leonardder commented
Sorry it took me some time to get back to this.

I'm now observing the following in Firefox:

1. In firefox, select a combo box in browse mode.
2. Expand with alt+down arrow
3. Press tab

Expected: NVDA stays in focus mode and moves to the control in tab order after the combo box. This is how Edge and IE work.
Actual: The combo box is collapsed and focus stays on the combo box. Browse mode is reactivated. IN Chrome 68, the focus stays on the combo box as well, but Chrome stays in focus mode. Another tab brings you to the expected next item in the tab order.

Apart from that, the code looks ok.

2018-09-04 08:16 UTC, michaelDCurran commented
It seems that this is a deliberate choice by Firefox and Chrome to 
simply collapse the combo box when tab is pressed.

I don't really believe we should work around this one.

2018-09-04 09:08 UTC, LeonarddeR submitted a review, later dismissed
IN that case, I agree.

2018-09-04 10:29 UTC, merged