Python 3 imports: additional work on builtins, relative imports, importlib
nvaccess/nvda pull request #8727
Opened 2018-09-09 05:19 UTC by josephsl

### Link to issue number:
Fixes #8712
Fixes #8724
Fixes #8768

### Summary of the issue:
More work on Python 3 imports, including relative imports and changing __builtin__ to builtins, as well as using importlib to import modules at runtime.

### Description of how this pull request fixes the issue:
Changes made:

* Import __builtin__ -> builtins (Python Console, language handler).
* GUI and IAccessible objects: more relative imports (from . import ...).
* Use importlib to import modules at runtime, including for IAccessible modules.

### Testing performed:
Tested with Python 2.7 interpreter to make sure they are imported.

### Known issues with pull request:
None

### Change log entry:
None

2018-09-14 19:10 UTC, leonardder commented
[**@josephsl**](https://github.com/josephsl) commented on [14 Sep 2018, 16:25 CEST](https://github.com/nvaccess/nvda/pull/8727#issuecomment-421375157 "2018-09-14T14:25:28Z - Replied by Github Reply Comments"):
> Hi, importlib is new in Python 3 (if I read this correctly).

It is also there in Python 2.7. 

> Help on built-in function __import__ in module __builtin__:
>
> __import__(...)
>     __import__(name, globals={}, locals={}, fromlist=[], level=-1) -> module
>    
>     Import a module. Because this function is meant for use by the Python
>    interpreter and not for general use, it is better to use
>    importlib.import_module() to programmatically import a module.

2018-09-14 20:36 UTC, josephsl commented
Hi, I see. In this case, I propose doing this via a new pull request. Thanks.

 

From: Leonard de Ruijter <notifications@github.com> 
Sent: Friday, September 14, 2018 12:11 PM
To: nvaccess/nvda <nvda@noreply.github.com>
Cc: Joseph Lee <joseph.lee22590@gmail.com>; Author <author@noreply.github.com>
Subject: Re: [nvaccess/nvda] Python 3 imports: additional work on builtins, relative imports (#8727)

 

 <https://github.com/josephsl> @josephsl commented on 14 Sep 2018, 16:25 CEST <https://github.com/nvaccess/nvda/pull/8727#issuecomment-421375157> :

Hi, importlib is new in Python 3 (if I read this correctly).

It is also there in Python 2.7.

Help on built-in function import in module builtin:

import(...)
import(name, globals={}, locals={}, fromlist=[], level=-1) -> module

Import a module. Because this function is meant for use by the Python

interpreter and not for general use, it is better to use
importlib.import_module() to programmatically import a module.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub <https://github.com/nvaccess/nvda/pull/8727#issuecomment-421456660> , or mute the thread <https://github.com/notifications/unsubscribe-auth/AHgLkMnNPWG39Deuw8xp1sxP1qyVafteks5ua_81gaJpZM4WgJnV> .

2018-09-20 05:10 UTC, leonardder commented
I'd rather see this as part of this one. It creates unnecessary overhead if we have to change one line of code in this pr, and then change it again in the next.

See also #8768.

2018-09-20 06:18 UTC, josephsl commented
Hi,

By the way, there is an unused "import Queue" in synthDrivers.espeak (no underscore), so I'm ignoring that one. People who will be working on transition should note that this import causes an exception, so should be removed then.

Thanks.

2018-09-24 13:50 UTC, LeonarddeR requested changes

2018-09-24 13:50 UTC, leonardder commented on source/appModuleHandler.py
> -		mod = __import__("appModules.%s" % appName.encode("mbcs"),
This is definitely going to fail on python 3

```
>>> "hello, %s" % "test".encode("mbcs")
"hello, b'test'"
```

str.format gives the same result.

It should be sufficient to check if not isinstance(appName, str) before encoding to mbcs.

2018-09-24 14:56 UTC, leonardder commented
I'm again not very happy with the idea to touch code in one pr, knowing that it requires another change in a subsequent pr. then, we either better leave the code alone in this pr or fix it for good. I'm happy with either way, but not with leaving as is, honestly.

2018-09-24 15:00 UTC, josephsl commented
Hi, I’m willing to make an exception by addressing encoding problem as part of this PR with a comment stating that Python 3 improves Unicode support. Thanks.

 

From: Leonard de Ruijter <notifications@github.com> 
Sent: Monday, September 24, 2018 7:57 AM
To: nvaccess/nvda <nvda@noreply.github.com>
Cc: Joseph Lee <joseph.lee22590@gmail.com>; Mention <mention@noreply.github.com>
Subject: Re: [nvaccess/nvda] Python 3 imports: additional work on builtins, relative imports, importlib (#8727)

 

I'm again not very happy with the idea to touch code in one pr, knowing that it requires another change in a subsequent pr. then, we either better leave the code alone in this pr or fix it for good. I'm happy with either way, but not with leaving as is, honestly.



—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub <https://github.com/nvaccess/nvda/pull/8727#issuecomment-424004597> , or mute the thread <https://github.com/notifications/unsubscribe-auth/AHgLkM0GjtdsQgRBupdEpav_TxDlS9Wiks5uePLVgaJpZM4WgJnV> .

2018-09-25 19:14 UTC, josephsl commented
Hi,

Addressed the import concern as of today's commit. As noted in the commit message, I'm making an exception, as nobody else calling import_module calls name.encode apart from app module handler.

Thanks.

2018-09-25 19:30 UTC, leonardder commented
Never mind, I was horribly wrong there. This place actually encodes (goes from unicode from bytes), my head was telling me that we had to decode (from bytes to unicode). So if it would have been isinstance, the right clause would be `if not isinstance(appname, str):`

2018-09-25 19:30 UTC, LeonarddeR approved these changes

2018-12-07 19:14 UTC, josephsl commented
Hi,

@feerrenrut, may I request a second look for this one? I'm interested in seeing if conflicts may arise when attempting to merge this pull request in the future.

Thanks.

2019-05-02 14:01 UTC, feerrenrut approved these changes
This looks good to me. Given that it is tested against python 2.7, I think we should merge it in now. We don't have any intention of continuing to support Python 2.7 once we move over to 3 so I will add a task to the python 3 project board to remove any 2.7 specific code.

2019-05-02 14:19 UTC, leonardder commented
I agree.

2019-05-02 14:22 UTC, merged

2019-05-29 06:08 UTC, josephsl commented
Possible regression reported: multi-byte file name issue. Multiple possibilities, including Python 2.7.16, this PR, or something else.

Thanks.

2019-06-04 07:28 UTC, leonardder commented
@josephsl: Could you please file this again against threshold?

2019-06-04 10:13 UTC, josephsl commented
Hi, yep that’ll be done (today at the earliest) with at least two separate PR’s: imports in one package, importlib in another. Thanks.

 

From: Leonard de Ruijter <notifications@github.com> 
Sent: Tuesday, June 4, 2019 12:29 AM
To: nvaccess/nvda <nvda@noreply.github.com>
Cc: Joseph Lee <joseph.lee22590@gmail.com>; Mention <mention@noreply.github.com>
Subject: Re: [nvaccess/nvda] Python 3 imports: additional work on builtins, relative imports, importlib (#8727)

 

@josephsl <https://github.com/josephsl> : Could you please file this again against threshold?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub <https://github.com/nvaccess/nvda/pull/8727?email_source=notifications&email_token=AB4AXEE7F2SOX2QQ4RSJ7ETPYYKTJA5CNFSM4FUATHK2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODW3VVSY#issuecomment-498555595> , or mute the thread <https://github.com/notifications/unsubscribe-auth/AB4AXEGNIJMDUODN4Z4IMVDPYYKTJANCNFSM4FUATHKQ> .