Work around crash in Google Chrome when navigating tweets on twitter.com
nvaccess/nvda pull request #8779
Opened 2018-09-25 04:45 UTC by michaelDCurran

### Link to issue number:
Fixes #8777 

### Summary of the issue:
Google Chrome crashes when navigating tweets in twitter.com due to a buffer overrun in Chrome's implementation of IAccessible2_2::relationTargetsOfType.
NVDA started calling relationTargetsOfType in pr #8352. 

### Description of how this pull request fixes the issue:
This PR works around the crash by making use of the fact that chrome's relationTargetsOftype works okay when requesting all targets (numRelations is 0) rather than a specific number of them that may be smaller than the total amount.

### Testing performed:
Tested NVDA and Chrome using the testcases in #8777.
And again with tests in pr #8352  

 ### Known issues with pull request:
None.

### Change log entry:
Already in PR.

2018-09-25 04:48 UTC, michaelDCurran commented
As this causes a crash, introduced in the 2018.3 release cycle, this should be  made available in a 2018.3 minor release.
@feerrenrut  could you please review this with priority so I can release an rc and then 2018.3.2.

2018-09-25 06:34 UTC, feerrenrut requested changes

2018-09-25 06:34 UTC, feerrenrut commented on nvdaHelper/vbufBackends/gecko_ia2/gecko_ia2.cpp
> +	if(this->toolkitName.compare(L"Chrome")==0) {
`toolkitName` might be null. This function should probably check for this.

2018-09-25 06:40 UTC, michaelDCurran commented
toolkitName is an std::wstring. It could be empty, but never null.

compare simply won't return 0 if it is empty.

2018-09-25 07:10 UTC, feerrenrut commented
Oh, of course it is. But then its assigned from a `BSTR`, I think this needs to be:
```
this->toolkitName = std::wstring(toolkitName, SysStringLen(toolkitName));
```
Check https://stackoverflow.com/a/6284978

2018-09-25 22:31 UTC, michaelDCurran commented
Done now.

2018-09-26 00:48 UTC, feerrenrut approved these changes

2018-09-26 03:40 UTC, merged