change order of informations presented by CTRL+NVDA+f1, to make changeable info presented first.
nvaccess/nvda pull request #8927
Opened 2018-11-07 17:10 UTC by lukaszgo1

### Link to issue number:
Fixes #7338
### Summary of the issue:
When pressing CTRL+NVDA+F1 the order of information's is not optimal.
### Description of how this pull request fixes the issue:
The changeable parts i.e. application name, and app module name are now presented first.
### Testing performed:
Tested, that script still present the same info, but in the different order.
### Known issues with pull request:
None
### Change log entry:
This command isn't even included in the user guide, so i believe, that Change log entry isn't nesesary.

2018-11-07 17:48 UTC, jscholes commented
I think this change itself is minor, and as you mentioned the command isn't mentioned in the user guide.  However, there is no seperator between your two messages, be it a comma, a similar character or the word "and".  This results in strings like:

> explorer.exe is currently running Explorer module is loaded

with the information running together.

2018-11-07 18:04 UTC, lukaszgo1 commented
@jscholes Thanks for your commends. I assumed, that the space at the beginning of the second message would be sufficient, but adding a dot after the first looks like a good solution.

2018-11-08 12:31 UTC, leonardder commented
Now while we're at it, I think I prefer swapping the order as well. First report the app module, than the executable name. This makes it more intuitive to hear whether a specific appmodule is loaded for an app.

2019-04-20 18:57 UTC, lukaszgo1 commented
It'd be nice to have this reviewed.

2019-05-09 17:22 UTC, feerrenrut commented
> It'd be nice to have this reviewed.

I'm looking at it now. In the future, please use the "request review" button. Though saying that, do you have access to it?

2019-05-09 17:29 UTC, lukaszgo1 commented
No i don't as per this commend in the GitHub documentation 

> Note: Pull request authors can't request reviews unless they are either a repository owner or collaborator with write access to the repository.

2019-05-09 17:34 UTC, feerrenrut commented
Ah, I see. My apologies.

2019-05-09 17:38 UTC, feerrenrut requested changes

2019-05-09 17:38 UTC, feerrenrut commented on source/globalCommands.py
> +			# For example, the complete message for Windows explorer is: Explorer.exe is currenty running. explorer module is loaded..
There is an extra tab here, and the order of the messages in the example is not correct. Please also put quote characters around the example to make it clear.

```suggestion
		# EG: "explorer module is loaded. Explorer.exe is currenty running."
```

2019-05-09 17:42 UTC, leonardder commented
[**@feerrenrut**](https://github.com/feerrenrut) commented on [9 May 2019, 19:22 CEST](https://github.com/nvaccess/nvda/pull/8927#issuecomment-490992334 "2019-05-09T17:22:38Z - Replied by Github Reply Comments"):
> I'm looking at it now. In the future, please use the "request review" button. Though saying that, do you have access to it?

Unfortunately, only collaborators can access this.

2019-05-10 10:24 UTC, lukaszgo1 commented
@feerrenrut I believe I have addressed your commend.

2019-05-10 11:00 UTC, feerrenrut approved these changes
Thanks @lukaszgo1

2019-05-10 11:50 UTC, feerrenrut commented
There should still be a change log entry. I will add something along the lines of:

**changes for developers**
```
When using the report module info command, the order of information has changed to present the module first. (#7338)
```

2019-05-10 11:54 UTC, merged