Add support for Foxit Reader and Foxit PhantomPDF (#8944)
nvaccess/nvda pull request #8947
Opened 2018-11-15 09:59 UTC by gauldoth

### Link to issue number:
Closes #8944

### Summary of the issue:
It is currently not possible to read PDF files in Foxit Reader.

Foxit Reader has implemented MSAA and PDF Dom interface in version 9.3.
The UIA implementation is not complete yet. Out of process queries are quite slow due to some unknown reasons. But their developers have implemented both MSAA and PDDom for the document, the UIA implementation may be removed in future releases.

Foxit PhantomPDF exposed the same interface as Foxit Reader did.

### Description of how this pull request fixes the issue:
Use Adobe Acrobat code to make Foxit Reader accessible.
Ignore Foxit Reader's UIA implementation.

### Testing performed:
Tested with Foxit Reader 9.3 and Foxit PhantomPDF 9.3 by me.
Tested with several PDF documents and PDF forms by me.
The guys from Foxit have tested against NVDA for a few weeks.

### Known issues with pull request:
None

### Change log entry:

Section: New features

* Add support for Foxit Reader and Foxit Phantom PDF (#8944)

2018-11-15 11:59 UTC, LeonarddeR requested changes
Thanks for this great work!

2018-11-15 11:59 UTC, leonardder commented on source/_UIAHandler.py
> +	"FoxitDocWnd",
Could you put a comment above this alone? Something like:

`# #8944: The Foxit UIA implementation is incomplete and should not be used for now.`

2018-11-15 11:59 UTC, leonardder commented on user_docs/en/changes.t2t
> +- Added support for Foxit Reader and Foxit PhantomPDF. (#8944)
Could you revert the changes to this file altogether? Changing the changes file will be taken care of before merging this pr.

2018-11-15 15:08 UTC, gauldoth commented
@leonardder Thanks for the review.
I have addressed your review comments.

2018-11-15 16:01 UTC, LeonarddeR approved these changes

2018-11-15 16:02 UTC, leonardder commented
@gauldoth: Will this do or break anything when using version 9.2 or older?

2018-11-15 16:32 UTC, josephsl commented
Hi,

Congratulations on the first contribution.

Can we get a second look from @MichaelDCurran or someone at NV Access please?

Footnote: this code is compatible with Python 3.

Thanks.

2018-11-15 19:29 UTC, gauldoth commented
> @gauldoth: Will this do or break anything when using version 9.2 or older?

It won't. If the window class name "FoxitDocWnd" is detected, the MSAA and PDDom interface is available.

2018-11-18 23:08 UTC, michaelDCurran approved these changes

2018-11-18 23:11 UTC, merged