Fix regression when reading and deleting text in MS Excel edit fields.
nvaccess/nvda pull request #9063
Opened 2018-12-13 13:49 UTC by lukaszgo1

## Link to issue number:
Fixes #9042
### Summary of the issue:
When #8165 was introduced it was assumed, that if particular edit field exposes line information it do not have to be accessed via displayModel. It unfortunately broke accessibility of most edit fields in Excel.
### Description of how this pull request fixes the issue:
For the class used by these fields displayModel is used again.
### Testing performed:
Tested with go to, find and custom list editing in Microsoft Excel 2010 and 2019.
### Known issues with pull request:
I am pretty new to this part of the code, so it is possible, that it should be solved in a completely different way. @leonardder your opinion would be appreciated.
### Change log entry:

Section: Bug fixes

NVDA will again track cursor and announce deleted characters in edit fields in Microsoft Excel such as go to or find.

2018-12-13 14:16 UTC, LeonarddeR requested changes
I think we should do either one of the following.

1. Create a list of badUdentifiedEditClassNames and list this window class in there.
2. If this window class is specific to Excel, which I think it is, this should be handled in an Excel appModule
3. Similar to the windowText and windowTextLineCount properties, create a windowTextLength property that fetches the window text length:
    `return watchdog.cancellableSendMessage(nav.windowHandle,winUser.WM_GETTEXTLENGTH,0,0)`
    Then, only set UnidentifiedEdit as an overlay if there is text in the control. For Excel, this returns 0 even though there is text. A drawback of this approach is that unidentified text edits will always initialize with a display model overlay class when they are found to be empty.

This is clearly a bad implementation in Excel, as the text is perfectly provided using the window text.

@MichaeldCurran: Do you have thoughts about this? I prefer either 2 or 3.

2018-12-13 20:12 UTC, lukaszgo1 commented
For me option two looked most reasonable, so I've committed required changes. Of course if @michaelDCurran would have a different opinion I am ready to reorganize it.

2018-12-20 07:58 UTC, LeonarddeR requested changes
I think this is the way to go indeed.

2018-12-20 07:58 UTC, leonardder commented on source/appModules/excel.py
> +		# #9042 Edit fields in Excel have to be accessed via displayModel.
There usually is a colon after the issue number in such comments.

```suggestion
 		# #9042: Edit fields in Excel have to be accessed via displayModel.
```

2018-12-20 07:58 UTC, leonardder commented on source/appModules/excel.py
> +			clsList.insert(0, DisplayModelEditableText)
You will also have to import UnidentifiedEdit from NVDAObjects.window.edit and remove that from the clsList. Make sure to wrap this in a try/except statement. See the putty module as an example.

2018-12-22 17:05 UTC, lukaszgo1 commented
@leonardder All your commends are now addressed.

2019-01-05 15:07 UTC, LeonarddeR approved these changes

2019-01-14 00:44 UTC, michaelDCurran approved these changes

2019-01-14 01:09 UTC, merged