Fast browse mode v2
nvaccess/nvda pull request #9360
Opened 2019-03-09 22:42 UTC by mltony

This PR is work in progress and is not ready for review. I'm publishing it for now just for the reference. I will send an explanation email to nvda-devel mailing list in just a few minutes.

2019-03-21 07:13 UTC, leonardder commented
@mltony: could you please merge master to fix the failing tests?

2019-03-21 14:45 UTC, mltony commented
Leonard, this is a draft pull request, it is not ready to be merged or 
even reviewed. I only published it as a reference - I was hoping that 
you or Michael could take a look at it and figure out why multiple 
NVDAObjects are being created for the same checkbox in browsers - for 
more details see my thread in NVDA-devel mailing list.

--Tony


On 3/21/2019 12:13 AM, Leonard de Ruijter wrote:
>
> @mltony <https://github.com/mltony>: could you please merge master to 
> fix the failing tests?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/nvaccess/nvda/pull/9360#issuecomment-475131221>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/AhMRnDS20G5slNoA6kH2gmXbv7orD0ciks5vYzEOgaJpZM4bm8nN>.
>

2019-03-28 01:13 UTC, dingpengyu commented
hi
@mltony 
could you please merge master to fix the failing tests?

2019-04-16 17:05 UTC, leonardder commented
@mltony: Another kind request to merge master. This ensures that reviewers are able to test your code. We don't have a working snapshot at this moment, so we can't test the code in action, unless running from source.

2019-04-17 05:37 UTC, LeonarddeR requested changes
First, I know that this is still a draft. However, for the first instance of this pr, I haven't had the time to closely look at it. I'm pretty sure these issues were already there, and I would have commented on these areas of the code if I'd have reviewed it.

2019-04-17 05:37 UTC, leonardder commented on source/NVDAObjects/window/__init__.py
> +		return self.windowHandle
I wonder how often window handles get reused.

```suggestion
		return (self.processID, self.windowHandle)
```

2019-04-17 05:37 UTC, leonardder commented on source/NVDAObjects/__init__.py
Could you please add uniqueID to the base NVDAObject, along with a doc string saying what it is supposed to be? I guess for the vanilla NVDAObject, hash(self) might suffice.

2019-04-19 06:11 UTC, leonardder commented
@mltony: I've been able to fix the issue as you described on NVDA Devel. Probably not the most elegant solution, however as it only takes two additional lines of code, I think it is by far the most effective.
You noted on NVDA Devel that you currently do not have the time to work on this. I guess we have three options:

1. We will use this pull request for the work, and I will push my changes directly to your branch
2. I will close this one and open a new pull request. This will make it easier to use this pull request as a reference.
3. I can file a pull request against your branch that incorporates the necessary changes. This, however, requires more work on your end, since you have to approve the changes and merge them.

Please let me know whatever you prefer. I personally prefer option 2.

2019-04-19 14:05 UTC, leonardder commented
[Here is a try build](https://ci.appveyor.com/api/buildjobs/xigep6w8jjru9vpb/artifacts/output%2Fnvda_snapshot_try-fastBrowseMode-17095%2Ceb2d9009.exe)

2019-04-19 16:51 UTC, mltony commented
@leonardder, Since you prefer #2, please go ahead with it. I am not that familiar with github and it would take me some time to figure out how to grant you permissions to push into my repo. So I prerfer #2 as well. Also could you share with me your branch - I'm curious how you fixed it in just 2 lines.
Anyway, thanks for your help!

2019-04-20 06:44 UTC, leonardder commented
Thanks, I'll close this for now and will discuss with @michaeldcurran how to bring this further. I will open a draft pr for my code changes later this weekend or next week.

In short, I added these lines to event_gainFocus in browseMode:

```
				if (
					not config.conf["virtualBuffers"]["focusFollowsBrowse"]
					and obj == self._lastFocusableObj
					and obj is not self._lastFocusableObj
				):
					speech.speakObject(self._lastFocusableObj,controlTypes.REASON_CHANGE)
```

This covers exactly this case. I agree it is not very elegant though, but it has to be discussed with NV Access how to bring this to a success without disturbing future work. Speech refactor and python 3 are really important things that have to be done in the very near term.

2019-04-20 06:44 UTC, closed without merging

2019-04-21 17:50 UTC, mltony commented
Thanks @leonardder, I really appreciate your help!

2019-04-22 11:25 UTC, leonardder commented
You're welcome

2019-04-27 17:37 UTC, mltony commented
@leonardder, I tried your test build and it works beautifully for me. All the fast browse mode functionality is working plus the bug with checkboxes is fixed indeed. Looking forward towards having this PR in the next release of NVDA!