Correct focus in Objects Explorer (vs2017 and up)
nvaccess/nvda pull request #9415
Opened 2019-03-28 17:40 UTC by francipvb

### Link to issue number:
Closes #9311 
### Summary of the issue:
In visual studio 2017 (version 15.3 and up), the object explorer window is not working properly due to an incorrect MSAA implementation.
See #9313 for a previous approach to solve this.
### Description of how this pull request fixes the issue:
This adds an overlay class for the tree view items in object explorer. It takes a `gainFocus` event and checks for its states
If `STATE_FOCUSED` is not in the states set, it redirects the event to the real focused object.
I'm not really sure if it is the right way of doing this.
### Testing performed:
Tested against visual studio 15.9 and up to 16.0.rc4.
### Known issues with pull request:
State changes are not reported for secondary items, so expand and contract events are not reported by NVDA. I don't have more information.
### Change log entry:

Section: Bug fixes

* In visual studio 2017 and up, in *Objects Explorer* window, selected item in objects tree or members tree with categories is reported correctly again. (#9311)

2019-03-28 17:42 UTC, francipvb commented
cc @leonardder

2019-03-29 14:02 UTC, codeofdusk commented
Could you maybe use the focus redirection system instead of getting `event_gainFocus`?

2019-03-31 21:04 UTC, lukaszgo1 commented
@francipvb You're importing ui in the appModule hovewer it isn't used anywhere - probably left when debugging.

2019-04-01 22:29 UTC, francipvb commented
Hello,

> 
> 
> Could you maybe use the focus redirection system instead of getting `event_gainFocus`?

Thanks, done. It is a more clean approach 👍 

> 
> 
> @francipvb You're importing ui in the appModule hovewer it isn't used anywhere - probably left when debugging.

Fixed too, thanks. 👍 

Cheers,

2019-04-10 18:18 UTC, leonardder commented
@dantegagne: Do you think there could be a possibility to fix this in Visual Studio itself?

2019-04-10 18:24 UTC, LeonarddeR requested changes
Just some small things

2019-04-10 18:24 UTC, leonardder commented on source/appModules/devenv.py
> +		vs_major, vs_minor, rest = self.productVersion.split(".", 2)
```suggestion
		vsMajor, vsMinor = map(int, self.productVersion.split(".", 2)[:2])
```

You can also remove the lina below. Note the change from vs_major to vsMajor, vs_minor to vsMinor, which is more like the general code style of NVDA.

2019-04-27 17:30 UTC, LeonarddeR approved these changes
I think this is ok from a code perspective. I need to have a look with Visual Studio, probably next week.
In the meanwhile, could you please update the initial description of the pr to reflect the current implementation (i.e. with focusRedirect instead of patching event_gainFocus)?

2019-05-06 17:59 UTC, feerrenrut approved these changes
@leonardder I'm going to merge this in, would you mind reporting back here if there are any issues with the focus in the object explorer window.

2019-05-06 18:01 UTC, merged