Fix error when copying to system config
nvaccess/nvda pull request #9449
Opened 2019-04-03 19:06 UTC by feerrenrut

Dont copy folders that previously allowed unpackaged addons to be run.
These folders ('appModules','brailleDisplayDrivers','globalPlugins',
'synthDrivers') are now only used if they are within the scratchpad
directory and the advanced option is turned on.
See commit: d1a8a710d37f5a376ebf9f32600d7cb857554b38

Since we are not copying these folders, and the contents would not be run
even if they were copied, we no longer warn about them.

A log message is added if they are present and we skip over them.

### Link to issue number:
Fixes #9448 

### Summary of the issue:
For a fresh install, when a user tries to copy settings to the system config, an error sound is heard and nothing happens.

Before copying settings to the system profile, NVDA was checking for any files inside the following directories:
- 'addons'
- 'appModules'
- 'brailleDisplayDrivers'
- 'globalPlugins'
- 'synthDrivers'

However, when these folders do not exist an error is raised and the method does not complete.

### Description of how this pull request fixes the issue:
Now only warn the user about the presence of files inside the addons directory. Do not copy any of the other folder contents, these files will not be considered during NVDA runtime any more (see commit: d1a8a710d37f5a376ebf9f32600d7cb857554b38). 

### Testing performed:
1. Delete the contents of my system config directory
1. Deleted the above listed folders from my user config directory
1. Installed NVDA
1. From the general panel (`NVDA+control+g`), press the button to copy to system config.
1. Ensure there is no error, and the config has been copied.

Repeat, after adding a "appModules" folder in my user configuration. Ensure that the system config does not contain an "appModules" folder, and there is a debug level log entry explaining it has been ignored.

### Known issues with pull request:

### Change log entry:
Section: Bug fixes

` - An issue has been fixed which prevented copying a users configuration to the system configuration profile. (#9448)`

2019-04-03 23:25 UTC, michaelDCurran approved these changes

2019-04-03 23:43 UTC, michaelDCurran requested changes
If any of the ignored directories contain subdirectories (E.g. globalPlugins contains a python package) then os.walk will still walk into it and copy it I think.
As os.walk returns curDir,subdirs,files, and because subdirs is mutable, you can:
If curDir is equal to fromPath, then you can subdirs.remove(x) for each item in the scratchpad dirs, catching valueError if one does not exist. 
Then os.walk will no longer walk into that directory at all.

2019-04-05 10:53 UTC, leonardder commented
I guess it is possible to change the base branch of this without creating a new pr. I requires a rebase, though.

2019-04-05 14:57 UTC, feerrenrut commented
I checked, the strings that have been moved are still translated.

2019-04-07 23:16 UTC, michaelDCurran approved these changes

2019-04-07 23:24 UTC, merged