Windows Store edition: disable developer scratch user interface
nvaccess/nvda pull request #9450
Opened 2019-04-03 23:42 UTC by josephsl

### Link to issue number:
Fixes #9438 

### Summary of the issue:
In Windows Store edition of nVDA, developer scratchpad user interface is shown when third-party modules are not supported yet.

### Description of how this pull request fixes the issue:
In Preferences/Advanced, disable developer scratchpad 9checkbox and theo pen button) if config.isAppX is in effect.

### Testing performed:
Tested with source code copy with config.isAppX set to true, along with a Windows Store side loadable version of NVDA with changes applied.

### Known issues with pull request:
None

### Change log entry:
None

2019-04-03 23:42 UTC, josephsl commented
Hi,

Actually, I think a review from Mick would suffice unless Reef says a visual UI review might be useful. Thanks.

2019-04-04 01:51 UTC, michaelDCurran requested changes

2019-04-04 01:51 UTC, michaelDCurran commented on source/gui/settingsDialogs.py
> +		# #9438: Windows Store version does not allow add-ons to be loaded, so there is no point enabling this.
I don't think this comment is supposed to be this high up?

2019-04-04 01:51 UTC, michaelDCurran commented on source/gui/settingsDialogs.py
> +			sHelper.addItem(devGroup)
Surely we should keep the grouping and controls around, but just disable the controls, like you are already doing below?

2019-04-04 02:10 UTC, josephsl commented
Hi,

Comment: I placed it up there because it describes the whole dev group sizer and controls inside it. Perhaps I may need to find either an alternative place for it or rewrite it.

Disabling the dev group panel: I'll look into this in a moment.

Thanks.

2019-04-04 03:38 UTC, michaelDCurran approved these changes

2019-04-04 03:38 UTC, merged