txt2tags for python3 #8734
nvaccess/nvda pull request #9648
Opened 2019-05-31 10:14 UTC by nishimotz

### Link to issue number:

#8734

### Summary of the issue:

This PR is against the threshold branch.
It replaces txt2tags.py and keyCommandDoc.py with my work of https://github.com/nvdajp/txt2tags.
Note that nvda-misc-deps is forked and https://github.com/nvdajp/nvda-misc-deps is used.

### Description of how this pull request fixes the issue:

Part of this repository is verified that it can make the same documents using Python 3.7.3.

### Testing performed:

This repository itself is not tested.

### Known issues with pull request:

### Change log entry:

Section: New features, Changes, Bug fixes

2019-05-31 10:28 UTC, zstanecic commented
Hi,

I am against putting the changelog item for this into the new features section, at it is a developers change not visible for the end-user.

 

From: Takuya Nishimoto <notifications@github.com> 
Sent: Friday, May 31, 2019 12:15 PM
To: nvaccess/nvda <nvda@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: [nvaccess/nvda] txt2tags for python3 #8734 (#9648)

 


Link to issue number:


#8734 <https://github.com/nvaccess/nvda/issues/8734> 


Summary of the issue:


This PR is against the threshold branch.
It replaces txt2tags.py and keyCommandDoc.py with my work of https://github.com/nvdajp/txt2tags.
Note that nvda-misc-deps is forked and https://github.com/nvdajp/nvda-misc-deps is used.


Description of how this pull request fixes the issue:


Part of this repository is verified that it can make the same documents using Python 3.7.3.


Testing performed:


This repository itself is not tested.


Known issues with pull request:


Change log entry:


Section: New features, Changes, Bug fixes

  _____  


You can view, comment on, or merge this pull request online at:


  https://github.com/nvaccess/nvda/pull/9648


Commit Summary


*	txt2tags for python3 #8734


File Changes


*	M .gitmodules <https://github.com/nvaccess/nvda/pull/9648/files#diff-0>  (2) 
*	M keyCommandsDoc.py <https://github.com/nvaccess/nvda/pull/9648/files#diff-1>  (15) 
*	M miscDeps <https://github.com/nvaccess/nvda/pull/9648/files#diff-2>  (2) 


Patch Links:


*	https://github.com/nvaccess/nvda/pull/9648.patch
*	https://github.com/nvaccess/nvda/pull/9648.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub <https://github.com/nvaccess/nvda/pull/9648?email_source=notifications&email_token=ACVCDE76TRDRUTBGEQBKKM3PYD3AVA5CNFSM4HRXXVV2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GW5QBAQ> , or mute the thread <https://github.com/notifications/unsubscribe-auth/ACVCDE34Y3GCJRUO2SFUWJTPYD3AVANCNFSM4HRXXVVQ> .

2019-05-31 11:06 UTC, LeonarddeR requested changes
1. Could you also process site_scons/site_tools/t2t.py
2. It would be good to know what you did to get this result. Was it simply running the code through 2to3?
3. I assume you're still planning to file a pr against nvda-misc-deps for txt2tags itself?

2019-05-31 11:06 UTC, leonardder commented on keyCommandsDoc.py
> +LINE_END = "\r\n"
I'm not against this change, but it is unnecessary.

2019-05-31 11:06 UTC, leonardder commented on keyCommandsDoc.py
> +			headingText = "{id}{txt}{id}{label}".format(
Same as above

2019-05-31 11:06 UTC, leonardder commented on keyCommandsDoc.py
> +		self._kc.write("| {name} | {keys} | {desc} |{lineEnd}".format(
Same as above

2019-05-31 11:06 UTC, leonardder commented on keyCommandsDoc.py
> +			keys=" | ".join(keys),
Same as above

2019-05-31 13:50 UTC, nishimotz commented on .gitmodules
> +	url = https://github.com/nvdajp/nvda-misc-deps
1. The threshold branch already has t2t.py which is the same as my work.

2. I have used modernizer, then manually tweaked regarding string.join and others. Finally, the same document is generated.

3. PR against nvda-misc-deps is as follows:
https://github.com/nvaccess/nvda-misc-deps/pull/12

2019-06-04 07:35 UTC, LeonarddeR requested changes
Just one thing

2019-06-04 07:35 UTC, leonardder commented on keyCommandsDoc.py
> +#Copyright (C) 2018-2019 Takuya Nishimoto
Please remove this line

2019-06-10 10:39 UTC, LeonarddeR approved these changes

2019-06-10 10:40 UTC, leonardder commented
@michaeldcurran: as soon as https://github.com/nvaccess/nvda-misc-deps/pull/12 is merged, this needs an update of misc-deps to master.

2019-06-11 02:39 UTC, michaelDCurran approved these changes

2019-06-11 02:42 UTC, merged