UI Automation in Windows Console: add focus redirection for the UIA console main window
nvaccess/nvda pull request #9674
Opened 2019-06-05 09:12 UTC by codeofdusk

### Link to issue number:
Builds on #9614.

### Summary of the issue:
Currently, in UIA consoles:

* Sometimes, attempting to interact with the console too quickly after focusing the window can make NVDA unable to get any caret or review information or receive new text events.

### Description of how this pull request fixes the issue:
This PR adds focus redirection from the console application's window to its text area.

### Testing performed:
This issue is hard to reproduce, but switching to the console and quickly interacting with it seemed to work after this change.

### Known issues with pull request:
None known.

### Change log entry:
None.

2019-06-05 22:53 UTC, codeofdusk commented
CC @feerrenrut @leonardder @michaelDCurran

2019-06-06 09:21 UTC, LeonarddeR requested changes

2019-06-06 09:21 UTC, leonardder commented on source/NVDAObjects/UIA/__init__.py
> -			from .winConsoleUIA import winConsoleUIA
Could you add a `findExtraOverlayClasses` method to the winConsoleUIA module? See NVDAObjects.IAccessible.mozilla.

2019-06-07 07:11 UTC, LeonarddeR approved these changes

2019-06-07 07:11 UTC, leonardder commented on source/NVDAObjects/UIA/winConsoleUIA.py
> +	if obj.UIAElement.cachedAutomationId == "Console Window":
Please make this an elif

2019-06-11 00:19 UTC, michaelDCurran approved these changes

2019-06-11 00:19 UTC, merged