Python3: fix NVDA's logging infrastructure
nvaccess/nvda pull request #9712
Opened 2019-06-10 19:51 UTC by michaelDCurran

### Link to issue number:
None.

### Summary of the issue:
In Python3: several issues cause NVDA's logging to fail:
* NVDA makes use of logging._levelNames which no longer exists in Python3.
* When NvDA calculates a code path when logging, it accesses a function's code object via its func_code property. In Python3 this is now ```__code__```.
* As strings are now unicode, and files that are opened in text mode deal in unicode, NVDA's logHandler.FileHandler no longer works. 
 
### Description of how this pull request fixes the issue:
* No longer use logging._levelNames, rather use logging.getLevelName.
* Changed logHandler.getCodePath to use ```__code__``` instead of func_code.
* logHandler.FileHandler now inherits from logging.Filehandler rather than the lower-level StreamHandler, and no longer converts to utf8 before writing. Rather the File object itself handles the utf8 encoding.

### Testing performed:
Started NVDA under Python3. Info messages and tracebacks were successfully logged.

### Known issues with pull request:
None.

### Change log entry:
None.

Section: New features, Changes, Bug fixes

2019-06-11 06:43 UTC, LeonarddeR approved these changes
Just a few comments

2019-06-11 06:43 UTC, leonardder commented on source/logHandler.py
>  # #7105: Python 3 split the following into two dictionaries.
This comment seems now obsolete.

2019-06-11 06:43 UTC, leonardder commented on source/logHandler.py
> -				if memberType is FunctionType and member.func_code is f.f_code:
I think I prefer something like `if isinstance(member, FunctionType)` while at it. Don't insist, though.

2019-06-11 06:43 UTC, leonardder commented on source/logHandler.py
>  				elif memberType is classmethod and type(member.__func__) is FunctionType and member.__func__.func_code is f.f_code:
Also note this line if you touch the former.

2019-06-11 06:43 UTC, leonardder commented on source/logHandler.py
> +		return logging.FileHandler.handle(self,record)
Can't you just call super here, or do you really want to be explicit?

2019-06-11 14:16 UTC, feerrenrut requested changes
There are still a few references to `func_code` in this file, could you check the rest of the code-base while you are at it? Could you also check for `logging._levelNames` in the rest of the code-base too?

Note, there are a few review comments from Leonard as well.

2019-06-11 21:49 UTC, michaelDCurran commented
I had previously grepped for any other uses of _levelNames and corrected them. There are none left.

2019-06-11 21:58 UTC, michaelDCurran commented
I have addressed review comments. Though didn't change  the 'is' to an isinstance as this was existing code and I'm trying to avoid changing anything not necessary to change due to Python 3.

2019-06-12 08:13 UTC, feerrenrut approved these changes

2019-06-12 09:02 UTC, merged