Python 3: zip function -> list(zip), itertools.izip -> zip()
nvaccess/nvda pull request #9729
Opened 2019-06-12 22:15 UTC by josephsl

Hi,

Discovered through a series of failing unit tests:

### Link to issue number:
None

### Summary of the issue:
Python 2 and 3 zip functions have different behaviors: returns a list in Python 2 vs an iterator in Python 3.

### Description of how this pull request fixes the issue:
Changed instances of zip() function call to list(zip), as well as rename itertools.izip to zip().

Steps:

1. Grep "zip(" source.
2. First, wrap language handler zip function inside a list call.
3. Convert itertools.izip to zip and remove itertools import from IA1 mozilla text module.

### Testing performed:
Tested in Python 2 and 3 interpreters.

### Known issues with pull request:
None

### Change log entry:
None

2019-06-13 03:56 UTC, LeonarddeR requested changes

2019-06-13 03:56 UTC, leonardder commented on source/NVDAObjects/IAccessible/ia2TextMozilla.py
> +		for (selfAncTi, selfAncObj), (otherAncTi, otherAncObj) in zip(selfAncs[maxAncIndex::-1], otherAncs[maxAncIndex::-1]):
Please split this line while at it

2019-06-13 03:56 UTC, leonardder commented on source/languageHandler.py
> +	# #7105 (Py3 review required): Python 2 list 0> Python 3 iterator.
I don't think this comment is necessary. Furthermore, it contains a typo.

2019-06-13 04:07 UTC, josephsl commented
Hi, done – hopefully the split lines are what you are looking for. Thanks.

 

From: Leonard de Ruijter <notifications@github.com> 
Sent: Wednesday, June 12, 2019 8:57 PM
To: nvaccess/nvda <nvda@noreply.github.com>
Cc: Joseph Lee <joseph.lee22590@gmail.com>; Author <author@noreply.github.com>
Subject: Re: [nvaccess/nvda] Python 3: zip function -> list(zip), itertools.izip -> zip() (#9729)

 

@leonardder requested changes on this pull request.

  _____  

In source/NVDAObjects/IAccessible/ia2TextMozilla.py <https://github.com/nvaccess/nvda/pull/9729#discussion_r293196651> :

> @@ -628,7 +627,7 @@ def compareEndPoints(self, other, which):
               otherAncs = self._getAncestors(otherTi, otherObj)
               # Find the first common ancestor.
               maxAncIndex = min(len(selfAncs), len(otherAncs)) - 1
-              for (selfAncTi, selfAncObj), (otherAncTi, otherAncObj) in itertools.izip(selfAncs[maxAncIndex::-1], otherAncs[maxAncIndex::-1]):
+              for (selfAncTi, selfAncObj), (otherAncTi, otherAncObj) in zip(selfAncs[maxAncIndex::-1], otherAncs[maxAncIndex::-1]):

Please split this line while at it

  _____  

In source/languageHandler.py <https://github.com/nvaccess/nvda/pull/9729#discussion_r293196893> :

> @@ -108,7 +108,9 @@ def getAvailableLanguages(presentational=False):
               displayNames.append("%s, %s"%(desc,entry) if desc else entry)
        #Prepare a zipped view of language codes and descriptions.
        # #7284: especially for sorting by description.
-       langs = zip(locales,displayNames)
+       # #7105 (Py3 review required): Python 2 list 0> Python 3 iterator.

I don't think this comment is necessary. Furthermore, it contains a typo.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub <https://github.com/nvaccess/nvda/pull/9729?email_source=notifications&email_token=AB4AXEH3E7OHA52VTZI5GWTP2HAQBA5CNFSM4HXTHZG2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB3MTKMI#pullrequestreview-249115953> , or mute the thread <https://github.com/notifications/unsubscribe-auth/AB4AXEAADI7GNRA6F3HIF2LP2HAQBANCNFSM4HXTHZGQ> .

2019-06-13 04:11 UTC, leonardder commented
I ran through all the items of `git grep "\Wstr\W"`, and all seems wel indeed.

2019-06-13 23:50 UTC, michaelDCurran commented
@leonardder  are you still waiting for changes on this, or are you going to approve?

2019-06-14 06:22 UTC, LeonarddeR approved these changes
Yes, go ahead.

2019-06-14 06:33 UTC, michaelDCurran approved these changes

2019-06-14 06:33 UTC, merged

2019-06-14 07:05 UTC, michaelDCurran commented
After merging this, setup.py failed as it found a syntax error in source\NVDAObjects\IAccessible\ia2TextMozilla.py, introduced by this pr. Due to a for loop being split across two lines.
I have manually fixed this in 5da17fd0, which is now on threshold_py3_staging.
I appreciate that shorter line lengths are easier to read for some people, but I would suggest we back down on this a bit, especially with reviewing code for the Python3 transition. Not only was there this syntax error, but a lot of other code is having to be slightly rewritten, which really has nothing to do with Python3 and could introduce further bugs.

2019-06-14 07:18 UTC, leonardder commented
That makes sense. I'll refrain from review comments requesting for line 
splitting.