UI Automation in Windows Console: Remove "Text area", replace isAtLeastWin10, and code cleanup
nvaccess/nvda pull request #9761
Opened 2019-06-17 06:00 UTC by codeofdusk

### Link to issue number:
Builds on #9614.

### Summary of the issue:
Currently:

* If the system language is not English, the name of the UIA console is not localized.
* The windows 10 detection function always returns `True` if the currently-running version is at least the supplied one. For example, this makes it difficult to enable UIA consoles for Windows 10 1809 and later except 1903.

### Description of how this pull request fixes the issue:
* The name "Text area" is no longer reported for UIA consoles.
* The `isAtLeastWin10` function has been renamed to `isWin10`. It now takes an optional `atLeast` keyword argument, which defaults to `True`. The caret movement workarounds have been explicitly enabled for 1903 (not 1903 and later) in anticipation of a possible future Microsoft fix.
* Various code cleanup/style changes. Notably, `winConsoleUIA.winConsoleUIA` has been renamed to `winConsoleUIA.WinConsoleUIA` to remain consistent with other NVDA classes.

### Testing performed:
Tested that the console is still functional and that `isWin10` returns expected results on Windows 10 1903.

### Known issues with pull request:
None.

### Change log entry:
== Changes for Developers ==
- Added a new isWin10 function to the winVersion module which returns whether or not this copy of NVDA is running on (at least) the supplied release version of Windows 10 (such as 1903). (#nnnn)

2019-06-17 06:03 UTC, codeofdusk commented
CC @feerrenrut @leonardder @michaelDCurran.

2019-06-17 21:59 UTC, michaelDCurran requested changes
I would like to see this pr just focus on actual code changes and comment clarification, rather than code style.
  I.e.
* Suppressing the name of the control
* Changing the windows 10 logic
* Renaming WinConsoleUIA
* Clarifying comments
This makes it a lot easier to review and test.
Plus, some of your style changes I find hard to agree with. For example, moving the final bracket up onto the line with the last argument. That is not consistant with other functions/lists split over multiple lines.
Perhaps we can revisit code style later on in this project, but if there was a major issue with styling in the first place, the previous prs would not have been approved. Getting style right in the first place is very good practice, but changing it after the fact tends to introduce bugs and makes it harder to track the history of lines in commits. Though this is just my personal opinion :)

2019-06-17 23:06 UTC, codeofdusk commented
> I would like to see this pr just focus on actual code changes and comment clarification, rather than code style.
> I.e.
> 
> * Suppressing the name of the control
> * Changing the windows 10 logic
> * Renaming WinConsoleUIA
> * Clarifying comments
>   This makes it a lot easier to review and test.
>   Plus, some of your style changes I find hard to agree with. For example, moving the final bracket up onto the line with the last argument. That is not consistant with other functions/lists split over multiple lines.
>   Perhaps we can revisit code style later on in this project, but if there was a major issue with styling in the first place, the previous prs would not have been approved. Getting style right in the first place is very good practice, but changing it after the fact tends to introduce bugs and makes it harder to track the history of lines in commits. Though this is just my personal opinion :)

@michaelDCurran I think I've reverted all code style changes. Could you please have another look?

2019-06-17 23:25 UTC, michaelDCurran approved these changes

2019-06-17 23:26 UTC, michaelDCurran commented
Have you ran with this pr (with the most recent changes) for a while? I just want to ensure this has had enough testing before I merge it.

2019-06-17 23:28 UTC, codeofdusk commented
> Have you ran with this pr (with the most recent changes) for a while? I just want to ensure this has had enough testing before I merge it.

I've tested on my machine (during development) and everything seemed fine to me...

2019-06-17 23:31 UTC, merged

2019-06-17 23:57 UTC, codeofdusk commented
@michaelDCurran Could you please update what's new for these PRs? (remove the old entry from 2019.2 changes and add the one from this description)

2019-06-18 00:40 UTC, codeofdusk commented
@michaelDCurran Please move the change from bug fixes to changes for developers. Thanks.

2019-06-18 02:16 UTC, michaelDCurran commented
I am confused. I placed it under Changes for Developers for 2019.3 in 
changes.t2t.

Are you seeing something different?

Oh, there was a missing blank line... perhaps it was that.