New handy tech display models
nvaccess/nvda pull request #9855
Opened 2019-07-02 09:50 UTC by FelixGruetzmacher

### Link to issue number:
Does not apply.
### Summary of the issue:
New Handy Tech display models are not recognized by NVDA as they use new ID bytes and/or Bluetooth names.
### Description of how this pull request fixes the issue:
This branch is kept up to date with new Braille displays from Handy Tech.
### Testing performed:
Tested with current models.
### Known issues with pull request:
None.
### Change log entry:

Added support for new Handy Tech Braille displays.

2019-07-02 10:52 UTC, leonardder commented
I'm confused. Wasn't this already merged?

2019-07-02 11:56 UTC, FelixGruetzmacher commented
No, there was an additional change I made on Friday, because Basic Braille
32 was not yet recognized. I had unfortunately left out some code required
for that. The version that was previously merged is, however, still
perfectly fine for 2019.2. No bug was discovered.

Am Di., 2. Juli 2019 um 12:52 Uhr schrieb Leonard de Ruijter <
notifications@github.com>:

> I'm confused. Wasn't this already merged?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/nvaccess/nvda/pull/9855?email_source=notifications&email_token=AEKTKKBNISIMPNAUMAAIQ2TP5MXPPA5CNFSM4H42AR4KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZA3XXQ#issuecomment-507624414>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AEKTKKE5VQ4XOXQPBANYRRTP5MXPPANCNFSM4H42AR4A>
> .
>

2019-07-02 13:18 UTC, leonardder commented
Yet, the diff on github shows code that is already in master.
Could you please either rebase your current branch on master, or merge in master?

2019-07-03 19:15 UTC, LeonarddeR approved these changes

2019-08-27 12:49 UTC, leonardder commented
@feerrenrut I'll add this to the 2019.3 milestone, since it is a relatively small change with positive impact for users of these new models.

2019-09-09 23:22 UTC, michaelDCurran approved these changes

2019-09-09 23:23 UTC, michaelDCurran requested changes
This branch has conflicts.

2019-09-26 05:14 UTC, leonardder commented
@FelixGruetzmacher I just rebased this onto latest master in order for @michaelDCurran to review this.

2019-09-26 05:20 UTC, leonardder commented
> ### Description of how this pull request fixes the issue:
> 
> This branch is kept up to date with new Braille displays from Handy Tech.

@FelixGruetzmacher  Note that keeping a branch up to date with changes is not going to work if you're intending to do subsequent pull requests in the future. This is because branches are squash merged into master, the history of the pull request branch isn't kept in master. You will always have to start from master if you file a new pr.

2019-09-26 07:18 UTC, michaelDCurran approved these changes

2019-09-26 07:23 UTC, michaelDCurran commented
@FelixGruetzmacher  I have reviewed and approved this. But before I merge could you please provide a clear changelog entry in the pr description so I can include it in changes.t2t? Something that mentions specifically which displays are now supported.

2019-09-26 08:26 UTC, FelixGruetzmacher commented
@michaelDCurran I have updated the description.
@leonardder thank you kindly for pointing it out. Will honour this next time.

2019-09-26 08:27 UTC, leonardder commented
Github gotcha!

2019-09-26 08:42 UTC, merged